# Business and Economics
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

startup|is_a|business type|1.0
startup|definition|early stage company seeking scalable business model|0.95
startup|domain_is|business|0.9
venture capital|is_a|funding type|1.0
venture capital|definition|investment in high growth potential startups|0.95
venture capital|domain_is|business|0.9
ipo|is_a|financial event|1.0
ipo|definition|initial public offering of company shares|0.95
ipo|domain_is|business|0.9
roi|is_a|metric|1.0
roi|definition|return on investment measures profitability|0.95
roi|domain_is|business|0.9
gdp|is_a|metric|1.0
gdp|definition|gross domestic product measures economic output|0.95
gdp|domain_is|business|0.9
inflation|is_a|economic concept|1.0
inflation|definition|general increase in prices over time|0.95
inflation|domain_is|business|0.9
recession|is_a|economic concept|1.0
recession|definition|period of economic decline|0.95
recession|domain_is|business|0.9
supply and demand|is_a|economic concept|1.0
supply and demand|definition|relationship between availability and desire|0.95
supply and demand|domain_is|business|0.9
market capitalization|is_a|metric|1.0
market capitalization|definition|total value of company outstanding shares|0.95
market capitalization|domain_is|business|0.9
dividend|is_a|financial term|1.0
dividend|definition|portion of earnings distributed to shareholders|0.95
dividend|domain_is|business|0.9
bond|is_a|financial instrument|1.0
bond|definition|debt security with fixed interest payments|0.95
bond|domain_is|business|0.9
equity|is_a|financial term|1.0
equity|definition|ownership interest in a company|0.95
equity|domain_is|business|0.9
revenue|is_a|financial term|1.0
revenue|definition|total income from business operations|0.95
revenue|domain_is|business|0.9
profit margin|is_a|metric|1.0
profit margin|definition|percentage of revenue that is profit|0.95
profit margin|domain_is|business|0.9
cash flow|is_a|metric|1.0
cash flow|definition|net amount of cash moving in and out|0.95
cash flow|domain_is|business|0.9
asset|is_a|financial term|1.0
asset|definition|resource owned that has economic value|0.95
asset|domain_is|business|0.9
liability|is_a|financial term|1.0
liability|definition|obligation owed to another party|0.95
liability|domain_is|business|0.9
monopoly|is_a|market structure|1.0
monopoly|definition|single seller dominates entire market|0.95
monopoly|domain_is|business|0.9
oligopoly|is_a|market structure|1.0
oligopoly|definition|few sellers dominate the market|0.95
oligopoly|domain_is|business|0.9
blockchain|is_a|technology|1.0
blockchain|definition|distributed ledger technology|0.95
blockchain|domain_is|business|0.9
cryptocurrency|is_a|financial instrument|1.0
cryptocurrency|definition|digital currency using cryptography|0.95
cryptocurrency|domain_is|business|0.9
hedge fund|is_a|investment vehicle|1.0
hedge fund|definition|pooled fund using complex strategies|0.95
hedge fund|domain_is|business|0.9
mutual fund|is_a|investment vehicle|1.0
mutual fund|definition|pooled fund investing in diversified assets|0.95
mutual fund|domain_is|business|0.9
balance sheet|is_a|financial statement|1.0
balance sheet|definition|snapshot of assets liabilities and equity|0.95
balance sheet|domain_is|business|0.9
income statement|is_a|financial statement|1.0
income statement|definition|summary of revenues and expenses|0.95
income statement|domain_is|business|0.9
depreciation|is_a|accounting concept|1.0
depreciation|definition|decrease in asset value over time|0.95
depreciation|domain_is|business|0.9
amortization|is_a|accounting concept|1.0
amortization|definition|spreading cost over useful life|0.95
amortization|domain_is|business|0.9
leverage|is_a|financial concept|1.0
leverage|definition|use of borrowed capital for investment|0.95
leverage|domain_is|business|0.9
liquidity|is_a|financial concept|1.0
liquidity|definition|ease of converting asset to cash|0.95
liquidity|domain_is|business|0.9
arbitrage|is_a|trading strategy|1.0
arbitrage|definition|exploiting price differences across markets|0.95
arbitrage|domain_is|business|0.9
apple|is_a|company|1.0
apple|sector_is|technology|1.0
apple|founded_in|1976|1.0
apple|ceo_is|tim cook|0.9
apple|headquartered_in|cupertino|0.95
google|is_a|company|1.0
google|sector_is|technology|1.0
google|founded_in|1998|1.0
google|ceo_is|sundar pichai|0.9
google|headquartered_in|mountain view|0.95
microsoft|is_a|company|1.0
microsoft|sector_is|technology|1.0
microsoft|founded_in|1975|1.0
microsoft|ceo_is|satya nadella|0.9
microsoft|headquartered_in|redmond|0.95
amazon|is_a|company|1.0
amazon|sector_is|ecommerce|1.0
amazon|founded_in|1994|1.0
amazon|ceo_is|andy jassy|0.9
amazon|headquartered_in|seattle|0.95
meta|is_a|company|1.0
meta|sector_is|social media|1.0
meta|founded_in|2004|1.0
meta|ceo_is|mark zuckerberg|0.9
meta|headquartered_in|menlo park|0.95
tesla|is_a|company|1.0
tesla|sector_is|automotive|1.0
tesla|founded_in|2003|1.0
tesla|ceo_is|elon musk|0.9
tesla|headquartered_in|austin|0.95
nvidia|is_a|company|1.0
nvidia|sector_is|semiconductors|1.0
nvidia|founded_in|1993|1.0
nvidia|ceo_is|jensen huang|0.9
nvidia|headquartered_in|santa clara|0.95
samsung|is_a|company|1.0
samsung|sector_is|electronics|1.0
samsung|founded_in|1938|1.0
samsung|ceo_is|lee jae yong|0.9
samsung|headquartered_in|seoul|0.95
toyota|is_a|company|1.0
toyota|sector_is|automotive|1.0
toyota|founded_in|1937|1.0
toyota|ceo_is|akio toyoda|0.9
toyota|headquartered_in|toyota city|0.95
berkshire hathaway|is_a|company|1.0
berkshire hathaway|sector_is|conglomerate|1.0
berkshire hathaway|founded_in|1839|1.0
berkshire hathaway|ceo_is|warren buffett|0.9
berkshire hathaway|headquartered_in|omaha|0.95
