# Sports and Athletics
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

soccer|is_a|sport|1.0
soccer|is_a|team sport|1.0
soccer|players_per_team|11|0.95
soccer|major_event|fifa world cup|0.95
soccer|originated_in|1863|0.85
soccer|uses|ball|0.9
soccer|uses|goal|0.9
soccer|uses|field|0.9
basketball|is_a|sport|1.0
basketball|is_a|team sport|1.0
basketball|players_per_team|5|0.95
basketball|major_event|nba finals|0.95
basketball|originated_in|1891|0.85
basketball|uses|ball|0.9
basketball|uses|hoop|0.9
basketball|uses|court|0.9
tennis|is_a|sport|1.0
tennis|is_a|individual sport|1.0
tennis|players_per_team|1 or 2|0.95
tennis|major_event|wimbledon|0.95
tennis|originated_in|1873|0.85
tennis|uses|racket|0.9
tennis|uses|ball|0.9
tennis|uses|net|0.9
baseball|is_a|sport|1.0
baseball|is_a|team sport|1.0
baseball|players_per_team|9|0.95
baseball|major_event|world series|0.95
baseball|originated_in|1846|0.85
baseball|uses|bat|0.9
baseball|uses|ball|0.9
baseball|uses|glove|0.9
american football|is_a|sport|1.0
american football|is_a|team sport|1.0
american football|players_per_team|11|0.95
american football|major_event|super bowl|0.95
american football|originated_in|1869|0.85
american football|uses|ball|0.9
american football|uses|helmet|0.9
american football|uses|field|0.9
cricket|is_a|sport|1.0
cricket|is_a|team sport|1.0
cricket|players_per_team|11|0.95
cricket|major_event|cricket world cup|0.95
cricket|originated_in|1844|0.85
cricket|uses|bat|0.9
cricket|uses|ball|0.9
cricket|uses|wicket|0.9
golf|is_a|sport|1.0
golf|is_a|individual sport|1.0
golf|players_per_team|1|0.95
golf|major_event|the masters|0.95
golf|originated_in|1457|0.85
golf|uses|clubs|0.9
golf|uses|ball|0.9
golf|uses|course|0.9
swimming|is_a|sport|1.0
swimming|is_a|individual sport|1.0
swimming|players_per_team|1|0.95
swimming|major_event|olympic games|0.95
swimming|originated_in|ancient|0.85
swimming|uses|pool|0.9
swimming|uses|goggles|0.9
swimming|uses|swimsuit|0.9
boxing|is_a|sport|1.0
boxing|is_a|combat sport|1.0
boxing|players_per_team|1|0.95
boxing|major_event|world championship|0.95
boxing|originated_in|ancient|0.85
boxing|uses|gloves|0.9
boxing|uses|ring|0.9
boxing|uses|mouthguard|0.9
hockey|is_a|sport|1.0
hockey|is_a|team sport|1.0
hockey|players_per_team|6|0.95
hockey|major_event|stanley cup|0.95
hockey|originated_in|1875|0.85
hockey|uses|stick|0.9
hockey|uses|puck|0.9
hockey|uses|ice rink|0.9
rugby|is_a|sport|1.0
rugby|is_a|team sport|1.0
rugby|players_per_team|15|0.95
rugby|major_event|rugby world cup|0.95
rugby|originated_in|1823|0.85
rugby|uses|ball|0.9
rugby|uses|goal|0.9
rugby|uses|field|0.9
volleyball|is_a|sport|1.0
volleyball|is_a|team sport|1.0
volleyball|players_per_team|6|0.95
volleyball|major_event|olympic games|0.95
volleyball|originated_in|1895|0.85
volleyball|uses|ball|0.9
volleyball|uses|net|0.9
volleyball|uses|court|0.9
table tennis|is_a|sport|1.0
table tennis|is_a|individual sport|1.0
table tennis|players_per_team|1 or 2|0.95
table tennis|major_event|olympic games|0.95
table tennis|originated_in|1880|0.85
table tennis|uses|paddle|0.9
table tennis|uses|ball|0.9
table tennis|uses|table|0.9
formula one|is_a|sport|1.0
formula one|is_a|motorsport|1.0
formula one|players_per_team|1|0.95
formula one|major_event|world championship|0.95
formula one|originated_in|1950|0.85
formula one|uses|car|0.9
formula one|uses|circuit|0.9
formula one|uses|helmet|0.9
mma|is_a|sport|1.0
mma|is_a|combat sport|1.0
mma|players_per_team|1|0.95
mma|major_event|ufc|0.95
mma|originated_in|ancient|0.85
mma|uses|gloves|0.9
mma|uses|octagon|0.9
mma|uses|mouthguard|0.9
