# Food, Cuisine, and Nutrition
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

pizza|is_a|food|1.0
pizza|cuisine_is|italian|1.0
pizza|category_is|main dish|0.95
pizza|contains|dough|0.9
pizza|contains|tomato sauce|0.9
pizza|contains|cheese|0.9
pizza|contains|toppings|0.9
pizza|origin_is|italian cuisine|0.9
sushi|is_a|food|1.0
sushi|cuisine_is|japanese|1.0
sushi|category_is|main dish|0.95
sushi|contains|rice|0.9
sushi|contains|fish|0.9
sushi|contains|seaweed|0.9
sushi|contains|wasabi|0.9
sushi|origin_is|japanese cuisine|0.9
tacos|is_a|food|1.0
tacos|cuisine_is|mexican|1.0
tacos|category_is|main dish|0.95
tacos|contains|tortilla|0.9
tacos|contains|meat|0.9
tacos|contains|salsa|0.9
tacos|contains|cheese|0.9
tacos|origin_is|mexican cuisine|0.9
curry|is_a|food|1.0
curry|cuisine_is|indian|1.0
curry|category_is|main dish|0.95
curry|contains|spices|0.9
curry|contains|rice|0.9
curry|contains|vegetables|0.9
curry|contains|protein|0.9
curry|origin_is|indian cuisine|0.9
pasta|is_a|food|1.0
pasta|cuisine_is|italian|1.0
pasta|category_is|main dish|0.95
pasta|contains|flour|0.9
pasta|contains|eggs|0.9
pasta|contains|sauce|0.9
pasta|contains|cheese|0.9
pasta|origin_is|italian cuisine|0.9
hamburger|is_a|food|1.0
hamburger|cuisine_is|american|1.0
hamburger|category_is|main dish|0.95
hamburger|contains|bun|0.9
hamburger|contains|beef patty|0.9
hamburger|contains|lettuce|0.9
hamburger|contains|tomato|0.9
hamburger|origin_is|american cuisine|0.9
ramen|is_a|food|1.0
ramen|cuisine_is|japanese|1.0
ramen|category_is|soup|0.95
ramen|contains|noodles|0.9
ramen|contains|broth|0.9
ramen|contains|pork|0.9
ramen|contains|eggs|0.9
ramen|origin_is|japanese cuisine|0.9
croissant|is_a|food|1.0
croissant|cuisine_is|french|1.0
croissant|category_is|pastry|0.95
croissant|contains|butter|0.9
croissant|contains|flour|0.9
croissant|contains|yeast|0.9
croissant|contains|milk|0.9
croissant|origin_is|french cuisine|0.9
paella|is_a|food|1.0
paella|cuisine_is|spanish|1.0
paella|category_is|main dish|0.95
paella|contains|rice|0.9
paella|contains|saffron|0.9
paella|contains|seafood|0.9
paella|contains|vegetables|0.9
paella|origin_is|spanish cuisine|0.9
dim sum|is_a|food|1.0
dim sum|cuisine_is|chinese|1.0
dim sum|category_is|appetizer|0.95
dim sum|contains|dumplings|0.9
dim sum|contains|buns|0.9
dim sum|contains|rolls|0.9
dim sum|contains|tea|0.9
dim sum|origin_is|chinese cuisine|0.9
kimchi|is_a|food|1.0
kimchi|cuisine_is|korean|1.0
kimchi|category_is|side dish|0.95
kimchi|contains|cabbage|0.9
kimchi|contains|chili flakes|0.9
kimchi|contains|garlic|0.9
kimchi|contains|salt|0.9
kimchi|origin_is|korean cuisine|0.9
falafel|is_a|food|1.0
falafel|cuisine_is|middle eastern|1.0
falafel|category_is|appetizer|0.95
falafel|contains|chickpeas|0.9
falafel|contains|herbs|0.9
falafel|contains|spices|0.9
falafel|contains|oil|0.9
falafel|origin_is|middle eastern cuisine|0.9
pho|is_a|food|1.0
pho|cuisine_is|vietnamese|1.0
pho|category_is|soup|0.95
pho|contains|rice noodles|0.9
pho|contains|broth|0.9
pho|contains|beef|0.9
pho|contains|herbs|0.9
pho|origin_is|vietnamese cuisine|0.9
pad thai|is_a|food|1.0
pad thai|cuisine_is|thai|1.0
pad thai|category_is|main dish|0.95
pad thai|contains|rice noodles|0.9
pad thai|contains|shrimp|0.9
pad thai|contains|peanuts|0.9
pad thai|contains|egg|0.9
pad thai|origin_is|thai cuisine|0.9
biryani|is_a|food|1.0
biryani|cuisine_is|indian|1.0
biryani|category_is|main dish|0.95
biryani|contains|basmati rice|0.9
biryani|contains|spices|0.9
biryani|contains|meat|0.9
biryani|contains|saffron|0.9
biryani|origin_is|indian cuisine|0.9
fish and chips|is_a|food|1.0
fish and chips|cuisine_is|british|1.0
fish and chips|category_is|main dish|0.95
fish and chips|contains|cod|0.9
fish and chips|contains|batter|0.9
fish and chips|contains|potatoes|0.9
fish and chips|contains|oil|0.9
fish and chips|origin_is|british cuisine|0.9
bratwurst|is_a|food|1.0
bratwurst|cuisine_is|german|1.0
bratwurst|category_is|main dish|0.95
bratwurst|contains|pork|0.9
bratwurst|contains|spices|0.9
bratwurst|contains|bread|0.9
bratwurst|contains|mustard|0.9
bratwurst|origin_is|german cuisine|0.9
ceviche|is_a|food|1.0
ceviche|cuisine_is|peruvian|1.0
ceviche|category_is|appetizer|0.95
ceviche|contains|raw fish|0.9
ceviche|contains|lime juice|0.9
ceviche|contains|onion|0.9
ceviche|contains|chili|0.9
ceviche|origin_is|peruvian cuisine|0.9
tiramisu|is_a|food|1.0
tiramisu|cuisine_is|italian|1.0
tiramisu|category_is|dessert|0.95
tiramisu|contains|mascarpone|0.9
tiramisu|contains|coffee|0.9
tiramisu|contains|ladyfingers|0.9
tiramisu|contains|cocoa|0.9
tiramisu|origin_is|italian cuisine|0.9
baklava|is_a|food|1.0
baklava|cuisine_is|turkish|1.0
baklava|category_is|dessert|0.95
baklava|contains|phyllo dough|0.9
baklava|contains|nuts|0.9
baklava|contains|honey|0.9
baklava|contains|butter|0.9
baklava|origin_is|turkish cuisine|0.9
protein|is_a|macronutrient|1.0
protein|function_is|builds muscle|0.95
meat|contains|protein|0.85
fish|contains|protein|0.85
eggs|contains|protein|0.85
beans|contains|protein|0.85
tofu|contains|protein|0.85
carbohydrate|is_a|macronutrient|1.0
carbohydrate|function_is|provides energy|0.95
bread|contains|carbohydrate|0.85
rice|contains|carbohydrate|0.85
pasta|contains|carbohydrate|0.85
potato|contains|carbohydrate|0.85
sugar|contains|carbohydrate|0.85
fat|is_a|macronutrient|1.0
fat|function_is|stores energy|0.95
butter|contains|fat|0.85
oil|contains|fat|0.85
nuts|contains|fat|0.85
avocado|contains|fat|0.85
cheese|contains|fat|0.85
vitamin c|is_a|vitamin|1.0
vitamin c|function_is|boosts immunity|0.95
orange|contains|vitamin c|0.85
lemon|contains|vitamin c|0.85
kiwi|contains|vitamin c|0.85
bell pepper|contains|vitamin c|0.85
strawberry|contains|vitamin c|0.85
iron|is_a|mineral|1.0
iron|function_is|carries oxygen|0.95
spinach|contains|iron|0.85
red meat|contains|iron|0.85
lentils|contains|iron|0.85
tofu|contains|iron|0.85
dark chocolate|contains|iron|0.85
calcium|is_a|mineral|1.0
calcium|function_is|builds bones|0.95
milk|contains|calcium|0.85
cheese|contains|calcium|0.85
yogurt|contains|calcium|0.85
broccoli|contains|calcium|0.85
almonds|contains|calcium|0.85
