# Human Languages, Design Patterns, Databases, OS
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

english|is_a|human language|1.0
english|language_family|germanic|0.95
english|speakers_count|1.5 billion|0.85
english|writing_system|latin|0.95
english|has_feature|subject verb object|0.85
english|has_feature|26 letters|0.85
english|has_feature|global lingua franca|0.85
mandarin chinese|is_a|human language|1.0
mandarin chinese|language_family|sino-tibetan|0.95
mandarin chinese|speakers_count|1.1 billion|0.85
mandarin chinese|writing_system|chinese characters|0.95
mandarin chinese|has_feature|tonal language|0.85
mandarin chinese|has_feature|simplified and traditional|0.85
mandarin chinese|has_feature|most native speakers|0.85
spanish|is_a|human language|1.0
spanish|language_family|romance|0.95
spanish|speakers_count|550 million|0.85
spanish|writing_system|latin|0.95
spanish|has_feature|gendered nouns|0.85
spanish|has_feature|subjunctive mood|0.85
spanish|has_feature|second most native speakers|0.85
hindi|is_a|human language|1.0
hindi|language_family|indo-aryan|0.95
hindi|speakers_count|600 million|0.85
hindi|writing_system|devanagari|0.95
hindi|has_feature|gendered nouns|0.85
hindi|has_feature|sov word order|0.85
hindi|has_feature|official language of india|0.85
arabic|is_a|human language|1.0
arabic|language_family|semitic|0.95
arabic|speakers_count|420 million|0.85
arabic|writing_system|arabic script|0.95
arabic|has_feature|right to left|0.85
arabic|has_feature|root system|0.85
arabic|has_feature|diglossia|0.85
french|is_a|human language|1.0
french|language_family|romance|0.95
french|speakers_count|320 million|0.85
french|writing_system|latin|0.95
french|has_feature|gendered nouns|0.85
french|has_feature|nasal vowels|0.85
french|has_feature|liaison|0.85
portuguese|is_a|human language|1.0
portuguese|language_family|romance|0.95
portuguese|speakers_count|260 million|0.85
portuguese|writing_system|latin|0.95
portuguese|has_feature|gendered nouns|0.85
portuguese|has_feature|nasal vowels|0.85
portuguese|has_feature|spoken in brazil|0.85
russian|is_a|human language|1.0
russian|language_family|slavic|0.95
russian|speakers_count|250 million|0.85
russian|writing_system|cyrillic|0.95
russian|has_feature|cases|0.85
russian|has_feature|aspect system|0.85
russian|has_feature|flexible word order|0.85
japanese|is_a|human language|1.0
japanese|language_family|japonic|0.95
japanese|speakers_count|125 million|0.85
japanese|writing_system|kanji hiragana katakana|0.95
japanese|has_feature|three writing systems|0.85
japanese|has_feature|honorifics|0.85
japanese|has_feature|sov word order|0.85
german|is_a|human language|1.0
german|language_family|germanic|0.95
german|speakers_count|130 million|0.85
german|writing_system|latin|0.95
german|has_feature|compound words|0.85
german|has_feature|cases|0.85
german|has_feature|verb final in subordinate clauses|0.85
korean|is_a|human language|1.0
korean|language_family|koreanic|0.95
korean|speakers_count|80 million|0.85
korean|writing_system|hangul|0.95
korean|has_feature|agglutinative|0.85
korean|has_feature|honorifics|0.85
korean|has_feature|sov word order|0.85
italian|is_a|human language|1.0
italian|language_family|romance|0.95
italian|speakers_count|67 million|0.85
italian|writing_system|latin|0.95
italian|has_feature|gendered nouns|0.85
italian|has_feature|verb conjugation|0.85
italian|has_feature|melodic intonation|0.85
turkish|is_a|human language|1.0
turkish|language_family|turkic|0.95
turkish|speakers_count|80 million|0.85
turkish|writing_system|latin|0.95
turkish|has_feature|vowel harmony|0.85
swahili|is_a|human language|1.0
swahili|language_family|bantu|0.95
swahili|speakers_count|100 million|0.85
swahili|writing_system|latin|0.95
swahili|has_feature|noun class system|0.85
dutch|is_a|human language|1.0
dutch|language_family|germanic|0.95
dutch|speakers_count|25 million|0.85
dutch|writing_system|latin|0.95
dutch|has_feature|similar to german and english|0.85
singleton pattern|is_a|design pattern|1.0
singleton pattern|category_is|creational|1.0
singleton pattern|description|ensures only one instance of a class exists|0.95
singleton pattern|domain_is|software engineering|0.9
factory pattern|is_a|design pattern|1.0
factory pattern|category_is|creational|1.0
factory pattern|description|creates objects without specifying exact class|0.95
factory pattern|domain_is|software engineering|0.9
observer pattern|is_a|design pattern|1.0
observer pattern|category_is|behavioral|1.0
observer pattern|description|defines one-to-many dependency between objects|0.95
observer pattern|domain_is|software engineering|0.9
strategy pattern|is_a|design pattern|1.0
strategy pattern|category_is|behavioral|1.0
strategy pattern|description|defines family of interchangeable algorithms|0.95
strategy pattern|domain_is|software engineering|0.9
decorator pattern|is_a|design pattern|1.0
decorator pattern|category_is|structural|1.0
decorator pattern|description|adds behavior to objects dynamically|0.95
decorator pattern|domain_is|software engineering|0.9
adapter pattern|is_a|design pattern|1.0
adapter pattern|category_is|structural|1.0
adapter pattern|description|converts interface of one class to another|0.95
adapter pattern|domain_is|software engineering|0.9
facade pattern|is_a|design pattern|1.0
facade pattern|category_is|structural|1.0
facade pattern|description|provides simplified interface to complex subsystem|0.95
facade pattern|domain_is|software engineering|0.9
proxy pattern|is_a|design pattern|1.0
proxy pattern|category_is|structural|1.0
proxy pattern|description|provides placeholder for another object|0.95
proxy pattern|domain_is|software engineering|0.9
command pattern|is_a|design pattern|1.0
command pattern|category_is|behavioral|1.0
command pattern|description|encapsulates request as an object|0.95
command pattern|domain_is|software engineering|0.9
iterator pattern|is_a|design pattern|1.0
iterator pattern|category_is|behavioral|1.0
iterator pattern|description|provides way to access elements sequentially|0.95
iterator pattern|domain_is|software engineering|0.9
template method pattern|is_a|design pattern|1.0
template method pattern|category_is|behavioral|1.0
template method pattern|description|defines skeleton of algorithm in base class|0.95
template method pattern|domain_is|software engineering|0.9
builder pattern|is_a|design pattern|1.0
builder pattern|category_is|creational|1.0
builder pattern|description|constructs complex objects step by step|0.95
builder pattern|domain_is|software engineering|0.9
prototype pattern|is_a|design pattern|1.0
prototype pattern|category_is|creational|1.0
prototype pattern|description|creates new objects by cloning existing ones|0.95
prototype pattern|domain_is|software engineering|0.9
mediator pattern|is_a|design pattern|1.0
mediator pattern|category_is|behavioral|1.0
mediator pattern|description|reduces coupling between components|0.95
mediator pattern|domain_is|software engineering|0.9
state pattern|is_a|design pattern|1.0
state pattern|category_is|behavioral|1.0
state pattern|description|allows object to alter behavior when internal state changes|0.95
state pattern|domain_is|software engineering|0.9
postgresql|is_a|database|1.0
postgresql|database_type|relational|1.0
postgresql|license_is|open source|0.9
postgresql|query_language|sql|0.95
postgresql|known_for|acid compliant|0.9
mysql|is_a|database|1.0
mysql|database_type|relational|1.0
mysql|license_is|open source|0.9
mysql|query_language|sql|0.95
mysql|known_for|widely used|0.9
mongodb|is_a|database|1.0
mongodb|database_type|document|1.0
mongodb|license_is|open source|0.9
mongodb|query_language|javascript|0.95
mongodb|known_for|schema flexible|0.9
redis|is_a|database|1.0
redis|database_type|key value|1.0
redis|license_is|open source|0.9
redis|query_language|custom protocol|0.95
redis|known_for|in memory|0.9
elasticsearch|is_a|database|1.0
elasticsearch|database_type|search engine|1.0
elasticsearch|license_is|open source|0.9
elasticsearch|query_language|rest api|0.95
elasticsearch|known_for|full text search|0.9
cassandra|is_a|database|1.0
cassandra|database_type|wide column|1.0
cassandra|license_is|open source|0.9
cassandra|query_language|cql|0.95
cassandra|known_for|highly available|0.9
sqlite|is_a|database|1.0
sqlite|database_type|relational|1.0
sqlite|license_is|embedded|0.9
sqlite|query_language|sql|0.95
sqlite|known_for|serverless|0.9
dynamodb|is_a|database|1.0
dynamodb|database_type|key value|1.0
dynamodb|license_is|aws managed|0.9
dynamodb|query_language|api|0.95
dynamodb|known_for|auto scaling|0.9
neo4j|is_a|database|1.0
neo4j|database_type|graph|1.0
neo4j|license_is|open source|0.9
neo4j|query_language|cypher|0.95
neo4j|known_for|relationship focused|0.9
couchdb|is_a|database|1.0
couchdb|database_type|document|1.0
couchdb|license_is|open source|0.9
couchdb|query_language|rest api|0.95
couchdb|known_for|offline first|0.9
linux|is_a|operating system|1.0
linux|license_is|open source|1.0
linux|created_by|linus torvalds|1.0
linux|released_in|1991|1.0
linux|kernel_type|monolithic kernel|0.95
windows|is_a|operating system|1.0
windows|license_is|proprietary|1.0
windows|created_by|microsoft|1.0
windows|released_in|1985|1.0
windows|kernel_type|nt kernel|0.95
macos|is_a|operating system|1.0
macos|license_is|proprietary|1.0
macos|created_by|apple|1.0
macos|released_in|2001|1.0
macos|kernel_type|xnu kernel|0.95
android|is_a|operating system|1.0
android|license_is|open source|1.0
android|created_by|google|1.0
android|released_in|2008|1.0
android|kernel_type|linux kernel|0.95
ios|is_a|operating system|1.0
ios|license_is|proprietary|1.0
ios|created_by|apple|1.0
ios|released_in|2007|1.0
ios|kernel_type|xnu kernel|0.95
freebsd|is_a|operating system|1.0
freebsd|license_is|open source|1.0
freebsd|created_by|freebsd project|1.0
freebsd|released_in|1993|1.0
freebsd|kernel_type|monolithic kernel|0.95
ubuntu|is_a|operating system|1.0
ubuntu|license_is|open source|1.0
ubuntu|created_by|canonical|1.0
ubuntu|released_in|2004|1.0
ubuntu|kernel_type|linux kernel|0.95
fedora|is_a|operating system|1.0
fedora|license_is|open source|1.0
fedora|created_by|red hat|1.0
fedora|released_in|2003|1.0
fedora|kernel_type|linux kernel|0.95
