# Science, Math, History, and CS Concepts
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

mercury|is_a|planet|1.0
mercury|position_is|1st from sun|1.0
mercury|known_for|smallest|0.9
mercury|distance_from_sun|57.9 million km|0.95
mercury|moons_count|0|0.9
mercury|temperature_is|hot|0.85
mercury|orbits|sun|1.0
mercury|part_of|solar system|1.0
venus|is_a|planet|1.0
venus|position_is|2nd from sun|1.0
venus|known_for|hottest|0.9
venus|distance_from_sun|108.2 million km|0.95
venus|moons_count|0|0.9
venus|temperature_is|very hot|0.85
venus|orbits|sun|1.0
venus|part_of|solar system|1.0
earth|is_a|planet|1.0
earth|position_is|3rd from sun|1.0
earth|known_for|habitable|0.9
earth|distance_from_sun|149.6 million km|0.95
earth|moons_count|1|0.9
earth|temperature_is|temperate|0.85
earth|orbits|sun|1.0
earth|part_of|solar system|1.0
mars|is_a|planet|1.0
mars|position_is|4th from sun|1.0
mars|known_for|red planet|0.9
mars|distance_from_sun|227.9 million km|0.95
mars|moons_count|2|0.9
mars|temperature_is|cold|0.85
mars|orbits|sun|1.0
mars|part_of|solar system|1.0
jupiter|is_a|planet|1.0
jupiter|position_is|5th from sun|1.0
jupiter|known_for|largest|0.9
jupiter|distance_from_sun|778.5 million km|0.95
jupiter|moons_count|95|0.9
jupiter|temperature_is|very cold|0.85
jupiter|orbits|sun|1.0
jupiter|part_of|solar system|1.0
saturn|is_a|planet|1.0
saturn|position_is|6th from sun|1.0
saturn|known_for|ringed|0.9
saturn|distance_from_sun|1432 million km|0.95
saturn|moons_count|146|0.9
saturn|temperature_is|very cold|0.85
saturn|orbits|sun|1.0
saturn|part_of|solar system|1.0
uranus|is_a|planet|1.0
uranus|position_is|7th from sun|1.0
uranus|known_for|tilted|0.9
uranus|distance_from_sun|2867 million km|0.95
uranus|moons_count|28|0.9
uranus|temperature_is|extremely cold|0.85
uranus|orbits|sun|1.0
uranus|part_of|solar system|1.0
neptune|is_a|planet|1.0
neptune|position_is|8th from sun|1.0
neptune|known_for|windiest|0.9
neptune|distance_from_sun|4515 million km|0.95
neptune|moons_count|16|0.9
neptune|temperature_is|extremely cold|0.85
neptune|orbits|sun|1.0
neptune|part_of|solar system|1.0
hydrogen|is_a|chemical element|1.0
hydrogen|symbol_is|H|1.0
hydrogen|atomic_number|1|1.0
hydrogen|state_at_room_temp|gas|0.95
hydrogen|category_is|nonmetal|1.0
helium|is_a|chemical element|1.0
helium|symbol_is|He|1.0
helium|atomic_number|2|1.0
helium|state_at_room_temp|gas|0.95
helium|category_is|noble gas|1.0
lithium|is_a|chemical element|1.0
lithium|symbol_is|Li|1.0
lithium|atomic_number|3|1.0
lithium|state_at_room_temp|solid|0.95
lithium|category_is|alkali metal|1.0
carbon|is_a|chemical element|1.0
carbon|symbol_is|C|1.0
carbon|atomic_number|6|1.0
carbon|state_at_room_temp|solid|0.95
carbon|category_is|nonmetal|1.0
nitrogen|is_a|chemical element|1.0
nitrogen|symbol_is|N|1.0
nitrogen|atomic_number|7|1.0
nitrogen|state_at_room_temp|gas|0.95
nitrogen|category_is|nonmetal|1.0
oxygen|is_a|chemical element|1.0
oxygen|symbol_is|O|1.0
oxygen|atomic_number|8|1.0
oxygen|state_at_room_temp|gas|0.95
oxygen|category_is|nonmetal|1.0
sodium|is_a|chemical element|1.0
sodium|symbol_is|Na|1.0
sodium|atomic_number|11|1.0
sodium|state_at_room_temp|solid|0.95
sodium|category_is|alkali metal|1.0
magnesium|is_a|chemical element|1.0
magnesium|symbol_is|Mg|1.0
magnesium|atomic_number|12|1.0
magnesium|state_at_room_temp|solid|0.95
magnesium|category_is|alkaline earth metal|1.0
aluminum|is_a|chemical element|1.0
aluminum|symbol_is|Al|1.0
aluminum|atomic_number|13|1.0
aluminum|state_at_room_temp|solid|0.95
aluminum|category_is|metal|1.0
silicon|is_a|chemical element|1.0
silicon|symbol_is|Si|1.0
silicon|atomic_number|14|1.0
silicon|state_at_room_temp|solid|0.95
silicon|category_is|metalloid|1.0
phosphorus|is_a|chemical element|1.0
phosphorus|symbol_is|P|1.0
phosphorus|atomic_number|15|1.0
phosphorus|state_at_room_temp|solid|0.95
phosphorus|category_is|nonmetal|1.0
sulfur|is_a|chemical element|1.0
sulfur|symbol_is|S|1.0
sulfur|atomic_number|16|1.0
sulfur|state_at_room_temp|solid|0.95
sulfur|category_is|nonmetal|1.0
chlorine|is_a|chemical element|1.0
chlorine|symbol_is|Cl|1.0
chlorine|atomic_number|17|1.0
chlorine|state_at_room_temp|gas|0.95
chlorine|category_is|halogen|1.0
iron|is_a|chemical element|1.0
iron|symbol_is|Fe|1.0
iron|atomic_number|26|1.0
iron|state_at_room_temp|solid|0.95
iron|category_is|transition metal|1.0
copper|is_a|chemical element|1.0
copper|symbol_is|Cu|1.0
copper|atomic_number|29|1.0
copper|state_at_room_temp|solid|0.95
copper|category_is|transition metal|1.0
zinc|is_a|chemical element|1.0
zinc|symbol_is|Zn|1.0
zinc|atomic_number|30|1.0
zinc|state_at_room_temp|solid|0.95
zinc|category_is|transition metal|1.0
silver|is_a|chemical element|1.0
silver|symbol_is|Ag|1.0
silver|atomic_number|47|1.0
silver|state_at_room_temp|solid|0.95
silver|category_is|transition metal|1.0
gold|is_a|chemical element|1.0
gold|symbol_is|Au|1.0
gold|atomic_number|79|1.0
gold|state_at_room_temp|solid|0.95
gold|category_is|transition metal|1.0
platinum|is_a|chemical element|1.0
platinum|symbol_is|Pt|1.0
platinum|atomic_number|78|1.0
platinum|state_at_room_temp|solid|0.95
platinum|category_is|transition metal|1.0
uranium|is_a|chemical element|1.0
uranium|symbol_is|U|1.0
uranium|atomic_number|92|1.0
uranium|state_at_room_temp|solid|0.95
uranium|category_is|actinide|1.0
pythagorean theorem|is_a|geometry|1.0
pythagorean theorem|description|a squared plus b squared equals c squared|0.95
pythagorean theorem|domain_is|mathematics|1.0
fibonacci sequence|is_a|number theory|1.0
fibonacci sequence|description|each number is sum of two preceding|0.95
fibonacci sequence|domain_is|mathematics|1.0
prime number|is_a|number theory|1.0
prime number|description|natural number greater than 1 with no divisors except 1 and itself|0.95
prime number|domain_is|mathematics|1.0
pi|is_a|constant|1.0
pi|description|ratio of circumference to diameter approximately 3.14159|0.95
pi|domain_is|mathematics|1.0
euler number|is_a|constant|1.0
euler number|description|base of natural logarithm approximately 2.71828|0.95
euler number|domain_is|mathematics|1.0
golden ratio|is_a|constant|1.0
golden ratio|description|approximately 1.618 found in nature and art|0.95
golden ratio|domain_is|mathematics|1.0
calculus|is_a|branch of math|1.0
calculus|description|study of continuous change|0.95
calculus|domain_is|mathematics|1.0
algebra|is_a|branch of math|1.0
algebra|description|study of mathematical symbols and rules|0.95
algebra|domain_is|mathematics|1.0
geometry|is_a|branch of math|1.0
geometry|description|study of shapes and spaces|0.95
geometry|domain_is|mathematics|1.0
statistics|is_a|branch of math|1.0
statistics|description|study of data collection and analysis|0.95
statistics|domain_is|mathematics|1.0
probability|is_a|branch of math|1.0
probability|description|study of likelihood of events|0.95
probability|domain_is|mathematics|1.0
linear algebra|is_a|branch of math|1.0
linear algebra|description|study of vectors and matrices|0.95
linear algebra|domain_is|mathematics|1.0
topology|is_a|branch of math|1.0
topology|description|study of geometric properties preserved under deformation|0.95
topology|domain_is|mathematics|1.0
set theory|is_a|branch of math|1.0
set theory|description|study of collections of objects|0.95
set theory|domain_is|mathematics|1.0
graph theory|is_a|branch of math|1.0
graph theory|description|study of mathematical structures with nodes and edges|0.95
graph theory|domain_is|mathematics|1.0
world war 1|is_a|historical event|1.0
world war 1|occurred_in|1914-1918|1.0
world war 1|description|global conflict involving major powers|0.95
world war 2|is_a|historical event|1.0
world war 2|occurred_in|1939-1945|1.0
world war 2|description|largest armed conflict in history|0.95
moon landing|is_a|historical event|1.0
moon landing|occurred_in|1969|1.0
moon landing|description|first humans walked on the moon|0.95
fall of berlin wall|is_a|historical event|1.0
fall of berlin wall|occurred_in|1989|1.0
fall of berlin wall|description|end of cold war division of germany|0.95
internet invention|is_a|historical event|1.0
internet invention|occurred_in|1969|1.0
internet invention|description|arpanet first message sent|0.95
french revolution|is_a|historical event|1.0
french revolution|occurred_in|1789|1.0
french revolution|description|overthrow of french monarchy|0.95
american revolution|is_a|historical event|1.0
american revolution|occurred_in|1776|1.0
american revolution|description|thirteen colonies declared independence|0.95
industrial revolution|is_a|historical event|1.0
industrial revolution|occurred_in|1760-1840|1.0
industrial revolution|description|transition to manufacturing processes|0.95
renaissance|is_a|historical event|1.0
renaissance|occurred_in|1400-1600|1.0
renaissance|description|cultural rebirth in europe|0.95
printing press invention|is_a|historical event|1.0
printing press invention|occurred_in|1440|1.0
printing press invention|description|gutenberg revolutionized communication|0.95
discovery of americas|is_a|historical event|1.0
discovery of americas|occurred_in|1492|1.0
discovery of americas|description|columbus reached the new world|0.95
magna carta|is_a|historical event|1.0
magna carta|occurred_in|1215|1.0
magna carta|description|charter of rights limiting royal power|0.95
roman empire fall|is_a|historical event|1.0
roman empire fall|occurred_in|476|1.0
roman empire fall|description|western roman empire collapsed|0.95
cold war|is_a|historical event|1.0
cold war|occurred_in|1947-1991|1.0
cold war|description|geopolitical tension between usa and ussr|0.95
civil rights movement|is_a|historical event|1.0
civil rights movement|occurred_in|1954-1968|1.0
civil rights movement|description|struggle for racial equality in usa|0.95
algorithm|is_a|procedure|1.0
algorithm|description|step by step instructions to solve a problem|0.95
algorithm|domain_is|computer science|1.0
data structure|is_a|concept|1.0
data structure|description|way of organizing and storing data|0.95
data structure|domain_is|computer science|1.0
recursion|is_a|technique|1.0
recursion|description|function that calls itself|0.95
recursion|domain_is|computer science|1.0
binary search|is_a|algorithm|1.0
binary search|description|divides sorted array in half each step|0.95
binary search|domain_is|computer science|1.0
sorting|is_a|algorithm category|1.0
sorting|description|arranging elements in a specific order|0.95
sorting|domain_is|computer science|1.0
hash table|is_a|data structure|1.0
hash table|description|maps keys to values using hash function|0.95
hash table|domain_is|computer science|1.0
linked list|is_a|data structure|1.0
linked list|description|sequence of nodes with pointers|0.95
linked list|domain_is|computer science|1.0
binary tree|is_a|data structure|1.0
binary tree|description|hierarchical structure with at most two children per node|0.95
binary tree|domain_is|computer science|1.0
stack|is_a|data structure|1.0
stack|description|last in first out collection|0.95
stack|domain_is|computer science|1.0
queue|is_a|data structure|1.0
queue|description|first in first out collection|0.95
queue|domain_is|computer science|1.0
graph|is_a|data structure|1.0
graph|description|nodes connected by edges|0.95
graph|domain_is|computer science|1.0
dynamic programming|is_a|technique|1.0
dynamic programming|description|breaking problems into overlapping subproblems|0.95
dynamic programming|domain_is|computer science|1.0
object oriented programming|is_a|paradigm|1.0
object oriented programming|description|organizing code around objects and classes|0.95
object oriented programming|domain_is|computer science|1.0
functional programming|is_a|paradigm|1.0
functional programming|description|organizing code around pure functions|0.95
functional programming|domain_is|computer science|1.0
machine learning|is_a|field|1.0
machine learning|description|algorithms that improve through experience|0.95
machine learning|domain_is|computer science|1.0
artificial intelligence|is_a|field|1.0
artificial intelligence|description|simulation of human intelligence by machines|0.95
artificial intelligence|domain_is|computer science|1.0
neural network|is_a|model|1.0
neural network|description|computing system inspired by biological neurons|0.95
neural network|domain_is|computer science|1.0
deep learning|is_a|technique|1.0
deep learning|description|neural networks with many layers|0.95
deep learning|domain_is|computer science|1.0
natural language processing|is_a|field|1.0
natural language processing|description|enabling computers to understand human language|0.95
natural language processing|domain_is|computer science|1.0
computer vision|is_a|field|1.0
computer vision|description|enabling computers to interpret visual information|0.95
computer vision|domain_is|computer science|1.0
encryption|is_a|technique|1.0
encryption|description|converting data into unreadable format for security|0.95
encryption|domain_is|computer science|1.0
database|is_a|system|1.0
database|description|organized collection of structured data|0.95
database|domain_is|computer science|1.0
api|is_a|concept|1.0
api|description|application programming interface for software communication|0.95
api|domain_is|computer science|1.0
tcp ip|is_a|protocol|1.0
tcp ip|description|fundamental communication protocol of the internet|0.95
tcp ip|domain_is|computer science|1.0
http|is_a|protocol|1.0
http|description|hypertext transfer protocol for web communication|0.95
http|domain_is|computer science|1.0
