# Famous Scientists and Discoveries
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

albert einstein|is_a|scientist|1.0
albert einstein|field_is|physics|1.0
albert einstein|discovered|theory of relativity|0.95
albert einstein|born_in|1879|1.0
albert einstein|died_in|1955|1.0
albert einstein|from_country|germany|1.0
albert einstein|received|nobel prize in physics|0.95
isaac newton|is_a|scientist|1.0
isaac newton|field_is|physics|1.0
isaac newton|discovered|laws of motion|0.95
isaac newton|born_in|1643|1.0
isaac newton|died_in|1727|1.0
isaac newton|from_country|england|1.0
isaac newton|received|knighthood|0.95
marie curie|is_a|scientist|1.0
marie curie|field_is|chemistry|1.0
marie curie|discovered|radioactivity|0.95
marie curie|born_in|1867|1.0
marie curie|died_in|1934|1.0
marie curie|from_country|poland|1.0
marie curie|received|nobel prize in physics|0.95
charles darwin|is_a|scientist|1.0
charles darwin|field_is|biology|1.0
charles darwin|discovered|theory of evolution|0.95
charles darwin|born_in|1809|1.0
charles darwin|died_in|1882|1.0
charles darwin|from_country|england|1.0
charles darwin|received|royal medal|0.95
nikola tesla|is_a|scientist|1.0
nikola tesla|field_is|engineering|1.0
nikola tesla|discovered|alternating current|0.95
nikola tesla|born_in|1856|1.0
nikola tesla|died_in|1943|1.0
nikola tesla|from_country|serbia|1.0
nikola tesla|received|edison medal|0.95
galileo galilei|is_a|scientist|1.0
galileo galilei|field_is|astronomy|1.0
galileo galilei|discovered|heliocentric model|0.95
galileo galilei|born_in|1564|1.0
galileo galilei|died_in|1642|1.0
galileo galilei|from_country|italy|1.0
stephen hawking|is_a|scientist|1.0
stephen hawking|field_is|physics|1.0
stephen hawking|discovered|hawking radiation|0.95
stephen hawking|born_in|1942|1.0
stephen hawking|died_in|2018|1.0
stephen hawking|from_country|england|1.0
stephen hawking|received|presidential medal of freedom|0.95
richard feynman|is_a|scientist|1.0
richard feynman|field_is|physics|1.0
richard feynman|discovered|quantum electrodynamics|0.95
richard feynman|born_in|1918|1.0
richard feynman|died_in|1988|1.0
richard feynman|from_country|united states|1.0
richard feynman|received|nobel prize in physics|0.95
niels bohr|is_a|scientist|1.0
niels bohr|field_is|physics|1.0
niels bohr|discovered|atomic model|0.95
niels bohr|born_in|1885|1.0
niels bohr|died_in|1962|1.0
niels bohr|from_country|denmark|1.0
niels bohr|received|nobel prize in physics|0.95
max planck|is_a|scientist|1.0
max planck|field_is|physics|1.0
max planck|discovered|quantum theory|0.95
max planck|born_in|1858|1.0
max planck|died_in|1947|1.0
max planck|from_country|germany|1.0
max planck|received|nobel prize in physics|0.95
alan turing|is_a|scientist|1.0
alan turing|field_is|computer science|1.0
alan turing|discovered|turing machine|0.95
alan turing|born_in|1912|1.0
alan turing|died_in|1954|1.0
alan turing|from_country|england|1.0
alan turing|received|order of the british empire|0.95
ada lovelace|is_a|scientist|1.0
ada lovelace|field_is|computer science|1.0
ada lovelace|discovered|first computer program|0.95
ada lovelace|born_in|1815|1.0
ada lovelace|died_in|1852|1.0
ada lovelace|from_country|england|1.0
carl sagan|is_a|scientist|1.0
carl sagan|field_is|astronomy|1.0
carl sagan|discovered|planetary science|0.95
carl sagan|born_in|1934|1.0
carl sagan|died_in|1996|1.0
carl sagan|from_country|united states|1.0
carl sagan|received|pulitzer prize|0.95
james watson|is_a|scientist|1.0
james watson|field_is|biology|1.0
james watson|discovered|dna structure|0.95
james watson|born_in|1928|1.0
james watson|died_in|living|1.0
james watson|from_country|united states|1.0
james watson|received|nobel prize in medicine|0.95
rosalind franklin|is_a|scientist|1.0
rosalind franklin|field_is|chemistry|1.0
rosalind franklin|discovered|dna xray crystallography|0.95
rosalind franklin|born_in|1920|1.0
rosalind franklin|died_in|1958|1.0
rosalind franklin|from_country|england|1.0
erwin schrodinger|is_a|scientist|1.0
erwin schrodinger|field_is|physics|1.0
erwin schrodinger|discovered|wave equation|0.95
erwin schrodinger|born_in|1887|1.0
erwin schrodinger|died_in|1961|1.0
erwin schrodinger|from_country|austria|1.0
erwin schrodinger|received|nobel prize in physics|0.95
werner heisenberg|is_a|scientist|1.0
werner heisenberg|field_is|physics|1.0
werner heisenberg|discovered|uncertainty principle|0.95
werner heisenberg|born_in|1901|1.0
werner heisenberg|died_in|1976|1.0
werner heisenberg|from_country|germany|1.0
werner heisenberg|received|nobel prize in physics|0.95
michael faraday|is_a|scientist|1.0
michael faraday|field_is|physics|1.0
michael faraday|discovered|electromagnetic induction|0.95
michael faraday|born_in|1791|1.0
michael faraday|died_in|1867|1.0
michael faraday|from_country|england|1.0
michael faraday|received|royal medal|0.95
gregor mendel|is_a|scientist|1.0
gregor mendel|field_is|biology|1.0
gregor mendel|discovered|genetics|0.95
gregor mendel|born_in|1822|1.0
gregor mendel|died_in|1884|1.0
gregor mendel|from_country|austria|1.0
louis pasteur|is_a|scientist|1.0
louis pasteur|field_is|biology|1.0
louis pasteur|discovered|pasteurization|0.95
louis pasteur|born_in|1822|1.0
louis pasteur|died_in|1895|1.0
louis pasteur|from_country|france|1.0
louis pasteur|received|legion of honour|0.95
alexander fleming|is_a|scientist|1.0
alexander fleming|field_is|medicine|1.0
alexander fleming|discovered|penicillin|0.95
alexander fleming|born_in|1881|1.0
alexander fleming|died_in|1955|1.0
alexander fleming|from_country|scotland|1.0
alexander fleming|received|nobel prize in medicine|0.95
carl linnaeus|is_a|scientist|1.0
carl linnaeus|field_is|biology|1.0
carl linnaeus|discovered|taxonomy|0.95
carl linnaeus|born_in|1707|1.0
carl linnaeus|died_in|1778|1.0
carl linnaeus|from_country|sweden|1.0
dmitri mendeleev|is_a|scientist|1.0
dmitri mendeleev|field_is|chemistry|1.0
dmitri mendeleev|discovered|periodic table|0.95
dmitri mendeleev|born_in|1834|1.0
dmitri mendeleev|died_in|1907|1.0
dmitri mendeleev|from_country|russia|1.0
dmitri mendeleev|received|davy medal|0.95
thomas edison|is_a|scientist|1.0
thomas edison|field_is|engineering|1.0
thomas edison|discovered|light bulb|0.95
thomas edison|born_in|1847|1.0
thomas edison|died_in|1931|1.0
thomas edison|from_country|united states|1.0
thomas edison|received|congressional gold medal|0.95
archimedes|is_a|scientist|1.0
archimedes|field_is|mathematics|1.0
archimedes|discovered|buoyancy principle|0.95
archimedes|born_in|287 bc|1.0
archimedes|died_in|212 bc|1.0
archimedes|from_country|greece|1.0
pythagoras|is_a|scientist|1.0
pythagoras|field_is|mathematics|1.0
pythagoras|discovered|pythagorean theorem|0.95
pythagoras|born_in|570 bc|1.0
pythagoras|died_in|495 bc|1.0
pythagoras|from_country|greece|1.0
euclid|is_a|scientist|1.0
euclid|field_is|mathematics|1.0
euclid|discovered|euclidean geometry|0.95
euclid|born_in|300 bc|1.0
euclid|died_in|unknown|1.0
euclid|from_country|greece|1.0
leonardo da vinci|is_a|scientist|1.0
leonardo da vinci|field_is|polymath|1.0
leonardo da vinci|discovered|anatomy and engineering|0.95
leonardo da vinci|born_in|1452|1.0
leonardo da vinci|died_in|1519|1.0
leonardo da vinci|from_country|italy|1.0
johannes kepler|is_a|scientist|1.0
johannes kepler|field_is|astronomy|1.0
johannes kepler|discovered|laws of planetary motion|0.95
johannes kepler|born_in|1571|1.0
johannes kepler|died_in|1630|1.0
johannes kepler|from_country|germany|1.0
nicolaus copernicus|is_a|scientist|1.0
nicolaus copernicus|field_is|astronomy|1.0
nicolaus copernicus|discovered|heliocentric model|0.95
nicolaus copernicus|born_in|1473|1.0
nicolaus copernicus|died_in|1543|1.0
nicolaus copernicus|from_country|poland|1.0
