# Animal Kingdom
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

lion|is_a|mammal|1.0
lion|is_a|animal|1.0
lion|diet_is|carnivore|0.95
lion|lives_in|africa|0.9
lion|habitat_is|savanna|0.9
lion|social_structure|pride|0.85
lion|lifespan_is|10-14 years|0.85
lion|has|mane|0.9
lion|has|retractable claws|0.9
lion|has|roar|0.9
elephant|is_a|mammal|1.0
elephant|is_a|animal|1.0
elephant|diet_is|herbivore|0.95
elephant|lives_in|africa|0.9
elephant|habitat_is|savanna|0.9
elephant|social_structure|herd|0.85
elephant|lifespan_is|60-70 years|0.85
elephant|has|trunk|0.9
elephant|has|tusks|0.9
elephant|has|large ears|0.9
eagle|is_a|bird|1.0
eagle|is_a|animal|1.0
eagle|diet_is|carnivore|0.95
eagle|lives_in|worldwide|0.9
eagle|habitat_is|mountains|0.9
eagle|social_structure|pair|0.85
eagle|lifespan_is|20-30 years|0.85
eagle|has|sharp talons|0.9
eagle|has|keen eyesight|0.9
eagle|has|wings|0.9
dolphin|is_a|mammal|1.0
dolphin|is_a|animal|1.0
dolphin|diet_is|carnivore|0.95
dolphin|lives_in|ocean|0.9
dolphin|habitat_is|open water|0.9
dolphin|social_structure|pod|0.85
dolphin|lifespan_is|40-50 years|0.85
dolphin|has|echolocation|0.9
dolphin|has|intelligence|0.9
dolphin|has|fins|0.9
shark|is_a|fish|1.0
shark|is_a|animal|1.0
shark|diet_is|carnivore|0.95
shark|lives_in|ocean|0.9
shark|habitat_is|open water|0.9
shark|social_structure|solitary|0.85
shark|lifespan_is|20-30 years|0.85
shark|has|sharp teeth|0.9
shark|has|cartilage skeleton|0.9
shark|has|electroreception|0.9
penguin|is_a|bird|1.0
penguin|is_a|animal|1.0
penguin|diet_is|carnivore|0.95
penguin|lives_in|antarctica|0.9
penguin|habitat_is|ice|0.9
penguin|social_structure|colony|0.85
penguin|lifespan_is|15-20 years|0.85
penguin|has|flippers|0.9
penguin|has|waterproof feathers|0.9
penguin|has|countershading|0.9
tiger|is_a|mammal|1.0
tiger|is_a|animal|1.0
tiger|diet_is|carnivore|0.95
tiger|lives_in|asia|0.9
tiger|habitat_is|forest|0.9
tiger|social_structure|solitary|0.85
tiger|lifespan_is|10-15 years|0.85
tiger|has|stripes|0.9
tiger|has|retractable claws|0.9
tiger|has|night vision|0.9
wolf|is_a|mammal|1.0
wolf|is_a|animal|1.0
wolf|diet_is|carnivore|0.95
wolf|lives_in|north america|0.9
wolf|habitat_is|forest|0.9
wolf|social_structure|pack|0.85
wolf|lifespan_is|6-8 years|0.85
wolf|has|howl|0.9
wolf|has|pack hunting|0.9
wolf|has|endurance|0.9
bear|is_a|mammal|1.0
bear|is_a|animal|1.0
bear|diet_is|omnivore|0.95
bear|lives_in|north america|0.9
bear|habitat_is|forest|0.9
bear|social_structure|solitary|0.85
bear|lifespan_is|20-30 years|0.85
bear|has|hibernation|0.9
bear|has|strong claws|0.9
bear|has|excellent smell|0.9
whale|is_a|mammal|1.0
whale|is_a|animal|1.0
whale|diet_is|varies|0.95
whale|lives_in|ocean|0.9
whale|habitat_is|deep water|0.9
whale|social_structure|pod|0.85
whale|lifespan_is|50-90 years|0.85
whale|has|blowhole|0.9
whale|has|echolocation|0.9
whale|has|baleen|0.9
cheetah|is_a|mammal|1.0
cheetah|is_a|animal|1.0
cheetah|diet_is|carnivore|0.95
cheetah|lives_in|africa|0.9
cheetah|habitat_is|savanna|0.9
cheetah|social_structure|coalition|0.85
cheetah|lifespan_is|10-12 years|0.85
cheetah|has|speed|0.9
cheetah|has|spotted coat|0.9
cheetah|has|non-retractable claws|0.9
gorilla|is_a|mammal|1.0
gorilla|is_a|animal|1.0
gorilla|diet_is|herbivore|0.95
gorilla|lives_in|africa|0.9
gorilla|habitat_is|rainforest|0.9
gorilla|social_structure|troop|0.85
gorilla|lifespan_is|35-40 years|0.85
gorilla|has|intelligence|0.9
gorilla|has|knuckle walking|0.9
gorilla|has|silverback|0.9
octopus|is_a|mollusk|1.0
octopus|is_a|animal|1.0
octopus|diet_is|carnivore|0.95
octopus|lives_in|ocean|0.9
octopus|habitat_is|coral reef|0.9
octopus|social_structure|solitary|0.85
octopus|lifespan_is|1-5 years|0.85
octopus|has|eight arms|0.9
octopus|has|camouflage|0.9
octopus|has|intelligence|0.9
cobra|is_a|reptile|1.0
cobra|is_a|animal|1.0
cobra|diet_is|carnivore|0.95
cobra|lives_in|asia|0.9
cobra|habitat_is|forest|0.9
cobra|social_structure|solitary|0.85
cobra|lifespan_is|20 years|0.85
cobra|has|venom|0.9
cobra|has|hood|0.9
cobra|has|heat sensing|0.9
crocodile|is_a|reptile|1.0
crocodile|is_a|animal|1.0
crocodile|diet_is|carnivore|0.95
crocodile|lives_in|tropics|0.9
crocodile|habitat_is|rivers|0.9
crocodile|social_structure|solitary|0.85
crocodile|lifespan_is|70-100 years|0.85
crocodile|has|armored skin|0.9
crocodile|has|powerful jaws|0.9
crocodile|has|stealth|0.9
kangaroo|is_a|mammal|1.0
kangaroo|is_a|animal|1.0
kangaroo|diet_is|herbivore|0.95
kangaroo|lives_in|australia|0.9
kangaroo|habitat_is|grassland|0.9
kangaroo|social_structure|mob|0.85
kangaroo|lifespan_is|12-18 years|0.85
kangaroo|has|pouch|0.9
kangaroo|has|powerful legs|0.9
kangaroo|has|jumping|0.9
panda|is_a|mammal|1.0
panda|is_a|animal|1.0
panda|diet_is|herbivore|0.95
panda|lives_in|china|0.9
panda|habitat_is|bamboo forest|0.9
panda|social_structure|solitary|0.85
panda|lifespan_is|20 years|0.85
panda|has|black and white fur|0.9
panda|has|bamboo diet|0.9
panda|has|thumb|0.9
giraffe|is_a|mammal|1.0
giraffe|is_a|animal|1.0
giraffe|diet_is|herbivore|0.95
giraffe|lives_in|africa|0.9
giraffe|habitat_is|savanna|0.9
giraffe|social_structure|tower|0.85
giraffe|lifespan_is|25 years|0.85
giraffe|has|long neck|0.9
giraffe|has|spotted pattern|0.9
giraffe|has|blue tongue|0.9
owl|is_a|bird|1.0
owl|is_a|animal|1.0
owl|diet_is|carnivore|0.95
owl|lives_in|worldwide|0.9
owl|habitat_is|forest|0.9
owl|social_structure|solitary|0.85
owl|lifespan_is|10-20 years|0.85
owl|has|night vision|0.9
owl|has|silent flight|0.9
owl|has|rotating head|0.9
parrot|is_a|bird|1.0
parrot|is_a|animal|1.0
parrot|diet_is|omnivore|0.95
parrot|lives_in|tropics|0.9
parrot|habitat_is|rainforest|0.9
parrot|social_structure|flock|0.85
parrot|lifespan_is|40-80 years|0.85
parrot|has|speech mimicry|0.9
parrot|has|colorful feathers|0.9
parrot|has|intelligence|0.9
