# Programming Languages & Frameworks
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

python|is_a|programming language|1.0
python|created_by|guido van rossum|1.0
python|created_in|1991|1.0
python|paradigm_is|multi-paradigm|0.9
python|typing_is|dynamically typed|1.0
python|used_for|web development|0.9
python|has_feature|list comprehension|0.85
python|has_feature|generators|0.85
python|has_feature|decorators|0.85
python|has_feature|duck typing|0.85
javascript|is_a|programming language|1.0
javascript|created_by|brendan eich|1.0
javascript|created_in|1995|1.0
javascript|paradigm_is|multi-paradigm|0.9
javascript|typing_is|dynamically typed|1.0
javascript|used_for|web development|0.9
javascript|has_feature|closures|0.85
javascript|has_feature|prototypal inheritance|0.85
javascript|has_feature|async await|0.85
javascript|has_feature|event loop|0.85
java|is_a|programming language|1.0
java|created_by|james gosling|1.0
java|created_in|1995|1.0
java|paradigm_is|object oriented|0.9
java|typing_is|statically typed|1.0
java|used_for|enterprise applications|0.9
java|has_feature|garbage collection|0.85
java|has_feature|jvm|0.85
java|has_feature|generics|0.85
java|has_feature|interfaces|0.85
c++|is_a|programming language|1.0
c++|created_by|bjarne stroustrup|1.0
c++|created_in|1985|1.0
c++|paradigm_is|multi-paradigm|0.9
c++|typing_is|statically typed|1.0
c++|used_for|system programming|0.9
c++|has_feature|templates|0.85
c++|has_feature|raii|0.85
c++|has_feature|operator overloading|0.85
c++|has_feature|multiple inheritance|0.85
rust|is_a|programming language|1.0
rust|created_by|graydon hoare|1.0
rust|created_in|2010|1.0
rust|paradigm_is|multi-paradigm|0.9
rust|typing_is|statically typed|1.0
rust|used_for|system programming|0.9
rust|has_feature|ownership system|0.85
rust|has_feature|borrowing|0.85
rust|has_feature|zero cost abstractions|0.85
rust|has_feature|pattern matching|0.85
c|is_a|programming language|1.0
c|created_by|dennis ritchie|1.0
c|created_in|1972|1.0
c|paradigm_is|procedural|0.9
c|typing_is|statically typed|1.0
c|used_for|operating systems|0.9
c|has_feature|pointers|0.85
c|has_feature|manual memory management|0.85
c|has_feature|preprocessor|0.85
c|has_feature|structs|0.85
go|is_a|programming language|1.0
go|created_by|rob pike|1.0
go|created_in|2009|1.0
go|paradigm_is|concurrent|0.9
go|typing_is|statically typed|1.0
go|used_for|cloud infrastructure|0.9
go|has_feature|goroutines|0.85
go|has_feature|channels|0.85
go|has_feature|garbage collection|0.85
go|has_feature|interfaces|0.85
swift|is_a|programming language|1.0
swift|created_by|chris lattner|1.0
swift|created_in|2014|1.0
swift|paradigm_is|multi-paradigm|0.9
swift|typing_is|statically typed|1.0
swift|used_for|ios development|0.9
swift|has_feature|optionals|0.85
swift|has_feature|protocol oriented|0.85
swift|has_feature|type inference|0.85
swift|has_feature|closures|0.85
kotlin|is_a|programming language|1.0
kotlin|created_by|jetbrains|1.0
kotlin|created_in|2011|1.0
kotlin|paradigm_is|multi-paradigm|0.9
kotlin|typing_is|statically typed|1.0
kotlin|used_for|android development|0.9
kotlin|has_feature|null safety|0.85
kotlin|has_feature|coroutines|0.85
kotlin|has_feature|extension functions|0.85
kotlin|has_feature|data classes|0.85
typescript|is_a|programming language|1.0
typescript|created_by|anders hejlsberg|1.0
typescript|created_in|2012|1.0
typescript|paradigm_is|multi-paradigm|0.9
typescript|typing_is|statically typed|1.0
typescript|used_for|web development|0.9
typescript|has_feature|type annotations|0.85
typescript|has_feature|interfaces|0.85
typescript|has_feature|generics|0.85
typescript|has_feature|union types|0.85
ruby|is_a|programming language|1.0
ruby|created_by|yukihiro matsumoto|1.0
ruby|created_in|1995|1.0
ruby|paradigm_is|object oriented|0.9
ruby|typing_is|dynamically typed|1.0
ruby|used_for|web development|0.9
ruby|has_feature|blocks|0.85
ruby|has_feature|mixins|0.85
ruby|has_feature|metaprogramming|0.85
ruby|has_feature|duck typing|0.85
php|is_a|programming language|1.0
php|created_by|rasmus lerdorf|1.0
php|created_in|1995|1.0
php|paradigm_is|multi-paradigm|0.9
php|typing_is|dynamically typed|1.0
php|used_for|web development|0.9
php|has_feature|templating|0.85
php|has_feature|arrays|0.85
php|has_feature|namespaces|0.85
php|has_feature|traits|0.85
scala|is_a|programming language|1.0
scala|created_by|martin odersky|1.0
scala|created_in|2004|1.0
scala|paradigm_is|functional|0.9
scala|typing_is|statically typed|1.0
scala|used_for|data processing|0.9
scala|has_feature|pattern matching|0.85
scala|has_feature|traits|0.85
scala|has_feature|implicits|0.85
scala|has_feature|case classes|0.85
haskell|is_a|programming language|1.0
haskell|created_by|committee|1.0
haskell|created_in|1990|1.0
haskell|paradigm_is|functional|0.9
haskell|typing_is|statically typed|1.0
haskell|used_for|academic research|0.9
haskell|has_feature|lazy evaluation|0.85
haskell|has_feature|monads|0.85
haskell|has_feature|type classes|0.85
haskell|has_feature|pattern matching|0.85
elixir|is_a|programming language|1.0
elixir|created_by|jose valim|1.0
elixir|created_in|2011|1.0
elixir|paradigm_is|functional|0.9
elixir|typing_is|dynamically typed|1.0
elixir|used_for|distributed systems|0.9
elixir|has_feature|pattern matching|0.85
elixir|has_feature|pipe operator|0.85
elixir|has_feature|processes|0.85
elixir|has_feature|supervision trees|0.85
react|is_a|frontend framework|1.0
react|written_in|javascript|1.0
react|created_by|meta|0.95
react|used_for|software development|0.9
angular|is_a|frontend framework|1.0
angular|written_in|typescript|1.0
angular|created_by|google|0.95
angular|used_for|software development|0.9
vue|is_a|frontend framework|1.0
vue|written_in|javascript|1.0
vue|created_by|evan you|0.95
vue|used_for|software development|0.9
django|is_a|web framework|1.0
django|written_in|python|1.0
django|created_by|adrian holovaty|0.95
django|used_for|software development|0.9
flask|is_a|web framework|1.0
flask|written_in|python|1.0
flask|created_by|armin ronacher|0.95
flask|used_for|software development|0.9
spring|is_a|application framework|1.0
spring|written_in|java|1.0
spring|created_by|rod johnson|0.95
spring|used_for|software development|0.9
express|is_a|web framework|1.0
express|written_in|javascript|1.0
express|created_by|tj holowaychuk|0.95
express|used_for|software development|0.9
rails|is_a|web framework|1.0
rails|written_in|ruby|1.0
rails|created_by|david heinemeier hansson|0.95
rails|used_for|software development|0.9
laravel|is_a|web framework|1.0
laravel|written_in|php|1.0
laravel|created_by|taylor otwell|0.95
laravel|used_for|software development|0.9
dotnet|is_a|application framework|1.0
dotnet|written_in|c sharp|1.0
dotnet|created_by|microsoft|0.95
dotnet|used_for|software development|0.9
fastapi|is_a|web framework|1.0
fastapi|written_in|python|1.0
fastapi|created_by|sebastian ramirez|0.95
fastapi|used_for|software development|0.9
nextjs|is_a|fullstack framework|1.0
nextjs|written_in|javascript|1.0
nextjs|created_by|vercel|0.95
nextjs|used_for|software development|0.9
svelte|is_a|frontend framework|1.0
svelte|written_in|javascript|1.0
svelte|created_by|rich harris|0.95
svelte|used_for|software development|0.9
pytorch|is_a|machine learning framework|1.0
pytorch|written_in|python|1.0
pytorch|created_by|meta|0.95
pytorch|used_for|software development|0.9
tensorflow|is_a|machine learning framework|1.0
tensorflow|written_in|python|1.0
tensorflow|created_by|google|0.95
tensorflow|used_for|software development|0.9
pandas|is_a|data analysis library|1.0
pandas|written_in|python|1.0
pandas|created_by|wes mckinney|0.95
pandas|used_for|software development|0.9
numpy|is_a|numerical computing library|1.0
numpy|written_in|python|1.0
numpy|created_by|travis oliphant|0.95
numpy|used_for|software development|0.9
