# Music Genres and Artists
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

rock|is_a|music genre|1.0
rock|originated_in|1950s|0.9
rock|characterized_by|electric guitar|0.9
led zeppelin|plays|rock|0.95
led zeppelin|is_a|musician|1.0
the beatles|plays|rock|0.95
the beatles|is_a|musician|1.0
pink floyd|plays|rock|0.95
pink floyd|is_a|musician|1.0
queen|plays|rock|0.95
queen|is_a|musician|1.0
nirvana|plays|rock|0.95
nirvana|is_a|musician|1.0
jazz|is_a|music genre|1.0
jazz|originated_in|1900s|0.9
jazz|characterized_by|improvisation|0.9
miles davis|plays|jazz|0.95
miles davis|is_a|musician|1.0
john coltrane|plays|jazz|0.95
john coltrane|is_a|musician|1.0
louis armstrong|plays|jazz|0.95
louis armstrong|is_a|musician|1.0
duke ellington|plays|jazz|0.95
duke ellington|is_a|musician|1.0
charlie parker|plays|jazz|0.95
charlie parker|is_a|musician|1.0
classical|is_a|music genre|1.0
classical|originated_in|1600s|0.9
classical|characterized_by|orchestra|0.9
beethoven|plays|classical|0.95
beethoven|is_a|musician|1.0
mozart|plays|classical|0.95
mozart|is_a|musician|1.0
bach|plays|classical|0.95
bach|is_a|musician|1.0
chopin|plays|classical|0.95
chopin|is_a|musician|1.0
tchaikovsky|plays|classical|0.95
tchaikovsky|is_a|musician|1.0
hip hop|is_a|music genre|1.0
hip hop|originated_in|1970s|0.9
hip hop|characterized_by|rapping|0.9
tupac|plays|hip hop|0.95
tupac|is_a|musician|1.0
notorious big|plays|hip hop|0.95
notorious big|is_a|musician|1.0
jay z|plays|hip hop|0.95
jay z|is_a|musician|1.0
kendrick lamar|plays|hip hop|0.95
kendrick lamar|is_a|musician|1.0
eminem|plays|hip hop|0.95
eminem|is_a|musician|1.0
electronic|is_a|music genre|1.0
electronic|originated_in|1970s|0.9
electronic|characterized_by|synthesizer|0.9
kraftwerk|plays|electronic|0.95
kraftwerk|is_a|musician|1.0
daft punk|plays|electronic|0.95
daft punk|is_a|musician|1.0
deadmau5|plays|electronic|0.95
deadmau5|is_a|musician|1.0
aphex twin|plays|electronic|0.95
aphex twin|is_a|musician|1.0
skrillex|plays|electronic|0.95
skrillex|is_a|musician|1.0
blues|is_a|music genre|1.0
blues|originated_in|1860s|0.9
blues|characterized_by|twelve bar|0.9
bb king|plays|blues|0.95
bb king|is_a|musician|1.0
muddy waters|plays|blues|0.95
muddy waters|is_a|musician|1.0
robert johnson|plays|blues|0.95
robert johnson|is_a|musician|1.0
howlin wolf|plays|blues|0.95
howlin wolf|is_a|musician|1.0
john lee hooker|plays|blues|0.95
john lee hooker|is_a|musician|1.0
country|is_a|music genre|1.0
country|originated_in|1920s|0.9
country|characterized_by|acoustic guitar|0.9
johnny cash|plays|country|0.95
johnny cash|is_a|musician|1.0
dolly parton|plays|country|0.95
dolly parton|is_a|musician|1.0
willie nelson|plays|country|0.95
willie nelson|is_a|musician|1.0
hank williams|plays|country|0.95
hank williams|is_a|musician|1.0
garth brooks|plays|country|0.95
garth brooks|is_a|musician|1.0
reggae|is_a|music genre|1.0
reggae|originated_in|1960s|0.9
reggae|characterized_by|offbeat rhythm|0.9
bob marley|plays|reggae|0.95
bob marley|is_a|musician|1.0
peter tosh|plays|reggae|0.95
peter tosh|is_a|musician|1.0
jimmy cliff|plays|reggae|0.95
jimmy cliff|is_a|musician|1.0
toots hibbert|plays|reggae|0.95
toots hibbert|is_a|musician|1.0
burning spear|plays|reggae|0.95
burning spear|is_a|musician|1.0
metal|is_a|music genre|1.0
metal|originated_in|1960s|0.9
metal|characterized_by|distortion|0.9
black sabbath|plays|metal|0.95
black sabbath|is_a|musician|1.0
metallica|plays|metal|0.95
metallica|is_a|musician|1.0
iron maiden|plays|metal|0.95
iron maiden|is_a|musician|1.0
slayer|plays|metal|0.95
slayer|is_a|musician|1.0
megadeth|plays|metal|0.95
megadeth|is_a|musician|1.0
pop|is_a|music genre|1.0
pop|originated_in|1950s|0.9
pop|characterized_by|catchy melodies|0.9
michael jackson|plays|pop|0.95
michael jackson|is_a|musician|1.0
madonna|plays|pop|0.95
madonna|is_a|musician|1.0
prince|plays|pop|0.95
prince|is_a|musician|1.0
taylor swift|plays|pop|0.95
taylor swift|is_a|musician|1.0
beyonce|plays|pop|0.95
beyonce|is_a|musician|1.0
rnb|is_a|music genre|1.0
rnb|originated_in|1940s|0.9
rnb|characterized_by|rhythm and blues|0.9
stevie wonder|plays|rnb|0.95
stevie wonder|is_a|musician|1.0
marvin gaye|plays|rnb|0.95
marvin gaye|is_a|musician|1.0
aretha franklin|plays|rnb|0.95
aretha franklin|is_a|musician|1.0
whitney houston|plays|rnb|0.95
whitney houston|is_a|musician|1.0
usher|plays|rnb|0.95
usher|is_a|musician|1.0
punk|is_a|music genre|1.0
punk|originated_in|1970s|0.9
punk|characterized_by|fast tempo|0.9
the ramones|plays|punk|0.95
the ramones|is_a|musician|1.0
sex pistols|plays|punk|0.95
sex pistols|is_a|musician|1.0
the clash|plays|punk|0.95
the clash|is_a|musician|1.0
dead kennedys|plays|punk|0.95
dead kennedys|is_a|musician|1.0
bad religion|plays|punk|0.95
bad religion|is_a|musician|1.0
folk|is_a|music genre|1.0
folk|originated_in|traditional|0.9
folk|characterized_by|acoustic instruments|0.9
bob dylan|plays|folk|0.95
bob dylan|is_a|musician|1.0
woody guthrie|plays|folk|0.95
woody guthrie|is_a|musician|1.0
joan baez|plays|folk|0.95
joan baez|is_a|musician|1.0
joni mitchell|plays|folk|0.95
joni mitchell|is_a|musician|1.0
pete seeger|plays|folk|0.95
pete seeger|is_a|musician|1.0
soul|is_a|music genre|1.0
soul|originated_in|1950s|0.9
soul|characterized_by|vocal emotion|0.9
james brown|plays|soul|0.95
james brown|is_a|musician|1.0
otis redding|plays|soul|0.95
otis redding|is_a|musician|1.0
sam cooke|plays|soul|0.95
sam cooke|is_a|musician|1.0
ray charles|plays|soul|0.95
ray charles|is_a|musician|1.0
al green|plays|soul|0.95
al green|is_a|musician|1.0
