# MK Knowledge File - World History and Politics
# Format: source|relation|target|weight
# Covers: civilizations, wars, political systems, international organizations

# === ANCIENT CIVILIZATIONS ===
mesopotamia|is_a|cradle_of_civilization|1.0
mesopotamia|located_in|modern_iraq|1.0
mesopotamia|invented|writing_cuneiform|1.0
sumer|is_a|mesopotamian_civilization|1.0
babylon|is_a|mesopotamian_city|1.0
hammurabi|created|first_written_law_code|1.0
ancient_egypt|lasted|3000_years|1.0
ancient_egypt|built|pyramids_of_giza|1.0
pharaoh|was|egyptian_ruler|1.0
nile_river|enabled|egyptian_agriculture|1.0
hieroglyphics|was|egyptian_writing_system|1.0
ancient_greece|birthplace_of|democracy|1.0
athens|invented|direct_democracy|1.0
sparta|was|military_society|1.0
alexander_the_great|conquered|persian_empire|1.0
aristotle|is_a|greek_philosopher|1.0
plato|is_a|greek_philosopher|1.0
socrates|is_a|greek_philosopher|1.0
roman_empire|lasted|from_27bc_to_476ad|1.0
roman_empire|built|roads_aqueducts_colosseum|1.0
julius_caesar|assassinated|44_bc|1.0
fall_of_rome|year|476_ad|1.0
indus_valley|is_a|ancient_civilization|1.0
indus_valley|located_in|modern_pakistan_india|1.0
ancient_china|dynasties|shang_zhou_qin_han_tang_song_ming_qing|1.0
great_wall|built_by|chinese_dynasties|1.0
silk_road|connected|east_and_west|1.0
persian_empire|founded_by|cyrus_the_great|1.0
ottoman_empire|lasted|1299_to_1922|1.0
mongol_empire|largest|contiguous_land_empire|1.0
genghis_khan|founded|mongol_empire|1.0
maya_civilization|developed|advanced_astronomy|1.0
aztec_empire|capital|tenochtitlan|1.0
inca_empire|located_in|south_america|1.0

# === MAJOR WARS ===
world_war_1|lasted|1914_to_1918|1.0
world_war_1|caused_by|assassination_of_archduke_ferdinand|0.8
world_war_1|casualties|about_20_million|1.0
world_war_1|introduced|trench_warfare|1.0
world_war_2|lasted|1939_to_1945|1.0
world_war_2|casualties|about_70_to_85_million|1.0
world_war_2|ended_with|atomic_bombs_on_japan|1.0
holocaust|killed|6_million_jews|1.0
cold_war|lasted|1947_to_1991|1.0
cold_war|between|usa_and_soviet_union|1.0
cold_war|threat|nuclear_annihilation|1.0
korean_war|lasted|1950_to_1953|1.0
vietnam_war|lasted|1955_to_1975|1.0
american_civil_war|lasted|1861_to_1865|1.0
american_civil_war|about|slavery_and_union|1.0
napoleonic_wars|lasted|1803_to_1815|1.0
hundred_years_war|lasted|1337_to_1453|1.0
crusades|lasted|1096_to_1291|1.0
american_revolution|year|1776|1.0
french_revolution|year|1789|1.0
russian_revolution|year|1917|1.0
chinese_civil_war|ended|1949|1.0
gulf_war|year|1991|1.0
war_on_terror|started|2001|1.0
treaty_of_versailles|ended|world_war_1|1.0

# === REVOLUTIONS AND MOVEMENTS ===
industrial_revolution|began_in|18th_century_britain|1.0
industrial_revolution|introduced|mechanized_production|1.0
enlightenment|promoted|reason_and_individual_rights|1.0
renaissance|revived|classical_learning|1.0
reformation|challenged|catholic_church_authority|1.0
martin_luther|posted|95_theses_1517|1.0
scientific_revolution|established|scientific_method|1.0
abolition_movement|ended|slavery|1.0
civil_rights_movement|fought_for|racial_equality|1.0
martin_luther_king|led|us_civil_rights_movement|1.0
suffrage_movement|won|women_right_to_vote|1.0
decolonization|freed|colonies_from_empires|1.0
arab_spring|began|2010_2011|1.0
fall_of_berlin_wall|year|1989|1.0
fall_of_berlin_wall|symbolized|end_of_cold_war|1.0
dissolution_of_ussr|year|1991|1.0
apartheid|ended_in|south_africa_1994|1.0
nelson_mandela|first|black_president_south_africa|1.0
gandhi|led|indian_independence_movement|1.0
meiji_restoration|modernized|japan_1868|1.0

# === POLITICAL SYSTEMS ===
democracy|is_a|political_system|1.0
democracy|means|rule_by_the_people|1.0
direct_democracy|citizens|vote_on_all_issues|1.0
representative_democracy|citizens|elect_representatives|1.0
presidential_system|has|separate_executive_and_legislature|1.0
parliamentary_system|executive|derives_from_legislature|1.0
constitutional_monarchy|monarch|has_limited_powers|1.0
absolute_monarchy|monarch|has_unlimited_power|1.0
authoritarianism|concentrates|power_in_one_leader_or_group|1.0
totalitarianism|controls|all_aspects_of_life|1.0
fascism|is_a|authoritarian_nationalist_ideology|1.0
communism|advocates|collective_ownership|1.0
socialism|advocates|social_ownership_of_production|1.0
capitalism|is_a|free_market_system|1.0
libertarianism|minimizes|government_intervention|1.0
anarchism|opposes|all_forms_of_government|1.0
federalism|divides|power_between_levels|1.0
unitary_state|concentrates|power_centrally|1.0
confederation|loose|association_of_states|1.0
theocracy|governed_by|religious_authority|1.0
oligarchy|ruled_by|small_elite_group|1.0
plutocracy|ruled_by|the_wealthy|1.0
meritocracy|advancement_based_on|ability|1.0
separation_of_powers|divides|executive_legislative_judicial|1.0
checks_and_balances|prevents|power_concentration|1.0
rule_of_law|means|everyone_subject_to_law|1.0
civil_liberties|protect|individual_freedoms|1.0
bill_of_rights|enumerates|fundamental_rights|1.0
constitution|is_a|supreme_law_document|1.0
amendment|changes|constitution|1.0

# === INTERNATIONAL ORGANIZATIONS ===
united_nations|founded|1945|1.0
united_nations|members|193_countries|1.0
un_security_council|has|5_permanent_members|1.0
un_general_assembly|forum_for|all_member_states|1.0
nato|stands_for|north_atlantic_treaty_organization|1.0
nato|founded|1949|1.0
nato|principle|collective_defense|1.0
european_union|founded|1993_maastricht|1.0
european_union|members|27_countries|1.0
european_union|has|single_market|1.0
wto|stands_for|world_trade_organization|1.0
wto|regulates|international_trade|1.0
imf|provides|financial_stability|1.0
world_bank|provides|development_financing|1.0
who|coordinates|global_health|1.0
icc|stands_for|international_criminal_court|1.0
icj|stands_for|international_court_of_justice|1.0
g7|is|group_of_7_major_economies|1.0
g20|is|group_of_20_major_economies|1.0
brics|stands_for|brazil_russia_india_china_south_africa|1.0
asean|is|association_of_southeast_asian_nations|1.0
african_union|represents|55_african_states|1.0
opec|controls|oil_production_quotas|1.0
red_cross|provides|humanitarian_aid|1.0
amnesty_international|monitors|human_rights|1.0

# === MODERN GEOPOLITICS ===
us_china_rivalry|defines|21st_century_geopolitics|0.9
south_china_sea|disputed_territory|multiple_nations|1.0
taiwan_strait|geopolitical|flashpoint|0.9
ukraine_russia_conflict|began|2014_escalated_2022|1.0
nuclear_proliferation|concern|more_states_with_nukes|0.9
npt|stands_for|non_proliferation_treaty|1.0
sanctions|tool_of|economic_pressure|1.0
soft_power|influence_through|culture_and_diplomacy|1.0
hard_power|influence_through|military_and_economy|1.0
globalization|integrates|world_economies|1.0
nationalism|prioritizes|national_interests|1.0
populism|appeals_to|common_people_vs_elite|1.0
terrorism|uses|violence_for_political_goals|1.0
cybersecurity|is_a|national_security_issue|1.0
climate_diplomacy|negotiates|emissions_reduction|1.0
paris_agreement|aims_to|limit_warming_to_1.5c|1.0
refugee_crisis|displaces|millions_worldwide|1.0
human_rights|universal_declaration|1948|1.0
geneva_conventions|protect|civilians_and_prisoners_of_war|1.0
sovereignty|is|supreme_authority_within_territory|1.0
self_determination|right_of|peoples_to_choose_government|1.0
diplomatic_immunity|protects|foreign_diplomats|1.0
embargo|is_a|trade_restriction|1.0
coup_detat|is|sudden_seizure_of_power|1.0
failed_state|cannot|maintain_order|1.0
proxy_war|is|conflict_between_outside_powers|1.0
arms_race|competitive|military_buildup|1.0
deterrence|prevents|attack_through_threatened_retaliation|1.0
mutually_assured_destruction|prevents|nuclear_war|0.8
space_race|competition|between_us_and_ussr|1.0

# === POLITICAL THEORY ===
social_contract|theory|people_consent_to_governance|1.0
john_locke|advocated|natural_rights_life_liberty_property|1.0
thomas_hobbes|advocated|strong_sovereign|1.0
rousseau|advocated|general_will|1.0
montesquieu|advocated|separation_of_powers|1.0
machiavelli|wrote|the_prince|1.0
karl_marx|wrote|das_kapital|1.0
adam_smith|wrote|wealth_of_nations|1.0
john_rawls|proposed|veil_of_ignorance|1.0
hannah_arendt|studied|totalitarianism|1.0
realism|in_ir|states_pursue_power|1.0
liberalism|in_ir|cooperation_through_institutions|1.0
constructivism|in_ir|ideas_shape_world_politics|1.0
balance_of_power|prevents|hegemony|1.0
hegemony|is|dominant_power_status|1.0
multipolarity|multiple|great_powers|1.0
unipolarity|single|dominant_power|1.0
bipolarity|two|dominant_powers|1.0

# === GOVERNANCE AND LAW ===
constitutional_law|governs|government_structure|1.0
criminal_law|prohibits|harmful_behavior|1.0
civil_law|resolves|private_disputes|1.0
international_law|governs|relations_between_states|1.0
common_law|based_on|precedent_and_custom|1.0
civil_law_system|based_on|codified_statutes|1.0
sharia_law|based_on|islamic_principles|1.0
judiciary|interprets|law|1.0
legislature|makes|law|1.0
executive|enforces|law|1.0
supreme_court|is|highest_court|1.0
judicial_review|checks|constitutionality_of_laws|1.0
habeas_corpus|protects|against_unlawful_detention|1.0
due_process|ensures|fair_legal_procedures|1.0
presumption_of_innocence|until|proven_guilty|1.0
freedom_of_speech|protected_by|first_amendment_us|1.0
freedom_of_press|essential_for|democracy|1.0
right_to_privacy|increasingly|important_in_digital_age|1.0
electoral_system|types|fptp_proportional_ranked|1.0
first_past_the_post|winner_takes|all_in_district|1.0
proportional_representation|seats_match|vote_share|1.0
gerrymandering|manipulates|electoral_boundaries|1.0
lobbying|attempts_to|influence_legislation|1.0
political_party|organizes|people_around_ideology|1.0
coalition_government|formed_by|multiple_parties|1.0

# === ECONOMIC HISTORY ===
gold_standard|backed|currency_with_gold|1.0
bretton_woods|established|post_ww2_monetary_system|1.0
nixon_shock|ended|gold_standard_1971|1.0
great_depression|lasted|1929_to_1939|1.0
great_depression|caused_by|stock_market_crash_bank_failures|1.0
marshall_plan|rebuilt|post_ww2_europe|1.0
opec_oil_crisis|year|1973|1.0
dot_com_bubble|burst|2000|1.0
2008_financial_crisis|triggered_by|subprime_mortgage_collapse|1.0
eurozone_debt_crisis|affected|greece_spain_portugal|1.0
quantitative_easing|introduced_after|2008_crisis|1.0
bitcoin_created|year|2009|1.0
trade_war|uses|tariffs_as_weapons|1.0
free_trade_agreement|removes|trade_barriers|1.0
nafta|became|usmca_2020|1.0
world_bank|established|1944|1.0
imf|established|1944|1.0
washington_consensus|advocated|free_market_policies|1.0

# === COLONIALISM AND IMPERIALISM ===
british_empire|was|largest_empire_in_history|1.0
spanish_empire|colonized|americas|1.0
scramble_for_africa|divided|africa_among_europeans|1.0
berlin_conference|year|1884_1885|1.0
decolonization|peaked_in|1960s|1.0
partition_of_india|year|1947|1.0
suez_crisis|year|1956|1.0
post_colonialism|studies|effects_of_colonization|1.0
neocolonialism|influence_through|economic_dependency|1.0
reparations|demanded_for|historical_injustices|0.8

# === MODERN HISTORY EVENTS ===
moon_landing|year|1969|1.0
chernobyl_disaster|year|1986|1.0
tiananmen_square|year|1989|1.0
rwandan_genocide|year|1994|1.0
september_11|year|2001|1.0
arab_spring|year|2011|1.0
brexit|year|2016_referendum|1.0
covid_pandemic|year|2020|1.0
fukushima_disaster|year|2011|1.0
syrian_civil_war|began|2011|1.0
climate_protests|led_by|greta_thunberg_2018|1.0
hong_kong_protests|year|2019|1.0
metoo_movement|began|2017|1.0
black_lives_matter|founded|2013|1.0
occupy_wall_street|year|2011|1.0
edward_snowden|revealed|nsa_surveillance_2013|1.0
wikileaks|published|classified_documents|1.0
panama_papers|exposed|offshore_tax_evasion_2016|1.0

# === PHILOSOPHY OF GOVERNANCE ===
utilitarianism|maximizes|greatest_good_for_greatest_number|1.0
deontology|follows|moral_rules_regardless_of_outcome|1.0
virtue_ethics|develops|moral_character|1.0
libertarian_paternalism|nudges|toward_good_choices|1.0
communitarianism|emphasizes|community_over_individual|1.0
cosmopolitanism|considers|all_humans_one_community|1.0
just_war_theory|criteria_for|morally_justified_war|1.0
pacifism|opposes|all_war_and_violence|1.0
civil_disobedience|nonviolent|resistance_to_unjust_law|1.0
political_philosophy|asks|how_should_society_be_organized|1.0
distributive_justice|concerns|fair_allocation_of_resources|1.0
retributive_justice|punishes|wrongdoers|1.0
restorative_justice|repairs|harm_done|1.0
procedural_justice|ensures|fair_processes|1.0

# === WORLD RELIGIONS ===
christianity|followers|about_2.4_billion|1.0
islam|followers|about_1.9_billion|1.0
hinduism|followers|about_1.2_billion|1.0
buddhism|followers|about_500_million|1.0
judaism|followers|about_15_million|1.0
sikhism|followers|about_30_million|1.0
protestant_reformation|split|christianity|1.0
sunni_shia_split|divides|islam|1.0
secular_state|separates|religion_from_government|1.0
religious_freedom|is_a|fundamental_right|1.0

# === KEY HISTORICAL FIGURES ===
julius_caesar|role|roman_dictator|1.0
cleopatra|ruled|ancient_egypt|1.0
charlemagne|united|western_europe|1.0
napoleon_bonaparte|emperor_of|france|1.0
queen_victoria|ruled|british_empire|1.0
abraham_lincoln|ended|slavery_in_us|1.0
winston_churchill|led|britain_in_ww2|1.0
franklin_roosevelt|led|us_in_ww2|1.0
mao_zedong|founded|peoples_republic_of_china|1.0
joseph_stalin|ruled|soviet_union|1.0
adolf_hitler|caused|world_war_2_and_holocaust|1.0
mahatma_gandhi|used|nonviolent_resistance|1.0
nelson_mandela|ended|apartheid_in_south_africa|1.0
martin_luther_king_jr|fought_for|civil_rights|1.0
che_guevara|symbol_of|revolution|1.0
fidel_castro|led|cuban_revolution|1.0
mikhail_gorbachev|reformed|soviet_union|1.0
deng_xiaoping|reformed|china_economy|1.0
margaret_thatcher|pm_of|uk_1979_to_1990|1.0
ronald_reagan|president_of|us_1981_to_1989|1.0

# === MEDIA AND INFORMATION ===
printing_press|invented_by|gutenberg_1440|1.0
printing_press|revolutionized|information_dissemination|1.0
radio|first_broadcast|early_1900s|1.0
television|mass_adoption|1950s|1.0
internet|created|1960s_arpanet|1.0
world_wide_web|invented_by|tim_berners_lee_1989|1.0
social_media|transformed|public_discourse|1.0
misinformation|spreads|faster_than_truth|0.8
propaganda|manipulates|public_opinion|1.0
censorship|restricts|information_access|1.0
freedom_of_information|enables|government_transparency|1.0
fourth_estate|refers_to|the_press|1.0
investigative_journalism|exposes|corruption|1.0
fake_news|undermines|trust_in_media|0.8
fact_checking|verifies|claims|1.0
media_literacy|helps|evaluate_information|1.0
echo_chamber|reinforces|existing_beliefs|0.9
filter_bubble|limits|information_diversity|0.8
citizen_journalism|is|reporting_by_non_professionals|1.0
open_source_intelligence|gathers|publicly_available_data|1.0

# === MODERN POLITICAL CONCEPTS ===
welfare_state|provides|social_safety_net|1.0
universal_basic_income|gives|unconditional_income|0.8
universal_healthcare|covers|all_citizens|1.0
progressive_taxation|higher_rates|for_higher_income|1.0
flat_tax|same_rate|for_all_income|1.0
minimum_wage|sets|lowest_legal_pay|1.0
labor_union|represents|workers_collectively|1.0
strike|is|work_stoppage_for_demands|1.0
gig_economy|uses|independent_contractors|1.0
automation|replaces|human_labor|1.0
digital_divide|separates|technology_haves_and_have_nots|1.0
surveillance_state|monitors|citizens_extensively|1.0
data_privacy|right_to|control_personal_information|1.0
net_neutrality|treats|all_internet_traffic_equally|1.0
intellectual_property|protects|creations_of_mind|1.0
copyright|protects|creative_works|1.0
patent|protects|inventions|1.0
antitrust|prevents|monopolistic_behavior|1.0
privatization|transfers|state_assets_to_private|1.0
nationalization|transfers|private_assets_to_state|1.0
immigration|is_a|political_issue|1.0
border_security|controls|who_enters_country|1.0
asylum|protection_for|persecuted_people|1.0
citizenship|grants|full_political_rights|1.0
statelessness|is|having_no_nationality|1.0
ethnic_conflict|driven_by|identity_differences|1.0
genocide|is|deliberate_destruction_of_group|1.0
war_crime|violates|laws_of_armed_conflict|1.0
peacekeeping|un_forces|maintain_ceasefire|1.0
diplomacy|resolves|conflicts_through_negotiation|1.0
summit|is_a|meeting_of_leaders|1.0
treaty|is_a|formal_agreement_between_states|1.0
ratification|makes|treaty_legally_binding|1.0
veto_power|blocks|un_security_council_resolutions|1.0
non_aligned_movement|refused|cold_war_sides|1.0
iron_curtain|divided|europe_in_cold_war|1.0
marshall_plan|rebuilt|western_europe|1.0
truman_doctrine|contained|communism|1.0
domino_theory|feared|communist_spread|0.7
detente|eased|cold_war_tensions|1.0
glasnost|meant|openness_in_ussr|1.0
perestroika|meant|restructuring_in_ussr|1.0
arab_israeli_conflict|ongoing_since|1948|1.0
two_state_solution|proposes|israel_and_palestine|0.8
nuclear_deterrence|prevents|war_through_threat|1.0
arms_control|treaties|limit_weapons|1.0
start_treaty|limits|nuclear_warheads|1.0
chemical_weapons_convention|bans|chemical_weapons|1.0
biological_weapons_convention|bans|biological_weapons|1.0
landmine_ban|ottawa_treaty|1997|1.0
responsibility_to_protect|allows|intervention_for_atrocities|0.8
humanitarian_intervention|justified_by|preventing_mass_atrocities|0.8
economic_sanctions|alternative_to|military_force|1.0
trade_embargo|blocks|commerce_with_country|1.0
foreign_aid|provides|development_assistance|1.0
bilateral_agreement|between|two_countries|1.0
multilateral_agreement|between|many_countries|1.0
supranational_organization|has|authority_over_member_states|1.0
intergovernmental_organization|coordinates|between_sovereign_states|1.0
non_governmental_organization|independent_of|government|1.0
civil_society|includes|ngos_media_academia|1.0
think_tank|researches|policy_issues|1.0
lobbyist|advocates|for_interest_groups|1.0
political_spectrum|ranges|left_center_right|1.0
left_wing|favors|social_equality|1.0
right_wing|favors|tradition_free_market|1.0
centrist|moderate|balanced_approach|1.0
extremism|rejects|mainstream_politics|1.0
radicalization|process_of|adopting_extreme_views|1.0
counter_terrorism|prevents|terrorist_attacks|1.0
intelligence_agency|gathers|security_information|1.0
cia|is_a|us_intelligence_agency|1.0
mi6|is_a|uk_intelligence_agency|1.0
mossad|is_a|israeli_intelligence_agency|1.0
fsb|is_a|russian_security_agency|1.0
whistleblower|exposes|illegal_or_unethical_activity|1.0
transparency|enables|accountability|1.0
corruption|undermines|governance|1.0
kleptocracy|is|government_by_thieves|1.0
failed_state|cannot|provide_basic_services|1.0
state_building|creates|functional_government|1.0
nation_building|creates|national_identity|1.0
geopolitical_risk|affects|investment_decisions|0.9

# === ADDITIONAL UNIQUE HISTORY FACTS ===
printing_revolution|enabled|mass_literacy|1.0
age_of_exploration|15th_16th|century|1.0
columbus|reached|americas_1492|1.0
magellan_expedition|first|circumnavigation_1522|1.0
vasco_da_gama|reached|india_by_sea_1498|1.0
treaty_of_tordesillas|divided|new_world_1494|1.0
mughal_empire|ruled|indian_subcontinent|1.0
ming_dynasty|ruled|china_1368_to_1644|1.0
qing_dynasty|last|chinese_dynasty|1.0
opium_wars|between|britain_and_china|1.0
meiji_era|modernized|japan_rapidly|1.0
russo_japanese_war|first|asian_victory_over_european_power|1.0
league_of_nations|predecessor_of|united_nations|1.0
treaty_of_westphalia|established|modern_state_system_1648|1.0
thirty_years_war|devastated|central_europe|1.0
glorious_revolution|established|constitutional_monarchy_england|1.0
magna_carta|limited|royal_power_1215|1.0
haitian_revolution|first|successful_slave_revolt|1.0
mexican_revolution|lasted|1910_to_1920|1.0
cuban_revolution|year|1959|1.0
iranian_revolution|year|1979|1.0
velvet_revolution|ended|communism_in_czechoslovakia|1.0
solidarity_movement|in|poland|1.0
cultural_revolution|in|china_1966_to_1976|1.0
great_leap_forward|caused|massive_famine_in_china|1.0
korean_peninsula|divided|at_38th_parallel|1.0
berlin_wall|built|1961|1.0
cuban_missile_crisis|year|1962|1.0
space_race_sputnik|launched|1957|1.0
yalta_conference|divided|post_ww2_europe|1.0
nuremberg_trials|prosecuted|war_criminals|1.0
marshall_plan|cost|about_13_billion_dollars|1.0
nato_article_5|collective|defense_clause|1.0
warsaw_pact|soviet|military_alliance|1.0
non_proliferation_treaty|signed|1968|1.0
camp_david_accords|peace_between|egypt_and_israel|1.0
oslo_accords|peace_process|israel_palestine|1.0
good_friday_agreement|peace_in|northern_ireland|1.0
dayton_agreement|ended|bosnian_war|1.0
rwandan_genocide|killed|about_800000|1.0
cambodian_genocide|killed|about_2_million|1.0
holodomor|famine_in|ukraine_1932_1933|1.0
armenian_genocide|year|1915|1.0
