# MK Knowledge File - Cybersecurity, Hacking, Defense
# Format: source|relation|target|weight
# Covers: encryption, OWASP, pentesting tools, network security, authentication, zero-trust

# === ENCRYPTION ALGORITHMS ===
aes|stands_for|advanced_encryption_standard|1.0
aes|is_a|symmetric_cipher|1.0
aes|key_sizes|128_192_256_bits|1.0
aes_256|is|military_grade_encryption|0.9
aes_gcm|provides|authenticated_encryption|1.0
aes_cbc|is_a|block_cipher_mode|1.0
aes_ctr|is_a|stream_cipher_mode|1.0
rsa|is_a|asymmetric_cipher|1.0
rsa|based_on|integer_factorization|1.0
rsa|key_sizes|2048_3072_4096_bits|1.0
rsa|used_for|key_exchange_and_signing|1.0
ecc|stands_for|elliptic_curve_cryptography|1.0
ecc|advantage|smaller_keys_same_security|1.0
curve25519|is_a|popular_elliptic_curve|1.0
ed25519|is_a|signature_algorithm|1.0
ecdsa|is_a|digital_signature_algorithm|1.0
chacha20|is_a|stream_cipher|1.0
chacha20|alternative_to|aes|1.0
chacha20_poly1305|provides|authenticated_encryption|1.0
chacha20_poly1305|used_by|wireguard_and_tls|1.0
sha256|is_a|hash_function|1.0
sha256|output|256_bits|1.0
sha3|is_a|hash_function|1.0
sha3|based_on|keccak|1.0
blake2|is_a|hash_function|1.0
blake2|faster_than|sha256|0.9
blake3|is_a|hash_function|1.0
blake3|parallelizable|tree_hashing|1.0
bcrypt|is_a|password_hashing_function|1.0
bcrypt|has|adaptive_cost_factor|1.0
argon2|is_a|password_hashing_function|1.0
argon2|winner_of|password_hashing_competition|1.0
argon2|memory_hard|resistant_to_gpu_attacks|1.0
scrypt|is_a|password_hashing_function|1.0
scrypt|memory_hard|resistant_to_asic|1.0
pbkdf2|is_a|key_derivation_function|1.0
hmac|provides|message_authentication|1.0
diffie_hellman|enables|key_exchange|1.0
ecdh|is_a|elliptic_curve_key_exchange|1.0
x25519|is_a|ecdh_using_curve25519|1.0
kyber|is_a|post_quantum_key_encapsulation|1.0
dilithium|is_a|post_quantum_signature|1.0
post_quantum|resists|quantum_computer_attacks|1.0

# === OWASP TOP 10 ===
owasp|stands_for|open_web_application_security_project|1.0
owasp_top_10|lists|most_critical_web_vulnerabilities|1.0
sql_injection|exploits|unsanitized_database_queries|1.0
sql_injection|prevention|parameterized_queries|1.0
xss|stands_for|cross_site_scripting|1.0
xss|injects|malicious_scripts|1.0
xss|types|reflected_stored_dom|1.0
xss|prevention|output_encoding_csp|1.0
csrf|stands_for|cross_site_request_forgery|1.0
csrf|tricks|user_into_unintended_actions|1.0
csrf|prevention|csrf_tokens_samesite_cookies|1.0
ssrf|stands_for|server_side_request_forgery|1.0
ssrf|exploits|server_to_make_requests|1.0
ssrf|can_access|internal_services|1.0
broken_auth|allows|unauthorized_access|1.0
broken_auth|caused_by|weak_passwords_session_issues|1.0
insecure_deserialization|allows|remote_code_execution|1.0
xml_external_entity|reads|server_files|1.0
path_traversal|accesses|files_outside_webroot|1.0
command_injection|executes|os_commands|1.0
idor|stands_for|insecure_direct_object_reference|1.0
idor|allows|accessing_other_users_data|1.0
security_misconfiguration|exposes|sensitive_data|1.0
cryptographic_failure|uses|weak_or_no_encryption|1.0
vulnerable_components|have|known_exploits|1.0
insufficient_logging|hides|attack_evidence|1.0

# === PENETRATION TESTING TOOLS ===
nmap|is_a|port_scanner|1.0
nmap|discovers|hosts_and_services|1.0
nmap|scripts|nse_for_vuln_detection|1.0
burp_suite|is_a|web_security_tool|1.0
burp_suite|intercepts|http_traffic|1.0
burp_suite|has|scanner_and_intruder|1.0
metasploit|is_a|exploitation_framework|1.0
metasploit|contains|thousands_of_exploits|1.0
metasploit|modules|exploit_payload_auxiliary|1.0
wireshark|is_a|packet_analyzer|1.0
wireshark|captures|network_traffic|1.0
wireshark|decodes|hundreds_of_protocols|1.0
john_the_ripper|is_a|password_cracker|1.0
hashcat|is_a|gpu_password_cracker|1.0
hashcat|uses|gpu_acceleration|1.0
sqlmap|automates|sql_injection_testing|1.0
nikto|is_a|web_server_scanner|1.0
dirb|is_a|directory_bruteforcer|1.0
gobuster|is_a|directory_bruteforcer|1.0
ffuf|is_a|web_fuzzer|1.0
hydra|is_a|login_bruteforcer|1.0
aircrack_ng|is_a|wifi_security_tool|1.0
responder|captures|ntlm_hashes|1.0
bloodhound|maps|active_directory_attacks|1.0
mimikatz|extracts|windows_credentials|1.0
nuclei|is_a|vulnerability_scanner|1.0
nuclei|uses|yaml_templates|1.0
subfinder|discovers|subdomains|1.0
amass|is_a|subdomain_enumeration_tool|1.0
crackmapexec|is_a|post_exploitation_tool|1.0
impacket|is_a|network_protocol_toolkit|1.0
netcat|is_a|network_utility|1.0
netcat|used_for|reverse_shells|0.8
linpeas|is_a|privilege_escalation_checker|1.0
pspy|monitors|processes_without_root|1.0

# === NETWORK SECURITY ===
firewall|blocks|unauthorized_traffic|1.0
next_gen_firewall|inspects|application_layer|1.0
ids|detects|suspicious_activity|1.0
ips|blocks|detected_attacks|1.0
snort|is_a|ids_ips|1.0
suricata|is_a|ids_ips|1.0
zeek|is_a|network_security_monitor|1.0
waf|protects|web_applications|1.0
modsecurity|is_a|open_source_waf|1.0
cloudflare_waf|is_a|cloud_waf|1.0
ddos_mitigation|absorbs|volumetric_attacks|1.0
ddos_types|include|syn_flood_udp_flood_amplification|1.0
rate_limiting|prevents|abuse_and_dos|1.0
geo_blocking|restricts|traffic_by_country|1.0
ip_reputation|scores|ip_trustworthiness|1.0
threat_intelligence|provides|known_bad_indicators|1.0
siem|stands_for|security_information_event_management|1.0
siem|correlates|security_events|1.0
splunk|is_a|siem_platform|1.0
elastic_security|is_a|siem_platform|1.0
soar|stands_for|security_orchestration_automation_response|1.0
edr|stands_for|endpoint_detection_response|1.0
xdr|stands_for|extended_detection_response|1.0
honeypot|attracts|attackers_for_analysis|1.0
canary_token|detects|unauthorized_access|1.0
network_forensics|analyzes|captured_traffic|1.0

# === AUTHENTICATION AND AUTHORIZATION ===
oauth2|is_a|authorization_framework|1.0
oauth2|flows|authorization_code_client_credentials|1.0
oauth2|separates|authentication_from_authorization|1.0
openid_connect|adds|authentication_to_oauth2|1.0
saml|stands_for|security_assertion_markup_language|1.0
saml|used_for|enterprise_sso|1.0
jwt|stands_for|json_web_token|1.0
jwt|contains|header_payload_signature|1.0
jwt|stateless|no_server_side_session|1.0
jwt|risk|token_theft_if_not_secured|0.8
mfa|stands_for|multi_factor_authentication|1.0
mfa|factors|something_you_know_have_are|1.0
totp|stands_for|time_based_one_time_password|1.0
totp|apps|google_authenticator_authy|1.0
fido2|is_a|passwordless_standard|1.0
passkeys|implement|fido2_webauthn|1.0
passkeys|replace|passwords|1.0
webauthn|is_a|web_authentication_api|1.0
kerberos|is_a|network_authentication_protocol|1.0
kerberos|used_in|active_directory|1.0
ldap|is_a|directory_protocol|1.0
radius|is_a|aaa_protocol|1.0
rbac|stands_for|role_based_access_control|1.0
abac|stands_for|attribute_based_access_control|1.0
principle_of_least_privilege|grants|minimum_necessary_access|1.0
separation_of_duties|prevents|single_point_of_compromise|1.0
session_management|tracks|authenticated_users|1.0
session_fixation|attack|reuses_known_session_id|1.0
cookie_flags|include|httponly_secure_samesite|1.0
api_key|is_a|simple_authentication_method|1.0
api_key|should_be|rotated_regularly|0.9

# === ZERO TRUST ARCHITECTURE ===
zero_trust|principle|never_trust_always_verify|1.0
zero_trust|assumes|breach_has_occurred|1.0
zero_trust|requires|continuous_verification|1.0
microsegmentation|limits|lateral_movement|1.0
identity_verification|required_for|every_access_request|1.0
device_posture|checks|device_health_before_access|1.0
least_privilege_access|grants|minimum_permissions|1.0
just_in_time_access|grants|temporary_elevated_access|1.0
software_defined_perimeter|hides|resources_until_authenticated|1.0
beyondcorp|is_a|google_zero_trust_implementation|1.0
ztna|stands_for|zero_trust_network_access|1.0
sase|stands_for|secure_access_service_edge|1.0
sase|combines|network_and_security_in_cloud|1.0
policy_engine|decides|access_based_on_context|1.0
conditional_access|evaluates|risk_before_granting|1.0

# === INCIDENT RESPONSE ===
incident_response|phases|prepare_detect_contain_eradicate_recover|1.0
containment|limits|damage_spread|1.0
eradication|removes|threat_from_environment|1.0
recovery|restores|normal_operations|1.0
lessons_learned|improves|future_response|1.0
forensic_imaging|preserves|evidence|1.0
chain_of_custody|maintains|evidence_integrity|1.0
ioc|stands_for|indicators_of_compromise|1.0
ttp|stands_for|tactics_techniques_procedures|1.0
mitre_attack|framework|adversary_behavior|1.0
kill_chain|models|attack_stages|1.0
threat_hunting|proactively|searches_for_threats|1.0
malware_analysis|studies|malicious_software|1.0
sandbox_analysis|runs|malware_safely|1.0
yara_rules|identify|malware_patterns|1.0

# === VULNERABILITY TYPES ===
buffer_overflow|exploits|memory_beyond_bounds|1.0
stack_overflow|overwrites|return_address|1.0
heap_overflow|corrupts|heap_metadata|1.0
use_after_free|accesses|freed_memory|1.0
double_free|frees|memory_twice|1.0
integer_overflow|wraps|beyond_max_value|1.0
format_string|exploits|printf_without_format|1.0
race_condition|exploits|timing_between_check_and_use|1.0
toctou|stands_for|time_of_check_time_of_use|1.0
dll_injection|loads|malicious_library|1.0
privilege_escalation|gains|higher_permissions|1.0
local_privilege_escalation|from_user_to_root|1.0
remote_code_execution|executes|arbitrary_code_remotely|1.0
information_disclosure|leaks|sensitive_data|1.0
denial_of_service|makes|service_unavailable|1.0
zero_day|is|unknown_unpatched_vulnerability|1.0
cve|stands_for|common_vulnerabilities_exposures|1.0
cvss|scores|vulnerability_severity|1.0
cwe|stands_for|common_weakness_enumeration|1.0
supply_chain_attack|compromises|software_dependencies|1.0
typosquatting|publishes|malicious_similar_named_packages|1.0
dependency_confusion|exploits|package_manager_resolution|1.0

# === CRYPTOGRAPHIC ATTACKS ===
brute_force|tries|all_possible_keys|1.0
dictionary_attack|tries|common_passwords|1.0
rainbow_table|precomputes|password_hashes|1.0
salt|prevents|rainbow_table_attacks|1.0
padding_oracle|exploits|cbc_padding_validation|1.0
timing_attack|exploits|execution_time_differences|1.0
side_channel|leaks|info_through_physical_behavior|1.0
downgrade_attack|forces|weaker_protocol_version|1.0
mitm|intercepts|communication_between_parties|1.0
replay_attack|resends|captured_valid_message|1.0
birthday_attack|exploits|collision_probability|1.0
chosen_plaintext|attacker|selects_encrypted_messages|1.0
known_plaintext|attacker|has_plaintext_ciphertext_pairs|1.0

# === SECURE DEVELOPMENT ===
secure_sdlc|integrates|security_in_development|1.0
threat_modeling|identifies|potential_threats|1.0
stride|stands_for|spoofing_tampering_repudiation_info_dos_elevation|1.0
dread|scores|threat_severity|1.0
code_review|finds|security_bugs|1.0
sast|stands_for|static_application_security_testing|1.0
dast|stands_for|dynamic_application_security_testing|1.0
sca|stands_for|software_composition_analysis|1.0
sca|checks|dependency_vulnerabilities|1.0
devsecops|integrates|security_in_cicd|1.0
secrets_management|stores|credentials_securely|1.0
vault|is_a|secrets_management_tool|1.0
secrets_scanning|detects|leaked_credentials|1.0
sbom|stands_for|software_bill_of_materials|1.0
input_validation|prevents|injection_attacks|1.0
output_encoding|prevents|xss|1.0
prepared_statements|prevent|sql_injection|1.0
csp|stands_for|content_security_policy|1.0
csp|prevents|xss_and_injection|1.0
cors|stands_for|cross_origin_resource_sharing|1.0
cors|controls|cross_origin_requests|1.0
sri|stands_for|subresource_integrity|1.0
security_headers|include|hsts_csp_x_frame_options|1.0

# === SOCIAL ENGINEERING ===
phishing|tricks|users_into_revealing_credentials|1.0
spear_phishing|targets|specific_individuals|1.0
whaling|targets|executives|1.0
vishing|is|voice_phishing|1.0
smishing|is|sms_phishing|1.0
pretexting|creates|false_scenario|1.0
baiting|offers|something_enticing|1.0
tailgating|follows|authorized_person_into_building|1.0
social_engineering|exploits|human_psychology|1.0
security_awareness_training|reduces|social_engineering_risk|1.0

# === MALWARE TYPES ===
ransomware|encrypts|files_for_ransom|1.0
trojan|disguises_as|legitimate_software|1.0
worm|self_replicates|across_networks|1.0
rootkit|hides|in_operating_system|1.0
keylogger|captures|keyboard_input|1.0
botnet|controls|many_infected_machines|1.0
cryptominer|steals|computing_resources|1.0
fileless_malware|lives|only_in_memory|1.0
apt|stands_for|advanced_persistent_threat|1.0
apt|is|state_sponsored_typically|0.8
c2|stands_for|command_and_control|1.0
c2|server|controls_malware_remotely|1.0
exfiltration|steals|data_from_network|1.0
lateral_movement|spreads|within_network|1.0
persistence|maintains|access_after_reboot|1.0
living_off_the_land|uses|legitimate_tools_for_attacks|1.0
lolbins|are|legitimate_binaries_used_maliciously|1.0

# === COMPLIANCE AND FRAMEWORKS ===
nist|is_a|cybersecurity_framework|1.0
iso_27001|is_a|security_management_standard|1.0
soc2|is_a|audit_standard|1.0
gdpr|is_a|data_protection_regulation|1.0
gdpr|applies_in|european_union|1.0
hipaa|protects|health_information|1.0
pci_dss|protects|payment_card_data|1.0
cis_benchmarks|provide|security_configuration_guides|1.0
pen_test_report|documents|findings_and_remediation|1.0
bug_bounty|rewards|vulnerability_reporters|1.0
responsible_disclosure|gives|vendor_time_to_fix|1.0
cisa|is_a|us_cybersecurity_agency|1.0

# === CONTAINER AND CLOUD SECURITY ===
container_escape|breaks_out|of_container_isolation|1.0
pod_security_policy|restricts|container_capabilities|1.0
image_scanning|detects|vulnerabilities_in_images|1.0
trivy|is_a|container_scanner|1.0
falco|is_a|runtime_security_tool|1.0
opa|stands_for|open_policy_agent|1.0
opa|enforces|policies_as_code|1.0
service_mesh_security|provides|mtls_between_services|1.0
cloud_misconfiguration|exposes|resources_publicly|1.0
s3_bucket_exposure|leaks|sensitive_data|0.8
iam_overprivilege|grants|excessive_permissions|0.9
cloud_trail|logs|api_calls|1.0
cspm|stands_for|cloud_security_posture_management|1.0
cwpp|stands_for|cloud_workload_protection_platform|1.0
terraform_sentinel|enforces|infrastructure_policies|1.0
infrastructure_as_code_scanning|finds|misconfigurations|1.0
checkov|scans|iac_for_security|1.0
kube_bench|checks|kubernetes_security|1.0
network_policy|restricts|pod_communication|1.0
admission_controller|validates|resource_creation|1.0

# === PRIVACY AND DATA PROTECTION ===
encryption_at_rest|protects|stored_data|1.0
encryption_in_transit|protects|data_in_network|1.0
data_masking|hides|sensitive_fields|1.0
tokenization|replaces|sensitive_data_with_tokens|1.0
anonymization|removes|identifying_information|1.0
pseudonymization|replaces|identifiers_with_aliases|1.0
data_classification|labels|sensitivity_levels|1.0
dlp|stands_for|data_loss_prevention|1.0
dlp|detects|sensitive_data_exfiltration|1.0
right_to_erasure|allows|data_deletion_requests|1.0
data_retention_policy|defines|how_long_to_keep_data|1.0
privacy_by_design|builds|privacy_into_systems|1.0
consent_management|tracks|user_permissions|1.0

# === WIRELESS AND PHYSICAL SECURITY ===
wpa3|provides|wifi_security|1.0
evil_twin|creates|fake_access_point|1.0
deauth_attack|disconnects|wifi_clients|1.0
wardriving|discovers|wifi_networks|1.0
bluetooth_sniffing|captures|bluetooth_traffic|1.0
rfid_cloning|copies|access_cards|1.0
usb_rubber_ducky|emulates|keyboard_for_injection|1.0
physical_access|means|game_over_for_security|0.9
clean_desk_policy|prevents|visual_data_theft|1.0
visitor_badge|controls|physical_access|1.0
cctv|provides|surveillance_deterrent|1.0
biometric_access|uses|fingerprint_face_iris|1.0
mantrap|prevents|tailgating|1.0
faraday_cage|blocks|electromagnetic_signals|1.0
tempest|protects_against|electromagnetic_eavesdropping|1.0

# === THREAT LANDSCAPE ===
ransomware_as_a_service|sells|ransomware_to_affiliates|1.0
initial_access_broker|sells|network_access|1.0
dark_web|hosts|criminal_marketplaces|1.0
tor_network|provides|anonymity|1.0
cryptocurrency_laundering|obfuscates|stolen_funds|1.0
nation_state_actor|has|significant_resources|1.0
hacktivism|attacks_for|political_motives|1.0
insider_threat|comes_from|trusted_employees|1.0
credential_stuffing|uses|leaked_password_databases|1.0
password_spraying|tries|few_passwords_many_accounts|1.0
business_email_compromise|impersonates|executives|1.0
deepfake|creates|fake_audio_video|1.0
ai_generated_phishing|creates|convincing_fake_emails|1.0
vulnerability_management|lifecycle|discover_assess_remediate_verify|1.0
patch_management|applies|security_updates|1.0
penetration_test_types|include|black_white_gray_box|1.0
black_box|no|prior_knowledge|1.0
white_box|full|source_code_access|1.0
osint|stands_for|open_source_intelligence|1.0
osint|gathers|publicly_available_info|1.0
shodan|searches|internet_connected_devices|1.0
censys|scans|internet_infrastructure|1.0
certificate_transparency_logs|reveal|issued_certificates|1.0
dns_enumeration|discovers|subdomains_and_records|1.0
port_scanning|identifies|open_services|1.0
banner_grabbing|identifies|service_versions|1.0
fingerprinting|identifies|os_and_software|1.0
enumeration|gathers|detailed_system_info|1.0

# === ADDITIONAL UNIQUE SECURITY FACTS ===
threat_modeling_frameworks|include|stride_pasta_attack_tree|1.0
attack_surface|is|all_points_where_attacker_can_interact|1.0
defense_in_depth|uses|multiple_security_layers|1.0
security_by_obscurity|is_not|reliable_defense|0.8
open_source_security|benefits_from|many_eyes|0.9
coordinated_disclosure|gives|vendor_90_days_typically|1.0
cve_database|tracks|known_vulnerabilities|1.0
exploit_database|contains|public_exploits|1.0
metasploit_module|types|exploit_auxiliary_post|1.0
payload_types|include|reverse_shell_meterpreter_bind|1.0
staged_payload|downloads|in_parts|1.0
stageless_payload|sends|all_at_once|1.0
persistence_techniques|include|cron_systemd_registry|1.0
privilege_escalation_linux|methods|suid_kernel_exploit_sudo|1.0
privilege_escalation_windows|methods|service_exploit_token_theft|1.0
lateral_movement_techniques|include|pass_the_hash_psexec_wmi|1.0
data_exfiltration_methods|include|dns_tunneling_https_steganography|1.0
anti_forensics|hides|evidence_of_attack|1.0
log_tampering|removes|attack_evidence|1.0
timestomping|modifies|file_timestamps|1.0
living_off_the_land_binaries|powershell_certutil_bitsadmin|used_maliciously|1.0
fileless_attack|executes|entirely_in_memory|1.0
process_injection|injects|code_into_running_process|1.0
dll_sideloading|loads|malicious_dll|1.0
api_hooking|intercepts|system_calls|1.0
code_signing|verifies|software_authenticity|1.0
certificate_pinning|prevents|mitm_on_tls|1.0
public_key_infrastructure|manages|certificates|1.0
hardware_security_module|stores|keys_in_tamper_resistant_hardware|1.0
trusted_platform_module|provides|hardware_root_of_trust|1.0
secure_enclave|isolates|sensitive_operations|1.0
intel_sgx|provides|hardware_enclaves|1.0
arm_trustzone|separates|secure_and_normal_world|1.0
fuzz_testing|finds|bugs_with_random_input|1.0
coverage_guided_fuzzing|maximizes|code_path_exploration|1.0
afl|is_a|popular_fuzzer|1.0
libfuzzer|is_a|in_process_fuzzer|1.0
symbolic_execution|explores|all_program_paths|1.0
taint_analysis|tracks|untrusted_data_flow|1.0
binary_analysis|reverse_engineers|compiled_code|1.0
ghidra|is_a|reverse_engineering_tool|1.0
ida_pro|is_a|disassembler|1.0
radare2|is_a|open_source_re_framework|1.0
