# MK Knowledge File - Crypto Trading Strategies, Patterns, and Market Mechanics
# Format: source|relation|target|weight
# Covers: candlestick patterns, order types, exchange mechanics, DeFi, yield farming,
# liquidity pools, tokenomics, market cycles, whale behavior, technical indicators

# === CANDLESTICK PATTERNS ===
doji|is_a|candlestick_pattern|1.0
doji|indicates|market_indecision|0.9
doji|has_property|open_equals_close|1.0
doji|used_for|reversal_signal|0.8
hammer|is_a|candlestick_pattern|1.0
hammer|indicates|bullish_reversal|0.9
hammer|has_property|long_lower_wick|1.0
hammer|appears_at|bottom_of_downtrend|0.9
inverted_hammer|is_a|candlestick_pattern|1.0
inverted_hammer|indicates|potential_bullish_reversal|0.8
inverted_hammer|has_property|long_upper_wick|1.0
hanging_man|is_a|candlestick_pattern|1.0
hanging_man|indicates|bearish_reversal|0.8
hanging_man|appears_at|top_of_uptrend|0.9
engulfing_bullish|is_a|candlestick_pattern|1.0
engulfing_bullish|indicates|strong_bullish_reversal|0.9
engulfing_bullish|has_property|green_candle_engulfs_red|1.0
engulfing_bearish|is_a|candlestick_pattern|1.0
engulfing_bearish|indicates|strong_bearish_reversal|0.9
engulfing_bearish|has_property|red_candle_engulfs_green|1.0
morning_star|is_a|candlestick_pattern|1.0
morning_star|indicates|bullish_reversal|0.9
morning_star|consists_of|three_candles|1.0
morning_star|appears_at|bottom_of_downtrend|0.9
evening_star|is_a|candlestick_pattern|1.0
evening_star|indicates|bearish_reversal|0.9
evening_star|consists_of|three_candles|1.0
evening_star|appears_at|top_of_uptrend|0.9
shooting_star|is_a|candlestick_pattern|1.0
shooting_star|indicates|bearish_reversal|0.8
shooting_star|has_property|long_upper_shadow|1.0
three_white_soldiers|is_a|candlestick_pattern|1.0
three_white_soldiers|indicates|strong_bullish_trend|0.9
three_black_crows|is_a|candlestick_pattern|1.0
three_black_crows|indicates|strong_bearish_trend|0.9
spinning_top|is_a|candlestick_pattern|1.0
spinning_top|indicates|market_indecision|0.8
marubozu|is_a|candlestick_pattern|1.0
marubozu|indicates|strong_momentum|0.9
marubozu|has_property|no_wicks|1.0
tweezer_top|is_a|candlestick_pattern|1.0
tweezer_top|indicates|bearish_reversal|0.8
tweezer_bottom|is_a|candlestick_pattern|1.0
tweezer_bottom|indicates|bullish_reversal|0.8
harami_bullish|is_a|candlestick_pattern|1.0
harami_bullish|indicates|potential_reversal|0.7
harami_bearish|is_a|candlestick_pattern|1.0
harami_bearish|indicates|potential_reversal|0.7
dragonfly_doji|is_a|candlestick_pattern|1.0
dragonfly_doji|indicates|bullish_reversal|0.8
gravestone_doji|is_a|candlestick_pattern|1.0
gravestone_doji|indicates|bearish_reversal|0.8
piercing_line|is_a|candlestick_pattern|1.0
piercing_line|indicates|bullish_reversal|0.8
dark_cloud_cover|is_a|candlestick_pattern|1.0
dark_cloud_cover|indicates|bearish_reversal|0.8

# === ORDER TYPES ===
market_order|is_a|order_type|1.0
market_order|executes_at|current_market_price|1.0
market_order|has_property|immediate_execution|1.0
market_order|risk|slippage_in_thin_markets|0.8
limit_order|is_a|order_type|1.0
limit_order|executes_at|specified_price_or_better|1.0
limit_order|has_property|no_slippage|1.0
limit_order|risk|may_not_fill|0.7
stop_loss|is_a|order_type|1.0
stop_loss|used_for|risk_management|1.0
stop_loss|triggers_at|specified_price|1.0
stop_loss|becomes|market_order_when_triggered|0.9
stop_limit|is_a|order_type|1.0
stop_limit|combines|stop_trigger_with_limit_price|1.0
trailing_stop|is_a|order_type|1.0
trailing_stop|follows|price_at_set_distance|1.0
trailing_stop|used_for|protecting_profits|0.9
oco_order|is_a|order_type|1.0
oco_order|stands_for|one_cancels_other|1.0
oco_order|combines|take_profit_and_stop_loss|1.0
iceberg_order|is_a|order_type|1.0
iceberg_order|hides|total_order_size|1.0
iceberg_order|used_by|institutional_traders|0.9
twap_order|is_a|order_type|1.0
twap_order|stands_for|time_weighted_average_price|1.0
twap_order|used_for|reducing_market_impact|0.9
fill_or_kill|is_a|order_type|1.0
fill_or_kill|must|execute_entirely_or_cancel|1.0
immediate_or_cancel|is_a|order_type|1.0
immediate_or_cancel|fills|what_it_can_then_cancels_rest|1.0
post_only|is_a|order_type|1.0
post_only|guarantees|maker_fee_only|1.0
reduce_only|is_a|order_type|1.0
reduce_only|can_only|decrease_position_size|1.0

# === EXCHANGE MECHANICS ===
order_book|is_a|exchange_component|1.0
order_book|contains|all_open_orders|1.0
order_book|has|bid_side_and_ask_side|1.0
matching_engine|is_a|exchange_component|1.0
matching_engine|matches|buy_orders_with_sell_orders|1.0
matching_engine|uses|price_time_priority|1.0
slippage|is_a|trading_concept|1.0
slippage|caused_by|low_liquidity|0.9
slippage|means|price_moves_during_execution|1.0
spread|is_a|trading_concept|1.0
spread|is|difference_between_bid_and_ask|1.0
spread|indicates|market_liquidity|0.8
maker_fee|is_a|fee_type|1.0
maker_fee|charged_for|adding_liquidity|1.0
maker_fee|typically|lower_than_taker_fee|0.9
taker_fee|is_a|fee_type|1.0
taker_fee|charged_for|removing_liquidity|1.0
funding_rate|is_a|perpetual_futures_concept|1.0
funding_rate|balances|longs_and_shorts|1.0
funding_rate|paid_every|8_hours_typically|0.9
liquidation|is_a|trading_event|1.0
liquidation|occurs_when|margin_insufficient|1.0
liquidation|causes|forced_position_close|1.0
margin_trading|uses|leverage_to_amplify|1.0
margin_trading|risk|liquidation_and_losses|0.9
cross_margin|shares|margin_across_positions|1.0
isolated_margin|limits|margin_per_position|1.0
market_depth|measures|liquidity_at_price_levels|1.0
volume_profile|shows|trading_activity_at_prices|1.0
open_interest|measures|total_outstanding_contracts|1.0
open_interest|indicates|market_participation|0.8

# === DEFI PROTOCOLS ===
uniswap|is_a|decentralized_exchange|1.0
uniswap|uses|automated_market_maker|1.0
uniswap|runs_on|ethereum|1.0
uniswap|token|UNI|1.0
uniswap_v3|has|concentrated_liquidity|1.0
uniswap_v3|allows|custom_price_ranges|1.0
aave|is_a|lending_protocol|1.0
aave|enables|flash_loans|1.0
aave|supports|variable_and_stable_rates|1.0
aave|token|AAVE|1.0
compound|is_a|lending_protocol|1.0
compound|uses|ctokens_for_deposits|1.0
compound|governed_by|COMP_token|1.0
curve_finance|is_a|dex|1.0
curve_finance|optimized_for|stablecoin_swaps|1.0
curve_finance|uses|stableswap_invariant|1.0
curve_finance|token|CRV|1.0
makerdao|is_a|stablecoin_protocol|1.0
makerdao|creates|DAI_stablecoin|1.0
makerdao|uses|collateralized_debt_positions|1.0
makerdao|token|MKR|1.0
lido|is_a|liquid_staking_protocol|1.0
lido|provides|stETH_for_staked_eth|1.0
lido|dominates|ethereum_staking|0.8
synthetix|is_a|synthetic_asset_protocol|1.0
synthetix|creates|synthetic_derivatives|1.0
yearn_finance|is_a|yield_aggregator|1.0
yearn_finance|optimizes|yield_farming_strategies|1.0
yearn_finance|token|YFI|1.0
pancakeswap|is_a|dex|1.0
pancakeswap|runs_on|binance_smart_chain|1.0
sushiswap|is_a|dex|1.0
sushiswap|forked_from|uniswap|1.0
balancer|is_a|dex|1.0
balancer|supports|weighted_pools|1.0
gmx|is_a|perpetual_dex|1.0
gmx|runs_on|arbitrum|1.0
dydx|is_a|perpetual_dex|1.0
dydx|uses|order_book_model|1.0
convex_finance|is_a|yield_optimizer|1.0
convex_finance|boosts|curve_rewards|1.0
raydium|is_a|dex|1.0
raydium|runs_on|solana|1.0
jupiter|is_a|dex_aggregator|1.0
jupiter|runs_on|solana|1.0
1inch|is_a|dex_aggregator|1.0
1inch|finds|best_swap_routes|1.0

# === YIELD FARMING ===
yield_farming|is_a|defi_strategy|1.0
yield_farming|involves|providing_liquidity_for_rewards|1.0
yield_farming|risk|impermanent_loss|0.9
yield_farming|risk|smart_contract_exploits|0.8
yield_farming|risk|rug_pulls|0.7
apr|stands_for|annual_percentage_rate|1.0
apr|does_not_include|compounding|1.0
apy|stands_for|annual_percentage_yield|1.0
apy|includes|compound_interest_effect|1.0
liquidity_mining|is_a|yield_farming_type|1.0
liquidity_mining|rewards|lp_tokens_and_governance_tokens|1.0
staking|is_a|yield_strategy|1.0
staking|locks|tokens_for_network_security|1.0
staking|rewards|validator_rewards|0.9
liquid_staking|allows|staking_without_locking|1.0
liquid_staking|provides|derivative_token|1.0
vault_strategy|is_a|yield_farming_type|1.0
vault_strategy|autocompounds|rewards|1.0
leveraged_yield_farming|amplifies|returns_and_risks|1.0
leveraged_yield_farming|uses|borrowed_funds|1.0

# === LIQUIDITY POOLS ===
liquidity_pool|is_a|defi_component|1.0
liquidity_pool|contains|token_pairs|1.0
liquidity_pool|enables|automated_trading|1.0
constant_product_formula|used_by|uniswap|1.0
constant_product_formula|equation|x_times_y_equals_k|1.0
impermanent_loss|is_a|liquidity_risk|1.0
impermanent_loss|occurs_when|price_divergence|1.0
impermanent_loss|affects|liquidity_providers|1.0
impermanent_loss|increases_with|price_volatility|0.9
lp_token|represents|share_of_liquidity_pool|1.0
lp_token|can_be|staked_for_additional_rewards|1.0
concentrated_liquidity|improves|capital_efficiency|1.0
concentrated_liquidity|introduced_by|uniswap_v3|1.0
single_sided_liquidity|requires|only_one_token|1.0
pool_ratio|determines|token_prices_in_amm|1.0
tvl|stands_for|total_value_locked|1.0
tvl|measures|defi_protocol_size|1.0

# === TOKENOMICS ===
token_supply|includes|max_supply_and_circulating|1.0
max_supply|is|total_tokens_that_will_exist|1.0
circulating_supply|is|tokens_currently_tradeable|1.0
market_cap|equals|price_times_circulating_supply|1.0
fully_diluted_valuation|equals|price_times_max_supply|1.0
token_burn|reduces|total_supply|1.0
token_burn|creates|deflationary_pressure|0.9
token_vesting|locks|tokens_for_time_period|1.0
token_vesting|prevents|early_dumping|0.8
cliff_period|is|time_before_first_unlock|1.0
linear_vesting|releases|tokens_gradually|1.0
token_distribution|includes|team_investors_community|1.0
token_utility|drives|long_term_demand|0.9
governance_token|gives|voting_rights|1.0
revenue_sharing_token|distributes|protocol_fees|1.0
inflationary_token|increases|supply_over_time|1.0
deflationary_token|decreases|supply_over_time|1.0
buyback_and_burn|uses|revenue_to_reduce_supply|0.9
token_unlock_event|can_cause|selling_pressure|0.8
fair_launch|means|no_presale_or_vc_allocation|1.0

# === MARKET CYCLES ===
accumulation_phase|is_a|market_phase|1.0
accumulation_phase|characterized_by|sideways_movement|0.9
accumulation_phase|smart_money|buying_quietly|0.8
markup_phase|is_a|market_phase|1.0
markup_phase|characterized_by|rising_prices|1.0
markup_phase|driven_by|increasing_demand|0.9
distribution_phase|is_a|market_phase|1.0
distribution_phase|characterized_by|high_volume_at_tops|0.9
distribution_phase|smart_money|selling_to_retail|0.8
markdown_phase|is_a|market_phase|1.0
markdown_phase|characterized_by|falling_prices|1.0
markdown_phase|driven_by|panic_selling|0.8
wyckoff_method|identifies|market_phases|1.0
wyckoff_method|created_by|richard_wyckoff|1.0
bitcoin_halving_cycle|repeats|every_4_years|1.0
bitcoin_halving_cycle|historically|precedes_bull_run|0.8
altcoin_season|occurs_when|altcoins_outperform_btc|1.0
altcoin_season|typically_during|late_bull_market|0.8
bear_market|lasts|12_to_18_months_typically|0.7
bull_market|lasts|12_to_24_months_typically|0.7
capitulation|is_a|market_event|1.0
capitulation|marks|final_selling_before_bottom|0.8
dead_cat_bounce|is_a|price_pattern|1.0
dead_cat_bounce|is|temporary_recovery_in_downtrend|1.0
blow_off_top|is_a|price_pattern|1.0
blow_off_top|marks|end_of_bull_run|0.8

# === WHALE BEHAVIOR AND ON-CHAIN ANALYSIS ===
whale|is_a|large_holder|1.0
whale|holds|significant_supply_percentage|1.0
whale_watching|tracks|large_wallet_movements|1.0
on_chain_analysis|studies|blockchain_transaction_data|1.0
on_chain_analysis|reveals|wallet_behavior_patterns|1.0
exchange_inflow|indicates|potential_selling|0.8
exchange_outflow|indicates|accumulation|0.8
miner_outflow|indicates|miner_selling_pressure|0.7
dormant_coins_moving|indicates|long_term_holder_activity|0.8
realized_cap|measures|value_at_last_movement|1.0
mvrv_ratio|compares|market_cap_to_realized_cap|1.0
mvrv_ratio|above_3|indicates_overvaluation|0.8
mvrv_ratio|below_1|indicates_undervaluation|0.8
nupl|stands_for|net_unrealized_profit_loss|1.0
nupl|measures|market_sentiment|0.9
sopr|stands_for|spent_output_profit_ratio|1.0
sopr|above_1|means_profitable_selling|1.0
hodl_waves|shows|age_distribution_of_coins|1.0
nft_whale|accumulates|high_value_nfts|0.8
smart_money_tracking|follows|known_profitable_wallets|0.8
token_concentration|measures|distribution_among_holders|1.0
gini_coefficient|measures|wealth_inequality_in_token|0.9

# === TECHNICAL INDICATORS ===
rsi|is_a|momentum_indicator|1.0
rsi|stands_for|relative_strength_index|1.0
rsi|range|0_to_100|1.0
rsi|above_70|overbought|0.9
rsi|below_30|oversold|0.9
rsi|divergence|signals_trend_reversal|0.8
macd|is_a|trend_indicator|1.0
macd|stands_for|moving_average_convergence_divergence|1.0
macd|signal_line_cross|buy_sell_signal|0.8
macd|histogram|shows_momentum_strength|0.9
bollinger_bands|is_a|volatility_indicator|1.0
bollinger_bands|uses|standard_deviations|1.0
bollinger_bands|squeeze|indicates_breakout_coming|0.8
moving_average|is_a|trend_indicator|1.0
sma|is_a|simple_moving_average|1.0
ema|is_a|exponential_moving_average|1.0
ema|reacts|faster_to_price_changes|0.9
golden_cross|is|50_sma_crosses_above_200_sma|1.0
golden_cross|signals|bullish_trend|0.8
death_cross|is|50_sma_crosses_below_200_sma|1.0
death_cross|signals|bearish_trend|0.8
fibonacci_retracement|levels|23.6_38.2_50_61.8_78.6|1.0
fibonacci_retracement|used_for|support_resistance_levels|0.9
volume|confirms|price_movements|0.9
volume_spike|indicates|significant_interest|0.8
obv|stands_for|on_balance_volume|1.0
obv|tracks|cumulative_volume_flow|1.0
atr|stands_for|average_true_range|1.0
atr|measures|volatility|1.0
atr|used_for|stop_loss_placement|0.9
stochastic_oscillator|is_a|momentum_indicator|1.0
stochastic_oscillator|compares|close_to_range|1.0
ichimoku_cloud|is_a|trend_indicator|1.0
ichimoku_cloud|shows|support_resistance_momentum|1.0
vwap|stands_for|volume_weighted_average_price|1.0
vwap|used_by|institutional_traders|0.9
supertrend|is_a|trend_following_indicator|1.0
supertrend|uses|atr_for_calculation|1.0
adx|stands_for|average_directional_index|1.0
adx|measures|trend_strength|1.0
adx|above_25|strong_trend|0.8
parabolic_sar|is_a|trend_indicator|1.0
parabolic_sar|provides|trailing_stop_levels|0.9
williams_r|is_a|momentum_indicator|1.0
williams_r|similar_to|stochastic_oscillator|0.8
cci|stands_for|commodity_channel_index|1.0
cci|measures|deviation_from_average|1.0
money_flow_index|combines|price_and_volume|1.0
money_flow_index|similar_to|volume_weighted_rsi|0.8
pivot_points|are|calculated_support_resistance|1.0
pivot_points|used_for|intraday_trading|0.9
heikin_ashi|is_a|chart_type|1.0
heikin_ashi|smooths|price_action|0.9
renko|is_a|chart_type|1.0
renko|ignores|time_dimension|1.0
point_and_figure|is_a|chart_type|1.0
point_and_figure|focuses_on|price_movements_only|1.0

# === TRADING STRATEGIES ===
scalping|is_a|trading_strategy|1.0
scalping|timeframe|seconds_to_minutes|1.0
scalping|targets|small_frequent_profits|1.0
day_trading|is_a|trading_strategy|1.0
day_trading|closes|all_positions_daily|1.0
swing_trading|is_a|trading_strategy|1.0
swing_trading|holds|days_to_weeks|1.0
position_trading|is_a|trading_strategy|1.0
position_trading|holds|weeks_to_months|1.0
grid_trading|is_a|trading_strategy|1.0
grid_trading|places|orders_at_intervals|1.0
dca|stands_for|dollar_cost_averaging|1.0
dca|reduces|timing_risk|0.9
mean_reversion|assumes|price_returns_to_average|0.8
trend_following|rides|existing_momentum|0.8
breakout_trading|enters|when_price_breaks_level|1.0
arbitrage|exploits|price_differences|1.0
triangular_arbitrage|uses|three_currency_pairs|1.0
statistical_arbitrage|uses|quantitative_models|1.0
market_making|provides|liquidity_both_sides|1.0
market_making|profits_from|spread|1.0
momentum_trading|follows|strong_price_movement|1.0
contrarian_trading|goes_against|market_consensus|0.8
pairs_trading|trades|correlated_assets|1.0
risk_reward_ratio|minimum|1_to_2_recommended|0.9
position_sizing|limits|risk_per_trade|1.0
kelly_criterion|calculates|optimal_bet_size|0.8
martingale|doubles|position_after_loss|0.7
martingale|risk|account_blowup|0.9
anti_martingale|doubles|position_after_win|0.7

# === EXCHANGE TYPES AND FEATURES ===
cex|stands_for|centralized_exchange|1.0
dex|stands_for|decentralized_exchange|1.0
cex|examples|binance_coinbase_kraken|1.0
dex|examples|uniswap_sushiswap_curve|1.0
cex|has|kyc_requirements|1.0
dex|has|no_kyc_required|1.0
spot_trading|buys|actual_asset|1.0
futures_trading|trades|contracts_not_asset|1.0
perpetual_futures|has|no_expiry_date|1.0
options_trading|gives|right_not_obligation|1.0
leverage|amplifies|gains_and_losses|1.0
leverage|maximum|typically_100x_to_125x|0.9
cross_exchange_arbitrage|exploits|price_differences_between_exchanges|1.0
flash_loan|borrows|without_collateral|1.0
flash_loan|must_repay|in_same_transaction|1.0
mev|stands_for|maximal_extractable_value|1.0
mev|includes|frontrunning_sandwich_attacks|1.0
sandwich_attack|exploits|pending_transactions|1.0
frontrunning|places|order_before_large_trade|1.0

# === RISK MANAGEMENT ===
risk_management|is|most_important_trading_skill|1.0
never_risk_more|than|1_to_2_percent_per_trade|0.9
stop_loss_placement|based_on|atr_or_structure|0.9
take_profit|should_be|at_least_2x_stop_loss|0.8
hedging|reduces|portfolio_risk|0.9
hedging|uses|inverse_positions|1.0
diversification|reduces|single_asset_risk|0.9
correlation|measures|asset_price_relationship|1.0
max_drawdown|measures|peak_to_trough_decline|1.0
sharpe_ratio|measures|risk_adjusted_returns|1.0
sortino_ratio|measures|downside_risk_adjusted_returns|1.0
profit_factor|equals|gross_profit_over_gross_loss|1.0
win_rate|alone|not_enough_without_risk_reward|0.9
emotional_trading|is|biggest_retail_mistake|0.9
fomo|stands_for|fear_of_missing_out|1.0
fomo|causes|buying_tops|0.8
fear_uncertainty_doubt|causes|panic_selling|0.8
overleveraging|leads_to|account_liquidation|0.9
revenge_trading|follows|loss_with_bigger_bet|0.8

# === ADVANCED TRADING CONCEPTS ===
order_flow|analyzes|buying_selling_pressure|1.0
order_flow|uses|level_2_data|1.0
market_structure|defines|higher_highs_higher_lows|1.0
market_structure|break|signals_trend_change|0.9
supply_zone|is_a|resistance_area|1.0
demand_zone|is_a|support_area|1.0
smart_money_concept|tracks|institutional_orders|0.8
fair_value_gap|is_a|price_imbalance|1.0
fair_value_gap|acts_as|magnet_for_price|0.8
liquidity_grab|sweeps|stop_losses|1.0
liquidity_grab|often_precedes|reversal|0.8
equal_highs|contain|liquidity_above|0.9
equal_lows|contain|liquidity_below|0.9
breaker_block|is_a|failed_order_block|1.0
order_block|is_a|institutional_footprint|1.0
order_block|marks|large_order_placement|0.9
displacement|is_a|strong_impulsive_move|1.0
inducement|tricks|retail_into_wrong_direction|0.8
mitigation|is|returning_to_order_block|1.0
choch|stands_for|change_of_character|1.0
bos|stands_for|break_of_structure|1.0
accumulation_schematic|has|spring_and_test|1.0
distribution_schematic|has|upthrust_and_test|1.0
volume_spread_analysis|combines|volume_and_range|1.0
no_demand_bar|shows|weakness_in_uptrend|0.8
no_supply_bar|shows|weakness_in_downtrend|0.8
stopping_volume|indicates|selling_climax|0.8
effort_vs_result|compares|volume_to_price_move|1.0

# === CRYPTO SPECIFIC TRADING ===
altcoin_dominance|measures|altcoin_market_share|1.0
bitcoin_dominance|measures|btc_percentage_of_market|1.0
bitcoin_dominance|rising|usually_bearish_for_alts|0.8
bitcoin_dominance|falling|usually_bullish_for_alts|0.8
gas_fee|is|transaction_cost_on_ethereum|1.0
gas_fee|spikes_during|high_network_activity|0.9
mempool|holds|unconfirmed_transactions|1.0
slippage_tolerance|sets|maximum_acceptable_slippage|1.0
price_impact|increases_with|trade_size_relative_to_pool|1.0
sandwich_bot|monitors|mempool_for_large_trades|1.0
flash_crash|is_a|sudden_price_drop|1.0
flash_crash|caused_by|cascading_liquidations|0.8
basis_trade|profits_from|futures_spot_difference|1.0
carry_trade|collects|funding_rate_payments|1.0
cash_and_carry|buys_spot|sells_futures|1.0
delta_neutral|has|zero_directional_exposure|1.0
perpetual_swap|most_traded|crypto_derivative|1.0
quarterly_futures|expire|every_3_months|1.0
inverse_perpetual|settled_in|cryptocurrency|1.0
linear_perpetual|settled_in|usdt|1.0
mark_price|prevents|unnecessary_liquidations|1.0
index_price|averages|multiple_exchange_prices|1.0
insurance_fund|covers|bankrupt_positions|1.0
auto_deleveraging|reduces|profitable_positions|0.8
position_mode|can_be|one_way_or_hedge|1.0
hedge_mode|allows|long_and_short_simultaneously|1.0

# === DEFI ADVANCED ===
flash_loan_arbitrage|uses|uncollateralized_loan|1.0
flash_loan_arbitrage|profits_from|price_discrepancy|1.0
vampire_attack|lures|liquidity_from_competitor|0.8
protocol_owned_liquidity|removes|mercenary_capital_risk|0.9
ve_tokenomics|locks_tokens_for|voting_power|1.0
ve_tokenomics|pioneered_by|curve_finance|1.0
bribing|pays|veCRV_holders_for_gauge_votes|0.8
gauge_weight|determines|emissions_allocation|1.0
real_yield|comes_from|protocol_revenue_not_emissions|0.9
ponzinomics|relies_on|new_money_for_old_payouts|0.8
rehypothecation|reuses|collateral_multiple_times|0.8
recursive_borrowing|loops|deposit_borrow_deposit|1.0
leveraged_staking|amplifies|staking_returns|1.0
liquid_restaking|stakes|lst_tokens_again|1.0
eigenlayer|enables|restaking_on_ethereum|1.0
account_abstraction|improves|wallet_ux|1.0
intent_based_trading|specifies|desired_outcome|1.0
crosschain_bridge|connects|different_blockchains|1.0
bridge_exploit|is|common_defi_hack_vector|0.9
wrapped_token|represents|asset_on_another_chain|1.0

# === PSYCHOLOGY AND DISCIPLINE ===
trading_journal|records|all_trades_and_reasoning|1.0
trading_journal|improves|self_awareness|0.9
backtesting|tests|strategy_on_historical_data|1.0
backtesting|limitation|past_not_equal_future|0.8
paper_trading|practices|without_real_money|1.0
paper_trading|builds|confidence_and_skill|0.8
cognitive_bias|affects|trading_decisions|0.9
confirmation_bias|seeks|info_supporting_position|0.8
anchoring_bias|fixates_on|entry_price|0.8
recency_bias|overweights|recent_events|0.8
loss_aversion|holds|losers_too_long|0.9
disposition_effect|sells|winners_too_early|0.8
overconfidence|leads_to|excessive_risk_taking|0.8
hindsight_bias|makes_past|seem_predictable|0.7
gambler_fallacy|assumes|past_affects_probability|0.8
sunk_cost_fallacy|holds|bad_position_due_to_loss|0.8
trading_plan|defines|entry_exit_risk_rules|1.0
trading_plan|must_be|followed_without_emotion|0.9
risk_of_ruin|probability|losing_entire_account|1.0
risk_of_ruin|minimized_by|proper_sizing|0.9
max_consecutive_losses|determines|drawdown_risk|0.9
expectancy|combines|win_rate_and_risk_reward|1.0

# === MARKET MICROSTRUCTURE ===
tick_size|is|minimum_price_increment|1.0
lot_size|is|minimum_order_size|1.0
circuit_breaker|halts|trading_on_extreme_moves|1.0
dark_pool|executes|large_orders_privately|1.0
spoofing|places|fake_orders_to_manipulate|0.8
wash_trading|inflates|volume_artificially|0.8
pump_and_dump|artificially|inflates_then_sells|0.9
rug_pull|removes|liquidity_suddenly|1.0
rug_pull|common_in|new_defi_tokens|0.8
honeypot_token|cannot|be_sold_after_buying|1.0
front_running_protection|uses|flashbots_or_private_txns|0.9
time_in_force|specifies|order_duration|1.0
good_till_cancelled|remains|until_filled_or_cancelled|1.0
day_order|expires|end_of_trading_day|1.0
auction|determines|opening_closing_price|1.0
price_discovery|process_of|finding_fair_value|1.0
efficient_market_hypothesis|claims|prices_reflect_all_info|0.7
random_walk_theory|claims|prices_are_unpredictable|0.7
behavioral_finance|studies|psychological_market_effects|1.0

# === CENTRALIZED EXCHANGE FEATURES ===
binance|is_a|crypto_exchange|1.0
binance|largest_by|trading_volume|0.9
binance|token|BNB|1.0
coinbase|is_a|crypto_exchange|1.0
coinbase|publicly_traded|nasdaq_COIN|1.0
kraken|is_a|crypto_exchange|1.0
kraken|known_for|security|0.9
bybit|is_a|crypto_exchange|1.0
bybit|popular_for|derivatives_trading|0.9
okx|is_a|crypto_exchange|1.0
bitget|is_a|crypto_exchange|1.0
kucoin|is_a|crypto_exchange|1.0
copy_trading|follows|successful_traders|1.0
copy_trading|risk|leader_can_still_lose|0.8
social_trading|combines|trading_and_community|1.0
trading_bot|automates|strategy_execution|1.0
api_trading|uses|programmatic_order_placement|1.0
websocket|provides|real_time_market_data|1.0
rest_api|provides|account_and_order_management|1.0
rate_limiting|restricts|api_calls_per_second|1.0
vip_tier|reduces|trading_fees|1.0
maker_rebate|pays|for_providing_liquidity|0.9
sub_account|separates|trading_strategies|1.0
portfolio_margin|calculates|risk_across_all_positions|1.0
unified_margin|shares|collateral_across_products|1.0
dual_investment|combines|staking_with_options|1.0
launchpool|stakes_tokens|for_new_project_allocation|1.0
launchpad|allows|early_token_purchase|1.0
otc_desk|handles|large_block_trades|1.0
otc_desk|avoids|slippage_on_large_orders|0.9
earn_products|offer|passive_yield_on_holdings|1.0
staking_service|delegates|to_validators|1.0
savings_account|offers|flexible_or_locked_yield|1.0
margin_interest|charged_for|borrowed_funds|1.0

# === BLOCKCHAIN ANALYTICS ===
glassnode|is_a|on_chain_analytics_platform|1.0
nansen|is_a|on_chain_analytics_platform|1.0
nansen|tracks|smart_money_wallets|1.0
dune_analytics|is_a|blockchain_data_platform|1.0
dune_analytics|uses|sql_queries|1.0
defi_llama|tracks|tvl_across_protocols|1.0
etherscan|is_a|block_explorer|1.0
token_terminal|tracks|protocol_revenue|1.0
messari|provides|crypto_research_data|1.0
coingecko|tracks|token_prices_and_data|1.0
coinmarketcap|tracks|market_cap_rankings|1.0
fear_and_greed_index|measures|market_sentiment|1.0
fear_and_greed_index|range|0_extreme_fear_to_100_extreme_greed|1.0
long_short_ratio|shows|trader_positioning|1.0
funding_rate_positive|means|longs_pay_shorts|1.0
funding_rate_negative|means|shorts_pay_longs|1.0
whale_alert|tracks|large_transactions|1.0
exchange_reserve|declining|bullish_signal|0.8
exchange_reserve|increasing|bearish_signal|0.8
stablecoin_supply|increasing|buying_power_available|0.8
miner_revenue|affects|selling_pressure|0.7
hash_rate|measures|network_security|1.0
difficulty_adjustment|maintains|block_time|1.0

# === ADDITIONAL CRYPTO KNOWLEDGE ===
defi_insurance|protects_against|smart_contract_exploits|1.0
nexus_mutual|is_a|defi_insurance_protocol|1.0
oracle|provides|off_chain_data_to_smart_contracts|1.0
chainlink|is_a|decentralized_oracle_network|1.0
chainlink|token|LINK|1.0
layer_2_scaling|processes|transactions_off_main_chain|1.0
optimistic_rollup|assumes|transactions_valid_unless_challenged|1.0
zk_rollup|uses|zero_knowledge_proofs_for_validity|1.0
arbitrum|is_a|optimistic_rollup|1.0
optimism|is_a|optimistic_rollup|1.0
polygon|is_a|ethereum_scaling_solution|1.0
polygon|token|MATIC|1.0
zksync|is_a|zk_rollup|1.0
starknet|is_a|zk_rollup|1.0
base|is_a|layer_2_by_coinbase|1.0
solana|is_a|high_performance_blockchain|1.0
solana|tps|thousands_per_second|1.0
solana|consensus|proof_of_history|1.0
avalanche|is_a|blockchain_platform|1.0
avalanche|uses|subnets|1.0
cosmos|is_a|interoperability_protocol|1.0
cosmos|uses|ibc_protocol|1.0
polkadot|is_a|interoperability_protocol|1.0
polkadot|uses|parachains|1.0
nft|stands_for|non_fungible_token|1.0
nft|standard|erc721|1.0
erc20|is_a|fungible_token_standard|1.0
erc1155|is_a|multi_token_standard|1.0
dao|stands_for|decentralized_autonomous_organization|1.0
governance_voting|allows|token_holders_to_decide|1.0
multisig_wallet|requires|multiple_signatures|1.0
hardware_wallet|stores|keys_offline|1.0
cold_storage|keeps|crypto_offline|1.0
hot_wallet|connected_to|internet|1.0
seed_phrase|is|12_or_24_words_for_recovery|1.0
gas_optimization|reduces|transaction_costs|1.0
eip_1559|introduced|base_fee_burning|1.0
mev_protection|uses|private_transaction_pools|1.0
token_sniping|buys|immediately_after_listing|0.8
bot_trading|automates|trading_decisions|1.0
grid_bot|places|buy_sell_at_intervals|1.0
dca_bot|automates|dollar_cost_averaging|1.0
rebalancing_bot|maintains|portfolio_allocation|1.0
sentiment_analysis|gauges|market_mood|1.0
social_trading|follows|top_trader_positions|1.0
portfolio_tracker|monitors|all_holdings|1.0
tax_reporting|calculates|crypto_capital_gains|1.0
fifo|method|first_in_first_out_tax|1.0
lifo|method|last_in_first_out_tax|1.0
wash_sale|selling_and_rebuying|for_tax_loss|0.8
stablecoin|pegged_to|fiat_currency|1.0
usdt|is_a|centralized_stablecoin|1.0
usdc|is_a|centralized_stablecoin|1.0
dai|is_a|decentralized_stablecoin|1.0
algorithmic_stablecoin|maintains_peg|via_algorithms|1.0
depeg_event|stablecoin|loses_its_peg|0.8

# === MORE UNIQUE CRYPTO FACTS ===
bitcoin_max_supply|exact|21000000|1.0
bitcoin_current_reward|is|3_125_btc_per_block|1.0
bitcoin_next_halving|approximately|2028|1.0
ethereum_gas_unit|is|gwei|1.0
ethereum_burned_since_eip1559|over|3_million_eth|0.8
solana_tps_record|over|65000|0.8
avalanche_subnet|is_a|custom_blockchain|1.0
cosmos_ibc_transfers|enable|cross_chain_tokens|1.0
polkadot_relay_chain|coordinates|parachains|1.0
near_protocol|uses|nightshade_sharding|1.0
aptos|uses|move_language|1.0
sui|uses|move_language|1.0
sei_blockchain|optimized_for|trading|1.0
injective|optimized_for|defi|1.0
ton_blockchain|created_by|telegram_team|1.0
tron|is_a|high_throughput_blockchain|1.0
bnb_chain|formerly|binance_smart_chain|1.0
fantom|uses|dag_based_consensus|1.0
hedera|uses|hashgraph_consensus|1.0
algorand|uses|pure_proof_of_stake|1.0
cardano|uses|ouroboros_proof_of_stake|1.0
tezos|uses|liquid_proof_of_stake|1.0
filecoin|provides|decentralized_storage|1.0
arweave|provides|permanent_storage|1.0
the_graph|indexes|blockchain_data|1.0
chainlink_ccip|enables|cross_chain_messaging|1.0
layerzero|enables|omnichain_messaging|1.0
wormhole|is_a|cross_chain_bridge|1.0
hyperliquid|is_a|perpetual_dex|1.0
drift|is_a|solana_perpetual_dex|1.0
marinade|is_a|solana_staking_protocol|1.0
jito|provides|mev_protection_on_solana|1.0
tensor|is_a|solana_nft_marketplace|1.0
blur|is_a|ethereum_nft_marketplace|1.0
opensea|is_a|nft_marketplace|1.0
ordinals|are|bitcoin_nfts|1.0
brc20|is_a|bitcoin_token_standard|1.0
runes|is_a|bitcoin_fungible_token|1.0
