# MK Knowledge File - Finance and Economics
# Format: source|relation|target|weight
# Covers: stock markets, options/futures, central banks, personal finance, economic indicators

# === STOCK MARKETS ===
stock_market|is_a|securities_exchange|1.0
stock|represents|ownership_in_company|1.0
nyse|stands_for|new_york_stock_exchange|1.0
nasdaq|is_a|electronic_stock_exchange|1.0
sp500|tracks|500_large_us_companies|1.0
dow_jones|tracks|30_large_us_companies|1.0
nasdaq_composite|tracks|all_nasdaq_stocks|1.0
ftse_100|tracks|100_largest_uk_companies|1.0
nikkei_225|tracks|225_japanese_companies|1.0
dax|tracks|40_german_companies|1.0
market_cap|equals|share_price_times_shares_outstanding|1.0
large_cap|market_cap|above_10_billion|1.0
mid_cap|market_cap|2_to_10_billion|1.0
small_cap|market_cap|below_2_billion|1.0
pe_ratio|measures|price_to_earnings|1.0
pe_ratio|high|growth_expectations|0.8
pe_ratio|low|value_or_declining|0.7
eps|stands_for|earnings_per_share|1.0
dividend|is|payment_to_shareholders|1.0
dividend_yield|equals|annual_dividend_over_price|1.0
book_value|is|total_assets_minus_liabilities|1.0
pb_ratio|measures|price_to_book_value|1.0
roe|stands_for|return_on_equity|1.0
revenue|is|total_income_before_expenses|1.0
ebitda|stands_for|earnings_before_interest_tax_depreciation_amortization|1.0
free_cash_flow|is|cash_after_capex|1.0
market_order|executes|immediately_at_market_price|1.0
limit_order|executes|at_specified_price_or_better|1.0
short_selling|profits_from|price_decline|1.0
short_squeeze|forces|shorts_to_cover|1.0
ipo|stands_for|initial_public_offering|1.0
ipo|is|company_going_public|1.0
spac|stands_for|special_purpose_acquisition_company|1.0
market_maker|provides|liquidity|1.0
dark_pool|trades|large_blocks_privately|1.0
after_hours_trading|occurs|outside_regular_hours|1.0
circuit_breaker|halts|trading_on_extreme_moves|1.0
bull_market|defined_by|20_percent_rise_from_low|1.0
bear_market|defined_by|20_percent_decline_from_high|1.0
correction|is|10_percent_decline|1.0
sector|types|technology_healthcare_finance_energy|1.0
etf|stands_for|exchange_traded_fund|1.0
etf|tracks|index_or_asset_basket|1.0
index_fund|passively|tracks_an_index|1.0
mutual_fund|actively|managed_by_professionals|1.0
hedge_fund|uses|complex_strategies|1.0
robo_advisor|automates|portfolio_management|1.0

# === OPTIONS AND FUTURES ===
call_option|gives|right_to_buy|1.0
put_option|gives|right_to_sell|1.0
strike_price|is|exercise_price|1.0
premium|is|price_paid_for_option|1.0
expiration_date|is|when_option_expires|1.0
in_the_money|has|intrinsic_value|1.0
out_of_the_money|has|no_intrinsic_value|1.0
at_the_money|strike|equals_current_price|1.0
intrinsic_value|is|immediate_exercise_profit|1.0
time_value|is|premium_minus_intrinsic|1.0
delta|measures|price_change_per_dollar_move|1.0
gamma|measures|delta_change_rate|1.0
theta|measures|time_decay|1.0
vega|measures|sensitivity_to_volatility|1.0
rho|measures|sensitivity_to_interest_rates|1.0
implied_volatility|reflects|market_expectation_of_movement|1.0
iv_crush|occurs_after|earnings_or_events|1.0
covered_call|sells|call_against_owned_shares|1.0
protective_put|buys|put_for_downside_protection|1.0
iron_condor|profits_from|low_volatility|1.0
straddle|profits_from|large_move_either_direction|1.0
strangle|similar_to|straddle_but_cheaper|1.0
butterfly_spread|profits_from|price_staying_near_strike|1.0
vertical_spread|limits|risk_and_reward|1.0
futures_contract|obligates|buy_sell_at_future_date|1.0
futures_contract|standardized|exchange_traded|1.0
margin_requirement|deposit_for|futures_positions|1.0
contango|futures_price|above_spot_price|1.0
backwardation|futures_price|below_spot_price|1.0
leverage|in_futures|significant_amplification|1.0
commodity_futures|trade|oil_gold_wheat_etc|1.0
index_futures|trade|sp500_nasdaq_etc|1.0
settlement|can_be|physical_or_cash|1.0

# === CENTRAL BANKS ===
federal_reserve|is|us_central_bank|1.0
federal_reserve|sets|federal_funds_rate|1.0
ecb|stands_for|european_central_bank|1.0
ecb|manages|eurozone_monetary_policy|1.0
bank_of_england|is|uk_central_bank|1.0
bank_of_japan|is|japanese_central_bank|1.0
pboc|is|chinese_central_bank|1.0
interest_rate|affects|borrowing_cost|1.0
rate_hike|makes|borrowing_expensive|1.0
rate_hike|typically|bearish_for_stocks|0.8
rate_cut|makes|borrowing_cheaper|1.0
rate_cut|typically|bullish_for_stocks|0.8
quantitative_easing|is|buying_bonds_to_inject_money|1.0
quantitative_easing|increases|money_supply|1.0
quantitative_tightening|is|reducing_bond_holdings|1.0
quantitative_tightening|decreases|money_supply|1.0
inflation_target|typically|2_percent|1.0
monetary_policy|tools|rates_qe_reserve_requirements|1.0
fiscal_policy|controlled_by|government_not_central_bank|1.0
open_market_operations|buy_sell|government_bonds|1.0
reserve_requirement|is|minimum_bank_reserves|1.0
yield_curve|plots|interest_rates_by_maturity|1.0
inverted_yield_curve|historically|predicts_recession|0.8
bond_yield|inverse_relationship|bond_price|1.0
treasury_bonds|are|us_government_debt|1.0
10_year_treasury|is|benchmark_rate|1.0

# === PERSONAL FINANCE ===
compound_interest|grows|exponentially_over_time|1.0
compound_interest|formula|P_times_1_plus_r_to_n|1.0
rule_of_72|estimates|doubling_time|1.0
rule_of_72|divide_72_by|interest_rate|1.0
fire_movement|stands_for|financial_independence_retire_early|1.0
fire|requires|high_savings_rate|1.0
4_percent_rule|suggests|safe_withdrawal_rate|0.8
emergency_fund|should_cover|3_to_6_months_expenses|1.0
budgeting|tracks|income_and_expenses|1.0
50_30_20_rule|splits|needs_wants_savings|1.0
dollar_cost_averaging|invests|fixed_amount_regularly|1.0
diversification|reduces|portfolio_risk|1.0
asset_allocation|splits|stocks_bonds_cash|1.0
rebalancing|maintains|target_allocation|1.0
tax_advantaged_account|types|401k_ira_roth|1.0
401k|is_a|employer_retirement_plan|1.0
roth_ira|grows|tax_free|1.0
traditional_ira|is|tax_deferred|1.0
capital_gains_tax|applied_to|investment_profits|1.0
long_term_capital_gains|taxed_at|lower_rate|1.0
tax_loss_harvesting|offsets|gains_with_losses|1.0
estate_planning|includes|will_trust_beneficiaries|1.0
credit_score|range|300_to_850|1.0
credit_score|affects|borrowing_ability_and_rates|1.0
debt_to_income|ratio|monthly_debt_over_income|1.0
mortgage|is_a|secured_loan_for_property|1.0
amortization|spreads|payments_over_loan_term|1.0

# === ECONOMIC INDICATORS ===
gdp|stands_for|gross_domestic_product|1.0
gdp|measures|total_economic_output|1.0
gdp_growth|positive|economic_expansion|1.0
gdp_growth|negative_two_quarters|recession|1.0
cpi|stands_for|consumer_price_index|1.0
cpi|measures|inflation|1.0
pce|stands_for|personal_consumption_expenditures|1.0
pce|preferred_by|federal_reserve|1.0
inflation|is|general_price_increase|1.0
deflation|is|general_price_decrease|1.0
stagflation|combines|stagnation_and_inflation|1.0
hyperinflation|is|extremely_rapid_inflation|1.0
unemployment_rate|measures|jobless_workforce_percentage|1.0
nfp|stands_for|non_farm_payrolls|1.0
nfp|released|first_friday_monthly|1.0
pmi|stands_for|purchasing_managers_index|1.0
pmi|above_50|expansion|1.0
pmi|below_50|contraction|1.0
consumer_confidence|measures|spending_outlook|1.0
housing_starts|indicates|construction_activity|1.0
retail_sales|measures|consumer_spending|1.0
industrial_production|measures|manufacturing_output|1.0
trade_balance|exports_minus|imports|1.0
current_account|tracks|international_transactions|1.0
leading_indicators|predict|future_economic_activity|1.0
lagging_indicators|confirm|past_economic_trends|1.0
coincident_indicators|reflect|current_conditions|1.0
vix|measures|market_volatility_expectation|1.0
vix|called|fear_index|0.8
bond_spread|measures|risk_premium|1.0
credit_spread|widens_in|market_stress|0.9
supply_and_demand|determines|market_prices|1.0
elasticity|measures|price_sensitivity|1.0
opportunity_cost|is|next_best_alternative_forgone|1.0
marginal_utility|decreases|with_consumption|1.0
economies_of_scale|reduce|per_unit_cost|1.0
comparative_advantage|drives|international_trade|1.0

# === BANKING AND FINANCIAL INSTRUMENTS ===
commercial_bank|takes|deposits_and_makes_loans|1.0
investment_bank|helps|companies_raise_capital|1.0
central_bank|controls|monetary_policy|1.0
fractional_reserve|banks_lend|more_than_they_hold|1.0
money_multiplier|amplifies|base_money|1.0
bond|is_a|fixed_income_security|1.0
corporate_bond|issued_by|companies|1.0
municipal_bond|issued_by|local_governments|1.0
junk_bond|is|high_yield_high_risk|1.0
zero_coupon_bond|pays|no_interest_sold_at_discount|1.0
convertible_bond|can_be|converted_to_stock|1.0
yield_to_maturity|is|total_return_if_held|1.0
duration|measures|interest_rate_sensitivity|1.0
coupon_rate|is|annual_interest_payment|1.0
face_value|is|bond_par_value|1.0
credit_rating|agencies|moody_sp_fitch|1.0
aaa_rating|is|highest_credit_quality|1.0
investment_grade|rating|bbb_or_above|1.0
cds|stands_for|credit_default_swap|1.0
cds|insures_against|bond_default|1.0
mbs|stands_for|mortgage_backed_security|1.0
abs|stands_for|asset_backed_security|1.0
securitization|packages|loans_into_securities|1.0
derivative|derives|value_from_underlying_asset|1.0
swap|exchanges|cash_flows|1.0
interest_rate_swap|exchanges|fixed_for_floating|1.0
currency_swap|exchanges|different_currencies|1.0
repo|stands_for|repurchase_agreement|1.0
repo|is|short_term_secured_lending|1.0
money_market|trades|short_term_instruments|1.0
commercial_paper|is|short_term_corporate_debt|1.0
certificate_of_deposit|is|time_deposit_at_bank|1.0
libor|was|benchmark_interest_rate|1.0
sofr|replaces|libor|1.0
sofr|stands_for|secured_overnight_financing_rate|1.0

# === INTERNATIONAL FINANCE ===
forex|is_a|foreign_exchange_market|1.0
forex|daily_volume|over_6_trillion_usd|1.0
currency_pair|notation|base_quote|1.0
eur_usd|is|most_traded_pair|1.0
pip|is|minimum_price_movement|1.0
carry_trade|borrows_low_rate|invests_high_rate|1.0
exchange_rate|determined_by|supply_and_demand|1.0
floating_exchange_rate|set_by|market_forces|1.0
fixed_exchange_rate|pegged_to|another_currency|1.0
devaluation|reduces|currency_value|1.0
strong_dollar|makes|imports_cheaper|1.0
weak_dollar|makes|exports_competitive|1.0
balance_of_payments|tracks|all_international_flows|1.0
capital_flight|is|rapid_money_outflow|1.0
sovereign_debt|is|government_borrowing|1.0
imf|stands_for|international_monetary_fund|1.0
world_bank|provides|development_loans|1.0
swift|enables|international_bank_transfers|1.0
sanctions|restrict|financial_transactions|1.0
offshore_banking|provides|tax_advantages|0.8
tax_haven|offers|low_or_no_taxes|1.0

# === BEHAVIORAL FINANCE ===
efficient_market_hypothesis|claims|prices_reflect_all_info|0.7
behavioral_finance|studies|irrational_market_behavior|1.0
herd_mentality|follows|crowd_regardless_of_fundamentals|0.9
loss_aversion|losses_feel|twice_as_painful_as_gains|1.0
anchoring_bias|fixates_on|irrelevant_reference_point|0.9
overconfidence_bias|overestimates|own_abilities|0.9
availability_heuristic|overweights|recent_memorable_events|0.8
sunk_cost_fallacy|continues|due_to_past_investment|0.9
endowment_effect|overvalues|what_we_own|0.8
prospect_theory|people|evaluate_gains_losses_differently|1.0
mental_accounting|treats|money_differently_by_source|0.8
disposition_effect|sells_winners|holds_losers|0.9
momentum_effect|past_winners|continue_winning|0.7
value_effect|cheap_stocks|outperform_long_term|0.7
january_effect|stocks_rally|in_january|0.6
market_bubble|prices_exceed|fundamental_value|1.0
tulip_mania|was|first_recorded_bubble|1.0
dot_com_bubble|burst_in|2000|1.0
2008_financial_crisis|caused_by|subprime_mortgages|1.0
black_swan|is|rare_high_impact_event|1.0

# === INVESTMENT STRATEGIES ===
value_investing|buys|underpriced_assets|1.0
value_investing|pioneer|benjamin_graham|1.0
growth_investing|buys|high_growth_companies|1.0
momentum_investing|follows|price_trends|1.0
income_investing|focuses_on|dividends_and_interest|1.0
contrarian_investing|goes_against|market_consensus|1.0
factor_investing|targets|specific_risk_factors|1.0
esg_investing|considers|environmental_social_governance|1.0
quantitative_investing|uses|mathematical_models|1.0
passive_investing|tracks|market_index|1.0
active_investing|tries_to|beat_the_market|1.0
warren_buffett|is|famous_value_investor|1.0
modern_portfolio_theory|optimizes|risk_return_tradeoff|1.0
sharpe_ratio|measures|risk_adjusted_return|1.0
beta|measures|market_sensitivity|1.0
alpha|measures|excess_return_over_benchmark|1.0
capm|stands_for|capital_asset_pricing_model|1.0
efficient_frontier|shows|optimal_portfolios|1.0
black_scholes|prices|european_options|1.0
monte_carlo_simulation|models|price_scenarios|1.0
backtesting|tests|strategy_on_historical_data|1.0
paper_trading|practices|without_real_money|1.0
position_sizing|determines|how_much_to_invest|1.0
stop_loss|limits|downside_risk|1.0
trailing_stop|protects|accumulated_gains|1.0

# === CORPORATE FINANCE ===
balance_sheet|shows|assets_liabilities_equity|1.0
income_statement|shows|revenue_expenses_profit|1.0
cash_flow_statement|shows|cash_inflows_outflows|1.0
working_capital|equals|current_assets_minus_current_liabilities|1.0
debt_to_equity|measures|financial_leverage|1.0
current_ratio|measures|short_term_liquidity|1.0
quick_ratio|excludes|inventory_from_current_ratio|1.0
return_on_assets|measures|profit_per_asset_dollar|1.0
gross_margin|is|revenue_minus_cogs|1.0
operating_margin|is|operating_income_over_revenue|1.0
net_margin|is|net_income_over_revenue|1.0
cost_of_capital|is|minimum_required_return|1.0
wacc|stands_for|weighted_average_cost_of_capital|1.0
npv|stands_for|net_present_value|1.0
irr|stands_for|internal_rate_of_return|1.0
dcf|stands_for|discounted_cash_flow|1.0
dcf|values_company_by|future_cash_flows|1.0
merger|combines|two_companies|1.0
acquisition|one_company|buys_another|1.0
leveraged_buyout|uses|debt_to_acquire|1.0
venture_capital|invests_in|early_stage_companies|1.0
private_equity|invests_in|mature_private_companies|1.0
angel_investor|provides|seed_funding|1.0
series_a_b_c|are|funding_rounds|1.0
valuation|determines|company_worth|1.0

# === REAL ESTATE ===
real_estate|is_a|asset_class|1.0
reit|stands_for|real_estate_investment_trust|1.0
reit|pays|90_percent_of_income_as_dividends|1.0
cap_rate|measures|property_return|1.0
cap_rate|equals|noi_over_property_value|1.0
ltv|stands_for|loan_to_value_ratio|1.0
appreciation|is|property_value_increase|1.0
rental_yield|is|annual_rent_over_price|1.0
cash_on_cash_return|measures|actual_cash_return|1.0
leverage_in_real_estate|amplifies|returns_with_mortgage|1.0
house_flipping|buys_renovates|sells_for_profit|1.0
commercial_real_estate|includes|office_retail_industrial|1.0
residential_real_estate|includes|houses_apartments_condos|1.0

# === INSURANCE AND RISK ===
insurance|transfers|risk_to_insurer|1.0
premium|is|price_of_insurance|1.0
deductible|is|amount_before_coverage|1.0
underwriting|assesses|risk_for_pricing|1.0
actuarial_science|calculates|risk_probabilities|1.0
life_insurance|types|term_whole_universal|1.0
health_insurance|covers|medical_expenses|1.0
property_insurance|covers|physical_assets|1.0
liability_insurance|covers|legal_claims|1.0
reinsurance|insures|insurance_companies|1.0
moral_hazard|increases|risk_taking_with_insurance|0.8
adverse_selection|attracts|high_risk_buyers|0.8
hedging|reduces|portfolio_risk|1.0
portfolio_insurance|uses|puts_for_protection|1.0
tail_risk|is|extreme_unlikely_events|1.0
value_at_risk|estimates|potential_loss|1.0
stress_testing|models|extreme_scenarios|1.0

# === TAXATION ===
progressive_tax|higher_rate|for_higher_income|1.0
marginal_tax_rate|applies_to|last_dollar_earned|1.0
effective_tax_rate|is|total_tax_over_total_income|1.0
capital_gains|is|profit_from_asset_sale|1.0
short_term_capital_gains|taxed_as|ordinary_income|1.0
long_term_capital_gains|held|over_one_year|1.0
tax_deduction|reduces|taxable_income|1.0
tax_credit|reduces|tax_owed_directly|1.0
depreciation|is|asset_value_decline_over_time|1.0
1031_exchange|defers|capital_gains_on_real_estate|1.0
tax_bracket|determines|rate_for_income_range|1.0
corporate_tax|applies_to|company_profits|1.0
vat|stands_for|value_added_tax|1.0
sales_tax|applied_at|point_of_sale|1.0
withholding_tax|deducted|from_salary|1.0
offshore_account|is_in|foreign_jurisdiction|1.0
tax_treaty|prevents|double_taxation|1.0

# === ECONOMIC THEORIES ===
keynesian_economics|advocates|government_spending|1.0
monetarism|focuses_on|money_supply_control|1.0
supply_side_economics|reduces|taxes_to_stimulate|0.8
marxist_economics|critiques|capitalism|1.0
austrian_economics|favors|free_markets_sound_money|1.0
game_theory|studies|strategic_decision_making|1.0
nash_equilibrium|no_player|benefits_from_changing|1.0
prisoners_dilemma|illustrates|cooperation_vs_betrayal|1.0
moral_hazard|incentivizes|risk_when_protected|1.0
free_rider_problem|benefits|without_contributing|1.0
tragedy_of_commons|overuses|shared_resources|1.0
gresham_law|bad_money|drives_out_good|1.0
phillips_curve|relates|inflation_to_unemployment|0.8
laffer_curve|shows|tax_revenue_vs_rate|0.7
pareto_efficiency|no_one|better_off_without_harm|1.0
gdp_per_capita|measures|individual_economic_output|1.0
purchasing_power_parity|adjusts|for_cost_of_living|1.0
gini_coefficient|measures|income_inequality|1.0
human_development_index|combines|life_health_education_income|1.0
recession|is|significant_economic_decline|1.0
depression|is|severe_prolonged_recession|1.0
austerity|reduces|government_spending|1.0
stimulus|increases|government_spending|1.0
deficit|is|spending_exceeds_revenue|1.0
national_debt|is|accumulated_deficits|1.0
debt_to_gdp|measures|debt_sustainability|1.0

# === ADDITIONAL UNIQUE FINANCE FACTS ===
high_frequency_trading|uses|algorithms_for_microsecond_trades|1.0
algorithmic_trading|automates|trading_decisions|1.0
smart_order_routing|finds|best_execution_venue|1.0
market_microstructure|studies|trading_mechanisms|1.0
tick_data|records|every_price_change|1.0
order_book_imbalance|signals|short_term_direction|0.8
time_weighted_average_price|minimizes|market_impact|1.0
volume_weighted_average_price|benchmarks|execution_quality|1.0
dark_pool_execution|avoids|market_impact|1.0
flash_crash_2010|lasted|about_36_minutes|1.0
market_fragmentation|spreads|liquidity_across_venues|1.0
regulation_nms|governs|us_equity_markets|1.0
mifid_ii|governs|european_markets|1.0
best_execution|obligation|to_get_best_price|1.0
payment_for_order_flow|controversial|market_practice|0.8
retail_trading_platform|examples|robinhood_etoro_webull|1.0
fractional_shares|allow|investing_small_amounts|1.0
direct_indexing|buys|individual_stocks_not_fund|1.0
tax_loss_harvesting_automated|uses|algorithms|1.0
robo_advisor_examples|include|betterment_wealthfront|1.0
social_trading_platform|copies|successful_traders|1.0
copy_trading_risk|leader|can_still_lose|0.8
structured_products|combine|derivatives_and_bonds|1.0
collateralized_debt_obligation|packages|debt_tranches|1.0
synthetic_cdo|uses|credit_default_swaps|1.0
total_return_swap|exchanges|asset_return_for_payment|1.0
variance_swap|pays|realized_vs_implied_volatility|1.0
volatility_surface|maps|iv_across_strikes_and_expirations|1.0
skew|measures|put_call_iv_difference|1.0
term_structure|shows|volatility_across_expirations|1.0
