docker|is_a|containerization_platform|1.0
docker|created_by|solomon_hykes|1.0
docker|uses|linux_namespaces|0.9
docker|uses|cgroups|0.9
docker|runs_on|linux|1.0
docker|runs_on|macos|0.9
docker|runs_on|windows|0.9
docker_compose|is_a|container_orchestration_tool|1.0
docker_compose|uses|yaml_files|1.0
docker_compose|manages|multi_container_apps|1.0
dockerfile|defines|container_image|1.0
dockerfile|uses|layer_caching|0.9
dockerfile|starts_with|base_image|1.0
docker_image|contains|application_code|1.0
docker_image|contains|dependencies|1.0
docker_image|stored_in|docker_registry|1.0
docker_hub|is_a|container_registry|1.0
docker_volume|provides|persistent_storage|1.0
docker_network|enables|container_communication|1.0
docker_network|types_include|bridge|1.0
docker_network|types_include|host|0.9
docker_network|types_include|overlay|0.9
container|is_a|isolated_process|1.0
container|lighter_than|virtual_machine|1.0
container|shares|host_kernel|1.0
container|has|own_filesystem|1.0
container|has|own_network_namespace|1.0
portainer|is_a|docker_management_ui|1.0
portainer|provides|web_interface|1.0
portainer|manages|containers|1.0
portainer|manages|images|1.0
portainer|manages|networks|1.0
watchtower|is_a|container_updater|1.0
watchtower|automates|container_updates|1.0
ssh|is_a|network_protocol|1.0
ssh|provides|encrypted_communication|1.0
ssh|uses|port_22|1.0
ssh|supports|key_authentication|1.0
ssh|supports|password_authentication|0.8
ssh_key|is_a|authentication_method|1.0
ssh_key|has_types|rsa|1.0
ssh_key|has_types|ed25519|1.0
ssh_key|has_types|ecdsa|0.9
ed25519|is_a|ssh_key_type|1.0
ed25519|considered|more_secure_than_rsa|0.9
ed25519|has|smaller_key_size|1.0
ssh_config|located_at|~/.ssh/config|1.0
ssh_config|enables|host_aliases|1.0
sshd|is_a|ssh_server_daemon|1.0
sshd|config_at|/etc/ssh/sshd_config|1.0
ssh_tunnel|enables|port_forwarding|1.0
ssh_tunnel|types_include|local_forward|1.0
ssh_tunnel|types_include|remote_forward|1.0
ssh_tunnel|types_include|dynamic_forward|1.0
scp|uses|ssh_protocol|1.0
scp|transfers|files_between_hosts|1.0
rsync|is_a|file_sync_tool|1.0
rsync|uses|ssh_transport|0.9
rsync|supports|incremental_sync|1.0
rsync|faster_than|scp|0.9
linux|is_a|operating_system|1.0
linux|created_by|linus_torvalds|1.0
linux|is|open_source|1.0
linux_kernel|manages|hardware_resources|1.0
linux_kernel|manages|process_scheduling|1.0
linux_kernel|manages|memory_management|1.0
ubuntu|is_a|linux_distribution|1.0
ubuntu|based_on|debian|1.0
ubuntu|popular_for|servers|1.0
debian|is_a|linux_distribution|1.0
debian|known_for|stability|1.0
arch_linux|is_a|linux_distribution|1.0
arch_linux|known_for|rolling_release|1.0
centos|is_a|linux_distribution|1.0
centos|based_on|rhel|1.0
alpine_linux|is_a|linux_distribution|1.0
alpine_linux|known_for|minimal_size|1.0
alpine_linux|popular_for|containers|1.0
systemd|is_a|init_system|1.0
systemd|manages|system_services|1.0
systemd|uses|unit_files|1.0
systemd|provides|journalctl|1.0
systemctl|is_a|systemd_control_tool|1.0
journalctl|is_a|log_viewer|1.0
journalctl|reads|systemd_journal|1.0
proc_filesystem|located_at|/proc|1.0
proc_filesystem|provides|process_information|1.0
proc_filesystem|provides|system_information|1.0
proc_cpuinfo|shows|cpu_details|1.0
proc_meminfo|shows|memory_usage|1.0
proc_loadavg|shows|system_load|1.0
cgroups|is_a|linux_kernel_feature|1.0
cgroups|controls|resource_allocation|1.0
cgroups|limits|cpu_usage|1.0
cgroups|limits|memory_usage|1.0
namespaces|is_a|linux_kernel_feature|1.0
namespaces|provides|process_isolation|1.0
namespaces|types_include|pid_namespace|1.0
namespaces|types_include|network_namespace|1.0
namespaces|types_include|mount_namespace|1.0
iptables|is_a|firewall_tool|1.0
iptables|manages|packet_filtering|1.0
nftables|is_a|firewall_framework|1.0
nftables|replaces|iptables|0.9
ufw|is_a|firewall_frontend|1.0
ufw|simplifies|iptables_management|1.0
ip_address|is_a|network_identifier|1.0
ipv4|uses|32_bit_addresses|1.0
ipv6|uses|128_bit_addresses|1.0
subnet|is_a|network_segment|1.0
cidr|is_a|ip_notation|1.0
cidr|example|192.168.1.0/24|1.0
dhcp|is_a|network_protocol|1.0
dhcp|assigns|ip_addresses_automatically|1.0
dns|is_a|name_resolution_system|1.0
dns|translates|domain_to_ip|1.0
dns|uses|port_53|1.0
tcp|is_a|transport_protocol|1.0
tcp|provides|reliable_delivery|1.0
tcp|uses|three_way_handshake|1.0
udp|is_a|transport_protocol|1.0
udp|provides|fast_delivery|1.0
udp|no_guarantee|delivery_order|0.9
http|is_a|application_protocol|1.0
http|uses|port_80|1.0
https|is_a|encrypted_http|1.0
https|uses|port_443|1.0
https|uses|tls_encryption|1.0
nginx|is_a|web_server|1.0
nginx|is_a|reverse_proxy|1.0
nginx|handles|load_balancing|1.0
nginx|supports|ssl_termination|1.0
traefik|is_a|reverse_proxy|1.0
traefik|provides|automatic_ssl|1.0
traefik|integrates_with|docker|1.0
caddy|is_a|web_server|1.0
caddy|provides|automatic_https|1.0
lets_encrypt|provides|free_ssl_certificates|1.0
lets_encrypt|uses|acme_protocol|1.0
wireguard|is_a|vpn_protocol|1.0
wireguard|known_for|simplicity|1.0
wireguard|known_for|performance|1.0
wireguard|uses|udp|1.0
tailscale|is_a|vpn_service|1.0
tailscale|based_on|wireguard|1.0
tailscale|provides|mesh_networking|1.0
plex|is_a|media_server|1.0
plex|streams|movies|1.0
plex|streams|tv_shows|1.0
plex|streams|music|1.0
plex|supports|transcoding|1.0
plex|uses|port_32400|1.0
jellyfin|is_a|media_server|1.0
jellyfin|is|open_source|1.0
jellyfin|alternative_to|plex|1.0
home_assistant|is_a|home_automation_platform|1.0
home_assistant|is|open_source|1.0
home_assistant|supports|zigbee|1.0
home_assistant|supports|z_wave|1.0
home_assistant|supports|mqtt|1.0
home_assistant|uses|yaml_configuration|1.0
home_assistant|has|web_interface|1.0
pihole|is_a|dns_sinkhole|1.0
pihole|blocks|advertisements|1.0
pihole|blocks|trackers|1.0
pihole|provides|network_wide_adblock|1.0
pihole|uses|dnsmasq|1.0
adguard_home|is_a|dns_sinkhole|1.0
adguard_home|alternative_to|pihole|1.0
grafana|is_a|monitoring_dashboard|1.0
grafana|visualizes|metrics|1.0
grafana|supports|prometheus_datasource|1.0
grafana|supports|influxdb_datasource|1.0
prometheus|is_a|monitoring_system|1.0
prometheus|collects|time_series_data|1.0
prometheus|uses|pull_model|1.0
uptime_kuma|is_a|monitoring_tool|1.0
uptime_kuma|tracks|service_availability|1.0
uptime_kuma|sends|alerts|1.0
nextcloud|is_a|cloud_storage_platform|1.0
nextcloud|is|open_source|1.0
nextcloud|provides|file_sync|1.0
nextcloud|provides|calendar|1.0
nextcloud|provides|contacts|1.0
proxmox|is_a|hypervisor|1.0
proxmox|manages|virtual_machines|1.0
proxmox|manages|containers|1.0
proxmox|uses|kvm|1.0
proxmox|uses|lxc|1.0
raspberry_pi|is_a|single_board_computer|1.0
raspberry_pi|runs|linux|1.0
raspberry_pi|popular_for|homelab|1.0
raspberry_pi|has|arm_cpu|1.0
raspberry_pi|has|gpio_pins|1.0
raid|is_a|storage_redundancy|1.0
raid_0|provides|striping|1.0
raid_1|provides|mirroring|1.0
raid_5|provides|striping_with_parity|1.0
zfs|is_a|filesystem|1.0
zfs|provides|data_integrity|1.0
zfs|supports|snapshots|1.0
zfs|supports|compression|1.0
btrfs|is_a|filesystem|1.0
btrfs|supports|snapshots|1.0
btrfs|supports|compression|1.0
nfs|is_a|network_filesystem|1.0
nfs|enables|file_sharing|1.0
smb|is_a|network_protocol|1.0
smb|used_by|windows_file_sharing|1.0
ansible|is_a|automation_tool|1.0
ansible|uses|yaml_playbooks|1.0
ansible|agentless|uses_ssh|1.0
ansible|manages|configuration|1.0
terraform|is_a|infrastructure_tool|1.0
terraform|manages|cloud_resources|1.0
kubernetes|is_a|container_orchestration|1.0
kubernetes|manages|container_clusters|1.0
kubernetes|abbreviated|k8s|1.0
k3s|is_a|lightweight_kubernetes|1.0
k3s|popular_for|homelab|1.0
cron|is_a|job_scheduler|1.0
cron|schedules|periodic_tasks|1.0
crontab|defines|cron_schedules|1.0
htop|is_a|process_monitor|1.0
htop|shows|cpu_usage|1.0
htop|shows|memory_usage|1.0
tmux|is_a|terminal_multiplexer|1.0
tmux|enables|persistent_sessions|1.0
screen|is_a|terminal_multiplexer|1.0
fail2ban|is_a|intrusion_prevention|1.0
fail2ban|blocks|brute_force_attacks|1.0
fail2ban|monitors|log_files|1.0
unattended_upgrades|automates|security_updates|1.0
apt|is_a|package_manager|1.0
apt|used_by|debian_ubuntu|1.0
yum|is_a|package_manager|1.0
yum|used_by|centos_rhel|1.0
snap|is_a|package_manager|1.0
flatpak|is_a|package_manager|1.0
lvm|is_a|logical_volume_manager|1.0
lvm|enables|flexible_partitioning|1.0
swap|is_a|virtual_memory|1.0
swap|uses|disk_space|1.0
grub|is_a|bootloader|1.0
grub|loads|linux_kernel|1.0
