# MK Knowledge File - Artificial Intelligence and Machine Learning
# Format: source|relation|target|weight
# Covers: neural networks, transformers, training, LLMs, RAG, fine-tuning,
# computer vision, NLP, embeddings, reinforcement learning

# === NEURAL NETWORK TYPES ===
neural_network|is_a|computational_model|1.0
neural_network|inspired_by|biological_neurons|0.8
feedforward_network|is_a|neural_network|1.0
feedforward_network|data_flows|input_to_output|1.0
cnn|stands_for|convolutional_neural_network|1.0
cnn|excels_at|image_processing|1.0
cnn|uses|convolutional_layers|1.0
cnn|uses|pooling_layers|1.0
cnn|has|translation_invariance|1.0
rnn|stands_for|recurrent_neural_network|1.0
rnn|processes|sequential_data|1.0
rnn|problem|vanishing_gradients|0.9
lstm|stands_for|long_short_term_memory|1.0
lstm|solves|vanishing_gradient_problem|1.0
lstm|has|forget_gate_input_gate_output_gate|1.0
gru|stands_for|gated_recurrent_unit|1.0
gru|simpler_than|lstm|0.9
gru|has|reset_gate_update_gate|1.0
transformer|is_a|neural_architecture|1.0
transformer|uses|self_attention_mechanism|1.0
transformer|advantage|parallelizable_training|1.0
transformer|introduced_in|attention_is_all_you_need_2017|1.0
transformer|has|encoder_and_decoder|1.0
gan|stands_for|generative_adversarial_network|1.0
gan|has|generator_and_discriminator|1.0
gan|used_for|image_generation|1.0
vae|stands_for|variational_autoencoder|1.0
vae|learns|latent_space_representation|1.0
diffusion_model|generates|images_from_noise|1.0
diffusion_model|used_by|stable_diffusion_dalle|1.0
autoencoder|learns|compressed_representation|1.0
graph_neural_network|processes|graph_structured_data|1.0
capsule_network|captures|spatial_hierarchies|1.0
resnet|is_a|deep_cnn_with_skip_connections|1.0
resnet|solved|degradation_problem|1.0
unet|is_a|encoder_decoder_architecture|1.0
unet|used_for|image_segmentation|1.0
mamba|is_a|state_space_model|1.0
mamba|alternative_to|transformer|1.0
mamba|has|linear_complexity|1.0

# === TRAINING TECHNIQUES ===
backpropagation|is_a|training_algorithm|1.0
backpropagation|computes|gradients_via_chain_rule|1.0
sgd|stands_for|stochastic_gradient_descent|1.0
sgd|updates|weights_per_mini_batch|1.0
adam_optimizer|combines|momentum_and_rmsprop|1.0
adam_optimizer|is|most_popular_optimizer|0.9
adamw|adds|weight_decay_to_adam|1.0
learning_rate|controls|step_size|1.0
learning_rate|too_high|overshooting_minima|0.9
learning_rate|too_low|slow_convergence|0.9
learning_rate_schedule|decreases|lr_over_time|1.0
cosine_annealing|is_a|lr_schedule|1.0
warmup|gradually_increases|lr_at_start|1.0
batch_size|affects|training_stability|1.0
batch_size|larger|smoother_gradients|0.8
epoch|is_one|pass_through_entire_dataset|1.0
overfitting|memorizes|training_data|1.0
overfitting|poor|generalization|1.0
underfitting|insufficient|model_capacity|1.0
regularization|prevents|overfitting|1.0
dropout|randomly_zeros|neuron_outputs|1.0
l2_regularization|penalizes|large_weights|1.0
batch_normalization|normalizes|layer_inputs|1.0
layer_normalization|normalizes|across_features|1.0
gradient_clipping|prevents|exploding_gradients|1.0
mixed_precision|uses|fp16_and_fp32|1.0
mixed_precision|speeds_up|training|1.0
data_augmentation|increases|training_data_variety|1.0
early_stopping|stops|when_validation_worsens|1.0
cross_validation|evaluates|model_robustness|1.0
loss_function|measures|prediction_error|1.0
cross_entropy|used_for|classification|1.0
mse|used_for|regression|1.0
gradient_accumulation|simulates|larger_batch_size|1.0
distributed_training|splits|across_multiple_gpus|1.0
data_parallel|replicates|model_across_gpus|1.0
model_parallel|splits|model_across_gpus|1.0
pipeline_parallel|splits|layers_across_gpus|1.0
deepspeed|is_a|training_framework|1.0
deepspeed|enables|zero_redundancy_optimizer|1.0

# === LLM CONCEPTS ===
llm|stands_for|large_language_model|1.0
llm|trained_on|massive_text_corpora|1.0
llm|uses|transformer_architecture|1.0
tokenization|converts|text_to_token_ids|1.0
bpe|stands_for|byte_pair_encoding|1.0
bpe|is_a|tokenization_method|1.0
sentencepiece|is_a|tokenizer|1.0
tiktoken|is_a|tokenizer_by_openai|1.0
attention_mechanism|computes|relevance_scores|1.0
self_attention|relates|positions_within_sequence|1.0
multi_head_attention|runs|multiple_attention_in_parallel|1.0
kv_cache|stores|computed_key_value_pairs|1.0
kv_cache|speeds_up|autoregressive_generation|1.0
context_window|limits|input_sequence_length|1.0
context_window|gpt4|128k_tokens|1.0
context_window|claude|200k_tokens|1.0
context_window|gemini|1m_tokens|1.0
positional_encoding|encodes|token_position|1.0
rope|stands_for|rotary_position_embedding|1.0
alibi|is_a|position_embedding_method|1.0
causal_masking|prevents|attending_to_future_tokens|1.0
temperature|controls|randomness_in_generation|1.0
top_p|filters|cumulative_probability|1.0
top_k|selects|k_most_probable_tokens|1.0
beam_search|explores|multiple_generation_paths|1.0
greedy_decoding|selects|most_probable_token|1.0
perplexity|measures|model_uncertainty|1.0
scaling_laws|predict|performance_from_compute|1.0
chinchilla_scaling|recommends|20_tokens_per_parameter|0.9
emergent_abilities|appear_at|large_scale|0.8
gpt4|is_a|large_language_model|1.0
gpt4|created_by|openai|1.0
claude|is_a|large_language_model|1.0
claude|created_by|anthropic|1.0
llama|is_a|open_source_llm|1.0
llama|created_by|meta|1.0
mistral|is_a|open_source_llm|1.0
mistral|created_by|mistral_ai|1.0
gemini|is_a|multimodal_llm|1.0
gemini|created_by|google|1.0
phi|is_a|small_language_model|1.0
phi|created_by|microsoft|1.0

# === RAG (Retrieval Augmented Generation) ===
rag|stands_for|retrieval_augmented_generation|1.0
rag|combines|retrieval_and_generation|1.0
rag|reduces|hallucination|0.9
rag|provides|up_to_date_information|1.0
vector_database|stores|embeddings_for_retrieval|1.0
vector_database|examples|pinecone_weaviate_milvus_chroma|1.0
chunking|splits|documents_into_segments|1.0
chunk_size|affects|retrieval_quality|1.0
overlap|maintains|context_between_chunks|1.0
semantic_search|finds|similar_meaning_not_keywords|1.0
hybrid_search|combines|semantic_and_keyword|1.0
reranking|improves|retrieval_relevance|1.0
cross_encoder_reranker|scores|query_document_pairs|1.0
query_expansion|enriches|search_queries|1.0
hypothetical_document_embedding|generates|hypothetical_answer_for_retrieval|1.0
parent_document_retrieval|retrieves|larger_context|1.0
multi_query_retrieval|generates|multiple_query_variants|1.0
contextual_compression|reduces|irrelevant_content|1.0
metadata_filtering|narrows|search_scope|1.0
recursive_retrieval|iteratively|refines_results|1.0

# === FINE-TUNING ===
fine_tuning|adapts|pretrained_model_to_task|1.0
full_fine_tuning|updates|all_model_parameters|1.0
full_fine_tuning|requires|significant_gpu_memory|1.0
lora|stands_for|low_rank_adaptation|1.0
lora|adds|small_trainable_matrices|1.0
lora|reduces|memory_requirements|1.0
qlora|combines|quantization_and_lora|1.0
qlora|enables|fine_tuning_on_consumer_gpu|1.0
rlhf|stands_for|reinforcement_learning_from_human_feedback|1.0
rlhf|aligns|model_with_human_preferences|1.0
rlhf|uses|reward_model|1.0
rlhf|used_by|chatgpt_claude|1.0
dpo|stands_for|direct_preference_optimization|1.0
dpo|simpler_than|rlhf|0.9
dpo|eliminates|reward_model|1.0
instruction_tuning|trains|to_follow_instructions|1.0
sft|stands_for|supervised_fine_tuning|1.0
prefix_tuning|optimizes|continuous_prompts|1.0
adapter_layers|adds|small_modules_to_model|1.0
distillation|transfers|knowledge_to_smaller_model|1.0
quantization|reduces|model_precision|1.0
quantization_types|include|int8_int4_gptq_awq|1.0
gptq|is_a|post_training_quantization|1.0
awq|stands_for|activation_aware_weight_quantization|1.0
gguf|is_a|quantization_format|1.0
gguf|used_by|llama_cpp|1.0

# === COMPUTER VISION ===
object_detection|locates|objects_in_images|1.0
object_detection|outputs|bounding_boxes_and_classes|1.0
yolo|stands_for|you_only_look_once|1.0
yolo|is_a|real_time_detector|1.0
yolo_v8|latest|high_performance_version|0.9
faster_rcnn|is_a|two_stage_detector|1.0
ssd|is_a|single_shot_detector|1.0
image_segmentation|assigns|class_to_each_pixel|1.0
semantic_segmentation|labels|all_pixels|1.0
instance_segmentation|distinguishes|individual_objects|1.0
panoptic_segmentation|combines|semantic_and_instance|1.0
sam|stands_for|segment_anything_model|1.0
sam|created_by|meta|1.0
sam|zero_shot|segmentation|1.0
image_classification|assigns|class_to_whole_image|1.0
vit|stands_for|vision_transformer|1.0
vit|applies|transformer_to_image_patches|1.0
clip|connects|images_and_text|1.0
clip|created_by|openai|1.0
stable_diffusion|is_a|text_to_image_model|1.0
stable_diffusion|uses|latent_diffusion|1.0
dalle|is_a|text_to_image_model|1.0
midjourney|is_a|text_to_image_model|1.0
ocr|stands_for|optical_character_recognition|1.0
face_detection|locates|faces_in_images|1.0
pose_estimation|detects|body_keypoints|1.0
depth_estimation|predicts|distance_from_camera|1.0
optical_flow|tracks|motion_between_frames|1.0
image_super_resolution|upscales|low_resolution_images|1.0
neural_style_transfer|applies|artistic_style|1.0

# === NLP TASKS ===
ner|stands_for|named_entity_recognition|1.0
ner|identifies|entities_in_text|1.0
ner|entity_types|person_organization_location_date|1.0
sentiment_analysis|classifies|text_emotion|1.0
sentiment_analysis|categories|positive_negative_neutral|1.0
machine_translation|converts|text_between_languages|1.0
text_summarization|condenses|long_text|1.0
extractive_summarization|selects|key_sentences|1.0
abstractive_summarization|generates|new_summary_text|1.0
question_answering|extracts|answer_from_context|1.0
text_classification|assigns|category_to_text|1.0
relation_extraction|identifies|relationships_between_entities|1.0
coreference_resolution|links|pronouns_to_entities|1.0
dependency_parsing|analyzes|grammatical_structure|1.0
topic_modeling|discovers|themes_in_documents|1.0
text_generation|produces|new_text|1.0
paraphrase_detection|identifies|same_meaning_different_words|1.0
natural_language_inference|determines|entailment_contradiction|1.0
information_retrieval|finds|relevant_documents|1.0
speech_to_text|converts|audio_to_text|1.0
text_to_speech|converts|text_to_audio|1.0
whisper|is_a|speech_recognition_model|1.0
whisper|created_by|openai|1.0

# === EMBEDDINGS ===
word2vec|is_a|word_embedding_model|1.0
word2vec|created_by|google|1.0
word2vec|methods|cbow_skipgram|1.0
glove|is_a|word_embedding_model|1.0
glove|trained_on|co_occurrence_matrix|1.0
fasttext|is_a|word_embedding_model|1.0
fasttext|handles|subword_information|1.0
sentence_transformers|create|sentence_embeddings|1.0
sentence_transformers|based_on|bert_architecture|1.0
embedding_dimension|typically|768_1024_1536|1.0
cosine_similarity|measures|embedding_similarity|1.0
euclidean_distance|measures|embedding_distance|1.0
dot_product|measures|embedding_relevance|1.0
openai_embeddings|model|text_embedding_3|1.0
hnsw|is_a|approximate_nn_algorithm|1.0
hnsw|used_in|vector_databases|1.0
annoy|is_a|approximate_nn_library|1.0
faiss|is_a|vector_similarity_library|1.0
faiss|created_by|meta|1.0
dimensionality_reduction|techniques|pca_tsne_umap|1.0
pca|stands_for|principal_component_analysis|1.0
tsne|stands_for|t_distributed_stochastic_neighbor_embedding|1.0
umap|stands_for|uniform_manifold_approximation|1.0

# === REINFORCEMENT LEARNING ===
reinforcement_learning|learns_from|rewards_and_penalties|1.0
reinforcement_learning|components|agent_environment_reward|1.0
q_learning|is_a|value_based_method|1.0
deep_q_network|combines|q_learning_and_neural_nets|1.0
policy_gradient|optimizes|action_probabilities|1.0
ppo|stands_for|proximal_policy_optimization|1.0
ppo|is_a|popular_rl_algorithm|1.0
actor_critic|combines|value_and_policy_methods|1.0
exploration|balances_with|exploitation|1.0
epsilon_greedy|is_a|exploration_strategy|1.0
markov_decision_process|formalizes|rl_problems|1.0
reward_shaping|guides|learning_process|1.0
multi_agent_rl|involves|multiple_learning_agents|1.0
alphago|used|monte_carlo_tree_search_and_rl|1.0
openai_gym|is_a|rl_environment_toolkit|1.0
stable_baselines|is_a|rl_implementations_library|1.0

# === AI FRAMEWORKS AND TOOLS ===
pytorch|is_a|deep_learning_framework|1.0
pytorch|created_by|meta|1.0
pytorch|advantage|dynamic_computation_graph|1.0
tensorflow|is_a|deep_learning_framework|1.0
tensorflow|created_by|google|1.0
jax|is_a|numerical_computing_library|1.0
jax|created_by|google|1.0
jax|advantage|composable_transformations|1.0
hugging_face|is_a|ml_platform|1.0
hugging_face|hosts|models_and_datasets|1.0
transformers_library|provides|pretrained_models|1.0
langchain|is_a|llm_application_framework|1.0
llamaindex|is_a|data_framework_for_llm|1.0
mlflow|tracks|ml_experiments|1.0
wandb|tracks|ml_experiments|1.0
onnx|is_a|model_interchange_format|1.0
tensorrt|optimizes|inference_for_nvidia_gpus|1.0
triton_inference|serves|models_in_production|1.0
vllm|is_a|llm_serving_engine|1.0
vllm|uses|paged_attention|1.0
ollama|runs|llms_locally|1.0
llama_cpp|runs|llms_on_cpu|1.0

# === AI SAFETY AND ALIGNMENT ===
ai_alignment|ensures|ai_follows_human_values|1.0
constitutional_ai|trains|using_principles|1.0
constitutional_ai|developed_by|anthropic|1.0
reward_hacking|exploits|reward_function_loopholes|0.9
mesa_optimization|is|learned_optimizer_within_model|0.8
deceptive_alignment|hides|true_objectives|0.7
interpretability|understands|model_decision_making|1.0
mechanistic_interpretability|studies|internal_computations|1.0
red_teaming|tests|model_safety|1.0
jailbreaking|bypasses|safety_guardrails|0.8
prompt_injection|manipulates|model_via_input|1.0
hallucination|generates|false_information|1.0
hallucination|reduced_by|rag_and_grounding|0.8
guardrails|enforce|output_constraints|1.0
content_filtering|blocks|harmful_outputs|1.0
watermarking|embeds|detectable_patterns_in_output|1.0
ai_detection|identifies|ai_generated_content|0.8
bias|in_models|reflects_training_data|0.9
fairness_metrics|measure|model_equity|1.0
differential_privacy|protects|training_data|1.0

# === MULTIMODAL AI ===
multimodal|processes|multiple_input_types|1.0
vision_language_model|processes|images_and_text|1.0
gpt4_vision|analyzes|images_with_text|1.0
llava|is_a|open_source_vision_language_model|1.0
audio_language_model|processes|audio_and_text|1.0
video_understanding|analyzes|video_content|1.0
image_captioning|generates|text_from_image|1.0
visual_question_answering|answers|questions_about_images|1.0
text_to_video|generates|video_from_text|1.0
sora|is_a|text_to_video_model|1.0
sora|created_by|openai|1.0
controlnet|conditions|image_generation|1.0
inpainting|fills|missing_image_regions|1.0
outpainting|extends|image_boundaries|1.0
img2img|transforms|image_to_image|1.0

# === MODEL DEPLOYMENT ===
model_serving|deploys|model_for_inference|1.0
batch_inference|processes|many_inputs_at_once|1.0
online_inference|processes|single_requests|1.0
latency|critical_for|real_time_applications|1.0
throughput|critical_for|batch_processing|1.0
model_optimization|reduces|inference_cost|1.0
pruning|removes|unimportant_weights|1.0
knowledge_distillation|trains|small_from_large|1.0
speculative_decoding|uses|draft_model_for_speed|1.0
continuous_batching|dynamically|groups_requests|1.0
flash_attention|optimizes|attention_computation|1.0
flash_attention|reduces|memory_usage|1.0
kv_cache_quantization|reduces|memory_for_generation|1.0
model_sharding|splits|model_across_devices|1.0
edge_deployment|runs|models_on_device|1.0
tflite|is_a|mobile_ml_framework|1.0
coreml|is_a|apple_ml_framework|1.0
onnx_runtime|accelerates|model_inference|1.0
triton_inference_server|serves|multiple_models|1.0
bentoml|packages|models_as_services|1.0

# === DATA ENGINEERING FOR ML ===
feature_engineering|creates|model_inputs|1.0
feature_store|manages|ml_features|1.0
data_pipeline|moves|data_for_training|1.0
data_labeling|annotates|training_examples|1.0
active_learning|selects|most_informative_samples|1.0
synthetic_data|generated|artificially|1.0
data_augmentation|increases|training_variety|1.0
class_imbalance|problem|uneven_class_distribution|1.0
oversampling|duplicates|minority_class|1.0
undersampling|reduces|majority_class|1.0
train_test_split|divides|data_for_evaluation|1.0
stratified_sampling|preserves|class_proportions|1.0
k_fold_cross_validation|uses|k_subsets_for_evaluation|1.0
data_drift|changes|in_data_distribution|1.0
concept_drift|changes|in_target_relationship|1.0
model_monitoring|detects|performance_degradation|1.0
a_b_testing|compares|model_variants|1.0
canary_deployment|gradually|rolls_out_new_model|1.0

# === CLASSICAL ML ===
linear_regression|predicts|continuous_values|1.0
logistic_regression|predicts|binary_classification|1.0
decision_tree|splits|data_on_features|1.0
random_forest|is_a|ensemble_of_trees|1.0
gradient_boosting|is_a|sequential_ensemble|1.0
xgboost|is_a|gradient_boosting_library|1.0
lightgbm|is_a|gradient_boosting_library|1.0
svm|stands_for|support_vector_machine|1.0
svm|finds|maximum_margin_hyperplane|1.0
knn|stands_for|k_nearest_neighbors|1.0
kmeans|is_a|clustering_algorithm|1.0
dbscan|is_a|density_based_clustering|1.0
pca|reduces|dimensionality|1.0
naive_bayes|uses|bayes_theorem|1.0
ensemble_learning|combines|multiple_models|1.0
bagging|trains|models_on_data_subsets|1.0
boosting|trains|models_sequentially|1.0
stacking|trains|meta_model_on_predictions|1.0
hyperparameter_tuning|optimizes|model_configuration|1.0
grid_search|tries|all_combinations|1.0
random_search|samples|random_configurations|1.0
bayesian_optimization|models|objective_function|1.0
confusion_matrix|shows|classification_results|1.0
precision|measures|positive_prediction_accuracy|1.0
recall|measures|positive_detection_rate|1.0
f1_score|harmonic_mean|precision_and_recall|1.0
roc_curve|plots|true_positive_vs_false_positive|1.0
auc|measures|area_under_roc_curve|1.0

# === AGENTS AND REASONING ===
ai_agent|takes|autonomous_actions|1.0
ai_agent|has|tools_and_memory|1.0
chain_of_thought|improves|reasoning_quality|1.0
tree_of_thought|explores|multiple_reasoning_paths|1.0
react_framework|reasons|then_acts|1.0
function_calling|enables|tool_use_by_llms|1.0
tool_use|extends|llm_capabilities|1.0
memory_augmented|stores|conversation_history|1.0
planning|decomposes|complex_tasks|1.0
reflection|evaluates|own_output_quality|1.0
multi_agent_system|coordinates|multiple_agents|1.0
autogpt|is_a|autonomous_agent|1.0
crewai|is_a|multi_agent_framework|1.0
code_generation|writes|code_from_description|1.0
copilot|assists|code_writing|1.0
cursor|is_a|ai_code_editor|1.0
devin|is_a|ai_software_engineer|1.0

# === NATURAL LANGUAGE PROCESSING MODELS ===
bert|stands_for|bidirectional_encoder_representations|1.0
bert|created_by|google|1.0
bert|is_a|encoder_only_model|1.0
gpt|stands_for|generative_pre_trained_transformer|1.0
gpt|is_a|decoder_only_model|1.0
t5|stands_for|text_to_text_transfer_transformer|1.0
t5|is_a|encoder_decoder_model|1.0
bart|is_a|encoder_decoder_model|1.0
roberta|is_a|optimized_bert_variant|1.0
electra|is_a|efficient_pretraining_method|1.0
deberta|improves|bert_with_disentangled_attention|1.0
xlnet|uses|permutation_language_modeling|1.0
albert|is_a|lite_bert_variant|1.0
distilbert|is_a|distilled_bert|1.0
pegasus|is_a|summarization_model|1.0
flan_t5|is_a|instruction_tuned_t5|1.0
bloom|is_a|multilingual_llm|1.0
falcon|is_a|open_source_llm|1.0
mixtral|is_a|mixture_of_experts_model|1.0
mixture_of_experts|activates|subset_of_parameters|1.0
mixture_of_experts|reduces|inference_compute|1.0
sparse_model|uses|conditional_computation|1.0
dense_model|uses|all_parameters_every_forward|1.0

# === AI HARDWARE ===
gpu|accelerates|parallel_computation|1.0
nvidia_a100|is_a|datacenter_gpu|1.0
nvidia_h100|is_a|latest_training_gpu|1.0
nvidia_h100|has|hopper_architecture|1.0
nvidia_b200|is_a|next_gen_training_gpu|1.0
tpu|stands_for|tensor_processing_unit|1.0
tpu|created_by|google|1.0
apple_neural_engine|accelerates|ml_on_apple_devices|1.0
cuda|is_a|gpu_programming_platform|1.0
cuda|made_by|nvidia|1.0
rocm|is_a|gpu_programming_platform|1.0
rocm|made_by|amd|1.0
tensor_cores|accelerate|matrix_operations|1.0
hbm|stands_for|high_bandwidth_memory|1.0
hbm|used_in|datacenter_gpus|1.0
nvlink|connects|gpus_with_high_bandwidth|1.0
infiniband|connects|servers_in_clusters|1.0
gpu_cluster|trains|large_models|1.0
flops|measures|compute_performance|1.0
memory_bandwidth|limits|inference_speed|1.0
compute_bound|limited_by|flops|1.0
memory_bound|limited_by|bandwidth|1.0

# === EVALUATION AND BENCHMARKS ===
perplexity|measures|language_model_quality|1.0
bleu_score|evaluates|translation_quality|1.0
rouge_score|evaluates|summarization_quality|1.0
mmlu|is_a|knowledge_benchmark|1.0
hellaswag|is_a|reasoning_benchmark|1.0
humaneval|is_a|code_generation_benchmark|1.0
gsm8k|is_a|math_reasoning_benchmark|1.0
chatbot_arena|ranks|llms_by_human_preference|1.0
elo_rating|ranks|models_competitively|1.0
lmsys|operates|chatbot_arena|1.0
truthfulqa|tests|factual_accuracy|1.0
winogrande|tests|commonsense_reasoning|1.0
arc_challenge|tests|science_reasoning|1.0
mt_bench|evaluates|multi_turn_conversation|1.0

# === ADDITIONAL AI KNOWLEDGE ===
attention_is_all_you_need|paper_from|2017|1.0
transformer_variants|include|encoder_decoder_causal|1.0
causal_language_model|predicts|next_token|1.0
masked_language_model|predicts|masked_tokens|1.0
contrastive_learning|learns|by_comparing_pairs|1.0
self_supervised_learning|learns|from_unlabeled_data|1.0
few_shot_learning|generalizes|from_few_examples|1.0
zero_shot_learning|generalizes|without_examples|1.0
in_context_learning|learns|from_prompt_examples|1.0
prompt_engineering|crafts|effective_prompts|1.0
chain_of_thought_prompting|improves|reasoning_ability|1.0
system_prompt|sets|model_behavior_context|1.0
temperature_sampling|controls|output_randomness|1.0
nucleus_sampling|filters|low_probability_tokens|1.0
stop_sequence|terminates|generation|1.0
tokenizer_vocabulary|typically|32k_to_128k_tokens|1.0
byte_pair_encoding|merges|frequent_byte_pairs|1.0
attention_head|computes|one_attention_pattern|1.0
residual_connection|adds|input_to_output|1.0
layer_norm|normalizes|activations|1.0
feedforward_network|in_transformer|two_linear_layers|1.0
positional_encoding|injects|position_information|1.0
causal_mask|prevents|attending_to_future|1.0
cross_attention|attends|to_encoder_output|1.0
encoder_only|examples|bert_roberta|1.0
decoder_only|examples|gpt_llama|1.0
encoder_decoder|examples|t5_bart|1.0
model_parallelism|splits|model_across_devices|1.0
tensor_parallelism|splits|tensors_across_gpus|1.0
sequence_parallelism|splits|sequence_across_gpus|1.0
gradient_checkpointing|trades|compute_for_memory|1.0
activation_recomputation|saves|memory_during_training|1.0
flash_attention_2|further|optimizes_attention|1.0
grouped_query_attention|reduces|kv_cache_size|1.0
multi_query_attention|shares|kv_heads|1.0
rotary_position_embedding|encodes|relative_position|1.0
alibi_position|adds|linear_bias|1.0
context_extension|methods|yarn_longrope_ntk|1.0
retrieval_augmented_llm|accesses|external_knowledge|1.0
tool_augmented_llm|uses|external_tools|1.0
multimodal_llm|processes|text_image_audio|1.0
vision_encoder|extracts|image_features|1.0
projection_layer|maps|vision_to_language_space|1.0
instruction_following|trained_via|instruction_tuning|1.0
chat_template|formats|conversation_for_model|1.0
system_message|defines|model_personality|1.0

# === ADDITIONAL UNIQUE AI FACTS ===
chinchilla_optimal|tokens_per_param|20|1.0
llama2_7b|parameters|7_billion|1.0
llama2_13b|parameters|13_billion|1.0
llama2_70b|parameters|70_billion|1.0
gpt4_parameters|estimated|over_1_trillion|0.7
mixtral_8x7b|active_params|12_9_billion|1.0
phi_2|parameters|2_7_billion|1.0
mistral_7b|parameters|7_billion|1.0
gemma_2b|parameters|2_billion|1.0
gemma_7b|parameters|7_billion|1.0
qwen_72b|parameters|72_billion|1.0
deepseek_coder|parameters|33_billion|1.0
codellama|parameters|7_13_34_billion|1.0
starcoder2|parameters|3_7_15_billion|1.0
whisper_large_v3|parameters|1_5_billion|1.0
stable_diffusion_xl|parameters|6_6_billion|1.0
sam_vit_h|parameters|636_million|1.0
clip_vit_l_14|parameters|427_million|1.0
dino_v2|is_a|self_supervised_vision_model|1.0
segment_anything_2|handles|video_segmentation|1.0
florence_2|is_a|vision_foundation_model|1.0
gpt4o|is|multimodal_gpt4_variant|1.0
claude_3_5_sonnet|is|anthropic_latest_model|1.0
gemini_1_5_pro|has|1_million_token_context|1.0
command_r_plus|is_a|cohere_rag_model|1.0
jamba|is_a|hybrid_mamba_transformer|1.0
rwkv|is_a|rnn_with_transformer_performance|1.0
retnet|is_a|retention_network|1.0
hyena|is_a|long_convolution_model|1.0
state_space_model|has|linear_time_complexity|1.0
selective_state_space|filters|irrelevant_information|1.0
mamba_2|improved|selective_scan|1.0
linear_attention|approximates|softmax_attention|1.0
ring_attention|distributes|context_across_devices|1.0
paged_attention|manages|kv_cache_like_virtual_memory|1.0
continuous_batching|maximizes|gpu_utilization|1.0
prefix_caching|reuses|common_prompt_computation|1.0
speculative_decoding_speed|typically|2x_to_3x_faster|0.9
medusa|uses|multiple_decoding_heads|1.0
lookahead_decoding|verifies|ngram_predictions|1.0
eagle|is_a|speculative_decoding_method|1.0
