# Oceans, Mountains, Rivers, Landmarks, Inventions
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

pacific ocean|is_a|ocean|1.0
pacific ocean|description|largest ocean|1.0
pacific ocean|area_is|165.25 million sq km|0.95
pacific ocean|deepest_point|mariana trench|0.9
atlantic ocean|is_a|ocean|1.0
atlantic ocean|description|second largest ocean|1.0
atlantic ocean|area_is|106.46 million sq km|0.95
atlantic ocean|deepest_point|puerto rico trench|0.9
indian ocean|is_a|ocean|1.0
indian ocean|description|third largest ocean|1.0
indian ocean|area_is|70.56 million sq km|0.95
indian ocean|deepest_point|java trench|0.9
southern ocean|is_a|ocean|1.0
southern ocean|description|fourth largest ocean|1.0
southern ocean|area_is|21.96 million sq km|0.95
southern ocean|deepest_point|south sandwich trench|0.9
arctic ocean|is_a|ocean|1.0
arctic ocean|description|smallest ocean|1.0
arctic ocean|area_is|14.06 million sq km|0.95
arctic ocean|deepest_point|molloy deep|0.9
mount everest|is_a|mountain|1.0
mount everest|range_is|himalayas|1.0
mount everest|located_in|nepal|1.0
mount everest|height_is|8849 meters|1.0
mount everest|known_for|tallest mountain|0.9
k2|is_a|mountain|1.0
k2|range_is|karakoram|1.0
k2|located_in|pakistan|1.0
k2|height_is|8611 meters|1.0
k2|known_for|second tallest mountain|0.9
kangchenjunga|is_a|mountain|1.0
kangchenjunga|range_is|himalayas|1.0
kangchenjunga|located_in|nepal|1.0
kangchenjunga|height_is|8586 meters|1.0
kangchenjunga|known_for|third tallest mountain|0.9
mont blanc|is_a|mountain|1.0
mont blanc|range_is|alps|1.0
mont blanc|located_in|france|1.0
mont blanc|height_is|4809 meters|1.0
mont blanc|known_for|tallest in alps|0.9
mount kilimanjaro|is_a|mountain|1.0
mount kilimanjaro|range_is|eastern rift|1.0
mount kilimanjaro|located_in|tanzania|1.0
mount kilimanjaro|height_is|5895 meters|1.0
mount kilimanjaro|known_for|tallest in africa|0.9
mount mckinley|is_a|mountain|1.0
mount mckinley|range_is|alaska range|1.0
mount mckinley|located_in|united states|1.0
mount mckinley|height_is|6190 meters|1.0
mount mckinley|known_for|tallest in north america|0.9
mount fuji|is_a|mountain|1.0
mount fuji|range_is|pacific ring|1.0
mount fuji|located_in|japan|1.0
mount fuji|height_is|3776 meters|1.0
mount fuji|known_for|iconic japanese mountain|0.9
matterhorn|is_a|mountain|1.0
matterhorn|range_is|alps|1.0
matterhorn|located_in|switzerland|1.0
matterhorn|height_is|4478 meters|1.0
matterhorn|known_for|iconic alpine peak|0.9
amazon river|is_a|river|1.0
amazon river|located_in|south america|1.0
amazon river|length_is|6400 km|0.95
amazon river|flows_into|atlantic ocean|1.0
amazon river|known_for|largest by discharge|0.9
nile river|is_a|river|1.0
nile river|located_in|africa|1.0
nile river|length_is|6650 km|0.95
nile river|flows_into|mediterranean sea|1.0
nile river|known_for|longest river|0.9
yangtze river|is_a|river|1.0
yangtze river|located_in|asia|1.0
yangtze river|length_is|6300 km|0.95
yangtze river|flows_into|east china sea|1.0
yangtze river|known_for|longest in asia|0.9
mississippi river|is_a|river|1.0
mississippi river|located_in|north america|1.0
mississippi river|length_is|3730 km|0.95
mississippi river|flows_into|gulf of mexico|1.0
mississippi river|known_for|major us waterway|0.9
danube river|is_a|river|1.0
danube river|located_in|europe|1.0
danube river|length_is|2850 km|0.95
danube river|flows_into|black sea|1.0
danube river|known_for|flows through 10 countries|0.9
ganges river|is_a|river|1.0
ganges river|located_in|asia|1.0
ganges river|length_is|2525 km|0.95
ganges river|flows_into|bay of bengal|1.0
ganges river|known_for|sacred river in hinduism|0.9
thames river|is_a|river|1.0
thames river|located_in|europe|1.0
thames river|length_is|346 km|0.95
thames river|flows_into|north sea|1.0
thames river|known_for|flows through london|0.9
rhine river|is_a|river|1.0
rhine river|located_in|europe|1.0
rhine river|length_is|1230 km|0.95
rhine river|flows_into|north sea|1.0
rhine river|known_for|major european trade route|0.9
congo river|is_a|river|1.0
congo river|located_in|africa|1.0
congo river|length_is|4700 km|0.95
congo river|flows_into|atlantic ocean|1.0
congo river|known_for|deepest river|0.9
volga river|is_a|river|1.0
volga river|located_in|europe|1.0
volga river|length_is|3530 km|0.95
volga river|flows_into|caspian sea|1.0
volga river|known_for|longest in europe|0.9
great wall of china|is_a|landmark|1.0
great wall of china|is_a|wall|1.0
great wall of china|located_in|china|1.0
great wall of china|built_in|221 bc|0.95
great wall of china|known_for|longest wall ever built|0.9
eiffel tower|is_a|landmark|1.0
eiffel tower|is_a|tower|1.0
eiffel tower|located_in|france|1.0
eiffel tower|built_in|1889|0.95
eiffel tower|known_for|symbol of paris|0.9
statue of liberty|is_a|landmark|1.0
statue of liberty|is_a|monument|1.0
statue of liberty|located_in|united states|1.0
statue of liberty|built_in|1886|0.95
statue of liberty|known_for|gift from france|0.9
taj mahal|is_a|landmark|1.0
taj mahal|is_a|mausoleum|1.0
taj mahal|located_in|india|1.0
taj mahal|built_in|1632|0.95
taj mahal|known_for|symbol of love|0.9
colosseum|is_a|landmark|1.0
colosseum|is_a|amphitheater|1.0
colosseum|located_in|italy|1.0
colosseum|built_in|80 ad|0.95
colosseum|known_for|largest roman amphitheater|0.9
machu picchu|is_a|landmark|1.0
machu picchu|is_a|citadel|1.0
machu picchu|located_in|peru|1.0
machu picchu|built_in|1450|0.95
machu picchu|known_for|inca mountain fortress|0.9
pyramids of giza|is_a|landmark|1.0
pyramids of giza|is_a|pyramid|1.0
pyramids of giza|located_in|egypt|1.0
pyramids of giza|built_in|2560 bc|0.95
pyramids of giza|known_for|only surviving ancient wonder|0.9
big ben|is_a|landmark|1.0
big ben|is_a|clock tower|1.0
big ben|located_in|england|1.0
big ben|built_in|1859|0.95
big ben|known_for|iconic london clock|0.9
sydney opera house|is_a|landmark|1.0
sydney opera house|is_a|theater|1.0
sydney opera house|located_in|australia|1.0
sydney opera house|built_in|1973|0.95
sydney opera house|known_for|architectural masterpiece|0.9
golden gate bridge|is_a|landmark|1.0
golden gate bridge|is_a|bridge|1.0
golden gate bridge|located_in|united states|1.0
golden gate bridge|built_in|1937|0.95
golden gate bridge|known_for|iconic san francisco bridge|0.9
telephone|is_a|invention|1.0
telephone|invented_by|alexander graham bell|1.0
telephone|invented_in|1876|1.0
telephone|used_for|communication|0.9
light bulb|is_a|invention|1.0
light bulb|invented_by|thomas edison|1.0
light bulb|invented_in|1879|1.0
light bulb|used_for|illumination|0.9
airplane|is_a|invention|1.0
airplane|invented_by|wright brothers|1.0
airplane|invented_in|1903|1.0
airplane|used_for|transportation|0.9
television|is_a|invention|1.0
television|invented_by|philo farnsworth|1.0
television|invented_in|1927|1.0
television|used_for|entertainment|0.9
computer|is_a|invention|1.0
computer|invented_by|charles babbage|1.0
computer|invented_in|1837|1.0
computer|used_for|computation|0.9
internet|is_a|invention|1.0
internet|invented_by|vint cerf and bob kahn|1.0
internet|invented_in|1983|1.0
internet|used_for|global network|0.9
printing press|is_a|invention|1.0
printing press|invented_by|johannes gutenberg|1.0
printing press|invented_in|1440|1.0
printing press|used_for|mass communication|0.9
steam engine|is_a|invention|1.0
steam engine|invented_by|james watt|1.0
steam engine|invented_in|1769|1.0
steam engine|used_for|industrial power|0.9
automobile|is_a|invention|1.0
automobile|invented_by|karl benz|1.0
automobile|invented_in|1886|1.0
automobile|used_for|personal transportation|0.9
radio|is_a|invention|1.0
radio|invented_by|guglielmo marconi|1.0
radio|invented_in|1895|1.0
radio|used_for|wireless communication|0.9
vaccination|is_a|invention|1.0
vaccination|invented_by|edward jenner|1.0
vaccination|invented_in|1796|1.0
vaccination|used_for|disease prevention|0.9
penicillin|is_a|invention|1.0
penicillin|invented_by|alexander fleming|1.0
penicillin|invented_in|1928|1.0
penicillin|used_for|antibiotic medicine|0.9
dynamite|is_a|invention|1.0
dynamite|invented_by|alfred nobel|1.0
dynamite|invented_in|1867|1.0
dynamite|used_for|construction and mining|0.9
telescope|is_a|invention|1.0
telescope|invented_by|hans lippershey|1.0
telescope|invented_in|1608|1.0
telescope|used_for|astronomy|0.9
microscope|is_a|invention|1.0
microscope|invented_by|antonie van leeuwenhoek|1.0
microscope|invented_in|1674|1.0
microscope|used_for|biology|0.9
