# MK Knowledge File - Biology and Medicine
# Format: source|relation|target|weight
# Covers: human body, genetics, diseases, neuroscience

# === HUMAN BODY SYSTEMS ===
circulatory_system|pumps|blood_throughout_body|1.0
heart|has|four_chambers|1.0
heart|pumps|about_5_liters_per_minute|1.0
arteries|carry|oxygenated_blood_from_heart|1.0
veins|carry|deoxygenated_blood_to_heart|1.0
capillaries|exchange|gases_nutrients_waste|1.0
blood|contains|red_cells_white_cells_platelets_plasma|1.0
red_blood_cells|carry|oxygen_via_hemoglobin|1.0
white_blood_cells|fight|infection|1.0
platelets|enable|blood_clotting|1.0
respiratory_system|exchanges|oxygen_and_co2|1.0
lungs|contain|300_million_alveoli|1.0
diaphragm|muscle_for|breathing|1.0
trachea|connects|throat_to_lungs|1.0
digestive_system|breaks_down|food_into_nutrients|1.0
stomach|produces|hydrochloric_acid|1.0
small_intestine|absorbs|most_nutrients|1.0
large_intestine|absorbs|water_and_forms_feces|1.0
liver|processes|nutrients_and_detoxifies|1.0
pancreas|produces|insulin_and_digestive_enzymes|1.0
kidneys|filter|blood_and_produce_urine|1.0
nephron|is_a|functional_kidney_unit|1.0
skeleton|has|206_bones_in_adult|1.0
bone_marrow|produces|blood_cells|1.0
muscle_types|include|skeletal_cardiac_smooth|1.0
skeletal_muscle|voluntary|conscious_control|1.0
cardiac_muscle|involuntary|heart_only|1.0
skin|is|largest_organ|1.0
skin|layers|epidermis_dermis_hypodermis|1.0
lymphatic_system|drains|excess_fluid|1.0
lymph_nodes|filter|lymph_and_fight_infection|1.0
endocrine_system|produces|hormones|1.0
thyroid|regulates|metabolism|1.0
adrenal_glands|produce|cortisol_and_adrenaline|1.0
pituitary_gland|is|master_gland|1.0
testosterone|is_a|male_sex_hormone|1.0
estrogen|is_a|female_sex_hormone|1.0
insulin|regulates|blood_sugar|1.0

# === GENETICS ===
dna|stands_for|deoxyribonucleic_acid|1.0
dna|structure|double_helix|1.0
dna|bases|adenine_thymine_guanine_cytosine|1.0
rna|stands_for|ribonucleic_acid|1.0
rna|types|mrna_trna_rrna|1.0
mrna|carries|genetic_code_to_ribosome|1.0
gene|is_a|unit_of_heredity|1.0
chromosome|contains|many_genes|1.0
human_genome|has|about_20000_genes|1.0
human_genome|has|23_chromosome_pairs|1.0
allele|is_a|gene_variant|1.0
dominant_allele|expressed_over|recessive|1.0
recessive_allele|expressed_only|when_homozygous|1.0
genotype|is|genetic_makeup|1.0
phenotype|is|observable_characteristics|1.0
mutation|is_a|dna_change|1.0
point_mutation|changes|single_nucleotide|1.0
insertion|adds|nucleotides|1.0
deletion|removes|nucleotides|1.0
frameshift_mutation|shifts|reading_frame|1.0
crispr|is_a|gene_editing_tool|1.0
crispr|uses|cas9_protein|1.0
crispr|enables|precise_dna_modification|1.0
gene_therapy|treats|disease_by_modifying_genes|1.0
pcr|stands_for|polymerase_chain_reaction|1.0
pcr|amplifies|dna_sequences|1.0
epigenetics|studies|gene_expression_changes|1.0
epigenetics|does_not|change_dna_sequence|1.0
dna_methylation|is_a|epigenetic_modification|1.0
histone_modification|affects|gene_accessibility|1.0
mitosis|produces|two_identical_cells|1.0
meiosis|produces|four_haploid_cells|1.0
meiosis|creates|genetic_diversity|1.0
crossing_over|exchanges|genetic_material|1.0
genetic_drift|is|random_allele_frequency_change|1.0
natural_selection|favors|beneficial_traits|1.0
evolution|driven_by|mutation_selection_drift|1.0
speciation|creates|new_species|1.0
phylogenetics|studies|evolutionary_relationships|1.0
common_ancestor|is|shared_evolutionary_origin|1.0
genomics|studies|entire_genomes|1.0
proteomics|studies|all_proteins|1.0
transcriptomics|studies|all_rna_transcripts|1.0
bioinformatics|uses|computing_for_biology|1.0

# === DISEASES AND MEDICINE ===
virus|is_a|obligate_intracellular_parasite|1.0
bacteria|is_a|single_celled_organism|1.0
antibiotic|kills|bacteria|1.0
antibiotic_resistance|makes|bacteria_immune|1.0
antiviral|treats|viral_infections|1.0
vaccine|trains|immune_system|1.0
vaccine|types|mrna_viral_vector_inactivated|1.0
mrna_vaccine|instructs|cells_to_make_antigen|1.0
immune_system|has|innate_and_adaptive_immunity|1.0
innate_immunity|provides|immediate_nonspecific_defense|1.0
adaptive_immunity|provides|specific_targeted_response|1.0
antibody|produced_by|b_cells|1.0
t_cell|kills|infected_cells|1.0
autoimmune_disease|attacks|own_body_tissues|1.0
cancer|is|uncontrolled_cell_growth|1.0
oncogene|promotes|cancer_when_mutated|1.0
tumor_suppressor|prevents|cancer_normally|1.0
chemotherapy|kills|rapidly_dividing_cells|1.0
radiation_therapy|uses|ionizing_radiation|1.0
immunotherapy|uses|immune_system_against_cancer|1.0
diabetes_type_1|is|autoimmune_insulin_deficiency|1.0
diabetes_type_2|is|insulin_resistance|1.0
cardiovascular_disease|is|leading_cause_of_death|1.0
atherosclerosis|is|plaque_buildup_in_arteries|1.0
stroke|is|blood_supply_cut_to_brain|1.0
alzheimer|is_a|neurodegenerative_disease|1.0
parkinson|is_a|neurodegenerative_disease|1.0
depression|is_a|mood_disorder|1.0
anxiety|is_a|mental_health_condition|1.0
antibiotic|examples|penicillin_amoxicillin_azithromycin|1.0
nsaid|stands_for|nonsteroidal_anti_inflammatory_drug|1.0
nsaid|examples|ibuprofen_aspirin_naproxen|1.0
clinical_trial|phases|1_safety_2_efficacy_3_large_4_post|1.0
placebo_effect|improvement|from_belief_not_treatment|1.0
drug_mechanism|types|agonist_antagonist_inhibitor|1.0

# === NEUROSCIENCE ===
brain|has|about_86_billion_neurons|1.0
neuron|is_a|nerve_cell|1.0
neuron|parts|dendrites_soma_axon|1.0
synapse|is_a|junction_between_neurons|1.0
neurotransmitter|crosses|synapse|1.0
dopamine|involved_in|reward_and_motivation|1.0
serotonin|involved_in|mood_and_sleep|1.0
norepinephrine|involved_in|alertness_and_arousal|1.0
gaba|is_a|inhibitory_neurotransmitter|1.0
glutamate|is_a|excitatory_neurotransmitter|1.0
acetylcholine|involved_in|muscle_contraction_memory|1.0
endorphins|are|natural_painkillers|1.0
cerebral_cortex|handles|higher_thinking|1.0
frontal_lobe|handles|planning_personality_decision|1.0
temporal_lobe|handles|hearing_memory_language|1.0
parietal_lobe|handles|touch_spatial_awareness|1.0
occipital_lobe|handles|vision_processing|1.0
hippocampus|essential_for|memory_formation|1.0
amygdala|processes|emotions_especially_fear|1.0
cerebellum|coordinates|movement_and_balance|1.0
brainstem|controls|basic_life_functions|1.0
prefrontal_cortex|handles|executive_functions|1.0
neuroplasticity|is|brain_ability_to_rewire|1.0
long_term_potentiation|strengthens|synaptic_connections|1.0
myelin_sheath|insulates|axons_for_speed|1.0
action_potential|is|electrical_nerve_impulse|1.0
blood_brain_barrier|protects|brain_from_toxins|1.0
sleep|stages|nrem1_nrem2_nrem3_rem|1.0
rem_sleep|associated_with|dreaming|1.0
circadian_rhythm|controls|sleep_wake_cycle|1.0
melatonin|regulates|sleep|1.0
consciousness|is|awareness_of_self_and_environment|1.0
default_mode_network|active_during|mind_wandering|1.0
mirror_neurons|fire_when|observing_actions_of_others|1.0

# === CELL BIOLOGY ===
cell|is_a|basic_unit_of_life|1.0
prokaryote|has|no_nucleus|1.0
eukaryote|has|membrane_bound_nucleus|1.0
nucleus|contains|dna|1.0
mitochondria|produces|atp_energy|1.0
mitochondria|has|own_dna|1.0
ribosome|synthesizes|proteins|1.0
endoplasmic_reticulum|processes|proteins_and_lipids|1.0
golgi_apparatus|packages|proteins|1.0
lysosome|digests|cellular_waste|1.0
cell_membrane|controls|what_enters_and_exits|1.0
cytoskeleton|provides|structural_support|1.0
chloroplast|performs|photosynthesis_in_plants|1.0
stem_cell|can_become|many_cell_types|1.0
apoptosis|is|programmed_cell_death|1.0
cell_cycle|phases|g1_s_g2_m|1.0
dna_replication|occurs_in|s_phase|1.0
telomere|protects|chromosome_ends|1.0
telomere|shortens|with_each_division|1.0
telomerase|extends|telomeres|1.0

# === ECOLOGY ===
ecosystem|includes|living_and_nonliving_components|1.0
food_chain|shows|energy_flow|1.0
producer|is_a|photosynthetic_organism|1.0
consumer|eats|other_organisms|1.0
decomposer|breaks_down|dead_matter|1.0
biodiversity|measures|variety_of_life|1.0
keystone_species|has|disproportionate_impact|1.0
endangered_species|at_risk_of|extinction|1.0
symbiosis|types|mutualism_commensalism_parasitism|1.0
photosynthesis|converts|co2_water_to_glucose_o2|1.0
cellular_respiration|converts|glucose_to_atp|1.0
nitrogen_cycle|converts|nitrogen_between_forms|1.0
carbon_cycle|moves|carbon_through_systems|1.0
climate_change|caused_by|greenhouse_gas_increase|0.9
greenhouse_effect|traps|heat_in_atmosphere|1.0
ozone_layer|protects_from|uv_radiation|1.0
coral_bleaching|caused_by|ocean_warming|0.9
deforestation|reduces|carbon_sinks|1.0
microbiome|is|community_of_microorganisms|1.0
gut_microbiome|affects|digestion_immunity_mood|1.0

# === MICROBIOLOGY ===
bacteria|shapes|cocci_bacilli_spirilla|1.0
gram_positive|has|thick_peptidoglycan_wall|1.0
gram_negative|has|thin_wall_outer_membrane|1.0
biofilm|is_a|structured_microbial_community|1.0
probiotic|is_a|beneficial_microorganism|1.0
pathogen|is_a|disease_causing_organism|1.0
epidemiology|studies|disease_patterns|1.0
pandemic|is|worldwide_disease_spread|1.0
endemic|is|constantly_present_in_population|1.0
zoonotic|is|disease_from_animals_to_humans|1.0
vector_borne|transmitted_by|insects|1.0
herd_immunity|protects|unvaccinated_population|1.0
quarantine|isolates|potentially_exposed|1.0
antibody_test|detects|past_infection|1.0
pcr_test|detects|current_infection|1.0

# === PHARMACOLOGY ===
pharmacokinetics|studies|drug_movement_in_body|1.0
pharmacodynamics|studies|drug_effects_on_body|1.0
bioavailability|is|fraction_reaching_circulation|1.0
half_life|is|time_to_halve_drug_concentration|1.0
therapeutic_window|is|effective_but_safe_range|1.0
drug_interaction|occurs_when|drugs_affect_each_other|1.0
side_effect|is_a|unintended_drug_effect|1.0
receptor_agonist|activates|receptor|1.0
receptor_antagonist|blocks|receptor|1.0
enzyme_inhibitor|blocks|enzyme_activity|1.0
dose_response|relates|dose_to_effect|1.0
ld50|is|dose_lethal_to_50_percent|1.0
generic_drug|has|same_active_ingredient|1.0
over_the_counter|available|without_prescription|1.0
prescription_drug|requires|doctor_order|1.0

# === HUMAN PHYSIOLOGY ===
homeostasis|maintains|stable_internal_environment|1.0
negative_feedback|counteracts|deviation_from_setpoint|1.0
positive_feedback|amplifies|change_from_setpoint|1.0
blood_pressure|normal|120_over_80_mmhg|1.0
heart_rate|normal_resting|60_to_100_bpm|1.0
body_temperature|normal|37_degrees_celsius|1.0
blood_glucose|normal_fasting|70_to_100_mg_dl|1.0
oxygen_saturation|normal|95_to_100_percent|1.0
ph_of_blood|normal|7.35_to_7.45|1.0
bmi|stands_for|body_mass_index|1.0
basal_metabolic_rate|is|energy_at_rest|1.0
calorie|is_a|unit_of_energy|1.0
macronutrients|are|carbohydrates_proteins_fats|1.0
micronutrients|are|vitamins_and_minerals|1.0
vitamin_d|produced_by|skin_in_sunlight|1.0
vitamin_c|prevents|scurvy|1.0
iron_deficiency|causes|anemia|1.0
dehydration|caused_by|insufficient_water_intake|1.0
electrolytes|include|sodium_potassium_calcium|1.0
atp|stands_for|adenosine_triphosphate|1.0
atp|is|energy_currency_of_cell|1.0

# === DEVELOPMENTAL BIOLOGY ===
fertilization|combines|sperm_and_egg|1.0
embryo|develops_during|first_8_weeks|1.0
fetus|develops_from|9_weeks_to_birth|1.0
placenta|provides|nutrients_to_fetus|1.0
stem_cell_types|include|totipotent_pluripotent_multipotent|1.0
totipotent|can_become|any_cell_type|1.0
pluripotent|can_become|most_cell_types|1.0
cell_differentiation|creates|specialized_cells|1.0
morphogenesis|shapes|organism_form|1.0
organogenesis|forms|organs|1.0
aging|involves|cellular_damage_accumulation|1.0
senescence|is|cell_aging_and_stopping_division|1.0
regenerative_medicine|aims_to|repair_damaged_tissues|1.0
organ_transplant|replaces|failed_organs|1.0
rejection|immune_system|attacks_transplant|1.0
immunosuppressant|prevents|transplant_rejection|1.0

# === EVOLUTIONARY BIOLOGY ===
darwin|proposed|natural_selection|1.0
fitness|is|reproductive_success|1.0
adaptation|is|trait_improving_survival|1.0
convergent_evolution|produces|similar_traits_independently|1.0
divergent_evolution|produces|different_traits_from_ancestor|1.0
homologous_structures|share|common_ancestry|1.0
analogous_structures|have|similar_function_different_origin|1.0
vestigial_structures|are|reduced_nonfunctional_remnants|1.0
fossil_record|documents|evolutionary_history|1.0
mass_extinction|eliminates|many_species|1.0
cambrian_explosion|rapid|diversification_of_life|1.0
endosymbiosis|explains|mitochondria_chloroplast_origin|1.0
horizontal_gene_transfer|moves|genes_between_species|1.0
sexual_selection|drives|mate_choice_traits|1.0
kin_selection|explains|altruism_toward_relatives|1.0
coevolution|is|mutual_evolutionary_influence|1.0

# === BIOTECHNOLOGY ===
genetic_engineering|modifies|organisms_dna|1.0
transgenic_organism|contains|foreign_genes|1.0
gmo|stands_for|genetically_modified_organism|1.0
recombinant_dna|combines|dna_from_different_sources|1.0
plasmid|is_a|vector_for_gene_transfer|1.0
restriction_enzyme|cuts|dna_at_specific_sequences|1.0
gel_electrophoresis|separates|dna_by_size|1.0
dna_sequencing|determines|nucleotide_order|1.0
next_gen_sequencing|sequences|millions_of_fragments|1.0
whole_genome_sequencing|reads|entire_genome|1.0
gene_expression|process|transcription_then_translation|1.0
transcription|copies|dna_to_mrna|1.0
translation|builds|protein_from_mrna|1.0
codon|is_a|three_nucleotide_sequence|1.0
genetic_code|is|universal_for_most_life|1.0
protein_folding|determines|protein_function|1.0
alphafold|predicts|protein_structure|1.0
alphafold|created_by|deepmind|1.0
synthetic_biology|designs|new_biological_systems|1.0
biofuel|produced_from|biological_sources|1.0

# === MEDICAL TECHNOLOGY ===
mri|stands_for|magnetic_resonance_imaging|1.0
mri|uses|magnetic_fields_and_radio_waves|1.0
ct_scan|uses|x_rays_for_cross_sections|1.0
ultrasound|uses|sound_waves_for_imaging|1.0
x_ray|shows|bones_and_dense_tissue|1.0
pet_scan|detects|metabolic_activity|1.0
eeg|measures|brain_electrical_activity|1.0
ecg|measures|heart_electrical_activity|1.0
stethoscope|listens|to_heart_and_lungs|1.0
blood_test|measures|various_biomarkers|1.0
biopsy|samples|tissue_for_analysis|1.0
surgery|types|minimally_invasive_open_robotic|1.0
robotic_surgery|provides|precision_and_small_incisions|1.0
prosthetic|replaces|missing_body_part|1.0
pacemaker|regulates|heart_rhythm|1.0
insulin_pump|delivers|continuous_insulin|1.0
dialysis|replaces|kidney_function|1.0
ventilator|assists|breathing|1.0
defibrillator|restores|heart_rhythm|1.0
telemedicine|provides|remote_healthcare|1.0

# === PUBLIC HEALTH ===
who|stands_for|world_health_organization|1.0
cdc|stands_for|centers_for_disease_control|1.0
epidemiology|tracks|disease_spread_patterns|1.0
r0|measures|disease_transmissibility|1.0
contact_tracing|identifies|exposure_chains|1.0
sanitation|prevents|disease_spread|1.0
clean_water|essential_for|public_health|1.0
vaccination_program|reduces|disease_incidence|1.0
smallpox|first_disease|eradicated_by_vaccination|1.0
polio|nearly|eradicated_worldwide|1.0
hiv|causes|aids|1.0
antiretroviral|treats|hiv_infection|1.0
tuberculosis|caused_by|mycobacterium|1.0
malaria|transmitted_by|mosquitoes|1.0
influenza|mutates|rapidly|1.0
covid_19|caused_by|sars_cov_2|1.0
mental_health|equally_important_as|physical_health|1.0
preventive_medicine|focuses_on|disease_prevention|1.0
screening|detects|disease_early|1.0
life_expectancy|global_average|about_73_years|0.9

# === ANATOMY DETAILS ===
spine|has|33_vertebrae|1.0
skull|has|22_bones|1.0
rib_cage|has|12_pairs|1.0
femur|is|longest_bone|1.0
stapes|is|smallest_bone_in_ear|1.0
tendon|connects|muscle_to_bone|1.0
ligament|connects|bone_to_bone|1.0
cartilage|provides|cushioning_at_joints|1.0
blood_types|include|a_b_ab_o|1.0
rh_factor|is|positive_or_negative|1.0
universal_donor|blood_type|o_negative|1.0
universal_recipient|blood_type|ab_positive|1.0
red_blood_cell_lifespan|about|120_days|1.0
liver|is|largest_internal_organ|1.0
liver|functions|over_500|1.0
appendix|may_serve|immune_function|0.7
spleen|filters|blood_and_stores_platelets|1.0
thymus|trains|t_cells|1.0
pineal_gland|produces|melatonin|1.0
hypothalamus|regulates|temperature_hunger_thirst|1.0
cornea|is|transparent_eye_covering|1.0
retina|contains|photoreceptors|1.0
cochlea|converts|sound_to_nerve_signals|1.0
olfactory_nerve|detects|smell|1.0
taste_buds|detect|sweet_sour_salty_bitter_umami|1.0
proprioception|senses|body_position|1.0
nociceptor|detects|pain|1.0
dna_repair|mechanisms|base_excision_nucleotide_excision_mismatch|1.0
prion|is_a|misfolded_protein|1.0
prion|causes|mad_cow_disease_cjd|1.0
fungal_infection|caused_by|fungi|1.0
parasitic_infection|caused_by|protozoa_or_helminths|1.0
allergic_reaction|is|overactive_immune_response|1.0
anaphylaxis|is_a|severe_allergic_reaction|1.0
inflammation|is|immune_response_to_injury|1.0
chronic_inflammation|contributes_to|many_diseases|0.9
fever|is|elevated_body_temperature|1.0
fever|helps|fight_infection|0.8
pain|is_a|warning_signal|1.0
referred_pain|felt_in|different_location_from_source|1.0
phantom_pain|felt_in|amputated_limb|1.0
placebo|is|inert_treatment|1.0
nocebo|is|harm_from_negative_expectation|1.0
evidence_based_medicine|uses|best_available_research|1.0
randomized_controlled_trial|is|gold_standard_of_research|1.0
meta_analysis|combines|results_from_multiple_studies|1.0
systematic_review|summarizes|all_relevant_evidence|1.0
peer_review|validates|research_quality|1.0
informed_consent|required_before|medical_procedures|1.0
hippocratic_oath|principle|first_do_no_harm|1.0
palliative_care|focuses_on|comfort_not_cure|1.0
hospice|provides|end_of_life_care|1.0
organ_donation|saves|lives_through_transplant|1.0
blood_donation|provides|transfusion_supply|1.0
physical_therapy|rehabilitates|movement_and_strength|1.0
occupational_therapy|helps|daily_activities|1.0
cognitive_behavioral_therapy|treats|mental_health|1.0
ssri|treats|depression_and_anxiety|1.0
ssri|stands_for|selective_serotonin_reuptake_inhibitor|1.0
benzodiazepine|treats|anxiety_short_term|1.0
opioid|treats|severe_pain|1.0
opioid|risk|addiction|0.9
antihistamine|blocks|histamine_receptors|1.0
statin|lowers|cholesterol|1.0
ace_inhibitor|lowers|blood_pressure|1.0
beta_blocker|slows|heart_rate|1.0
diuretic|increases|urine_output|1.0

# === ADDITIONAL UNIQUE BIOLOGY FACTS ===
human_body_water_percentage|approximately|60_percent|1.0
human_body_cells|approximately|37_trillion|1.0
human_dna_length|if_stretched|about_2_meters_per_cell|1.0
heart_beats_per_day|approximately|100000|1.0
breaths_per_day|approximately|20000|1.0
neurons_in_brain|approximately|86_billion|1.0
synapses_in_brain|approximately|100_trillion|1.0
nerve_impulse_speed|up_to|120_meters_per_second|1.0
fastest_muscle|is|orbicularis_oculi_blink|1.0
strongest_muscle|relative|masseter_jaw|1.0
longest_bone|is|femur|1.0
smallest_bone|is|stapes_in_ear|1.0
largest_organ_external|is|skin|1.0
liver_regeneration|can_regrow|from_25_percent|1.0
stomach_acid_ph|approximately|1_5_to_3_5|1.0
blood_volume|average_adult|about_5_liters|1.0
rbc_production_rate|about|2_million_per_second|1.0
platelet_lifespan|approximately|8_to_10_days|1.0
wbc_lifespan|varies|hours_to_years|1.0
oxygen_consumption|brain_uses|20_percent_of_total|1.0
glucose_consumption|brain_uses|25_percent_of_total|1.0
body_heat|from_metabolism|about_100_watts|1.0
dna_replication_error_rate|approximately|1_per_billion_bases|1.0
protein_number_in_human|approximately|20000_different|1.0
amino_acid_types|standard|20|1.0
essential_amino_acids|number|9|1.0
vitamin_types|total|13|1.0
mineral_types_essential|approximately|15|1.0
caloric_need_adult|approximately|2000_to_2500_daily|1.0
water_need_daily|approximately|2_to_3_liters|1.0
sleep_requirement_adult|approximately|7_to_9_hours|1.0
circadian_rhythm_length|approximately|24_hours|1.0
fastest_growing_tissue|is|bone_marrow|1.0
hair_growth_rate|approximately|1_cm_per_month|1.0
nail_growth_rate|approximately|3_mm_per_month|1.0
skin_renewal_cycle|approximately|27_days|1.0
taste_bud_lifespan|approximately|10_days|1.0
olfactory_receptor_types|approximately|400|1.0
cone_types_in_eye|three|red_green_blue|1.0
rod_cells_per_eye|approximately|120_million|1.0
cone_cells_per_eye|approximately|6_million|1.0
cochlear_hair_cells|approximately|15000_per_ear|1.0
pain_receptors|most_dense_in|fingertips|1.0
fastest_reflex|is|blink_reflex|1.0
bone_density_peak|age|approximately_30|1.0
muscle_mass_peak|age|approximately_25_to_30|1.0
metabolic_rate_declines|by|2_percent_per_decade|0.8
telomere_shortening|per_division|50_to_200_base_pairs|1.0
maximum_human_lifespan|documented|122_years|1.0
bacteria_in_gut|approximately|38_trillion|1.0
