# MK Knowledge File - Computer Networking, Protocols, Infrastructure
# Format: source|relation|target|weight
# Covers: TCP/IP, DNS, HTTP, SSH, TLS, VPN, routing, load balancing

# === TCP/IP STACK ===
osi_model|has|7_layers|1.0
physical_layer|is|layer_1|1.0
physical_layer|handles|bits_on_wire|1.0
data_link_layer|is|layer_2|1.0
data_link_layer|handles|frames|1.0
data_link_layer|protocols|ethernet_wifi_ppp|1.0
network_layer|is|layer_3|1.0
network_layer|handles|packets_and_routing|1.0
network_layer|protocols|ip_icmp_arp|1.0
transport_layer|is|layer_4|1.0
transport_layer|handles|end_to_end_communication|1.0
transport_layer|protocols|tcp_udp_sctp|1.0
session_layer|is|layer_5|1.0
presentation_layer|is|layer_6|1.0
application_layer|is|layer_7|1.0
application_layer|protocols|http_ftp_smtp_dns|1.0
tcp|is_a|transport_protocol|1.0
tcp|provides|reliable_ordered_delivery|1.0
tcp|uses|three_way_handshake|1.0
tcp|has|flow_control_congestion_control|1.0
tcp_handshake|steps|syn_synack_ack|1.0
tcp_window|controls|flow_rate|1.0
tcp_congestion_control|algorithms|cubic_bbr_reno|1.0
tcp_bbr|optimized_for|high_bandwidth_networks|0.9
tcp_keepalive|detects|dead_connections|1.0
tcp_nagle|combines|small_packets|1.0
tcp_rst|indicates|connection_reset|1.0
tcp_fin|indicates|graceful_close|1.0
udp|is_a|transport_protocol|1.0
udp|provides|unreliable_fast_delivery|1.0
udp|used_for|streaming_gaming_dns|1.0
udp|has|no_handshake|1.0
ipv4|is_a|network_protocol|1.0
ipv4|address_size|32_bits|1.0
ipv4|notation|dotted_decimal|1.0
ipv6|is_a|network_protocol|1.0
ipv6|address_size|128_bits|1.0
ipv6|notation|colon_hexadecimal|1.0
icmp|is_a|network_protocol|1.0
icmp|used_for|ping_traceroute|1.0
arp|resolves|ip_to_mac_address|1.0
subnet_mask|determines|network_and_host_portions|1.0
cidr|notation|/prefix_length|1.0
private_ip_ranges|include|10.0_172.16_192.168|1.0
mtu|stands_for|maximum_transmission_unit|1.0
mtu|typically|1500_bytes_ethernet|1.0
ttl|stands_for|time_to_live|1.0
ttl|prevents|infinite_packet_loops|1.0
multicast|sends|to_group_of_hosts|1.0
broadcast|sends|to_all_hosts_on_network|1.0
anycast|sends|to_nearest_node|1.0

# === DNS ===
dns|stands_for|domain_name_system|1.0
dns|resolves|domain_names_to_ip|1.0
dns|uses|port_53|1.0
dns_a_record|maps|domain_to_ipv4|1.0
dns_aaaa_record|maps|domain_to_ipv6|1.0
dns_cname_record|is_a|alias_record|1.0
dns_mx_record|specifies|mail_servers|1.0
dns_ns_record|specifies|nameservers|1.0
dns_txt_record|holds|arbitrary_text|1.0
dns_txt_record|used_for|spf_dkim_dmarc|1.0
dns_srv_record|specifies|service_location|1.0
dns_soa_record|contains|zone_authority_info|1.0
dns_ptr_record|maps|ip_to_domain|1.0
dns_caa_record|specifies|allowed_certificate_authorities|1.0
recursive_resolver|queries|on_behalf_of_client|1.0
authoritative_nameserver|holds|actual_dns_records|1.0
root_nameserver|is|top_of_dns_hierarchy|1.0
tld_nameserver|manages|top_level_domains|1.0
dns_cache|stores|recent_lookups|1.0
dns_ttl|determines|cache_duration|1.0
dnssec|provides|dns_authentication|1.0
dnssec|prevents|dns_spoofing|1.0
doh|stands_for|dns_over_https|1.0
doh|encrypts|dns_queries|1.0
doh|uses|port_443|1.0
dot|stands_for|dns_over_tls|1.0
dot|uses|port_853|1.0
split_dns|provides|different_records_internal_external|1.0
dns_load_balancing|distributes|traffic_via_multiple_a_records|1.0
dns_failover|removes|unhealthy_server_records|1.0
cloudflare_dns|is|1.1.1.1|1.0
google_dns|is|8.8.8.8|1.0
pihole|is_a|dns_based_ad_blocker|1.0
unbound|is_a|recursive_dns_resolver|1.0
bind|is_a|authoritative_dns_server|1.0
coredns|is_a|dns_server|1.0
coredns|used_in|kubernetes|1.0

# === HTTP/2, HTTP/3, QUIC, WebSocket, gRPC ===
http|is_a|application_protocol|1.0
http|uses|tcp_port_80|1.0
https|uses|tcp_port_443|1.0
https|encrypts_with|tls|1.0
http_1_1|uses|text_based_protocol|1.0
http_1_1|problem|head_of_line_blocking|1.0
http_2|uses|binary_framing|1.0
http_2|supports|multiplexing|1.0
http_2|supports|header_compression_hpack|1.0
http_2|supports|server_push|1.0
http_2|single|tcp_connection|1.0
http_3|uses|quic_protocol|1.0
http_3|eliminates|tcp_head_of_line_blocking|1.0
http_3|uses|udp_underneath|1.0
quic|is_a|transport_protocol|1.0
quic|built_on|udp|1.0
quic|integrates|tls_1_3|1.0
quic|has|0_rtt_connection_setup|1.0
quic|supports|connection_migration|1.0
quic|developed_by|google|1.0
websocket|is_a|full_duplex_protocol|1.0
websocket|starts_with|http_upgrade|1.0
websocket|uses|ws_or_wss_scheme|1.0
websocket|enables|real_time_communication|1.0
websocket|maintains|persistent_connection|1.0
grpc|is_a|rpc_framework|1.0
grpc|uses|http_2|1.0
grpc|serializes_with|protocol_buffers|1.0
grpc|supports|streaming|1.0
grpc|supports|bidirectional_streaming|1.0
grpc|developed_by|google|1.0
rest_api|uses|http_methods|1.0
rest_api|methods|get_post_put_patch_delete|1.0
graphql|is_a|query_language_for_apis|1.0
graphql|allows|client_specified_queries|1.0
server_sent_events|is_a|one_way_streaming|1.0
server_sent_events|simpler_than|websocket|0.8
long_polling|is_a|server_push_technique|1.0

# === SSH ===
ssh|stands_for|secure_shell|1.0
ssh|uses|port_22|1.0
ssh|provides|encrypted_remote_access|1.0
ssh_key_types|include|rsa_ed25519_ecdsa|1.0
ed25519|is|recommended_ssh_key_type|1.0
ed25519|based_on|elliptic_curve|1.0
rsa_key|minimum_recommended|4096_bits|0.9
ssh_agent|caches|decrypted_private_keys|1.0
ssh_agent_forwarding|allows|key_use_on_remote|1.0
ssh_agent_forwarding|risk|key_theft_by_admin|0.8
ssh_tunnel|is_a|encrypted_port_forward|1.0
local_port_forward|syntax|-L_localport:host:remoteport|1.0
remote_port_forward|syntax|-R_remoteport:host:localport|1.0
dynamic_port_forward|creates|socks_proxy|1.0
ssh_config|located_at|~/.ssh/config|1.0
ssh_config|simplifies|connection_commands|1.0
sshd_config|located_at|/etc/ssh/sshd_config|1.0
ssh_hardening|disable|password_authentication|1.0
ssh_hardening|set|maxauthtries_3|1.0
ssh_jump_host|syntax|-J_bastion|1.0
ssh_multiplexing|reuses|connections|1.0
scp|copies|files_over_ssh|1.0
sftp|is_a|file_transfer_over_ssh|1.0
mosh|is_a|mobile_shell|1.0
mosh|handles|connection_interruptions|1.0

# === TLS ===
tls|stands_for|transport_layer_security|1.0
tls|provides|encryption_authentication_integrity|1.0
tls_1_2|is|widely_supported|1.0
tls_1_3|is|current_recommended_version|1.0
tls_1_3|faster|1_rtt_handshake|1.0
tls_1_3|removes|weak_cipher_suites|1.0
tls_handshake|establishes|shared_secret|1.0
tls_handshake|verifies|server_certificate|1.0
cipher_suite|specifies|key_exchange_encryption_mac|1.0
aes_gcm|is_a|recommended_cipher|1.0
chacha20_poly1305|is_a|recommended_cipher|1.0
x509_certificate|contains|public_key_and_identity|1.0
certificate_authority|issues|signed_certificates|1.0
lets_encrypt|is_a|free_certificate_authority|1.0
lets_encrypt|uses|acme_protocol|1.0
certificate_chain|links|server_cert_to_root_ca|1.0
ocsp|checks|certificate_revocation|1.0
ocsp_stapling|server_provides|revocation_status|1.0
certificate_transparency|logs|all_issued_certificates|1.0
mtls|stands_for|mutual_tls|1.0
mtls|both_parties|verify_certificates|1.0
sni|stands_for|server_name_indication|1.0
sni|allows|multiple_certs_per_ip|1.0
hsts|forces|https_connections|1.0
hsts|header|strict_transport_security|1.0
certificate_pinning|restricts|accepted_certificates|1.0
pfs|stands_for|perfect_forward_secrecy|1.0
pfs|uses|ephemeral_keys|1.0
dhe|provides|forward_secrecy|1.0
ecdhe|provides|forward_secrecy_with_ec|1.0

# === VPN TYPES ===
vpn|stands_for|virtual_private_network|1.0
vpn|creates|encrypted_tunnel|1.0
wireguard|is_a|vpn_protocol|1.0
wireguard|advantage|simple_fast_modern|1.0
wireguard|uses|curve25519_chacha20|1.0
wireguard|kernel_module|built_into_linux|1.0
openvpn|is_a|vpn_protocol|1.0
openvpn|uses|openssl_library|1.0
openvpn|modes|tun_tap|1.0
ipsec|is_a|vpn_protocol|1.0
ipsec|modes|tunnel_transport|1.0
ipsec|protocols|ah_esp_ike|1.0
tailscale|is_a|mesh_vpn|1.0
tailscale|built_on|wireguard|1.0
tailscale|uses|coordination_server|1.0
zerotier|is_a|software_defined_network|1.0
zerotier|creates|virtual_lan|1.0
site_to_site_vpn|connects|two_networks|1.0
remote_access_vpn|connects|user_to_network|1.0
split_tunneling|routes|only_some_traffic_through_vpn|1.0

# === ROUTING PROTOCOLS ===
bgp|stands_for|border_gateway_protocol|1.0
bgp|is_a|path_vector_protocol|1.0
bgp|manages|internet_routing|1.0
bgp|uses|tcp_port_179|1.0
bgp|autonomous_systems|exchange_routes|1.0
ospf|stands_for|open_shortest_path_first|1.0
ospf|is_a|link_state_protocol|1.0
ospf|uses|dijkstra_algorithm|1.0
ospf|areas|divide_network_into_zones|1.0
rip|stands_for|routing_information_protocol|1.0
rip|is_a|distance_vector_protocol|1.0
rip|max_hops|15|1.0
eigrp|is_a|advanced_distance_vector|1.0
eigrp|cisco_proprietary|now_open_standard|0.9
static_route|manually_configured|by_admin|1.0
default_route|used_when|no_specific_route_matches|1.0
route_table|contains|all_known_routes|1.0
routing_metric|determines|best_path|1.0
ecmp|stands_for|equal_cost_multi_path|1.0
ecmp|distributes|traffic_across_equal_routes|1.0
as_number|identifies|autonomous_system|1.0
ibgp|runs_within|same_autonomous_system|1.0
ebgp|runs_between|different_autonomous_systems|1.0
route_redistribution|shares|routes_between_protocols|1.0

# === LOAD BALANCING ===
load_balancer|distributes|traffic_across_servers|1.0
l4_load_balancer|operates_at|transport_layer|1.0
l4_load_balancer|balances_based_on|ip_port|1.0
l7_load_balancer|operates_at|application_layer|1.0
l7_load_balancer|balances_based_on|http_headers_url|1.0
haproxy|is_a|load_balancer|1.0
haproxy|supports|l4_and_l7|1.0
nginx|is_a|reverse_proxy|1.0
nginx|supports|load_balancing|1.0
envoy|is_a|service_proxy|1.0
envoy|used_in|service_mesh|1.0
round_robin|is_a|lb_algorithm|1.0
round_robin|distributes|equally_in_order|1.0
weighted_round_robin|considers|server_capacity|1.0
least_connections|routes_to|server_with_fewest_connections|1.0
ip_hash|routes|same_client_to_same_server|1.0
random|selects|random_backend_server|1.0
health_check|detects|unhealthy_servers|1.0
health_check|removes|failed_servers_from_pool|1.0
sticky_session|maintains|client_server_affinity|1.0
ssl_termination|decrypts|tls_at_load_balancer|1.0
ssl_passthrough|forwards|encrypted_traffic_to_backend|1.0
connection_draining|completes|existing_requests_before_removal|1.0
global_server_load_balancing|routes|based_on_geography|1.0
dns_based_load_balancing|uses|multiple_a_records|1.0
cdn|stands_for|content_delivery_network|1.0
cdn|caches|content_at_edge_locations|1.0
cdn|reduces|latency_and_origin_load|1.0
cloudflare|is_a|cdn_and_security_provider|1.0
akamai|is_a|cdn_provider|1.0
fastly|is_a|cdn_provider|1.0

# === ADDITIONAL PROTOCOLS ===
mqtt|is_a|messaging_protocol|1.0
mqtt|used_for|iot_devices|1.0
mqtt|uses|publish_subscribe_model|1.0
amqp|is_a|messaging_protocol|1.0
amqp|used_by|rabbitmq|1.0
smtp|is_a|email_protocol|1.0
smtp|uses|port_25_587|1.0
imap|is_a|email_retrieval_protocol|1.0
imap|uses|port_993|1.0
ftp|is_a|file_transfer_protocol|1.0
ftp|uses|ports_20_21|1.0
ntp|is_a|time_synchronization_protocol|1.0
ntp|uses|port_123|1.0
snmp|is_a|network_management_protocol|1.0
snmp|monitors|network_devices|1.0
dhcp|assigns|ip_addresses_automatically|1.0
dhcp|uses|ports_67_68|1.0
radius|is_a|authentication_protocol|1.0
ldap|is_a|directory_access_protocol|1.0
sip|is_a|voip_signaling_protocol|1.0
rtp|is_a|real_time_transport_protocol|1.0

# === NETWORK SECURITY ===
firewall|filters|network_traffic|1.0
stateful_firewall|tracks|connection_state|1.0
stateless_firewall|evaluates|each_packet_independently|1.0
waf|stands_for|web_application_firewall|1.0
waf|protects_against|sql_injection_xss|1.0
ids|stands_for|intrusion_detection_system|1.0
ips|stands_for|intrusion_prevention_system|1.0
dmz|stands_for|demilitarized_zone|1.0
dmz|separates|public_and_private_networks|1.0
network_segmentation|isolates|sensitive_systems|1.0
vlan_segmentation|separates|traffic_logically|1.0
microsegmentation|applies|per_workload_policies|1.0
zero_trust_network|assumes|no_implicit_trust|1.0
nat_traversal|techniques|stun_turn_ice|1.0
stun|discovers|public_ip_and_port|1.0
turn|relays|traffic_when_direct_fails|1.0
ice|finds|optimal_connection_path|1.0
port_knocking|hides|services_until_sequence|0.8
vpn_concentrator|aggregates|vpn_connections|1.0
network_tap|mirrors|traffic_for_analysis|1.0
packet_capture|records|network_traffic|1.0
deep_packet_inspection|analyzes|packet_contents|1.0
ssl_inspection|decrypts|tls_for_analysis|1.0

# === NETWORK ARCHITECTURE ===
spine_leaf|is_a|datacenter_topology|1.0
spine_leaf|reduces|latency_between_hosts|1.0
three_tier|is_a|traditional_network_design|1.0
three_tier|layers|access_distribution_core|1.0
software_defined_networking|separates|control_and_data_plane|1.0
openflow|is_a|sdn_protocol|1.0
underlay_network|provides|physical_connectivity|1.0
overlay_network|provides|virtual_connectivity|1.0
east_west_traffic|flows|within_datacenter|1.0
north_south_traffic|flows|in_and_out_of_datacenter|1.0
network_fabric|provides|any_to_any_connectivity|1.0
leaf_switch|connects_to|servers|1.0
spine_switch|connects_to|leaf_switches|1.0
tor_switch|stands_for|top_of_rack|1.0
bgp_evpn|provides|layer_2_over_layer_3|1.0
network_virtualization|creates|virtual_networks|1.0
vpc|stands_for|virtual_private_cloud|1.0
subnet|is_a|network_subdivision|1.0
gateway|connects|different_networks|1.0
router|forwards|packets_between_networks|1.0
switch|forwards|frames_within_network|1.0
hub|broadcasts|to_all_ports|1.0
access_point|provides|wireless_connectivity|1.0
mesh_network|has|self_healing_topology|1.0

# === PERFORMANCE AND TROUBLESHOOTING ===
ping|tests|connectivity_and_latency|1.0
traceroute|shows|path_to_destination|1.0
mtr|combines|ping_and_traceroute|1.0
dig|queries|dns_records|1.0
nslookup|queries|dns|1.0
netstat|shows|network_connections|1.0
ss|shows|socket_statistics|1.0
iperf|measures|network_bandwidth|1.0
bandwidth|measured_in|bits_per_second|1.0
throughput|is|actual_data_transfer_rate|1.0
latency|is|time_for_packet_to_arrive|1.0
jitter|is|variation_in_latency|1.0
packet_loss|percentage|packets_not_delivered|1.0
congestion|causes|increased_latency_and_loss|1.0
quality_of_service|prioritizes|certain_traffic|1.0
dscp|marks|packets_for_qos|1.0
traffic_shaping|smooths|traffic_bursts|1.0
rate_limiting|caps|bandwidth_usage|1.0
tcp_window_scaling|allows|larger_windows|1.0
jumbo_frames|mtu|9000_bytes|1.0
nagle_algorithm|combines|small_tcp_segments|1.0
tcp_nodelay|disables|nagle_algorithm|1.0
syn_flood|is_a|dos_attack|1.0
syn_cookies|mitigate|syn_flood_attacks|1.0
ddos|stands_for|distributed_denial_of_service|1.0
amplification_attack|uses|dns_ntp_memcached|1.0
bgp_hijacking|redirects|traffic_maliciously|1.0
arp_spoofing|redirects|local_traffic|1.0
dns_poisoning|corrupts|dns_cache|1.0
man_in_the_middle|intercepts|communication|1.0

# === WIRELESS NETWORKING ===
wifi|uses|ieee_802_11_standard|1.0
wifi_6|is|802.11ax|1.0
wifi_6|supports|ofdma_and_mu_mimo|1.0
wifi_6e|extends|to_6ghz_band|1.0
wifi_7|is|802.11be|1.0
wpa3|is|latest_wifi_security|1.0
wpa3|uses|sae_handshake|1.0
channel_width|affects|speed_and_range|1.0
2_4ghz|has|better_range_lower_speed|1.0
5ghz|has|higher_speed_shorter_range|1.0
beamforming|focuses|signal_to_client|1.0
mimo|stands_for|multiple_input_multiple_output|1.0
bluetooth|is_a|short_range_wireless|1.0
bluetooth|versions|4.0_5.0_5.3|1.0
zigbee|is_a|iot_wireless_protocol|1.0
lora|is_a|long_range_low_power_protocol|1.0
5g|is_a|cellular_technology|1.0
5g|bands|sub6_and_mmwave|1.0

# === ADDITIONAL UNIQUE NETWORKING FACTS ===
network_interface_card|connects|host_to_network|1.0
mac_address|is|48_bit_hardware_identifier|1.0
mac_address|format|xx:xx:xx:xx:xx:xx|1.0
arp_table|maps|ip_to_mac_locally|1.0
ndp|replaces|arp_in_ipv6|1.0
neighbor_discovery|uses|icmpv6|1.0
slaac|provides|stateless_ipv6_configuration|1.0
dhcpv6|provides|stateful_ipv6_configuration|1.0
link_local_address|always|fe80_prefix|1.0
global_unicast|starts_with|2000_to_3fff|1.0
network_address_translation|types|static_dynamic_pat|1.0
port_address_translation|maps|many_to_one_ip|1.0
cgnat|stands_for|carrier_grade_nat|1.0
ipv4_exhaustion|led_to|ipv6_development|1.0
dual_stack|runs|ipv4_and_ipv6_simultaneously|1.0
tunneling_6in4|encapsulates|ipv6_in_ipv4|1.0
sdn_controller|centralizes|network_decisions|1.0
network_function_virtualization|virtualizes|network_appliances|1.0
white_box_switch|runs|open_network_os|1.0
cumulus_linux|is_a|network_os|1.0
sonic|is_a|open_network_os|1.0
bgp_community|tags|routes_for_policy|1.0
route_reflector|reduces|ibgp_full_mesh|1.0
confederation|partitions|bgp_as|1.0
mpls|stands_for|multiprotocol_label_switching|1.0
mpls|uses|labels_for_forwarding|1.0
segment_routing|simplifies|mpls_with_source_routing|1.0
traffic_engineering|optimizes|path_selection|1.0
qos_marking|tags|packets_for_priority|1.0
weighted_fair_queuing|allocates|bandwidth_proportionally|1.0
priority_queuing|serves|high_priority_first|1.0
policing|drops|excess_traffic|1.0
shaping|delays|excess_traffic|1.0
congestion_avoidance|reduces|packet_loss|1.0
explicit_congestion_notification|signals|congestion_without_dropping|1.0
red|stands_for|random_early_detection|1.0
wred|stands_for|weighted_random_early_detection|1.0
tail_drop|drops|when_queue_full|1.0
network_slicing|allocates|virtual_network_segments|1.0
intent_based_networking|declares|desired_outcome|1.0
programmable_network|uses|apis_for_configuration|1.0
netconf|is_a|network_configuration_protocol|1.0
restconf|provides|rest_api_for_network|1.0
yang_model|defines|network_data_model|1.0
grpc_network|provides|streaming_telemetry|1.0
streaming_telemetry|pushes|data_in_real_time|1.0
snmp_polling|pulls|data_periodically|1.0
network_automation|uses|ansible_nornir_netmiko|1.0
nornir|is_a|python_automation_framework|1.0
netmiko|simplifies|ssh_to_network_devices|1.0
napalm|provides|vendor_agnostic_automation|1.0
batfish|validates|network_configuration|1.0
network_simulation|tools|gns3_eve_ng_containerlab|1.0
containerlab|uses|containers_for_network_labs|1.0
packet_broker|aggregates|and_distributes_traffic|1.0
tap_aggregation|combines|multiple_taps|1.0
network_observability|traces|packets_end_to_end|1.0
flowlog|records|network_flow_metadata|1.0
netflow|is_a|cisco_flow_protocol|1.0
sflow|is_a|sampling_based_flow|1.0
ipfix|is_a|standard_flow_export|1.0
