# MK Knowledge File - Psychology and Philosophy
# Format: source|relation|target|weight
# Covers: cognitive biases, personality, philosophy, decision theory

# === COGNITIVE BIASES ===
confirmation_bias|seeks|info_supporting_existing_beliefs|1.0
confirmation_bias|ignores|contradicting_evidence|0.9
anchoring_bias|fixates_on|first_piece_of_information|1.0
availability_heuristic|judges_probability_by|ease_of_recall|1.0
survivorship_bias|focuses_on|successes_ignoring_failures|1.0
dunning_kruger_effect|unskilled|overestimate_ability|1.0
dunning_kruger_effect|skilled|underestimate_ability|0.9
hindsight_bias|makes_past|seem_predictable|1.0
recency_bias|overweights|recent_events|1.0
sunk_cost_fallacy|continues|because_of_past_investment|1.0
bandwagon_effect|follows|popular_opinion|1.0
halo_effect|generalizes|from_one_positive_trait|1.0
horns_effect|generalizes|from_one_negative_trait|1.0
framing_effect|influenced_by|how_info_is_presented|1.0
loss_aversion|losses_feel|twice_as_painful_as_gains|1.0
status_quo_bias|prefers|current_state_of_affairs|1.0
optimism_bias|believes|bad_things_wont_happen_to_me|1.0
negativity_bias|focuses_more_on|negative_events|1.0
gambler_fallacy|believes|past_affects_random_probability|1.0
hot_hand_fallacy|believes|success_streaks_continue|0.8
fundamental_attribution_error|attributes|others_behavior_to_character|1.0
self_serving_bias|attributes|success_to_self_failure_to_others|1.0
spotlight_effect|overestimates|how_much_others_notice_us|1.0
planning_fallacy|underestimates|time_and_cost|1.0
ikea_effect|overvalues|things_we_built|1.0
endowment_effect|overvalues|what_we_already_own|1.0
zero_risk_bias|prefers|eliminating_risk_entirely|0.8
authority_bias|trusts|authority_figures_more|1.0
in_group_bias|favors|own_group_members|1.0
out_group_homogeneity|sees|other_groups_as_similar|1.0
just_world_hypothesis|believes|people_get_what_they_deserve|0.8
curse_of_knowledge|assumes|others_know_what_we_know|1.0
mere_exposure_effect|prefers|familiar_things|1.0
peak_end_rule|judges|experiences_by_peak_and_end|1.0
anchoring_effect|first_number|influences_all_estimates|1.0
cognitive_dissonance|discomfort_from|conflicting_beliefs|1.0
choice_overload|too_many_options|leads_to_paralysis|0.9
decoy_effect|irrelevant_option|changes_preference|1.0
availability_cascade|repeated_belief|becomes_truth|0.8
blind_spot_bias|sees|bias_in_others_not_self|1.0
reactive_devaluation|rejects|proposals_from_adversary|0.8
normalcy_bias|underestimates|disaster_probability|0.8
affect_heuristic|emotions|influence_decisions|1.0
representativeness_heuristic|judges_by|similarity_to_stereotype|1.0
base_rate_neglect|ignores|statistical_base_rates|1.0

# === PERSONALITY THEORIES ===
big_five|model_has|openness_conscientiousness_extraversion_agreeableness_neuroticism|1.0
openness|is|curiosity_and_creativity|1.0
conscientiousness|is|organization_and_discipline|1.0
extraversion|is|sociability_and_energy|1.0
agreeableness|is|cooperation_and_trust|1.0
neuroticism|is|emotional_instability|1.0
mbti|stands_for|myers_briggs_type_indicator|1.0
mbti|has|16_personality_types|1.0
mbti|dimensions|extraversion_introversion_sensing_intuition_thinking_feeling_judging_perceiving|1.0
mbti|criticism|low_scientific_validity|0.7
trait_theory|describes|stable_personality_characteristics|1.0
psychodynamic_theory|emphasizes|unconscious_motivations|1.0
freud|proposed|id_ego_superego|1.0
jung|proposed|archetypes_and_collective_unconscious|1.0
maslow_hierarchy|needs|physiological_safety_belonging_esteem_actualization|1.0
self_actualization|is|reaching_full_potential|1.0
intrinsic_motivation|driven_by|internal_satisfaction|1.0
extrinsic_motivation|driven_by|external_rewards|1.0
flow_state|is|complete_immersion_in_activity|1.0
flow_state|requires|challenge_skill_balance|1.0
grit|is|perseverance_and_passion_for_long_term_goals|1.0
growth_mindset|believes|abilities_can_be_developed|1.0
fixed_mindset|believes|abilities_are_innate|1.0
locus_of_control|internal|believe_you_control_outcomes|1.0
locus_of_control|external|believe_external_forces_control|1.0
self_efficacy|is|belief_in_own_capability|1.0
learned_helplessness|gives_up|after_repeated_failure|1.0
delayed_gratification|predicts|success|0.8
emotional_intelligence|includes|self_awareness_empathy_regulation|1.0
resilience|is|ability_to_recover_from_adversity|1.0

# === PHILOSOPHY - EPISTEMOLOGY ===
epistemology|studies|nature_of_knowledge|1.0
empiricism|knowledge_from|sensory_experience|1.0
rationalism|knowledge_from|reason_alone|1.0
skepticism|doubts|possibility_of_certain_knowledge|1.0
justified_true_belief|traditional|definition_of_knowledge|1.0
gettier_problem|challenges|justified_true_belief|1.0
a_priori|knowledge|independent_of_experience|1.0
a_posteriori|knowledge|dependent_on_experience|1.0
scientific_method|involves|hypothesis_experiment_conclusion|1.0
falsifiability|criterion_for|scientific_theory|1.0
karl_popper|proposed|falsificationism|1.0
thomas_kuhn|proposed|paradigm_shifts|1.0
induction|generalizes|from_specific_observations|1.0
deduction|derives|specific_from_general|1.0
abduction|infers|best_explanation|1.0
occam_razor|prefers|simplest_explanation|1.0
bayesian_reasoning|updates|beliefs_with_evidence|1.0
problem_of_induction|questions|whether_past_predicts_future|1.0
solipsism|only_certain|own_mind_exists|0.7
phenomenology|studies|conscious_experience|1.0

# === PHILOSOPHY - ETHICS ===
ethics|studies|right_and_wrong|1.0
metaethics|studies|nature_of_morality|1.0
normative_ethics|prescribes|how_to_act|1.0
applied_ethics|addresses|specific_moral_issues|1.0
utilitarianism|maximizes|overall_happiness|1.0
utilitarianism|founders|bentham_mill|1.0
deontology|follows|moral_rules|1.0
deontology|founder|immanuel_kant|1.0
categorical_imperative|act_only|on_universalizable_maxims|1.0
virtue_ethics|develops|moral_character|1.0
virtue_ethics|founder|aristotle|1.0
consequentialism|judges_actions_by|outcomes|1.0
moral_relativism|morality_varies|between_cultures|0.8
moral_realism|moral_facts|exist_objectively|0.8
trolley_problem|illustrates|utilitarian_vs_deontological|1.0
is_ought_problem|cannot_derive|ought_from_is|1.0
naturalistic_fallacy|confuses|natural_with_good|1.0
moral_dilemma|no_option|fully_satisfies_morality|1.0
ethical_egoism|maximize|own_self_interest|0.7
altruism|selfless|concern_for_others|1.0
social_contract_theory|morality_from|mutual_agreement|1.0
rawls_veil_of_ignorance|design_society|without_knowing_your_position|1.0
effective_altruism|uses|evidence_to_maximize_good|1.0
bioethics|applies_ethics_to|medicine_biology|1.0
ai_ethics|addresses|moral_issues_in_ai|1.0

# === PHILOSOPHY - LOGIC ===
logic|studies|valid_reasoning|1.0
propositional_logic|uses|connectives_and_or_not_if|1.0
predicate_logic|uses|quantifiers_and_predicates|1.0
modus_ponens|if_p_then_q_p|therefore_q|1.0
modus_tollens|if_p_then_q_not_q|therefore_not_p|1.0
syllogism|two_premises|lead_to_conclusion|1.0
valid_argument|conclusion_follows|from_premises|1.0
sound_argument|valid_and|premises_are_true|1.0
formal_fallacy|error_in|logical_structure|1.0
informal_fallacy|error_in|reasoning_content|1.0
ad_hominem|attacks|person_not_argument|1.0
straw_man|misrepresents|opponents_argument|1.0
appeal_to_authority|cites|authority_as_proof|1.0
false_dichotomy|presents|only_two_options|1.0
slippery_slope|claims|one_step_leads_to_extreme|1.0
circular_reasoning|assumes|what_it_tries_to_prove|1.0
red_herring|diverts|attention_from_topic|1.0
tu_quoque|deflects_by|pointing_to_hypocrisy|1.0
no_true_scotsman|redefines|group_to_exclude_counter|1.0
burden_of_proof|on|person_making_claim|1.0

# === MAJOR PHILOSOPHERS ===
socrates|method|socratic_questioning|1.0
plato|wrote|the_republic|1.0
plato|theory|forms_or_ideas|1.0
aristotle|wrote|nicomachean_ethics|1.0
aristotle|founder_of|formal_logic|1.0
descartes|said|i_think_therefore_i_am|1.0
descartes|is|father_of_modern_philosophy|1.0
hume|is_a|empiricist_philosopher|1.0
kant|wrote|critique_of_pure_reason|1.0
nietzsche|declared|god_is_dead|1.0
nietzsche|concept|will_to_power|1.0
kierkegaard|founder_of|existentialism|1.0
sartre|existentialism_is|a_humanism|1.0
sartre|concept|existence_precedes_essence|1.0
camus|concept|the_absurd|1.0
wittgenstein|wrote|tractatus_logico_philosophicus|1.0
wittgenstein|later|philosophical_investigations|1.0
heidegger|concept|being_and_time|1.0
foucault|studied|power_and_knowledge|1.0
simone_de_beauvoir|wrote|the_second_sex|1.0

# === DECISION THEORY ===
expected_value|is|probability_times_outcome|1.0
expected_utility|considers|subjective_value|1.0
risk_aversion|prefers|certain_outcome_over_gamble|1.0
risk_seeking|prefers|gamble_over_certain_outcome|0.8
prospect_theory|asymmetric|treatment_of_gains_and_losses|1.0
prospect_theory|created_by|kahneman_and_tversky|1.0
bounded_rationality|recognizes|cognitive_limitations|1.0
bounded_rationality|proposed_by|herbert_simon|1.0
satisficing|accepts|good_enough_option|1.0
maximizing|seeks|best_possible_option|1.0
paradox_of_choice|more_options|less_satisfaction|0.9
decision_fatigue|depletes|willpower_over_time|1.0
system_1_thinking|is|fast_intuitive_automatic|1.0
system_2_thinking|is|slow_deliberate_analytical|1.0
nudge_theory|designs|choices_for_better_outcomes|1.0
libertarian_paternalism|preserves_freedom|while_guiding|1.0
game_theory|studies|strategic_interactions|1.0
prisoners_dilemma|illustrates|cooperation_problem|1.0
nash_equilibrium|no_player|benefits_from_changing|1.0
zero_sum_game|one_gains|other_loses_equally|1.0
positive_sum_game|both_parties|can_benefit|1.0
minimax_strategy|minimizes|maximum_possible_loss|1.0
regret_minimization|chooses|to_minimize_future_regret|1.0
opportunity_cost|is|value_of_next_best_alternative|1.0

# === BEHAVIORAL ECONOMICS ===
behavioral_economics|combines|psychology_and_economics|1.0
daniel_kahneman|won|nobel_prize_2002|1.0
richard_thaler|won|nobel_prize_2017|1.0
mental_accounting|treats|money_differently_by_category|1.0
disposition_effect|sells|winners_holds_losers|1.0
present_bias|overvalues|immediate_rewards|1.0
hyperbolic_discounting|devalues|future_rewards_steeply|1.0
commitment_device|locks_in|future_behavior|1.0
social_proof|follows|what_others_do|1.0
reciprocity|feels|obligation_to_return_favors|1.0
scarcity_effect|values_more|when_rare|1.0
default_effect|sticks_with|preset_option|1.0
loss_framing|stronger|than_gain_framing|1.0
money_illusion|confuses|nominal_and_real_value|1.0
fairness_preference|rejects|unfair_offers|1.0
ultimatum_game|illustrates|fairness_in_decision|1.0

# === PSYCHOLOGY - CLINICAL ===
cognitive_behavioral_therapy|is_a|evidence_based_therapy|1.0
cbt|changes|negative_thought_patterns|1.0
exposure_therapy|treats|phobias_and_anxiety|1.0
mindfulness|is|nonjudgmental_present_awareness|1.0
meditation|trains|attention_and_awareness|1.0
psychoanalysis|explores|unconscious_mind|1.0
humanistic_psychology|emphasizes|self_actualization|1.0
positive_psychology|studies|human_flourishing|1.0
behaviorism|focuses_on|observable_behavior|1.0
classical_conditioning|associates|stimulus_with_response|1.0
operant_conditioning|uses|rewards_and_punishments|1.0
pavlov|demonstrated|classical_conditioning|1.0
skinner|developed|operant_conditioning|1.0
cognitive_psychology|studies|mental_processes|1.0
developmental_psychology|studies|changes_across_lifespan|1.0
social_psychology|studies|social_influence|1.0
milgram_experiment|showed|obedience_to_authority|1.0
stanford_prison_experiment|showed|power_of_situation|1.0
bystander_effect|less_help|when_more_people_present|1.0
conformity|adjusts|behavior_to_group_norms|1.0
groupthink|suppresses|dissent_in_group|1.0
deindividuation|loses|self_awareness_in_group|1.0
cognitive_load|limits|working_memory_capacity|1.0
working_memory|holds|7_plus_minus_2_items|1.0
long_term_memory|types|declarative_procedural|1.0
declarative_memory|types|episodic_semantic|1.0
episodic_memory|stores|personal_experiences|1.0
semantic_memory|stores|general_knowledge|1.0
procedural_memory|stores|skills_and_habits|1.0
encoding|is|process_of_forming_memory|1.0
retrieval|is|process_of_accessing_memory|1.0
forgetting_curve|shows|rapid_initial_decay|1.0
spaced_repetition|improves|long_term_retention|1.0
elaborative_rehearsal|creates|stronger_memories|1.0
interference|disrupts|memory_recall|1.0
false_memory|is|remembering_events_incorrectly|1.0
implicit_bias|is|unconscious_prejudice|1.0
stereotype_threat|reduces|performance_under_stigma|1.0
self_fulfilling_prophecy|expectations|create_reality|1.0
pygmalion_effect|higher_expectations|better_performance|1.0

# === CONSCIOUSNESS AND MIND ===
hard_problem_of_consciousness|asks|why_subjective_experience_exists|1.0
qualia|are|subjective_conscious_experiences|1.0
free_will|debated|determinism_vs_libertarianism|1.0
determinism|all_events|are_caused|1.0
compatibilism|free_will|compatible_with_determinism|1.0
mind_body_problem|asks|how_mind_relates_to_body|1.0
dualism|mind_and_body|are_separate|1.0
physicalism|mind_is|physical_brain_process|1.0
functionalism|mind_is|what_brain_does|1.0
chinese_room|challenges|strong_ai|1.0
turing_test|tests|machine_intelligence|1.0
philosophical_zombie|has|no_consciousness|0.7
panpsychism|consciousness_is|fundamental_property|0.7
integrated_information_theory|measures|consciousness_as_phi|0.8
global_workspace_theory|consciousness_is|broadcast_of_information|0.8
attention|selects|information_for_processing|1.0
selective_attention|filters|irrelevant_stimuli|1.0
inattentional_blindness|misses|obvious_things_when_focused|1.0
change_blindness|fails_to_notice|visual_changes|1.0
perception|is|interpretation_of_sensory_input|1.0
illusion|demonstrates|perception_is_constructed|1.0
gestalt_principles|organize|perception_into_patterns|1.0
cognitive_dissonance_reduction|strategies|change_belief_or_behavior|1.0
defense_mechanisms|include|denial_projection_rationalization|1.0
sublimation|redirects|impulses_into_positive_outlets|1.0
projection|attributes|own_feelings_to_others|1.0
rationalization|creates|logical_excuse_for_behavior|1.0

# === SOCIAL INFLUENCE ===
persuasion_principles|cialdini|reciprocity_scarcity_authority_consistency_liking_consensus|1.0
foot_in_the_door|small_request|leads_to_larger_compliance|1.0
door_in_the_face|large_request|then_smaller_reasonable_one|1.0
anchoring_in_negotiation|first_offer|sets_reference_point|1.0
commitment_and_consistency|people|act_consistently_with_past|1.0
social_norms|guide|acceptable_behavior|1.0
descriptive_norm|what_people|actually_do|1.0
injunctive_norm|what_people|should_do|1.0
obedience|follows|authority_commands|1.0
compliance|agrees|to_direct_request|1.0
conformity|aligns|with_group|1.0
informational_influence|accepts|info_from_others_as_truth|1.0
normative_influence|conforms|to_be_liked_accepted|1.0
minority_influence|small_group|changes_majority_view|0.8
attitude_change|routes|central_and_peripheral|1.0
elaboration_likelihood_model|predicts|persuasion_route|1.0
cognitive_dissonance|motivates|attitude_change|1.0
self_perception_theory|infers|attitudes_from_behavior|1.0
attribution_theory|explains|how_we_interpret_causes|1.0
fundamental_attribution_error|over_attributes|to_disposition|1.0
actor_observer_asymmetry|situation_for_self|disposition_for_others|1.0
motivation|types|intrinsic_extrinsic|1.0
self_determination_theory|needs|autonomy_competence_relatedness|1.0
achievement_motivation|drives|goal_pursuit|1.0
procrastination|delays|important_tasks|1.0
willpower|is|limited_resource|0.8
ego_depletion|reduces|self_control_over_time|0.8
habit_formation|requires|cue_routine_reward|1.0
neuroplasticity|allows|brain_to_change|1.0
stress_response|activates|fight_or_flight|1.0
cortisol|released_during|stress|1.0
burnout|caused_by|chronic_stress|1.0
impostor_syndrome|feels|undeserving_of_success|1.0
perfectionism|sets|unrealistically_high_standards|1.0

# === ADDITIONAL UNIQUE PSYCHOLOGY FACTS ===
working_memory_duration|approximately|20_to_30_seconds|1.0
short_term_memory_capacity|miller_number|7_plus_minus_2|1.0
long_term_memory_capacity|theoretically|unlimited|1.0
forgetting_curve_ebbinghaus|forgets|50_percent_in_1_hour|0.8
sleep_consolidates|memories|during_nrem_and_rem|1.0
emotion_processing_speed|faster_than|cognitive_processing|1.0
facial_expression_recognition|universal|across_cultures|0.9
body_language|conveys|55_percent_of_communication|0.7
tone_of_voice|conveys|38_percent_of_communication|0.7
words_convey|only|7_percent_in_emotional_communication|0.7
mirror_neuron_system|enables|empathy_and_imitation|1.0
oxytocin|promotes|bonding_and_trust|1.0
cortisol|increases_with|chronic_stress|1.0
dopamine|released_during|anticipation_of_reward|1.0
serotonin|regulated_by|sunlight_exercise_diet|1.0
endorphin_release|triggered_by|exercise_laughter_music|1.0
neurogenesis|occurs_in|hippocampus_throughout_life|1.0
brain_plasticity|highest_in|childhood|1.0
critical_period|for_language|birth_to_puberty|1.0
attachment_theory|bowlby|secure_anxious_avoidant|1.0
strange_situation|tests|infant_attachment|1.0
erikson_stages|eight|psychosocial_development_stages|1.0
piaget_stages|four|cognitive_development_stages|1.0
kohlberg_stages|six|moral_development_stages|1.0
vygotsky|proposed|zone_of_proximal_development|1.0
bandura|proposed|social_learning_theory|1.0
self_efficacy_theory|bandura|belief_in_ability_affects_outcome|1.0
learned_optimism|seligman|explanatory_style|1.0
positive_psychology|seligman|study_of_wellbeing|1.0
perma_model|pillars|positive_emotion_engagement_relationships_meaning_achievement|1.0
broaden_and_build|positive_emotions|expand_thinking|1.0
hedonic_adaptation|returns_to|baseline_happiness|1.0
set_point_theory|happiness|has_genetic_baseline|0.8
dual_process_theory|system_1_and_2|fast_and_slow_thinking|1.0
cognitive_load_theory|limited|processing_capacity|1.0
selective_attention|cocktail_party|effect|1.0
inattentional_blindness_gorilla|missed|obvious_gorilla|1.0
change_blindness|fails_to_notice|gradual_changes|1.0
priming_effect|exposure|influences_subsequent_response|1.0
anchoring_experiment|judges|influenced_by_random_number|1.0
