# MK Knowledge File - Physics and Chemistry
# Format: source|relation|target|weight
# Covers: quantum mechanics, relativity, thermodynamics, chemistry

# === QUANTUM MECHANICS ===
quantum_mechanics|governs|subatomic_particles|1.0
uncertainty_principle|states|cannot_know_position_and_momentum_precisely|1.0
uncertainty_principle|discovered_by|heisenberg|1.0
superposition|is|particle_in_multiple_states_simultaneously|1.0
wave_function|describes|quantum_state|1.0
wave_function_collapse|occurs_upon|measurement|1.0
schrodinger_equation|governs|wave_function_evolution|1.0
schrodinger_cat|illustrates|superposition_paradox|1.0
quantum_entanglement|links|particles_across_distance|1.0
entanglement|called|spooky_action_at_distance|0.8
quantum_tunneling|allows|particle_through_barrier|1.0
quantum_tunneling|used_in|flash_memory_and_stm|1.0
photon|is_a|quantum_of_light|1.0
electron|is_a|fundamental_particle|1.0
quark|is_a|fundamental_particle|1.0
quark|types|up_down_strange_charm_bottom_top|1.0
lepton|is_a|fundamental_particle|1.0
boson|is_a|force_carrying_particle|1.0
higgs_boson|gives|mass_to_particles|1.0
higgs_boson|discovered|2012_at_cern|1.0
spin|is_a|quantum_property|1.0
pauli_exclusion_principle|forbids|identical_fermions_same_state|1.0
quantum_computing|uses|qubits|1.0
qubit|can_be|0_and_1_simultaneously|1.0
quantum_decoherence|destroys|superposition|1.0
quantum_error_correction|protects|quantum_information|1.0
shor_algorithm|breaks|rsa_encryption|0.9
grover_algorithm|speeds_up|database_search|1.0
bell_inequality|proves|quantum_nonlocality|1.0
double_slit_experiment|shows|wave_particle_duality|1.0
wave_particle_duality|means|matter_is_both_wave_and_particle|1.0
planck_constant|value|6.626e-34_joule_seconds|1.0
photoelectric_effect|explained_by|einstein|1.0
photoelectric_effect|proves|light_is_quantized|1.0
quantum_field_theory|unifies|quantum_mechanics_and_special_relativity|1.0
standard_model|describes|all_known_particles|1.0
strong_force|holds|quarks_together|1.0
weak_force|responsible_for|radioactive_decay|1.0
electromagnetic_force|governs|charged_particles|1.0
gravity|is|weakest_fundamental_force|1.0

# === RELATIVITY ===
special_relativity|published_by|einstein_1905|1.0
special_relativity|postulate|speed_of_light_is_constant|1.0
special_relativity|postulate|laws_same_in_all_inertial_frames|1.0
time_dilation|means|time_slows_at_high_speed|1.0
length_contraction|means|objects_shorter_at_high_speed|1.0
mass_energy_equivalence|equation|E_equals_mc_squared|1.0
lorentz_factor|determines|relativistic_effects|1.0
speed_of_light|value|299792458_m_per_s|1.0
nothing|can_travel|faster_than_light|1.0
general_relativity|published_by|einstein_1915|1.0
general_relativity|describes|gravity_as_spacetime_curvature|1.0
gravitational_waves|are|ripples_in_spacetime|1.0
gravitational_waves|detected_by|ligo_2015|1.0
black_hole|has|event_horizon|1.0
black_hole|gravity|so_strong_light_cannot_escape|1.0
schwarzschild_radius|defines|event_horizon_size|1.0
hawking_radiation|allows|black_holes_to_evaporate|1.0
gravitational_lensing|bends|light_around_massive_objects|1.0
gps|requires|relativistic_corrections|1.0
frame_dragging|twists|spacetime_around_rotating_mass|1.0
cosmological_constant|is|energy_density_of_empty_space|1.0
dark_energy|drives|accelerating_expansion|1.0
dark_matter|provides|extra_gravitational_pull|1.0
big_bang|is|origin_of_universe|1.0
cosmic_microwave_background|is|afterglow_of_big_bang|1.0
hubble_constant|measures|universe_expansion_rate|1.0
redshift|indicates|object_moving_away|1.0
neutron_star|is_a|extremely_dense_remnant|1.0
pulsar|is_a|rotating_neutron_star|1.0
singularity|is|point_of_infinite_density|1.0

# === THERMODYNAMICS ===
first_law_thermodynamics|states|energy_is_conserved|1.0
first_law_thermodynamics|means|energy_cannot_be_created_or_destroyed|1.0
second_law_thermodynamics|states|entropy_always_increases|1.0
second_law_thermodynamics|implies|perpetual_motion_impossible|1.0
third_law_thermodynamics|states|absolute_zero_unreachable|1.0
zeroth_law_thermodynamics|defines|thermal_equilibrium|1.0
entropy|measures|disorder_of_system|1.0
entropy|always|increases_in_isolated_system|1.0
enthalpy|measures|heat_content|1.0
gibbs_free_energy|determines|reaction_spontaneity|1.0
heat_engine|converts|heat_to_work|1.0
carnot_cycle|is|most_efficient_heat_engine|1.0
carnot_efficiency|equals|1_minus_Tc_over_Th|1.0
absolute_zero|is|0_kelvin_minus_273_celsius|1.0
heat_transfer|modes|conduction_convection_radiation|1.0
conduction|transfers|heat_through_material|1.0
convection|transfers|heat_through_fluid_motion|1.0
radiation|transfers|heat_through_electromagnetic_waves|1.0
specific_heat|is|energy_to_raise_1kg_by_1_degree|1.0
latent_heat|is|energy_for_phase_change|1.0
phase_transition|types|melting_boiling_sublimation|1.0
ideal_gas_law|equation|PV_equals_nRT|1.0
boltzmann_constant|connects|temperature_to_energy|1.0
maxwell_boltzmann_distribution|describes|molecular_speeds|1.0
adiabatic_process|has|no_heat_exchange|1.0
isothermal_process|has|constant_temperature|1.0
isobaric_process|has|constant_pressure|1.0

# === ELECTROMAGNETISM ===
maxwell_equations|unify|electricity_and_magnetism|1.0
coulomb_law|describes|force_between_charges|1.0
electric_field|surrounds|charged_particles|1.0
magnetic_field|created_by|moving_charges|1.0
electromagnetic_induction|generates|voltage_from_changing_field|1.0
faraday_law|describes|electromagnetic_induction|1.0
lenz_law|opposes|change_in_flux|1.0
ohm_law|equation|V_equals_IR|1.0
resistance|measured_in|ohms|1.0
capacitance|measured_in|farads|1.0
inductance|measured_in|henrys|1.0
electromagnetic_spectrum|ranges|radio_to_gamma|1.0
visible_light|wavelength|380_to_700_nm|1.0
frequency|related_to|wavelength_by_c|1.0
semiconductor|between|conductor_and_insulator|1.0
pn_junction|is_a|diode|1.0
transistor|is_a|electronic_switch|1.0
mosfet|is_a|field_effect_transistor|1.0
superconductor|has|zero_resistance|1.0
superconductor|requires|very_low_temperature|1.0

# === CHEMISTRY ===
periodic_table|organizes|elements_by_atomic_number|1.0
element|defined_by|number_of_protons|1.0
atom|consists_of|protons_neutrons_electrons|1.0
proton|has_charge|positive|1.0
neutron|has_charge|neutral|1.0
electron|has_charge|negative|1.0
isotope|same_element|different_neutrons|1.0
ion|is_a|charged_atom|1.0
cation|is_a|positive_ion|1.0
anion|is_a|negative_ion|1.0
ionic_bond|transfers|electrons|1.0
covalent_bond|shares|electrons|1.0
metallic_bond|has|electron_sea|1.0
hydrogen_bond|is_a|weak_intermolecular_force|1.0
van_der_waals|is_a|weak_intermolecular_force|1.0
electronegativity|measures|electron_attracting_ability|1.0
oxidation|is|loss_of_electrons|1.0
reduction|is|gain_of_electrons|1.0
redox_reaction|involves|electron_transfer|1.0
acid|donates|protons|1.0
base|accepts|protons|1.0
ph_scale|measures|acidity_0_to_14|1.0
catalyst|speeds_up|reaction_without_being_consumed|1.0
enzyme|is_a|biological_catalyst|1.0
exothermic_reaction|releases|energy|1.0
endothermic_reaction|absorbs|energy|1.0
mole|is|6.022e23_particles|1.0
avogadro_number|is|6.022e23|1.0
stoichiometry|balances|chemical_equations|1.0
organic_chemistry|studies|carbon_compounds|1.0
alkane|is_a|saturated_hydrocarbon|1.0
alkene|has|carbon_carbon_double_bond|1.0
alkyne|has|carbon_carbon_triple_bond|1.0
aromatic_compound|has|benzene_ring|1.0
polymer|is_a|long_chain_molecule|1.0
amino_acid|is_a|protein_building_block|1.0
nucleotide|is_a|dna_rna_building_block|1.0
carbohydrate|is_a|sugar_molecule|1.0
lipid|is_a|fat_molecule|1.0
chemical_equilibrium|forward_rate|equals_reverse_rate|1.0
le_chatelier_principle|predicts|equilibrium_shift|1.0
activation_energy|is|minimum_energy_for_reaction|1.0
reaction_rate|affected_by|temperature_concentration_catalyst|1.0
nuclear_fission|splits|heavy_nuclei|1.0
nuclear_fusion|combines|light_nuclei|1.0
radioactive_decay|types|alpha_beta_gamma|1.0
half_life|is|time_for_half_to_decay|1.0
carbon_14_dating|uses|radioactive_decay|1.0

# === NUCLEAR PHYSICS ===
uranium_235|is_a|fissile_material|1.0
plutonium_239|is_a|fissile_material|1.0
nuclear_reactor|uses|controlled_fission|1.0
chain_reaction|is|self_sustaining_fission|1.0
critical_mass|is|minimum_for_chain_reaction|1.0
moderator|slows|neutrons|1.0
control_rod|absorbs|neutrons|1.0
nuclear_fusion|powers|the_sun|1.0
hydrogen_isotopes|used_in|fusion_deuterium_tritium|1.0
tokamak|is_a|fusion_reactor_design|1.0
iter|is_a|international_fusion_project|1.0
radioactivity|types|alpha_beta_gamma|1.0
alpha_particle|is|helium_nucleus|1.0
beta_particle|is|electron_or_positron|1.0
gamma_ray|is|high_energy_photon|1.0
geiger_counter|detects|radiation|1.0
radiation_dose|measured_in|sieverts|1.0

# === MATERIALS SCIENCE ===
crystal_structure|types|cubic_hexagonal_tetragonal|1.0
alloy|is_a|mixture_of_metals|1.0
steel|is_a|iron_carbon_alloy|1.0
stainless_steel|contains|chromium_for_corrosion_resistance|1.0
titanium|is|strong_light_corrosion_resistant|1.0
graphene|is_a|single_layer_of_carbon|1.0
graphene|has|extraordinary_strength|1.0
carbon_nanotube|is_a|cylindrical_carbon_structure|1.0
ceramic|is|hard_brittle_heat_resistant|1.0
glass|is_a|amorphous_solid|1.0
composite_material|combines|two_or_more_materials|1.0
carbon_fiber|is_a|strong_lightweight_material|1.0
metamaterial|has|engineered_properties|1.0
piezoelectric|generates|voltage_from_pressure|1.0
shape_memory_alloy|returns|to_original_shape|1.0
biomaterial|compatible_with|biological_systems|1.0

# === CLASSICAL MECHANICS ===
newton_first_law|states|object_at_rest_stays_at_rest|1.0
newton_second_law|states|force_equals_mass_times_acceleration|1.0
newton_third_law|states|equal_and_opposite_reaction|1.0
momentum|equals|mass_times_velocity|1.0
conservation_of_momentum|total_momentum|stays_constant|1.0
conservation_of_energy|total_energy|stays_constant|1.0
kinetic_energy|equals|half_mv_squared|1.0
potential_energy|depends_on|position_in_field|1.0
gravitational_potential|equals|mgh|1.0
work|equals|force_times_distance|1.0
power|equals|work_over_time|1.0
torque|is|rotational_force|1.0
angular_momentum|is|rotational_momentum|1.0
centripetal_force|directed|toward_center_of_circle|1.0
friction|opposes|relative_motion|1.0
drag|opposes|motion_through_fluid|1.0
buoyancy|is|upward_force_on_submerged_object|1.0
archimedes_principle|buoyancy_equals|weight_of_displaced_fluid|1.0
simple_harmonic_motion|oscillates|about_equilibrium|1.0
pendulum|period_depends_on|length_and_gravity|1.0
resonance|occurs_at|natural_frequency|1.0
doppler_effect|shifts|frequency_with_motion|1.0
speed_of_sound|in_air|343_m_per_s|1.0
ultrasound|frequency_above|20000_hz|1.0

# === OPTICS ===
reflection|angle_of_incidence|equals_angle_of_reflection|1.0
refraction|bends|light_at_interface|1.0
snell_law|relates|angles_of_refraction|1.0
total_internal_reflection|used_in|fiber_optics|1.0
lens|converges_or_diverges|light|1.0
concave_lens|diverges|light|1.0
convex_lens|converges|light|1.0
diffraction|bends|light_around_obstacles|1.0
interference|constructive_or_destructive|wave_superposition|1.0
polarization|restricts|wave_oscillation_direction|1.0
laser|produces|coherent_monochromatic_light|1.0
laser|stands_for|light_amplification_by_stimulated_emission|1.0
fiber_optic|uses|total_internal_reflection|1.0
prism|separates|white_light_into_spectrum|1.0
spectrum|order|red_orange_yellow_green_blue_indigo_violet|1.0

# === ASTROPHYSICS ===
star|is_a|ball_of_plasma|1.0
main_sequence|where|stars_spend_most_of_life|1.0
red_giant|is_a|late_stage_star|1.0
white_dwarf|is_a|stellar_remnant|1.0
supernova|is_a|stellar_explosion|1.0
supernova|creates|heavy_elements|1.0
galaxy|contains|billions_of_stars|1.0
milky_way|is_a|spiral_galaxy|1.0
andromeda|is_a|nearest_large_galaxy|1.0
quasar|is_a|extremely_luminous_object|1.0
exoplanet|is_a|planet_outside_solar_system|1.0
habitable_zone|is|region_where_liquid_water_possible|1.0
dark_matter|makes_up|27_percent_of_universe|1.0
dark_energy|makes_up|68_percent_of_universe|1.0
normal_matter|makes_up|5_percent_of_universe|1.0
cosmic_inflation|expanded|universe_exponentially|1.0
multiverse|is_a|theoretical_concept|0.7
string_theory|proposes|extra_dimensions|0.7

# === FLUID DYNAMICS ===
fluid_dynamics|studies|fluids_in_motion|1.0
viscosity|measures|fluid_resistance_to_flow|1.0
turbulent_flow|is|chaotic_fluid_motion|1.0
laminar_flow|is|smooth_ordered_flow|1.0
reynolds_number|predicts|turbulence|1.0
bernoulli_principle|relates|speed_and_pressure|1.0
navier_stokes_equations|govern|fluid_motion|1.0
lift|generated_by|pressure_difference|1.0
aerodynamics|studies|air_flow|1.0
hydrodynamics|studies|water_flow|1.0

# === PARTICLE PHYSICS ===
hadron|made_of|quarks|1.0
proton|is_a|hadron|1.0
neutron|is_a|hadron|1.0
meson|is_a|quark_antiquark_pair|1.0
gluon|carries|strong_force|1.0
w_boson|carries|weak_force|1.0
z_boson|carries|weak_force|1.0
photon|carries|electromagnetic_force|1.0
graviton|hypothetical|carrier_of_gravity|0.7
neutrino|is_a|nearly_massless_lepton|1.0
antimatter|is|mirror_of_matter|1.0
positron|is|antielectron|1.0
particle_accelerator|accelerates|particles_to_high_energy|1.0
large_hadron_collider|is_a|particle_accelerator|1.0
large_hadron_collider|located_at|cern_switzerland|1.0
feynman_diagram|represents|particle_interactions|1.0
quantum_chromodynamics|describes|strong_force|1.0
quantum_electrodynamics|describes|electromagnetic_force|1.0

# === ADVANCED CHEMISTRY ===
catalysis|types|homogeneous_heterogeneous|1.0
enzyme_catalysis|lowers|activation_energy_in_biology|1.0
electrochemistry|studies|reactions_involving_electricity|1.0
galvanic_cell|converts|chemical_to_electrical_energy|1.0
electrolysis|uses|electricity_to_drive_reaction|1.0
corrosion|is|electrochemical_degradation|1.0
photochemistry|studies|light_driven_reactions|1.0
photosynthesis|converts|light_to_chemical_energy|1.0
thermochemistry|studies|heat_in_reactions|1.0
hess_law|states|enthalpy_is_path_independent|1.0
equilibrium_constant|Keq|ratio_of_products_to_reactants|1.0
solubility|measures|how_much_dissolves|1.0
solution|is_a|homogeneous_mixture|1.0
colloid|is_a|mixture_with_suspended_particles|1.0
suspension|is_a|mixture_with_settling_particles|1.0
molarity|is|moles_per_liter|1.0
titration|determines|concentration_by_adding_reagent|1.0
spectroscopy|identifies|substances_by_spectra|1.0
mass_spectrometry|measures|mass_to_charge_ratio|1.0
nmr|stands_for|nuclear_magnetic_resonance|1.0
chromatography|separates|mixture_components|1.0
distillation|separates|by_boiling_points|1.0
crystallization|purifies|by_forming_crystals|1.0
coordination_chemistry|studies|metal_ligand_complexes|1.0
transition_metals|have|partially_filled_d_orbitals|1.0
lanthanides|are|rare_earth_elements|1.0
noble_gases|are|chemically_inert|1.0
halogens|are|highly_reactive_nonmetals|1.0
alkali_metals|are|very_reactive_metals|1.0
alkaline_earth_metals|are|reactive_metals|1.0
metalloid|has|properties_of_metals_and_nonmetals|1.0
allotrope|is|different_form_of_same_element|1.0
carbon_allotropes|include|diamond_graphite_fullerene|1.0
nanotechnology|manipulates|matter_at_nanoscale|1.0
quantum_dots|are|nanoscale_semiconductors|1.0
battery_chemistry|types|lithium_ion_solid_state|1.0
lithium_ion_battery|uses|lithium_intercalation|1.0
solid_state_battery|uses|solid_electrolyte|1.0
fuel_cell|converts|hydrogen_to_electricity|1.0
supercapacitor|stores|energy_in_electric_field|1.0

# === WAVES AND ACOUSTICS ===
wave|types|transverse_longitudinal|1.0
transverse_wave|oscillates|perpendicular_to_direction|1.0
longitudinal_wave|oscillates|parallel_to_direction|1.0
frequency|measured_in|hertz|1.0
wavelength|measured_in|meters|1.0
amplitude|measures|wave_intensity|1.0
standing_wave|forms|at_resonant_frequencies|1.0
harmonics|are|integer_multiples_of_fundamental|1.0
acoustic_resonance|amplifies|specific_frequencies|1.0
sound_intensity|measured_in|decibels|1.0
infrasound|frequency_below|20_hz|1.0
sonar|uses|sound_waves_for_detection|1.0
seismic_waves|caused_by|earthquakes|1.0
p_wave|is_a|compressional_seismic_wave|1.0
s_wave|is_a|shear_seismic_wave|1.0
plasmonics|studies|light_metal_interactions|1.0
bose_einstein_condensate|is_a|state_of_matter|1.0
plasma|is_a|ionized_gas_state|1.0
plasma|fourth|state_of_matter|1.0
degenerate_matter|exists_in|white_dwarfs|1.0
neutronium|exists_in|neutron_stars|1.0
quark_gluon_plasma|existed|after_big_bang|1.0
superfluidity|has|zero_viscosity|1.0
quantum_teleportation|transfers|quantum_state|1.0
entanglement_swapping|extends|entanglement_range|1.0
quantum_key_distribution|uses|quantum_properties_for_security|1.0
no_cloning_theorem|forbids|copying_quantum_state|1.0
quantum_decoherence|is|loss_of_quantum_behavior|1.0
measurement_problem|is|unsolved_quantum_question|1.0
many_worlds_interpretation|proposes|all_outcomes_happen|0.7
copenhagen_interpretation|says|wave_function_collapses|0.8
pilot_wave_theory|is_a|deterministic_interpretation|0.7
quantum_gravity|attempts_to|unify_qm_and_gr|0.8
loop_quantum_gravity|quantizes|spacetime|0.7
holographic_principle|states|volume_encoded_on_boundary|0.7
information_paradox|concerns|black_hole_information|0.8
hawking_temperature|inversely_proportional|black_hole_mass|1.0
chandrasekhar_limit|maximum_mass|white_dwarf_1.4_solar|1.0
tolman_oppenheimer_volkoff_limit|maximum_mass|neutron_star|1.0
nuclear_binding_energy|holds|nucleus_together|1.0
mass_defect|converted_to|binding_energy|1.0
strong_nuclear_force|range|very_short_femtometers|1.0
weak_nuclear_force|responsible_for|beta_decay|1.0
electroweak_unification|unifies|electromagnetic_and_weak|1.0
grand_unified_theory|attempts_to|unify_three_forces|0.7
theory_of_everything|attempts_to|unify_all_four_forces|0.7
symmetry_breaking|gives|particles_different_masses|1.0
conservation_laws|include|energy_momentum_charge|1.0
noether_theorem|links|symmetries_to_conservation_laws|1.0
entropy_of_black_hole|proportional_to|surface_area|1.0
bekenstein_hawking_entropy|formula|A_over_4_planck_area|1.0
cosmic_string|is_a|topological_defect|0.7
magnetic_monopole|hypothetical|isolated_magnetic_pole|0.6
tachyon|hypothetical|faster_than_light_particle|0.5
casimir_effect|is|attraction_between_plates|1.0
vacuum_energy|is|energy_of_empty_space|1.0
zero_point_energy|is|minimum_quantum_energy|1.0
lamb_shift|is|quantum_correction_to_energy_levels|1.0
cherenkov_radiation|emitted_when|particle_exceeds_light_in_medium|1.0
synchrotron_radiation|emitted_by|accelerated_charged_particles|1.0
bremsstrahlung|is|radiation_from_deceleration|1.0
blackbody_radiation|spectrum|depends_on_temperature|1.0
wien_law|peak_wavelength|inversely_proportional_to_temp|1.0
stefan_boltzmann_law|power|proportional_to_T_fourth|1.0
photoelectric_effect|threshold|minimum_frequency_needed|1.0
compton_scattering|shifts|photon_wavelength|1.0
pair_production|creates|electron_positron_from_photon|1.0
annihilation|converts|matter_to_energy|1.0
conservation_of_charge|total_charge|remains_constant|1.0
conservation_of_baryon_number|baryons|minus_antibaryons_constant|1.0
conservation_of_lepton_number|leptons|minus_antileptons_constant|1.0
cp_violation|explains|matter_antimatter_asymmetry|0.9
neutrino_oscillation|proves|neutrinos_have_mass|1.0
dark_matter_candidates|include|wimps_axions|0.8
axion|is_a|hypothetical_dark_matter_particle|0.7
wimp|stands_for|weakly_interacting_massive_particle|0.8
gravitational_wave_detection|uses|laser_interferometry|1.0
ligo|stands_for|laser_interferometer_gravitational_observatory|1.0

# === ADDITIONAL UNIQUE PHYSICS FACTS ===
planck_length|is|smallest_meaningful_distance|1.0
planck_time|is|smallest_meaningful_time|1.0
planck_mass|is|mass_of_small_black_hole|1.0
planck_temperature|is|maximum_temperature|1.0
fine_structure_constant|value|approximately_1_over_137|1.0
speed_of_light_in_vacuum|exact|299792458_meters_per_second|1.0
gravitational_constant|value|6_674e_minus_11|1.0
electron_mass|value|9_109e_minus_31_kg|1.0
proton_mass|value|1_673e_minus_27_kg|1.0
elementary_charge|value|1_602e_minus_19_coulombs|1.0
boltzmann_constant_value|is|1_381e_minus_23_J_per_K|1.0
avogadro_constant|value|6_022e23_per_mol|1.0
stefan_boltzmann_constant|value|5_670e_minus_8|1.0
hubble_constant_value|approximately|70_km_per_s_per_mpc|1.0
age_of_universe|approximately|13_8_billion_years|1.0
observable_universe_radius|approximately|46_5_billion_light_years|1.0
number_of_stars|in_observable_universe|about_200_billion_billion|1.0
sun_surface_temperature|approximately|5778_kelvin|1.0
earth_escape_velocity|approximately|11_2_km_per_s|1.0
earth_orbital_velocity|approximately|29_8_km_per_s|1.0
earth_mass|approximately|5_97e24_kg|1.0
moon_distance|approximately|384400_km|1.0
light_year|equals|9_461e12_km|1.0
parsec|equals|3_26_light_years|1.0
astronomical_unit|equals|149_6_million_km|1.0
solar_luminosity|approximately|3_828e26_watts|1.0
coulomb_constant|value|8_988e9|1.0
permittivity_of_free_space|value|8_854e_minus_12|1.0
permeability_of_free_space|value|4pi_e_minus_7|1.0
speed_of_sound_in_water|approximately|1480_m_per_s|1.0
speed_of_sound_in_steel|approximately|5960_m_per_s|1.0
refractive_index_water|approximately|1_33|1.0
refractive_index_glass|approximately|1_5|1.0
refractive_index_diamond|approximately|2_42|1.0
absolute_zero|equals|minus_273_15_celsius|1.0
triple_point_of_water|defines|273_16_kelvin|1.0
critical_temperature_of_water|approximately|374_celsius|1.0
boiling_point_of_nitrogen|approximately|minus_196_celsius|1.0
boiling_point_of_helium|approximately|minus_269_celsius|1.0
melting_point_of_tungsten|approximately|3422_celsius|1.0
density_of_water|at_4c|1000_kg_per_cubic_meter|1.0
density_of_air|at_sea_level|approximately_1_225_kg_per_m3|1.0
atmospheric_pressure|at_sea_level|101325_pascals|1.0
viscosity_of_water|at_20c|approximately_1_millipascal_second|1.0
thermal_conductivity_copper|approximately|401_w_per_m_k|1.0
thermal_conductivity_diamond|approximately|2200_w_per_m_k|1.0
electrical_resistivity_copper|approximately|1_68e_minus_8_ohm_m|1.0
electrical_resistivity_silver|approximately|1_59e_minus_8_ohm_m|1.0
youngs_modulus_steel|approximately|200_gpa|1.0
tensile_strength_steel|approximately|400_to_550_mpa|1.0
