# MK Knowledge File - Computer Hardware
# Format: source|relation|target|weight
# Covers: CPUs, GPUs, RAM, storage, cooling, power supplies

# === AMD CPUS ===
amd_ryzen|is_a|cpu_brand|1.0
ryzen_5_5600x|is_a|6_core_cpu|1.0
ryzen_5_5600x|architecture|zen_3|1.0
ryzen_5_5600x|socket|am4|1.0
ryzen_5_5600x|tdp|65w|1.0
ryzen_7_5800x|is_a|8_core_cpu|1.0
ryzen_7_5800x|architecture|zen_3|1.0
ryzen_9_5900x|is_a|12_core_cpu|1.0
ryzen_9_5950x|is_a|16_core_cpu|1.0
ryzen_5_7600x|is_a|6_core_cpu|1.0
ryzen_5_7600x|architecture|zen_4|1.0
ryzen_5_7600x|socket|am5|1.0
ryzen_7_7700x|is_a|8_core_cpu|1.0
ryzen_7_7700x|architecture|zen_4|1.0
ryzen_7_7800x3d|has|3d_vcache|1.0
ryzen_7_7800x3d|best_for|gaming|0.9
ryzen_9_7900x|is_a|12_core_cpu|1.0
ryzen_9_7950x|is_a|16_core_cpu|1.0
ryzen_9_7950x3d|has|3d_vcache|1.0
amd_threadripper|is_a|hedt_cpu|1.0
amd_threadripper|cores_up_to|96|1.0
amd_epyc|is_a|server_cpu|1.0
amd_epyc|cores_up_to|128|1.0
zen_3|is_a|cpu_architecture|1.0
zen_4|is_a|cpu_architecture|1.0
zen_4|uses|5nm_process|1.0
zen_5|is_a|cpu_architecture|1.0
am4_socket|supports|ryzen_3000_to_5000|1.0
am5_socket|supports|ryzen_7000_plus|1.0
am5_socket|uses|ddr5_and_pcie_5|1.0

# === INTEL CPUS ===
intel_core|is_a|cpu_brand|1.0
i5_12600k|is_a|hybrid_cpu|1.0
i5_12600k|architecture|alder_lake|1.0
i5_12600k|has|p_cores_and_e_cores|1.0
i7_12700k|is_a|12th_gen_cpu|1.0
i9_12900k|is_a|12th_gen_flagship|1.0
i5_13600k|is_a|13th_gen_cpu|1.0
i5_13600k|architecture|raptor_lake|1.0
i7_13700k|is_a|13th_gen_cpu|1.0
i9_13900k|is_a|13th_gen_flagship|1.0
i9_13900k|cores|24_total_8p_16e|1.0
i5_14600k|is_a|14th_gen_cpu|1.0
i7_14700k|is_a|14th_gen_cpu|1.0
i9_14900k|is_a|14th_gen_flagship|1.0
intel_lga1700|supports|12th_13th_14th_gen|1.0
intel_lga1851|supports|arrow_lake|1.0
intel_xeon|is_a|server_cpu|1.0
alder_lake|is_a|hybrid_architecture|1.0
raptor_lake|is_a|refined_alder_lake|1.0
p_core|is_a|performance_core|1.0
e_core|is_a|efficiency_core|1.0
intel_thread_director|manages|core_scheduling|1.0
intel_7_process|is|10nm_enhanced|1.0
intel_4_process|is|7nm_equivalent|1.0

# === ARM AND APPLE ===
arm|is_a|risc_architecture|1.0
arm|dominates|mobile_processors|1.0
arm|power_efficient|compared_to_x86|0.9
apple_m1|is_a|arm_soc|1.0
apple_m1|has|unified_memory|1.0
apple_m2|is_a|arm_soc|1.0
apple_m2|uses|5nm_process|1.0
apple_m3|is_a|arm_soc|1.0
apple_m3|uses|3nm_process|1.0
apple_m3_pro|has|12_cpu_cores|1.0
apple_m3_max|has|16_cpu_cores|1.0
apple_m3_ultra|has|32_cpu_cores|1.0
qualcomm_snapdragon|is_a|mobile_soc|1.0
qualcomm_snapdragon_x_elite|targets|pc_laptops|1.0
arm_cortex_a|is_a|application_processor|1.0
arm_neoverse|is_a|server_processor|1.0
aws_graviton|is_a|arm_server_chip|1.0

# === GPUS AMD ===
amd_radeon|is_a|gpu_brand|1.0
rx_6600|is_a|rdna2_gpu|1.0
rx_6600|vram|8gb_gddr6|1.0
rx_6700_xt|is_a|rdna2_gpu|1.0
rx_6700_xt|vram|12gb_gddr6|1.0
rx_6800|is_a|rdna2_gpu|1.0
rx_6800_xt|is_a|rdna2_gpu|1.0
rx_6900_xt|is_a|rdna2_flagship|1.0
rx_7600|is_a|rdna3_gpu|1.0
rx_7600|vram|8gb_gddr6|1.0
rx_7700_xt|is_a|rdna3_gpu|1.0
rx_7800_xt|is_a|rdna3_gpu|1.0
rx_7800_xt|vram|16gb_gddr6|1.0
rx_7900_xt|is_a|rdna3_gpu|1.0
rx_7900_xtx|is_a|rdna3_flagship|1.0
rx_7900_xtx|vram|24gb_gddr6|1.0
rdna2|is_a|gpu_architecture|1.0
rdna3|is_a|gpu_architecture|1.0
rdna3|uses|chiplet_design|1.0
fsr|stands_for|fidelityfx_super_resolution|1.0
fsr|is_a|upscaling_technology|1.0

# === GPUS NVIDIA ===
nvidia_geforce|is_a|gpu_brand|1.0
rtx_3060|is_a|ampere_gpu|1.0
rtx_3060|vram|12gb_gddr6|1.0
rtx_3070|is_a|ampere_gpu|1.0
rtx_3080|is_a|ampere_gpu|1.0
rtx_3080|vram|10gb_gddr6x|1.0
rtx_3090|is_a|ampere_flagship|1.0
rtx_3090|vram|24gb_gddr6x|1.0
rtx_4060|is_a|ada_lovelace_gpu|1.0
rtx_4060|vram|8gb_gddr6|1.0
rtx_4070|is_a|ada_lovelace_gpu|1.0
rtx_4070_super|is_a|ada_lovelace_gpu|1.0
rtx_4080|is_a|ada_lovelace_gpu|1.0
rtx_4080|vram|16gb_gddr6x|1.0
rtx_4090|is_a|ada_lovelace_flagship|1.0
rtx_4090|vram|24gb_gddr6x|1.0
rtx_4090|cuda_cores|16384|1.0
ampere|is_a|nvidia_architecture|1.0
ada_lovelace|is_a|nvidia_architecture|1.0
dlss|stands_for|deep_learning_super_sampling|1.0
dlss|uses|ai_upscaling|1.0
dlss_3|has|frame_generation|1.0
ray_tracing|simulates|realistic_lighting|1.0
tensor_cores|accelerate|ai_workloads|1.0
rt_cores|accelerate|ray_tracing|1.0
nvidia_a100|is_a|datacenter_gpu|1.0
nvidia_h100|is_a|datacenter_gpu|1.0
nvidia_h100|architecture|hopper|1.0

# === RAM ===
ddr4|is_a|memory_type|1.0
ddr4|speeds|2133_to_5333_mhz|1.0
ddr4|voltage|1.2v|1.0
ddr4|common_speed|3200_3600_mhz|1.0
ddr5|is_a|memory_type|1.0
ddr5|speeds|4800_to_8400_plus_mhz|1.0
ddr5|voltage|1.1v|1.0
ddr5|has|on_die_ecc|1.0
ddr5|advantage|higher_bandwidth|1.0
ecc_memory|detects_and_corrects|single_bit_errors|1.0
ecc_memory|required_for|servers|1.0
dual_channel|doubles|memory_bandwidth|1.0
quad_channel|quadruples|memory_bandwidth|1.0
ram_timings|expressed_as|cl_trcd_trp_tras|1.0
cas_latency|measures|column_access_time|1.0
lower_cas_latency|is|better_for_performance|1.0
xmp|stands_for|extreme_memory_profile|1.0
xmp|enables|rated_speed_in_bios|1.0
expo|is_a|amd_xmp_equivalent|1.0
dimm|stands_for|dual_inline_memory_module|1.0
sodimm|used_in|laptops|1.0
ram_ranks|affect|interleaving|1.0
memory_controller|on|cpu_die|1.0
infinity_fabric|connects|amd_cpu_components|1.0
infinity_fabric|speed|tied_to_memory_speed|0.9

# === STORAGE ===
nvme|is_a|storage_protocol|1.0
nvme|uses|pcie_interface|1.0
nvme_gen3|max_speed|3500_MB_s|1.0
nvme_gen4|max_speed|7000_MB_s|1.0
nvme_gen5|max_speed|14000_MB_s|1.0
m2_form_factor|size|2280_most_common|1.0
sata_ssd|max_speed|550_MB_s|1.0
sata_ssd|interface|6gbps|1.0
hdd|is_a|mechanical_storage|1.0
hdd|capacity|up_to_24TB|1.0
hdd|speed|5400_or_7200_rpm|1.0
hdd|best_for|bulk_storage|0.9
raid_0|stripes|data_across_drives|1.0
raid_0|no|redundancy|1.0
raid_1|mirrors|data_on_two_drives|1.0
raid_5|stripes_with|distributed_parity|1.0
raid_5|minimum_drives|3|1.0
raid_6|has|double_parity|1.0
raid_10|combines|mirroring_and_striping|1.0
tlc_nand|stores|3_bits_per_cell|1.0
qlc_nand|stores|4_bits_per_cell|1.0
slc_nand|stores|1_bit_per_cell|1.0
slc_nand|most_durable|highest_endurance|1.0
dram_cache|on_ssd|improves_performance|1.0
trim_command|maintains|ssd_performance|1.0
wear_leveling|extends|ssd_lifespan|1.0
tbw|stands_for|terabytes_written|1.0
tbw|measures|ssd_endurance|1.0

# === COOLING ===
air_cooling|uses|heatsink_and_fan|1.0
tower_cooler|is_a|air_cooling_type|1.0
noctua_nh_d15|is_a|top_air_cooler|0.9
aio_cooler|stands_for|all_in_one_liquid|1.0
aio_cooler|has|radiator_pump_block|1.0
aio_sizes|include|120_240_280_360mm|1.0
custom_loop|is_a|liquid_cooling_type|1.0
custom_loop|components|reservoir_pump_blocks_radiators|1.0
thermal_paste|transfers|heat_to_cooler|1.0
thermal_paste|apply|pea_size_dot|0.9
liquid_metal|is_a|thermal_interface|1.0
liquid_metal|better_than|thermal_paste|0.9
liquid_metal|risk|electrically_conductive|0.8
tdp|stands_for|thermal_design_power|1.0
tdp|measures|heat_output|1.0
case_airflow|important_for|component_cooling|1.0
positive_pressure|prevents|dust_buildup|0.8
fan_curve|adjusts|speed_based_on_temperature|1.0
pwm_fan|has|variable_speed_control|1.0
delidding|replaces|ihs_thermal_interface|0.8

# === POWER SUPPLIES ===
psu|stands_for|power_supply_unit|1.0
80_plus|certifies|efficiency_levels|1.0
80_plus_gold|efficiency|87_to_90_percent|1.0
80_plus_platinum|efficiency|89_to_92_percent|1.0
80_plus_titanium|efficiency|90_to_94_percent|1.0
modular_psu|has|detachable_cables|1.0
semi_modular_psu|has|some_detachable_cables|1.0
atx_3_0|supports|12vhpwr_connector|1.0
12vhpwr|powers|rtx_4000_series|1.0
psu_wattage|should_exceed|system_draw_by_20_percent|0.9
single_rail|one|12v_output|1.0
multi_rail|splits|12v_into_sections|1.0
ups|stands_for|uninterruptible_power_supply|1.0
ups|protects_against|power_outages|1.0
surge_protector|protects_against|voltage_spikes|1.0

# === MOTHERBOARDS ===
motherboard|connects|all_components|1.0
atx|is_a|form_factor|1.0
atx|size|305x244mm|1.0
micro_atx|is_a|form_factor|1.0
micro_atx|size|244x244mm|1.0
mini_itx|is_a|form_factor|1.0
mini_itx|size|170x170mm|1.0
chipset|manages|io_and_connectivity|1.0
intel_z790|is_a|chipset|1.0
intel_z790|supports|overclocking|1.0
intel_b760|is_a|chipset|1.0
amd_x670e|is_a|chipset|1.0
amd_x670e|supports|pcie_5_everywhere|1.0
amd_b650|is_a|chipset|1.0
vrm|stands_for|voltage_regulator_module|1.0
vrm|powers|cpu|1.0
vrm_phases|more|better_power_delivery|0.9
bios|is_a|firmware|1.0
uefi|replaces|legacy_bios|1.0
pcie_slots|connect|gpus_and_cards|1.0
pcie_5_0|bandwidth|32_GT_s_per_lane|1.0
pcie_4_0|bandwidth|16_GT_s_per_lane|1.0
m2_slot|connects|nvme_ssd|1.0
sata_port|connects|sata_devices|1.0
usb_header|provides|front_panel_usb|1.0
thunderbolt|provides|40_gbps_connectivity|1.0
usb4|provides|40_gbps_compatible_with_tb3|1.0

# === MONITORS AND DISPLAYS ===
resolution_1080p|is|1920x1080|1.0
resolution_1440p|is|2560x1440|1.0
resolution_4k|is|3840x2160|1.0
resolution_ultrawide|is|3440x1440|1.0
refresh_rate|measured_in|hz|1.0
144hz|popular_for|gaming|0.9
240hz|popular_for|competitive_gaming|0.9
response_time|measured_in|milliseconds|1.0
ips_panel|has|good_colors_and_angles|1.0
va_panel|has|good_contrast|1.0
tn_panel|has|fast_response_time|1.0
oled_panel|has|perfect_blacks|1.0
hdr|stands_for|high_dynamic_range|1.0
freesync|is_a|adaptive_sync_technology|1.0
gsync|is_a|nvidia_adaptive_sync|1.0
displayport|is_a|video_connector|1.0
hdmi|is_a|video_connector|1.0
dp_2_1|supports|4k_240hz|1.0
hdmi_2_1|supports|4k_120hz|1.0

# === PERIPHERALS ===
mechanical_keyboard|uses|individual_switches|1.0
cherry_mx_red|is_a|linear_switch|1.0
cherry_mx_blue|is_a|clicky_switch|1.0
cherry_mx_brown|is_a|tactile_switch|1.0
optical_mouse|uses|led_or_laser_sensor|1.0
dpi|stands_for|dots_per_inch|1.0
polling_rate|measured_in|hz|1.0
1000hz_polling|means|1ms_response|1.0
usb_c|is_a|universal_connector|1.0
usb_3_2_gen2|speed|10_gbps|1.0
usb_3_2_gen2x2|speed|20_gbps|1.0
wifi_6e|supports|6_ghz_band|1.0
pcie_wifi_card|provides|wifi_to_desktop|1.0
ethernet|provides|wired_networking|1.0
2_5gbe|speed|2500_mbps|1.0
10gbe|speed|10000_mbps|1.0
sound_card|provides|audio_processing|1.0
dac|stands_for|digital_to_analog_converter|1.0

# === BENCHMARKING ===
cinebench|benchmarks|cpu_rendering|1.0
cinebench_r23|is|current_version|1.0
geekbench|benchmarks|cpu_performance|1.0
geekbench|tests|single_and_multi_core|1.0
3dmark|benchmarks|gpu_performance|1.0
timespy|is_a|3dmark_test|1.0
firestrike|is_a|3dmark_test|1.0
crystaldiskmark|benchmarks|storage_speed|1.0
memtest86|tests|ram_stability|1.0
furmark|stress_tests|gpu|1.0
prime95|stress_tests|cpu|1.0
aida64|monitors|system_components|1.0
hwinfo|monitors|hardware_sensors|1.0
fps|stands_for|frames_per_second|1.0
frame_time|measures|individual_frame_duration|1.0
1_percent_low|measures|worst_frame_times|1.0
bottleneck|occurs_when|one_component_limits_others|1.0
cpu_bottleneck|gpu_underutilized|cpu_at_100|1.0
gpu_bottleneck|gpu_at_100|cpu_has_headroom|1.0
thermal_throttling|reduces|performance_at_high_temp|1.0
power_throttling|reduces|performance_at_power_limit|1.0

# === BUILDING AND OVERCLOCKING ===
overclocking|increases|clock_speed_beyond_stock|1.0
overclocking|requires|adequate_cooling|1.0
overclocking|risk|instability_and_heat|0.8
multiplier_overclocking|changes|cpu_multiplier|1.0
bclk_overclocking|changes|base_clock|1.0
gpu_overclocking|increases|core_and_memory_clock|1.0
undervolting|reduces|voltage_for_efficiency|1.0
undervolting|reduces|heat_and_power|0.9
silicon_lottery|means|chip_quality_varies|0.8
binning|selects|best_chips_for_higher_skus|1.0
stress_testing|validates|overclock_stability|1.0
blue_screen|indicates|system_instability|0.8
event_viewer|logs|system_errors|1.0
cable_management|improves|airflow_and_aesthetics|0.8
standoff_screws|prevent|motherboard_shorting|1.0
io_shield|covers|rear_motherboard_ports|1.0
anti_static|prevents|esd_damage|1.0
thermal_pad|transfers_heat_from|vrm_and_m2|1.0
fan_splitter|connects|multiple_fans_to_header|1.0
rgb_header|controls|rgb_lighting|1.0
argb|stands_for|addressable_rgb|1.0
pcie_riser|extends|gpu_mounting_position|1.0

# === NETWORKING HARDWARE ===
router|manages|home_network|1.0
managed_switch|allows|vlan_and_qos_config|1.0
unmanaged_switch|provides|basic_connectivity|1.0
access_point|extends|wifi_coverage|1.0
mesh_wifi|uses|multiple_nodes|1.0
poe|stands_for|power_over_ethernet|1.0
poe|powers|devices_through_cable|1.0
nas|stands_for|network_attached_storage|1.0
nas|provides|shared_storage|1.0
synology|is_a|nas_brand|1.0
qnap|is_a|nas_brand|1.0
truenas|is_a|nas_os|1.0

# === SERVER HARDWARE ===
rack_server|is_a|server_form_factor|1.0
blade_server|is_a|compact_server|1.0
tower_server|is_a|standalone_server|1.0
1u_server|height|44.45mm|1.0
2u_server|allows|more_drives_and_gpus|1.0
ipmi|provides|remote_management|1.0
ilo|is_a|hp_remote_management|1.0
idrac|is_a|dell_remote_management|1.0
hot_swap|allows|drive_replacement_without_shutdown|1.0
redundant_psu|provides|power_failover|1.0
ecc_ram|required_for|data_integrity|1.0
registered_dimm|supports|higher_capacity|1.0
lrdimm|supports|even_higher_capacity|1.0
numa|stands_for|non_uniform_memory_access|1.0
numa|affects|multi_socket_performance|1.0
pcie_bifurcation|splits|slot_into_multiple|1.0
nvme_u2|is_a|enterprise_ssd_form_factor|1.0
sas_interface|used_in|enterprise_storage|1.0
sas_speed|12_gbps|current_gen|1.0
backplane|connects|drives_to_controller|1.0
hba|stands_for|host_bus_adapter|1.0
raid_controller|hardware|offloads_raid_calculation|1.0
bmc|stands_for|baseboard_management_controller|1.0
kvm_switch|shares|keyboard_video_mouse|1.0
pdu|stands_for|power_distribution_unit|1.0
ups_runtime|depends_on|battery_capacity_and_load|1.0
datacenter_cooling|methods|air_liquid_immersion|1.0
pue|stands_for|power_usage_effectiveness|1.0
pue|ideal|close_to_1_0|1.0

# === EMBEDDED AND IOT ===
raspberry_pi|is_a|single_board_computer|1.0
raspberry_pi_5|has|bcm2712_soc|1.0
arduino|is_a|microcontroller_platform|1.0
esp32|is_a|wifi_microcontroller|1.0
esp32|supports|wifi_and_bluetooth|1.0
fpga|stands_for|field_programmable_gate_array|1.0
fpga|configurable|hardware_logic|1.0
asic|stands_for|application_specific_integrated_circuit|1.0
gpio|stands_for|general_purpose_input_output|1.0
i2c|is_a|serial_communication_protocol|1.0
spi|is_a|serial_communication_protocol|1.0
uart|is_a|serial_communication_protocol|1.0
pwm|stands_for|pulse_width_modulation|1.0
adc|stands_for|analog_to_digital_converter|1.0

# === ADDITIONAL UNIQUE HARDWARE FACTS ===
cpu_cache_l1|size|typically_64kb_per_core|1.0
cpu_cache_l2|size|typically_256kb_to_1mb_per_core|1.0
cpu_cache_l3|size|typically_8mb_to_64mb_shared|1.0
cache_line|size|typically_64_bytes|1.0
branch_predictor|reduces|pipeline_stalls|1.0
out_of_order_execution|improves|instruction_throughput|1.0
speculative_execution|executes|before_branch_resolved|1.0
instruction_pipeline|overlaps|fetch_decode_execute|1.0
simd|stands_for|single_instruction_multiple_data|1.0
avx_512|is_a|simd_extension|1.0
neon|is_a|arm_simd_extension|1.0
hyper_threading|allows|two_threads_per_core|1.0
smt|stands_for|simultaneous_multithreading|1.0
ipc|stands_for|instructions_per_clock|1.0
clock_speed|measured_in|ghz|1.0
turbo_boost|increases|clock_temporarily|1.0
precision_boost|is_a|amd_turbo_technology|1.0
pbo|stands_for|precision_boost_overdrive|1.0
curve_optimizer|reduces|voltage_per_core|1.0
undervolt|reduces|power_and_heat|1.0
chiplet_design|uses|multiple_dies_per_package|1.0
monolithic_die|is|single_piece_of_silicon|1.0
infinity_cache|is_a|amd_large_l3_cache|1.0
3d_vcache|stacks|additional_cache_vertically|1.0
process_node|measured_in|nanometers|1.0
tsmc_3nm|used_by|apple_m3|1.0
tsmc_4nm|used_by|zen_4|1.0
samsung_foundry|manufactures|chips|1.0
intel_foundry|manufactures|chips|1.0
euv_lithography|enables|sub_7nm_manufacturing|1.0
transistor_count|modern_cpu|billions|1.0
die_size|affects|manufacturing_cost|1.0
yield_rate|percentage|good_dies_per_wafer|1.0
wafer|is|silicon_disc_for_chip_manufacturing|1.0
photomask|patterns|circuits_onto_silicon|1.0
copper_interconnect|connects|transistors|1.0
power_delivery|network_on_die|distributes_voltage|1.0
voltage_island|independent|power_domain|1.0
dark_silicon|transistors|not_all_active_simultaneously|1.0
heterogeneous_computing|combines|different_processor_types|1.0
dsp|stands_for|digital_signal_processor|1.0
npu|stands_for|neural_processing_unit|1.0
isp|stands_for|image_signal_processor|1.0
soc|stands_for|system_on_chip|1.0
soc|integrates|cpu_gpu_memory_io|1.0
memory_fabric|connects|chiplets_and_memory|1.0
ucie|stands_for|universal_chiplet_interconnect_express|1.0
cxl|stands_for|compute_express_link|1.0
cxl|enables|memory_pooling_and_sharing|1.0
gen_z|is_a|fabric_interconnect|1.0
coherency_protocol|ensures|cache_consistency|1.0
mesi_protocol|states|modified_exclusive_shared_invalid|1.0
moesi_protocol|adds|owned_state|1.0
snoop_filter|reduces|coherency_traffic|1.0
directory_based_coherence|scales|better_than_snooping|1.0
memory_channel|provides|independent_access_path|1.0
interleaving|distributes|data_across_channels|1.0
rank|is_a|memory_access_unit|1.0
bank|is_a|memory_subdivision|1.0
refresh_rate|dram|must_refresh_periodically|1.0
rowhammer|exploits|dram_disturbance_errors|1.0
ecc_detection|catches|memory_bit_flips|1.0
