# MK Knowledge File - Practical Skills for Productivity and Communication
# Format: source|relation|target|weight
# Covers: project management, communication, productivity, problem-solving

# === PROJECT MANAGEMENT ===
agile|is_a|project_methodology|1.0
agile|values|individuals_over_processes|1.0
agile|values|working_software_over_documentation|1.0
agile|values|responding_to_change|1.0
scrum|is_a|agile_framework|1.0
scrum|has|sprints_of_1_to_4_weeks|1.0
scrum|roles|product_owner_scrum_master_developers|1.0
scrum|ceremonies|planning_daily_review_retrospective|1.0
sprint_planning|defines|sprint_goals_and_backlog|1.0
daily_standup|is|15_minute_sync|1.0
sprint_review|demonstrates|completed_work|1.0
retrospective|improves|team_process|1.0
product_backlog|ordered_list_of|requirements|1.0
user_story|format|as_a_user_i_want_so_that|1.0
story_points|estimate|relative_effort|1.0
velocity|measures|team_throughput|1.0
burndown_chart|shows|remaining_work|1.0
kanban|is_a|visual_workflow_method|1.0
kanban|uses|board_with_columns|1.0
kanban|principle|limit_work_in_progress|1.0
kanban|principle|pull_not_push|1.0
wip_limit|prevents|multitasking_overload|1.0
lead_time|measures|request_to_delivery|1.0
cycle_time|measures|start_to_finish|1.0
waterfall|is_a|sequential_methodology|1.0
waterfall|phases|requirements_design_build_test_deploy|1.0
lean|eliminates|waste_in_processes|1.0
lean|principles|value_stream_flow_pull_perfection|1.0
mvp|stands_for|minimum_viable_product|1.0
mvp|tests|hypothesis_with_minimal_effort|1.0
estimation|techniques|planning_poker_t_shirt_sizing|1.0
planning_poker|uses|consensus_based_estimation|1.0
cone_of_uncertainty|estimates|more_accurate_over_time|1.0
scope_creep|is|uncontrolled_expansion_of_work|1.0
scope_creep|prevented_by|clear_requirements|0.9
stakeholder_management|keeps|stakeholders_informed|1.0
risk_management|identifies|and_mitigates_risks|1.0
risk_matrix|plots|probability_vs_impact|1.0
critical_path|determines|minimum_project_duration|1.0
gantt_chart|shows|task_timeline|1.0
dependency_management|tracks|task_relationships|1.0
milestone|marks|significant_achievement|1.0
definition_of_done|criteria_for|complete_work|1.0
acceptance_criteria|defines|what_success_looks_like|1.0
technical_debt|is|shortcuts_that_need_fixing|1.0
refactoring|improves|code_without_changing_behavior|1.0

# === COMMUNICATION SKILLS ===
active_listening|gives|full_attention_to_speaker|1.0
active_listening|includes|paraphrasing_and_asking_questions|1.0
empathy|understands|others_perspective|1.0
nonverbal_communication|includes|body_language_tone_gesture|1.0
eye_contact|shows|engagement_and_confidence|0.9
open_body_language|signals|receptiveness|0.8
mirroring|builds|rapport|0.8
feedback|should_be|specific_actionable_timely|1.0
sandwich_feedback|structure|positive_constructive_positive|0.8
radical_candor|combines|caring_personally_and_challenging_directly|1.0
difficult_conversations|framework|describe_express_specify|1.0
conflict_resolution|steps|identify_discuss_agree|1.0
win_win_negotiation|both_parties|benefit|1.0
batna|stands_for|best_alternative_to_negotiated_agreement|1.0
anchoring_in_negotiation|first_offer|sets_expectations|1.0
concession|should_be|reciprocal_and_gradual|0.9
storytelling|engages|audience_emotionally|1.0
narrative_structure|has|beginning_middle_end|1.0
presentation_skills|include|clear_structure_practice|1.0
rule_of_three|groups_info|in_threes_for_memory|0.9
elevator_pitch|is|30_second_value_proposition|1.0
public_speaking|requires|preparation_and_practice|1.0
audience_awareness|adapts|message_to_audience|1.0
persuasion|techniques|ethos_pathos_logos|1.0
ethos|is|credibility_appeal|1.0
pathos|is|emotional_appeal|1.0
logos|is|logical_appeal|1.0
written_communication|should_be|clear_concise_complete|1.0
email_etiquette|includes|clear_subject_brief_body|1.0
meeting_effectiveness|requires|agenda_facilitator_actions|1.0
standup_format|covers|yesterday_today_blockers|1.0
documentation|should_be|up_to_date_and_findable|1.0

# === PRODUCTIVITY SYSTEMS ===
gtd|stands_for|getting_things_done|1.0
gtd|steps|capture_clarify_organize_reflect_engage|1.0
gtd|principle|get_tasks_out_of_head|1.0
pomodoro_technique|works_in|25_minute_focused_blocks|1.0
pomodoro_technique|includes|5_minute_breaks|1.0
pomodoro_technique|after_4|take_longer_break|1.0
time_blocking|assigns|specific_hours_to_tasks|1.0
time_blocking|prevents|context_switching|0.9
deep_work|is|focused_undistracted_work|1.0
deep_work|coined_by|cal_newport|1.0
deep_work|requires|eliminating_distractions|1.0
shallow_work|is|logistical_low_value_tasks|1.0
eisenhower_matrix|categorizes|urgent_important|1.0
eisenhower_matrix|quadrants|do_schedule_delegate_eliminate|1.0
eat_the_frog|do|hardest_task_first|1.0
two_minute_rule|do_immediately|if_under_2_minutes|1.0
batching|groups|similar_tasks_together|1.0
single_tasking|focuses_on|one_thing_at_a_time|1.0
multitasking|reduces|productivity_by_40_percent|0.8
context_switching|costs|up_to_23_minutes_to_refocus|0.9
inbox_zero|processes|all_messages_to_zero|1.0
weekly_review|reflects|on_progress_and_plans|1.0
habit_stacking|links|new_habit_to_existing|1.0
implementation_intention|specifies|when_where_how|1.0
environment_design|removes|friction_for_good_habits|1.0
temptation_bundling|pairs|pleasure_with_productivity|1.0
accountability_partner|increases|follow_through|0.8
morning_routine|sets|tone_for_productive_day|0.9
energy_management|works_with|natural_energy_cycles|1.0
ultradian_rhythm|cycles|of_90_minute_focus|0.8
digital_minimalism|reduces|technology_distraction|1.0
notification_management|turns_off|non_essential_alerts|0.9
second_brain|externalizes|knowledge_and_ideas|1.0
zettelkasten|is_a|note_taking_method|1.0
zettelkasten|uses|interconnected_notes|1.0
personal_knowledge_management|organizes|information_for_retrieval|1.0
spaced_repetition|optimizes|learning_retention|1.0
feynman_technique|explains|concepts_simply|1.0
active_recall|tests|memory_without_looking|1.0

# === PROBLEM-SOLVING FRAMEWORKS ===
first_principles|breaks_down|to_fundamental_truths|1.0
first_principles|rebuilds|from_ground_up|1.0
first_principles|used_by|elon_musk|0.8
five_whys|asks_why|five_times_to_find_root|1.0
five_whys|developed_by|toyota|1.0
root_cause_analysis|identifies|underlying_problem|1.0
fishbone_diagram|organizes|causes_by_category|1.0
fishbone_diagram|also_called|ishikawa_diagram|1.0
pareto_principle|states|80_percent_from_20_percent|1.0
pareto_analysis|focuses_on|highest_impact_items|1.0
swot_analysis|examines|strengths_weaknesses_opportunities_threats|1.0
design_thinking|stages|empathize_define_ideate_prototype_test|1.0
design_thinking|human_centered|problem_solving|1.0
hypothesis_driven|starts_with|proposed_explanation|1.0
systems_thinking|sees|interconnections_not_parts|1.0
systems_thinking|identifies|feedback_loops|1.0
lateral_thinking|approaches|problem_from_new_angle|1.0
lateral_thinking|coined_by|edward_de_bono|1.0
six_thinking_hats|examines|problem_from_six_angles|1.0
inversion|asks|what_would_make_this_fail|1.0
inversion|then|avoids_those_things|1.0
decomposition|breaks|big_problem_into_small_parts|1.0
abstraction|removes|unnecessary_detail|1.0
analogy|applies|solution_from_similar_domain|1.0
brainstorming|generates|many_ideas_without_judgment|1.0
brainwriting|writes|ideas_silently_then_shares|1.0
mind_mapping|visually|organizes_related_concepts|1.0
decision_matrix|scores|options_against_criteria|1.0
pro_con_list|weighs|advantages_and_disadvantages|1.0
cost_benefit_analysis|compares|costs_to_benefits|1.0
opportunity_cost|considers|what_you_give_up|1.0
reversibility|considers|can_decision_be_undone|1.0
one_way_door|irreversible|requires_careful_analysis|1.0
two_way_door|reversible|decide_quickly|1.0
premature_optimization|is|root_of_all_evil|0.8
rubber_duck_debugging|explains|problem_to_find_solution|1.0
socratic_method|asks|questions_to_find_truth|1.0
scientific_method|hypothesis|experiment_analyze_conclude|1.0
trial_and_error|iterates|until_solution_found|1.0

# === LEARNING SKILLS ===
growth_mindset|believes|abilities_improve_with_effort|1.0
deliberate_practice|targets|specific_weaknesses|1.0
deliberate_practice|requires|feedback_and_challenge|1.0
ten_thousand_hours|myth|mastery_requires_quality_not_just_time|0.7
interleaving|mixes|different_topics_while_studying|1.0
elaboration|connects|new_knowledge_to_existing|1.0
metacognition|is|thinking_about_thinking|1.0
chunking|groups|information_into_meaningful_units|1.0
mnemonic_devices|aid|memory_recall|1.0
method_of_loci|associates|info_with_locations|1.0
teaching_others|deepens|own_understanding|1.0
bloom_taxonomy|levels|remember_understand_apply_analyze_evaluate_create|1.0
zone_of_proximal_development|learning|just_beyond_current_ability|1.0
scaffolding|provides|temporary_support_for_learning|1.0
retrieval_practice|strengthens|memory_through_testing|1.0

# === LEADERSHIP AND MANAGEMENT ===
servant_leadership|puts|team_needs_first|1.0
situational_leadership|adapts|style_to_context|1.0
transformational_leadership|inspires|through_vision|1.0
psychological_safety|allows|taking_risks_without_fear|1.0
one_on_one|meeting|for_coaching_and_support|1.0
delegation|assigns|tasks_with_authority|1.0
micromanagement|controls|every_detail|1.0
micromanagement|reduces|motivation_and_trust|0.9
trust_building|requires|consistency_and_transparency|1.0
team_building|stages|forming_storming_norming_performing|1.0
diversity_of_thought|improves|decision_quality|0.9
inclusive_leadership|values|all_perspectives|1.0
coaching|develops|individual_capability|1.0
mentoring|shares|experience_and_guidance|1.0
performance_review|evaluates|work_quality_and_growth|1.0
okr|stands_for|objectives_and_key_results|1.0
okr|aligns|team_to_company_goals|1.0
kpi|stands_for|key_performance_indicator|1.0
smart_goals|are|specific_measurable_achievable_relevant_time_bound|1.0
north_star_metric|guides|overall_direction|1.0

# === CAREER DEVELOPMENT ===
resume|should_be|tailored_to_job|1.0
cover_letter|explains|why_you_fit|1.0
networking|builds|professional_relationships|1.0
informational_interview|learns|about_career_path|1.0
personal_brand|communicates|unique_value|1.0
portfolio|demonstrates|actual_work_quality|1.0
salary_negotiation|research|market_rate_first|1.0
interview_preparation|includes|research_practice_questions|1.0
star_method|structures|behavioral_answers|1.0
star_method|stands_for|situation_task_action_result|1.0
continuous_learning|keeps|skills_relevant|1.0
t_shaped_skills|deep_expertise|plus_broad_knowledge|1.0
side_project|builds|skills_and_portfolio|1.0
open_source_contribution|demonstrates|collaboration_skills|1.0
imposter_syndrome|common_among|high_achievers|0.8

# === NEGOTIATION ===
negotiation|is_a|collaborative_problem_solving|1.0
preparation|most_important|negotiation_step|1.0
zopa|stands_for|zone_of_possible_agreement|1.0
reservation_price|is|walk_away_point|1.0
aspiration_price|is|best_hoped_outcome|1.0
value_creation|expands|pie_before_dividing|1.0
logrolling|trades|concessions_on_different_issues|1.0
principled_negotiation|separates|people_from_problem|1.0
interest_based|focuses_on|why_not_what|1.0
silence|is|powerful_negotiation_tool|0.9
best_alternative|strengthens|negotiation_position|1.0
walk_away_power|is|willingness_to_leave|1.0
rapport_building|creates|trust_before_negotiating|1.0
deadline_pressure|forces|decisions|0.8
package_deal|bundles|multiple_issues_together|1.0

# === CREATIVE THINKING ===
divergent_thinking|generates|many_ideas|1.0
convergent_thinking|selects|best_idea|1.0
creative_constraints|paradoxically|increase_creativity|0.8
cross_pollination|applies|ideas_from_other_fields|1.0
incubation|unconscious|processing_of_problem|1.0
eureka_moment|sudden|insight_after_incubation|0.8
random_input|technique|uses_random_word_as_stimulus|1.0
scamper|technique|substitute_combine_adapt_modify_put_eliminate_reverse|1.0
reframing|sees|problem_from_different_angle|1.0
assumption_challenging|questions|underlying_beliefs|1.0
provocative_operation|deliberately|makes_absurd_statement|0.8
forced_connections|links|unrelated_concepts|1.0
bisociation|combines|two_unrelated_frames|1.0
serendipity|is|fortunate_accidental_discovery|0.8
beginner_mind|approaches|without_preconceptions|1.0
fail_fast|tests|ideas_quickly_cheaply|1.0
iteration|improves|through_repeated_cycles|1.0
prototyping|creates|quick_testable_version|1.0
minimum_viable_experiment|tests|assumption_cheaply|1.0
pivot|changes|direction_based_on_learning|1.0

# === EMOTIONAL MANAGEMENT ===
emotional_regulation|manages|responses_to_emotions|1.0
self_awareness|recognizes|own_emotions_and_triggers|1.0
triggers|are|events_that_provoke_reactions|1.0
response_vs_reaction|response_is|considered_and_chosen|1.0
breathing_exercises|activate|parasympathetic_system|1.0
journaling|processes|emotions_through_writing|1.0
gratitude_practice|improves|wellbeing_and_perspective|0.9
reappraisal|reinterprets|situation_positively|1.0
acceptance|acknowledges|emotions_without_judgment|1.0
boundaries|define|acceptable_behavior_limits|1.0
saying_no|protects|time_and_energy|1.0
assertiveness|expresses|needs_respectfully|1.0
emotional_contagion|spreads|emotions_between_people|0.8
compassion_fatigue|results_from|prolonged_empathy|0.8
work_life_balance|prevents|burnout|0.9

# === WRITING AND DOCUMENTATION ===
technical_writing|is|clear_precise_purposeful|1.0
audience_analysis|determines|level_of_detail|1.0
structure|should_be|logical_and_scannable|1.0
headings|help|readers_navigate|1.0
bullet_points|present|concise_information|1.0
diagrams|explain|complex_concepts_visually|1.0
readme|explains|project_purpose_and_setup|1.0
changelog|records|notable_changes|1.0
api_documentation|describes|endpoints_and_usage|1.0
code_comments|explain|why_not_what|1.0
adr|stands_for|architecture_decision_record|1.0
runbook|documents|operational_procedures|1.0
style_guide|ensures|consistent_writing|1.0
plain_language|avoids|jargon_when_possible|1.0
editing|improves|clarity_after_drafting|1.0
proofreading|catches|errors_before_publishing|1.0

# === TIME MANAGEMENT ADVANCED ===
parkinsons_law|work_expands|to_fill_time_available|1.0
hofstadter_law|it_always_takes|longer_than_expected|1.0
planning_poker|consensus_based|estimation_method|1.0
velocity_tracking|predicts|future_throughput|1.0
burndown_chart|visualizes|remaining_work|1.0
timeboxing|allocates|fixed_time_to_activity|1.0
maker_schedule|needs|long_uninterrupted_blocks|1.0
manager_schedule|works_in|short_meeting_intervals|1.0
calendar_audit|reveals|where_time_goes|1.0
task_prioritization|uses|impact_effort_matrix|1.0
impact_effort_matrix|plots|value_vs_difficulty|1.0
quick_wins|high_impact|low_effort|1.0
strategic_work|high_impact|high_effort|1.0
fill_in_tasks|low_impact|low_effort|1.0
time_wasters|low_impact|high_effort|1.0
decision_fatigue|reduces|quality_of_decisions|1.0
routine|reduces|decision_fatigue|0.9
automation|eliminates|repetitive_tasks|1.0
templates|speed_up|recurring_work|1.0
checklists|prevent|skipping_steps|1.0
standard_operating_procedure|documents|how_to_do_tasks|1.0
process_improvement|continuously|optimizes_workflows|1.0
bottleneck|constrains|overall_throughput|1.0
theory_of_constraints|focuses_on|bottleneck_improvement|1.0
critical_thinking|evaluates|arguments_logically|1.0
critical_thinking|identifies|assumptions_and_biases|1.0
information_literacy|finds|evaluates_uses_information|1.0
source_evaluation|checks|credibility_bias_evidence|1.0

# === ADDITIONAL UNIQUE KNOWLEDGE ===
six_sigma|methodology_for|process_improvement|1.0
six_sigma|levels|green_belt_black_belt_master|1.0
lean_startup|build_measure_learn|cycle|1.0
business_model_canvas|visualizes|business_model|1.0
value_proposition|describes|customer_benefit|1.0
customer_discovery|validates|market_need|1.0
product_market_fit|achieved_when|customers_love_product|1.0
growth_hacking|finds|scalable_growth_channels|1.0
a_b_testing|compares|two_variants|1.0
conversion_rate|measures|desired_action_percentage|1.0
funnel_analysis|tracks|user_journey_stages|1.0
churn_rate|measures|customer_loss_rate|1.0
customer_lifetime_value|predicts|total_customer_revenue|1.0
net_promoter_score|measures|customer_loyalty|1.0
burn_rate|measures|monthly_cash_spending|1.0
runway|equals|cash_divided_by_burn_rate|1.0
pivot|changes|strategy_based_on_learning|1.0
unit_economics|calculates|profit_per_customer|1.0
moat|protects|business_from_competition|1.0
network_effect|value_increases_with|more_users|1.0
viral_coefficient|measures|organic_growth_rate|1.0
freemium|offers|basic_free_premium_paid|1.0
saas|stands_for|software_as_a_service|1.0
mrr|stands_for|monthly_recurring_revenue|1.0
arr|stands_for|annual_recurring_revenue|1.0
cac|stands_for|customer_acquisition_cost|1.0
ltv_to_cac|ratio_should_be|greater_than_3|0.9
product_led_growth|product_itself|drives_acquisition|1.0
developer_experience|measures|ease_of_using_tools|1.0
technical_interview|types|coding_system_design_behavioral|1.0
whiteboard_coding|solving|problems_live|1.0
take_home_assignment|completing|project_offline|1.0
pair_programming|two_developers|one_computer|1.0
code_review|improves|code_quality|1.0
test_driven_development|writes|tests_before_code|1.0
behavior_driven_development|specifies|behavior_in_plain_language|1.0
continuous_improvement|japanese|kaizen|1.0
retrospective|reflects|on_what_to_improve|1.0
blameless_postmortem|focuses_on|systems_not_people|1.0
root_cause|is|fundamental_underlying_issue|1.0
corrective_action|fixes|root_cause|1.0
preventive_action|prevents|future_occurrence|1.0
standard_work|documents|best_known_method|1.0
visual_management|makes|status_visible_at_glance|1.0
andon|signals|problem_requiring_attention|1.0
gemba|means|go_to_where_work_happens|1.0
value_stream_mapping|visualizes|end_to_end_process|1.0
waste_types|muda|transport_inventory_motion_waiting_overproduction_overprocessing_defects|1.0
just_in_time|produces|only_what_is_needed|1.0
pull_system|produces|based_on_demand|1.0
push_system|produces|based_on_forecast|1.0
takt_time|equals|available_time_over_demand|1.0
bottleneck_theory|constraint|limits_throughput|1.0
drum_buffer_rope|schedules|around_constraint|1.0
five_s|sort_set_shine_standardize_sustain|workplace_organization|1.0
pdca_cycle|plan_do_check_act|continuous_improvement|1.0
dmaic|define_measure_analyze_improve_control|six_sigma|1.0

# === MORE UNIQUE PRACTICAL SKILLS ===
decision_journal|records|decisions_and_reasoning|1.0
premortem_analysis|imagines|project_failed_then_why|1.0
scenario_planning|considers|multiple_possible_futures|1.0
red_team_thinking|argues|against_your_own_plan|1.0
steel_man_argument|strongest|version_of_opposing_view|1.0
fermi_estimation|approximates|unknown_quantities|1.0
back_of_envelope|calculation|quick_rough_estimate|1.0
opportunity_cost_thinking|always|considers_alternatives|1.0
second_order_thinking|considers|consequences_of_consequences|1.0
inversion_thinking|considers|what_would_make_it_fail|1.0
circle_of_competence|knows|what_you_know_and_dont|1.0
survivorship_bias_awareness|looks_for|hidden_failures|1.0
base_rate_awareness|checks|statistical_frequency|1.0
regression_to_mean|extreme_results|tend_to_normalize|1.0
correlation_not_causation|association|does_not_imply_cause|1.0
sample_size_matters|small_samples|unreliable|1.0
selection_bias_awareness|sample|may_not_represent_population|1.0
hanlons_razor|never_attribute_to_malice|what_is_explained_by_stupidity|1.0
chestertons_fence|understand_why|before_removing|1.0
lindy_effect|longer_lasted|likely_to_last_longer|1.0
antifragility|benefits_from|disorder_and_stress|1.0
optionality|having|multiple_paths_forward|1.0
asymmetric_upside|limited_downside|unlimited_upside|1.0
barbell_strategy|extreme_safety|plus_extreme_risk|1.0
skin_in_the_game|having|personal_stake_in_outcome|1.0
via_negativa|improve_by|removing_bad_things|1.0
map_is_not_territory|model|simplification_of_reality|1.0
goodharts_law|when_measure_becomes_target|ceases_to_be_good_measure|1.0
campbell_law|quantitative_indicator|distorts_process|1.0
cobra_effect|incentive|creates_opposite_result|1.0
streisand_effect|suppression|draws_more_attention|1.0
moral_licensing|good_deed|permits_subsequent_bad|1.0
observers_paradox|observing|changes_the_observed|1.0
hawthorne_effect|being_watched|changes_behavior|1.0
streetlight_effect|looking|where_it_is_easy_not_useful|1.0
bikeshedding|spending_time_on|trivial_matters|1.0
parkinson_trivial|inverse_importance|of_time_spent|1.0
yak_shaving|solving|tangential_prerequisites|1.0
analysis_paralysis|overthinking|prevents_action|1.0
premature_optimization_knuth|root_of_all_evil|focus_on_bottleneck|1.0
worse_is_better|simpler_solution|wins_adoption|0.8
minimum_effective_dose|smallest_input|for_desired_output|1.0
deliberate_ignorance|ignoring|irrelevant_information|1.0
batched_processing|reduces|cognitive_switching_cost|1.0
theme_days|dedicate|entire_day_to_one_type|1.0
maker_vs_manager|need|different_schedules|1.0
meeting_free_day|protects|deep_work_time|1.0
two_pizza_team|team_size|6_to_8_people|1.0
dunbar_number|maximum|meaningful_relationships_150|1.0
brooks_law|adding_people|to_late_project_makes_later|1.0
conway_law|systems_mirror|organization_structure|1.0
dunning_kruger_peak|of_mount|stupid|0.8
valley_of_despair|after|learning_enough_to_know_you_dont_know|0.8
plateau_of_sustainability|competence|with_realistic_expectations|0.8
1_percent_improvement_daily|compound|to_37x_in_a_year|1.0
compounding_knowledge|builds|on_previous_learning|1.0
adjacent_possible|next|achievable_innovation|1.0
serendipity_surface_area|increases_with|curiosity_and_exposure|1.0
idea_sex|combining|two_existing_ideas|1.0
creative_destruction|new|replaces_old|1.0
innovators_dilemma|success|blinds_to_disruption|1.0
blue_ocean_strategy|creates|uncontested_market_space|1.0
red_ocean_strategy|competes|in_existing_market|1.0
