# MK Knowledge File - Linux Systems, Kernel, Administration, Security
# Format: source|relation|target|weight
# Covers: kernel concepts, systemd, networking, filesystems, containers,
# package managers, shell scripting, system administration, security, processes

# === KERNEL CONCEPTS ===
linux_kernel|is_a|monolithic_kernel|1.0
linux_kernel|created_by|linus_torvalds|1.0
linux_kernel|first_released|1991|1.0
linux_kernel|written_in|c_language|1.0
linux_kernel|license|gpl_v2|1.0
kernel_module|is_a|loadable_kernel_extension|1.0
kernel_module|loaded_with|insmod_or_modprobe|1.0
kernel_module|listed_with|lsmod|1.0
kernel_module|compiled_as|.ko_file|1.0
syscall|is_a|kernel_interface|1.0
syscall|provides|userspace_to_kernel_access|1.0
syscall|examples|read_write_open_close_fork|1.0
syscall|invoked_via|software_interrupt|1.0
cgroups|is_a|kernel_feature|1.0
cgroups|controls|resource_allocation|1.0
cgroups|limits|cpu_memory_io_bandwidth|1.0
cgroups|version_2|unified_hierarchy|1.0
cgroups|used_by|containers_and_systemd|1.0
namespaces|is_a|kernel_feature|1.0
namespaces|provides|process_isolation|1.0
pid_namespace|isolates|process_id_space|1.0
net_namespace|isolates|network_stack|1.0
mount_namespace|isolates|filesystem_view|1.0
user_namespace|isolates|uid_gid_mapping|1.0
uts_namespace|isolates|hostname|1.0
ipc_namespace|isolates|interprocess_communication|1.0
cgroup_namespace|isolates|cgroup_root|1.0
kernel_ring_buffer|stores|kernel_messages|1.0
dmesg|reads|kernel_ring_buffer|1.0
procfs|is_a|virtual_filesystem|1.0
procfs|mounted_at|/proc|1.0
procfs|exposes|kernel_and_process_info|1.0
sysfs|is_a|virtual_filesystem|1.0
sysfs|mounted_at|/sys|1.0
sysfs|exposes|device_and_driver_info|1.0
kconfig|configures|kernel_build_options|1.0
initramfs|is|initial_ram_filesystem|1.0
initramfs|loads|before_root_filesystem|1.0
ebpf|is_a|kernel_technology|1.0
ebpf|allows|programmable_kernel_hooks|1.0
ebpf|used_for|tracing_networking_security|1.0
io_uring|is_a|async_io_interface|1.0
io_uring|replaces|aio_for_performance|1.0
ftrace|is_a|kernel_tracing_tool|1.0
perf|is_a|performance_analysis_tool|1.0
perf|measures|cpu_cycles_cache_misses|1.0

# === SYSTEMD ===
systemd|is_a|init_system|1.0
systemd|pid|1|1.0
systemd|manages|services_and_targets|1.0
systemd|uses|unit_files|1.0
systemd_unit|types|service_socket_timer_mount_target|1.0
service_unit|manages|daemon_processes|1.0
socket_unit|manages|ipc_network_sockets|1.0
timer_unit|is_a|cron_alternative|1.0
timer_unit|triggers|service_on_schedule|1.0
target_unit|groups|units_for_synchronization|1.0
mount_unit|manages|filesystem_mounts|1.0
slice_unit|manages|cgroup_resource_limits|1.0
systemctl|is|systemd_control_command|1.0
systemctl_start|starts|a_service|1.0
systemctl_stop|stops|a_service|1.0
systemctl_enable|enables|service_at_boot|1.0
systemctl_status|shows|service_status|1.0
systemctl_restart|restarts|a_service|1.0
systemctl_daemon_reload|reloads|unit_configurations|1.0
journald|is_a|logging_daemon|1.0
journald|stores|structured_log_data|1.0
journalctl|reads|systemd_journal|1.0
journalctl_u|filters|by_unit|1.0
journalctl_f|follows|live_output|1.0
journalctl_since|filters|by_time|1.0
systemd_resolved|manages|dns_resolution|1.0
systemd_networkd|manages|network_configuration|1.0
systemd_timesyncd|manages|time_synchronization|1.0
systemd_logind|manages|user_sessions|1.0
unit_file_location|system|/etc/systemd/system|1.0
unit_file_location|packages|/usr/lib/systemd/system|1.0
override_file|placed_in|/etc/systemd/system/unit.d/|1.0

# === NETWORKING ===
iptables|is_a|packet_filter|1.0
iptables|uses|chains_and_tables|1.0
iptables|chains|input_output_forward|1.0
iptables|tables|filter_nat_mangle_raw|1.0
nftables|is_a|packet_filter|1.0
nftables|replaces|iptables|1.0
nftables|uses|nft_command|1.0
nftables|advantage|unified_framework|1.0
tc|is_a|traffic_control_tool|1.0
tc|manages|queueing_disciplines|1.0
tc|can|shape_limit_delay_traffic|1.0
ip_route|manages|routing_table|1.0
ip_route|shows|current_routes|1.0
ip_link|manages|network_interfaces|1.0
ip_addr|manages|ip_addresses|1.0
bridge|connects|network_segments|1.0
bridge|operates_at|layer_2|1.0
veth|is_a|virtual_ethernet_pair|1.0
veth|used_for|container_networking|1.0
tun_tap|creates|virtual_network_devices|1.0
vlan|tags|ethernet_frames|1.0
vlan|uses|802.1q|1.0
bond|combines|multiple_interfaces|1.0
bond|modes|balance_rr_active_backup_lacp|1.0
netfilter|is_a|kernel_framework|1.0
netfilter|provides|packet_filtering_hooks|1.0
conntrack|tracks|connection_state|1.0
nat|translates|network_addresses|1.0
snat|changes|source_address|1.0
dnat|changes|destination_address|1.0
masquerade|is_a|dynamic_snat|1.0
ss|shows|socket_statistics|1.0
ss|replaces|netstat|1.0
ethtool|configures|network_interface_settings|1.0
tcpdump|captures|network_packets|1.0
networkmanager|manages|network_connections_gui|1.0
wpa_supplicant|manages|wifi_authentication|1.0
iw|configures|wireless_interfaces|1.0
firewalld|is_a|firewall_manager|1.0
firewalld|uses|zones_and_services|1.0
ufw|stands_for|uncomplicated_firewall|1.0
ufw|simplifies|iptables_management|1.0

# === FILESYSTEMS ===
ext4|is_a|journaling_filesystem|1.0
ext4|default_on|many_linux_distros|1.0
ext4|max_file_size|16TB|1.0
ext4|max_volume|1EB|1.0
ext4|supports|extents_and_delayed_allocation|1.0
btrfs|is_a|copy_on_write_filesystem|1.0
btrfs|supports|snapshots|1.0
btrfs|supports|subvolumes|1.0
btrfs|supports|transparent_compression|1.0
btrfs|supports|raid_0_1_10|1.0
zfs|is_a|copy_on_write_filesystem|1.0
zfs|combines|volume_manager_and_filesystem|1.0
zfs|supports|snapshots_and_clones|1.0
zfs|supports|deduplication|1.0
zfs|supports|raidz_1_2_3|1.0
zfs|has|self_healing_with_checksums|1.0
xfs|is_a|high_performance_filesystem|1.0
xfs|excels_at|large_files|1.0
xfs|default_on|rhel_and_centos|1.0
xfs|supports|online_resizing_grow_only|1.0
tmpfs|is_a|ram_based_filesystem|1.0
tmpfs|mounted_at|/tmp_and_/dev/shm|1.0
tmpfs|data_lost|on_reboot|1.0
overlayfs|is_a|union_filesystem|1.0
overlayfs|combines|upper_and_lower_layers|1.0
overlayfs|used_by|docker_and_containers|1.0
f2fs|is_a|flash_friendly_filesystem|1.0
f2fs|optimized_for|nand_flash|1.0
fuse|is_a|filesystem_in_userspace|1.0
fuse|allows|custom_filesystem_implementations|1.0
nfs|is_a|network_filesystem|1.0
nfs|shares|files_over_network|1.0
cifs_smb|is_a|network_filesystem|1.0
cifs_smb|used_for|windows_file_sharing|1.0
luks|provides|disk_encryption|1.0
luks|uses|dm_crypt|1.0
lvm|is_a|logical_volume_manager|1.0
lvm|allows|flexible_partition_management|1.0
lvm|components|pv_vg_lv|1.0
mdadm|manages|software_raid|1.0
mount|attaches|filesystem_to_directory|1.0
fstab|configures|automatic_mounts|1.0
blkid|identifies|block_devices|1.0
fdisk|manages|mbr_partitions|1.0
gdisk|manages|gpt_partitions|1.0

# === CONTAINERS ===
docker|is_a|container_platform|1.0
docker|uses|containerd_runtime|1.0
docker|uses|overlay2_storage_driver|1.0
docker|command|docker_run_build_push_pull|1.0
dockerfile|defines|container_image|1.0
docker_compose|orchestrates|multi_container_apps|1.0
docker_volume|persists|data_outside_container|1.0
docker_network|connects|containers|1.0
podman|is_a|container_platform|1.0
podman|advantage|daemonless_rootless|1.0
podman|compatible_with|docker_cli|1.0
lxc|is_a|system_container_platform|1.0
lxc|runs|full_os_in_container|1.0
lxd|manages|lxc_containers|1.0
runc|is_a|oci_runtime|1.0
runc|executes|containers_from_spec|1.0
containerd|is_a|container_runtime|1.0
containerd|manages|container_lifecycle|1.0
cri_o|is_a|kubernetes_container_runtime|1.0
buildah|builds|oci_container_images|1.0
skopeo|copies|container_images|1.0
container_image|is_a|layered_filesystem|1.0
container_registry|stores|container_images|1.0
oci_spec|defines|container_format_standard|1.0
pivot_root|changes|container_root_filesystem|1.0
seccomp_profile|restricts|container_syscalls|1.0
capabilities|grant|specific_privileges|1.0
rootless_container|runs|without_root_privileges|1.0

# === PACKAGE MANAGERS ===
apt|is_a|package_manager|1.0
apt|used_by|debian_ubuntu|1.0
apt|command|apt_install_remove_update_upgrade|1.0
dpkg|is_a|low_level_package_tool|1.0
dpkg|manages|.deb_packages|1.0
pacman|is_a|package_manager|1.0
pacman|used_by|arch_linux|1.0
pacman|sync_flag|-Syu|1.0
yay|is_a|aur_helper|1.0
yay|extends|pacman_with_aur|1.0
dnf|is_a|package_manager|1.0
dnf|used_by|fedora_rhel|1.0
dnf|replaces|yum|1.0
rpm|is_a|package_format|1.0
rpm|used_by|redhat_family|1.0
nix|is_a|package_manager|1.0
nix|provides|reproducible_builds|1.0
nix|has|declarative_configuration|1.0
nix|store|/nix/store|1.0
flatpak|is_a|application_sandboxing|1.0
flatpak|provides|universal_linux_packages|1.0
snap|is_a|application_packaging|1.0
snap|created_by|canonical|1.0
appimage|is_a|portable_app_format|1.0
appimage|needs|no_installation|1.0
zypper|is_a|package_manager|1.0
zypper|used_by|opensuse|1.0
emerge|is_a|package_manager|1.0
emerge|used_by|gentoo|1.0
emerge|compiles|from_source|1.0

# === SHELL SCRIPTING ===
bash|is_a|shell|1.0
bash|stands_for|bourne_again_shell|1.0
zsh|is_a|shell|1.0
zsh|default_on|macos|1.0
fish|is_a|shell|1.0
fish|has|autosuggestions_built_in|1.0
shebang|is|#!/bin/bash|1.0
shebang|specifies|interpreter|1.0
variable_assignment|syntax|VAR=value|1.0
command_substitution|syntax|$(command)|1.0
pipe|operator|||1.0
pipe|sends|stdout_to_next_stdin|1.0
redirect_stdout|operator|>|1.0
redirect_stderr|operator|2>|1.0
redirect_both|operator|&>|1.0
append_redirect|operator|>>|1.0
here_document|syntax|<<EOF|1.0
if_statement|syntax|if_then_elif_else_fi|1.0
for_loop|syntax|for_in_do_done|1.0
while_loop|syntax|while_do_done|1.0
case_statement|syntax|case_in_esac|1.0
function_definition|syntax|function_name_braces|1.0
exit_code|0|success|1.0
exit_code|nonzero|failure|1.0
set_e|exits_on|any_command_failure|1.0
set_u|exits_on|undefined_variable|1.0
set_o_pipefail|catches|pipe_failures|1.0
trap|catches|signals_and_exits|1.0
xargs|builds|command_from_stdin|1.0
awk|is_a|text_processing_language|1.0
sed|is_a|stream_editor|1.0
grep|searches|text_patterns|1.0
find|searches|filesystem|1.0
cut|extracts|fields_from_text|1.0
sort|sorts|lines_of_text|1.0
uniq|removes|duplicate_lines|1.0
wc|counts|words_lines_characters|1.0
tee|writes|stdout_and_file|1.0
tr|translates|characters|1.0

# === SYSTEM ADMINISTRATION ===
systemctl|manages|systemd_services|1.0
crontab|schedules|recurring_tasks|1.0
crontab|format|min_hour_dom_mon_dow_cmd|1.0
useradd|creates|new_user|1.0
usermod|modifies|user_account|1.0
userdel|deletes|user_account|1.0
groupadd|creates|new_group|1.0
passwd|changes|user_password|1.0
chmod|changes|file_permissions|1.0
chown|changes|file_ownership|1.0
umask|sets|default_permissions|1.0
sudo|executes|command_as_root|1.0
sudoers|configures|sudo_privileges|1.0
visudo|edits|sudoers_safely|1.0
ssh|provides|secure_remote_access|1.0
scp|copies|files_over_ssh|1.0
rsync|synchronizes|files_efficiently|1.0
rsync|supports|incremental_transfer|1.0
tar|creates|archive_files|1.0
gzip|compresses|files|1.0
top|shows|running_processes|1.0
htop|is_a|interactive_process_viewer|1.0
ps|lists|processes|1.0
kill|sends|signal_to_process|1.0
nice|sets|process_priority|1.0
renice|changes|running_process_priority|1.0
df|shows|disk_usage|1.0
du|shows|directory_size|1.0
free|shows|memory_usage|1.0
uptime|shows|system_uptime|1.0
hostname|shows|system_hostname|1.0
uname|shows|system_information|1.0
lsblk|lists|block_devices|1.0
lspci|lists|pci_devices|1.0
lsusb|lists|usb_devices|1.0
dmidecode|shows|hardware_info|1.0
dmesg|shows|kernel_messages|1.0

# === SECURITY ===
selinux|is_a|mandatory_access_control|1.0
selinux|provides|fine_grained_security_policies|1.0
selinux|modes|enforcing_permissive_disabled|1.0
selinux|uses|labels_and_contexts|1.0
apparmor|is_a|mandatory_access_control|1.0
apparmor|uses|path_based_profiles|1.0
apparmor|simpler_than|selinux|0.8
seccomp|filters|system_calls|1.0
seccomp|used_by|containers_and_browsers|1.0
capabilities|split|root_privileges_into_units|1.0
cap_net_admin|allows|network_administration|1.0
cap_sys_admin|allows|system_administration|1.0
cap_net_raw|allows|raw_socket_access|1.0
pam|is_a|authentication_framework|1.0
pam|stands_for|pluggable_authentication_modules|1.0
fail2ban|blocks|repeated_failed_logins|1.0
auditd|logs|security_relevant_events|1.0
audit_rules|monitor|file_access_and_syscalls|1.0
ssh_key_auth|more_secure_than|password_auth|1.0
ssh_hardening|disable|root_login_and_passwords|1.0
firewall|blocks|unauthorized_network_access|1.0
chroot|changes|apparent_root_directory|1.0
firejail|sandboxes|desktop_applications|1.0
openssl|provides|cryptographic_functions|1.0
gpg|provides|encryption_and_signing|1.0
luks|encrypts|disk_partitions|1.0
dm_crypt|is_a|kernel_encryption_layer|1.0
tpm|provides|hardware_security|1.0
secure_boot|verifies|boot_chain_integrity|1.0
aide|detects|filesystem_changes|1.0
rkhunter|detects|rootkits|1.0
lynis|audits|system_security|1.0

# === PROCESS MANAGEMENT ===
process|is_a|running_program|1.0
process|has|pid_ppid_uid_gid|1.0
thread|is_a|lightweight_process|1.0
thread|shares|memory_with_parent|1.0
fork|creates|child_process|1.0
exec|replaces|process_image|1.0
zombie_process|has|exited_but_not_reaped|1.0
orphan_process|adopted_by|init_process|1.0
signal|is_a|ipc_mechanism|1.0
sigterm|requests|graceful_termination|1.0
sigkill|forces|immediate_termination|1.0
sighup|is|terminal_hangup|1.0
sigusr1|is|user_defined_signal|1.0
sigstop|suspends|process_execution|1.0
sigcont|resumes|suspended_process|1.0
nice_value|range|-20_to_19|1.0
nice_value|lower|higher_priority|1.0
oom_killer|terminates|processes_when_out_of_memory|1.0
oom_score|determines|kill_priority|1.0
cgroups_cpu|limits|cpu_usage_per_group|1.0
cgroups_memory|limits|memory_per_group|1.0
cgroups_io|limits|disk_io_per_group|1.0
cpu_scheduler|types|cfs_rt_deadline|1.0
cfs|stands_for|completely_fair_scheduler|1.0
process_state|can_be|running_sleeping_stopped_zombie|1.0
nohup|runs|process_immune_to_hangup|1.0
disown|detaches|job_from_shell|1.0
screen|provides|persistent_terminal_sessions|1.0
tmux|provides|terminal_multiplexing|1.0
systemd_scope|tracks|transient_process_groups|1.0

# === LINUX DISTRIBUTIONS ===
ubuntu|is_a|linux_distribution|1.0
ubuntu|based_on|debian|1.0
ubuntu|release_cycle|6_months|1.0
ubuntu|lts_support|5_years|1.0
debian|is_a|linux_distribution|1.0
debian|known_for|stability|1.0
arch_linux|is_a|linux_distribution|1.0
arch_linux|philosophy|keep_it_simple|1.0
arch_linux|uses|rolling_release|1.0
fedora|is_a|linux_distribution|1.0
fedora|sponsored_by|red_hat|1.0
fedora|has|latest_packages|0.9
centos_stream|is_a|linux_distribution|1.0
centos_stream|upstream_of|rhel|1.0
rocky_linux|is_a|linux_distribution|1.0
rocky_linux|binary_compatible|rhel|1.0
alpine_linux|is_a|linux_distribution|1.0
alpine_linux|uses|musl_libc|1.0
alpine_linux|popular_for|containers|0.9
gentoo|is_a|linux_distribution|1.0
gentoo|compiles|everything_from_source|1.0
nixos|is_a|linux_distribution|1.0
nixos|uses|declarative_configuration|1.0
opensuse|is_a|linux_distribution|1.0
opensuse|has|tumbleweed_and_leap|1.0
kali_linux|is_a|linux_distribution|1.0
kali_linux|used_for|penetration_testing|1.0
void_linux|is_a|linux_distribution|1.0
void_linux|uses|runit_init|1.0

# === BOOT PROCESS ===
bios|performs|power_on_self_test|1.0
uefi|replaces|bios|1.0
uefi|supports|secure_boot|1.0
bootloader|loads|kernel_into_memory|1.0
grub|is_a|bootloader|1.0
grub|config_at|/boot/grub/grub.cfg|1.0
systemd_boot|is_a|simple_uefi_bootloader|1.0
initrd|is|initial_ramdisk|1.0
initrd|loads|essential_drivers|1.0
kernel_parameters|passed_via|grub_or_cmdline|1.0
init_process|first|userspace_process|1.0
runlevel|legacy|sysvinit_concept|1.0
target|is|systemd_equivalent_of_runlevel|1.0
multi_user_target|is|normal_boot_no_gui|1.0
graphical_target|is|boot_with_gui|1.0

# === STORAGE AND DISK MANAGEMENT ===
raid_0|provides|striping_no_redundancy|1.0
raid_1|provides|mirroring|1.0
raid_5|provides|striping_with_parity|1.0
raid_6|provides|striping_with_double_parity|1.0
raid_10|provides|mirroring_and_striping|1.0
iscsi|provides|block_storage_over_network|1.0
nbd|provides|network_block_device|1.0
multipath|provides|redundant_storage_paths|1.0
ssd_trim|optimizes|ssd_performance|1.0
io_scheduler|types|none_mq_deadline_bfq_kyber|1.0
bfq_scheduler|optimized_for|interactive_workloads|1.0
direct_io|bypasses|page_cache|1.0
page_cache|caches|file_data_in_memory|1.0
swap_space|extends|virtual_memory_to_disk|1.0
swappiness|controls|kernel_swap_aggressiveness|1.0
zram|provides|compressed_ram_block_device|1.0
bcache|provides|ssd_caching_for_hdd|1.0

# === VIRTUALIZATION ===
kvm|is_a|hypervisor|1.0
kvm|stands_for|kernel_virtual_machine|1.0
kvm|uses|hardware_virtualization|1.0
qemu|is_a|machine_emulator|1.0
qemu|used_with|kvm_for_acceleration|1.0
libvirt|manages|virtual_machines|1.0
virsh|is_a|libvirt_cli_tool|1.0
virt_manager|is_a|gui_for_vm_management|1.0
virtio|provides|paravirtualized_drivers|1.0
xen|is_a|type_1_hypervisor|1.0
vagrant|manages|development_vms|1.0
vagrant|uses|virtualbox_or_libvirt|1.0

# === LOGGING AND MONITORING ===
syslog|is_a|logging_protocol|1.0
rsyslog|is_a|syslog_implementation|1.0
logrotate|manages|log_file_rotation|1.0
logrotate|prevents|disk_space_exhaustion|1.0
sysstat|collects|system_performance_data|1.0
sar|reports|system_activity|1.0
iostat|reports|disk_io_statistics|1.0
vmstat|reports|virtual_memory_statistics|1.0
mpstat|reports|per_cpu_statistics|1.0
nmon|is_a|performance_monitor|1.0
nagios|is_a|monitoring_system|1.0
prometheus_node_exporter|exports|linux_metrics|1.0
collectd|collects|system_metrics|1.0
strace|traces|system_calls|1.0
ltrace|traces|library_calls|1.0
lsof|lists|open_files|1.0
fuser|shows|processes_using_files|1.0

# === NETWORKING ADVANCED ===
wireguard|is_a|vpn_protocol|1.0
wireguard|built_into|linux_kernel|1.0
wireguard|advantage|simple_and_fast|1.0
openvpn|is_a|vpn_solution|1.0
openvpn|uses|tls_for_key_exchange|1.0
ipsec|is_a|vpn_protocol|1.0
ipsec|operates_at|network_layer|1.0
keepalived|provides|vrrp_failover|1.0
haproxy|is_a|load_balancer|1.0
haproxy|operates_at|layer_4_and_7|1.0
nginx|can_be|reverse_proxy_load_balancer|1.0
ipvs|is_a|kernel_load_balancer|1.0
macvlan|creates|virtual_mac_interfaces|1.0
ipvlan|creates|virtual_ip_interfaces|1.0
geneve|is_a|overlay_network_protocol|1.0
vxlan|is_a|overlay_network_protocol|1.0
vxlan|encapsulates|layer_2_in_udp|1.0

# === ADDITIONAL LINUX KNOWLEDGE ===
inotify|monitors|filesystem_events|1.0
fanotify|monitors|filesystem_events_globally|1.0
epoll|is_a|io_multiplexing_mechanism|1.0
select|is_a|io_multiplexing_mechanism|1.0
poll|is_a|io_multiplexing_mechanism|1.0
mmap|maps|files_into_memory|1.0
shared_memory|allows|ipc_via_memory|1.0
semaphore|controls|concurrent_access|1.0
mutex|provides|mutual_exclusion|1.0
futex|is_a|fast_userspace_mutex|1.0
pipe|provides|unidirectional_ipc|1.0
named_pipe|provides|ipc_via_filesystem|1.0
unix_socket|provides|local_ipc|1.0
dbus|is_a|message_bus_system|1.0
systemd_socket_activation|starts|services_on_demand|1.0
cgroup_v2|unified|hierarchy_for_resource_control|1.0
memory_overcommit|allows|more_allocation_than_ram|1.0
transparent_huge_pages|improves|memory_performance|0.8
numa_aware|optimizes|memory_access_locality|1.0
cpu_affinity|binds|process_to_specific_cpus|1.0
taskset|sets|cpu_affinity|1.0
numactl|controls|numa_policy|1.0
perf_events|provides|performance_counters|1.0
bpftrace|is_a|dynamic_tracing_tool|1.0
systemtap|is_a|kernel_tracing_framework|1.0
kdump|captures|crash_dump|1.0
kexec|boots|new_kernel_without_bios|1.0
livepatch|applies|kernel_patches_without_reboot|1.0
device_tree|describes|hardware_on_arm|1.0
udev|manages|device_nodes|1.0
udev_rules|customize|device_handling|1.0
sysctl|tunes|kernel_parameters|1.0
proc_sys|exposes|tunable_parameters|1.0
cgroup_freezer|suspends|all_processes_in_cgroup|1.0
oom_cgroup|kills|processes_within_cgroup_first|1.0
hugepages|reduces|tlb_misses|1.0
kernel_same_page_merging|deduplicates|memory_pages|1.0
balloon_driver|adjusts|vm_memory_dynamically|1.0
virtio_balloon|used_in|kvm_guests|1.0
paravirtualization|modifies|guest_for_performance|1.0
sr_iov|provides|hardware_virtualized_io|1.0
dpdk|provides|userspace_network_processing|1.0
xdp|provides|early_packet_processing|1.0
af_xdp|provides|zero_copy_networking|1.0
io_uring|provides|async_io|1.0
splice|moves|data_between_fds_without_copy|1.0
sendfile|sends|file_to_socket_efficiently|1.0

# === LINUX KERNEL TUNING ===
vm_swappiness_default|value|60|1.0
vm_dirty_ratio_default|value|20_percent|1.0
vm_dirty_background_ratio|value|10_percent|1.0
net_core_somaxconn|default|4096|1.0
tcp_max_syn_backlog|default|128|1.0
tcp_tw_reuse|enables|time_wait_socket_reuse|1.0
tcp_fin_timeout|default|60_seconds|1.0
tcp_keepalive_time|default|7200_seconds|1.0
ip_local_port_range|default|32768_to_60999|1.0
file_max|limits|system_wide_open_files|1.0
ulimit_nofile|limits|per_process_open_files|1.0
core_dump|saves|crash_memory_to_disk|1.0
kernel_panic_timeout|reboots_after|specified_seconds|1.0
overcommit_memory_0|heuristic|allows_some_overcommit|1.0
overcommit_memory_1|always|allows_overcommit|1.0
overcommit_memory_2|never|allows_overcommit|1.0
transparent_hugepages_always|allocates|thp_aggressively|1.0
transparent_hugepages_madvise|allocates|thp_on_request|1.0
numa_balancing|automatically|migrates_pages|1.0
scheduler_migration_cost|determines|core_migration_threshold|1.0
kernel_tick_rate|options|100_250_300_1000_hz|1.0
tickless_kernel|skips|timer_interrupts_when_idle|1.0
preempt_voluntary|reduces|latency_slightly|1.0
preempt_full|reduces|latency_significantly|1.0
preempt_rt|real_time|kernel_patch|1.0
io_scheduler_none|best_for|nvme_drives|1.0
io_scheduler_mq_deadline|best_for|spinning_disks|1.0
readahead|prefetches|sequential_data|1.0
dirty_writeback_centisecs|flushes_every|default_500cs|1.0
vm_min_free_kbytes|reserves|memory_for_kernel|1.0

# === LINUX TRACING AND DEBUGGING ===
ftrace_function|traces|every_function_call|1.0
kprobe|dynamic|kernel_function_probe|1.0
uprobe|dynamic|userspace_function_probe|1.0
tracepoint|static|kernel_trace_point|1.0
bpf_program_types|include|kprobe_tracepoint_xdp_socket|1.0
bpf_map_types|include|hash_array_ringbuf_lru|1.0
bpftool|manages|bpf_programs_and_maps|1.0
perf_record|captures|performance_samples|1.0
perf_report|analyzes|captured_samples|1.0
perf_stat|counts|hardware_events|1.0
flame_graph|visualizes|stack_traces|1.0
off_cpu_analysis|finds|blocking_time|1.0
on_cpu_analysis|finds|computation_time|1.0
memory_leak_detection|tools|valgrind_asan_memleak|1.0
address_sanitizer|detects|memory_errors|1.0
thread_sanitizer|detects|data_races|1.0
undefined_behavior_sanitizer|detects|ub_in_code|1.0
core_analyzer|inspects|core_dump_files|1.0
gdb|is_a|gnu_debugger|1.0
lldb|is_a|llvm_debugger|1.0
ptrace|syscall_for|debugging_and_tracing|1.0
seccomp_bpf|filters|syscalls_with_bpf|1.0
landlock|is_a|access_control_mechanism|1.0
io_uring_sqpoll|kernel|thread_polls_submission_queue|1.0
registered_buffers|avoid|memory_mapping_overhead|1.0
fixed_files|avoid|file_descriptor_lookup|1.0
multishot_operations|complete|multiple_times|1.0
linked_operations|chain|dependent_ios|1.0
