# Countries, Capitals, and Geography
# Format: source|relation|target|weight
# Auto-generated by generate_knowledge.py

united states|is_a|country|1.0
united states|capital_is|washington dc|1.0
united states|located_in|north america|1.0
united states|language_is|english|0.95
united states|currency_is|dollar|0.95
united states|population_is|331000000|0.85
washington dc|is_a|capital city|1.0
washington dc|capital_of|united states|1.0
canada|is_a|country|1.0
canada|capital_is|ottawa|1.0
canada|located_in|north america|1.0
canada|language_is|english|0.95
canada|currency_is|canadian dollar|0.95
canada|population_is|38000000|0.85
ottawa|is_a|capital city|1.0
ottawa|capital_of|canada|1.0
mexico|is_a|country|1.0
mexico|capital_is|mexico city|1.0
mexico|located_in|north america|1.0
mexico|language_is|spanish|0.95
mexico|currency_is|peso|0.95
mexico|population_is|129000000|0.85
mexico city|is_a|capital city|1.0
mexico city|capital_of|mexico|1.0
brazil|is_a|country|1.0
brazil|capital_is|brasilia|1.0
brazil|located_in|south america|1.0
brazil|language_is|portuguese|0.95
brazil|currency_is|real|0.95
brazil|population_is|213000000|0.85
brasilia|is_a|capital city|1.0
brasilia|capital_of|brazil|1.0
argentina|is_a|country|1.0
argentina|capital_is|buenos aires|1.0
argentina|located_in|south america|1.0
argentina|language_is|spanish|0.95
argentina|currency_is|peso|0.95
argentina|population_is|45000000|0.85
buenos aires|is_a|capital city|1.0
buenos aires|capital_of|argentina|1.0
colombia|is_a|country|1.0
colombia|capital_is|bogota|1.0
colombia|located_in|south america|1.0
colombia|language_is|spanish|0.95
colombia|currency_is|peso|0.95
colombia|population_is|51000000|0.85
bogota|is_a|capital city|1.0
bogota|capital_of|colombia|1.0
chile|is_a|country|1.0
chile|capital_is|santiago|1.0
chile|located_in|south america|1.0
chile|language_is|spanish|0.95
chile|currency_is|peso|0.95
chile|population_is|19000000|0.85
santiago|is_a|capital city|1.0
santiago|capital_of|chile|1.0
peru|is_a|country|1.0
peru|capital_is|lima|1.0
peru|located_in|south america|1.0
peru|language_is|spanish|0.95
peru|currency_is|sol|0.95
peru|population_is|33000000|0.85
lima|is_a|capital city|1.0
lima|capital_of|peru|1.0
united kingdom|is_a|country|1.0
united kingdom|capital_is|london|1.0
united kingdom|located_in|europe|1.0
united kingdom|language_is|english|0.95
united kingdom|currency_is|pound sterling|0.95
united kingdom|population_is|67000000|0.85
london|is_a|capital city|1.0
london|capital_of|united kingdom|1.0
france|is_a|country|1.0
france|capital_is|paris|1.0
france|located_in|europe|1.0
france|language_is|french|0.95
france|currency_is|euro|0.95
france|population_is|67000000|0.85
paris|is_a|capital city|1.0
paris|capital_of|france|1.0
germany|is_a|country|1.0
germany|capital_is|berlin|1.0
germany|located_in|europe|1.0
germany|language_is|german|0.95
germany|currency_is|euro|0.95
germany|population_is|83000000|0.85
berlin|is_a|capital city|1.0
berlin|capital_of|germany|1.0
italy|is_a|country|1.0
italy|capital_is|rome|1.0
italy|located_in|europe|1.0
italy|language_is|italian|0.95
italy|currency_is|euro|0.95
italy|population_is|60000000|0.85
rome|is_a|capital city|1.0
rome|capital_of|italy|1.0
spain|is_a|country|1.0
spain|capital_is|madrid|1.0
spain|located_in|europe|1.0
spain|language_is|spanish|0.95
spain|currency_is|euro|0.95
spain|population_is|47000000|0.85
madrid|is_a|capital city|1.0
madrid|capital_of|spain|1.0
portugal|is_a|country|1.0
portugal|capital_is|lisbon|1.0
portugal|located_in|europe|1.0
portugal|language_is|portuguese|0.95
portugal|currency_is|euro|0.95
portugal|population_is|10000000|0.85
lisbon|is_a|capital city|1.0
lisbon|capital_of|portugal|1.0
netherlands|is_a|country|1.0
netherlands|capital_is|amsterdam|1.0
netherlands|located_in|europe|1.0
netherlands|language_is|dutch|0.95
netherlands|currency_is|euro|0.95
netherlands|population_is|17000000|0.85
amsterdam|is_a|capital city|1.0
amsterdam|capital_of|netherlands|1.0
belgium|is_a|country|1.0
belgium|capital_is|brussels|1.0
belgium|located_in|europe|1.0
belgium|language_is|dutch|0.95
belgium|currency_is|euro|0.95
belgium|population_is|11500000|0.85
brussels|is_a|capital city|1.0
brussels|capital_of|belgium|1.0
switzerland|is_a|country|1.0
switzerland|capital_is|bern|1.0
switzerland|located_in|europe|1.0
switzerland|language_is|german|0.95
switzerland|currency_is|swiss franc|0.95
switzerland|population_is|8700000|0.85
bern|is_a|capital city|1.0
bern|capital_of|switzerland|1.0
austria|is_a|country|1.0
austria|capital_is|vienna|1.0
austria|located_in|europe|1.0
austria|language_is|german|0.95
austria|currency_is|euro|0.95
austria|population_is|9000000|0.85
vienna|is_a|capital city|1.0
vienna|capital_of|austria|1.0
sweden|is_a|country|1.0
sweden|capital_is|stockholm|1.0
sweden|located_in|europe|1.0
sweden|language_is|swedish|0.95
sweden|currency_is|krona|0.95
sweden|population_is|10400000|0.85
stockholm|is_a|capital city|1.0
stockholm|capital_of|sweden|1.0
norway|is_a|country|1.0
norway|capital_is|oslo|1.0
norway|located_in|europe|1.0
norway|language_is|norwegian|0.95
norway|currency_is|krone|0.95
norway|population_is|5400000|0.85
oslo|is_a|capital city|1.0
oslo|capital_of|norway|1.0
denmark|is_a|country|1.0
denmark|capital_is|copenhagen|1.0
denmark|located_in|europe|1.0
denmark|language_is|danish|0.95
denmark|currency_is|krone|0.95
denmark|population_is|5800000|0.85
copenhagen|is_a|capital city|1.0
copenhagen|capital_of|denmark|1.0
finland|is_a|country|1.0
finland|capital_is|helsinki|1.0
finland|located_in|europe|1.0
finland|language_is|finnish|0.95
finland|currency_is|euro|0.95
finland|population_is|5500000|0.85
helsinki|is_a|capital city|1.0
helsinki|capital_of|finland|1.0
poland|is_a|country|1.0
poland|capital_is|warsaw|1.0
poland|located_in|europe|1.0
poland|language_is|polish|0.95
poland|currency_is|zloty|0.95
poland|population_is|38000000|0.85
warsaw|is_a|capital city|1.0
warsaw|capital_of|poland|1.0
greece|is_a|country|1.0
greece|capital_is|athens|1.0
greece|located_in|europe|1.0
greece|language_is|greek|0.95
greece|currency_is|euro|0.95
greece|population_is|10700000|0.85
athens|is_a|capital city|1.0
athens|capital_of|greece|1.0
ireland|is_a|country|1.0
ireland|capital_is|dublin|1.0
ireland|located_in|europe|1.0
ireland|language_is|english|0.95
ireland|currency_is|euro|0.95
ireland|population_is|5000000|0.85
dublin|is_a|capital city|1.0
dublin|capital_of|ireland|1.0
czech republic|is_a|country|1.0
czech republic|capital_is|prague|1.0
czech republic|located_in|europe|1.0
czech republic|language_is|czech|0.95
czech republic|currency_is|koruna|0.95
czech republic|population_is|10700000|0.85
prague|is_a|capital city|1.0
prague|capital_of|czech republic|1.0
russia|is_a|country|1.0
russia|capital_is|moscow|1.0
russia|located_in|europe|1.0
russia|language_is|russian|0.95
russia|currency_is|ruble|0.95
russia|population_is|146000000|0.85
moscow|is_a|capital city|1.0
moscow|capital_of|russia|1.0
ukraine|is_a|country|1.0
ukraine|capital_is|kyiv|1.0
ukraine|located_in|europe|1.0
ukraine|language_is|ukrainian|0.95
ukraine|currency_is|hryvnia|0.95
ukraine|population_is|44000000|0.85
kyiv|is_a|capital city|1.0
kyiv|capital_of|ukraine|1.0
turkey|is_a|country|1.0
turkey|capital_is|ankara|1.0
turkey|located_in|asia|1.0
turkey|language_is|turkish|0.95
turkey|currency_is|lira|0.95
turkey|population_is|84000000|0.85
ankara|is_a|capital city|1.0
ankara|capital_of|turkey|1.0
china|is_a|country|1.0
china|capital_is|beijing|1.0
china|located_in|asia|1.0
china|language_is|mandarin|0.95
china|currency_is|yuan|0.95
china|population_is|1400000000|0.85
beijing|is_a|capital city|1.0
beijing|capital_of|china|1.0
japan|is_a|country|1.0
japan|capital_is|tokyo|1.0
japan|located_in|asia|1.0
japan|language_is|japanese|0.95
japan|currency_is|yen|0.95
japan|population_is|126000000|0.85
tokyo|is_a|capital city|1.0
tokyo|capital_of|japan|1.0
south korea|is_a|country|1.0
south korea|capital_is|seoul|1.0
south korea|located_in|asia|1.0
south korea|language_is|korean|0.95
south korea|currency_is|won|0.95
south korea|population_is|52000000|0.85
seoul|is_a|capital city|1.0
seoul|capital_of|south korea|1.0
india|is_a|country|1.0
india|capital_is|new delhi|1.0
india|located_in|asia|1.0
india|language_is|hindi|0.95
india|currency_is|rupee|0.95
india|population_is|1380000000|0.85
new delhi|is_a|capital city|1.0
new delhi|capital_of|india|1.0
indonesia|is_a|country|1.0
indonesia|capital_is|jakarta|1.0
indonesia|located_in|asia|1.0
indonesia|language_is|indonesian|0.95
indonesia|currency_is|rupiah|0.95
indonesia|population_is|274000000|0.85
jakarta|is_a|capital city|1.0
jakarta|capital_of|indonesia|1.0
thailand|is_a|country|1.0
thailand|capital_is|bangkok|1.0
thailand|located_in|asia|1.0
thailand|language_is|thai|0.95
thailand|currency_is|baht|0.95
thailand|population_is|70000000|0.85
bangkok|is_a|capital city|1.0
bangkok|capital_of|thailand|1.0
vietnam|is_a|country|1.0
vietnam|capital_is|hanoi|1.0
vietnam|located_in|asia|1.0
vietnam|language_is|vietnamese|0.95
vietnam|currency_is|dong|0.95
vietnam|population_is|97000000|0.85
hanoi|is_a|capital city|1.0
hanoi|capital_of|vietnam|1.0
philippines|is_a|country|1.0
philippines|capital_is|manila|1.0
philippines|located_in|asia|1.0
philippines|language_is|filipino|0.95
philippines|currency_is|peso|0.95
philippines|population_is|110000000|0.85
manila|is_a|capital city|1.0
manila|capital_of|philippines|1.0
malaysia|is_a|country|1.0
malaysia|capital_is|kuala lumpur|1.0
malaysia|located_in|asia|1.0
malaysia|language_is|malay|0.95
malaysia|currency_is|ringgit|0.95
malaysia|population_is|32000000|0.85
kuala lumpur|is_a|capital city|1.0
kuala lumpur|capital_of|malaysia|1.0
singapore|is_a|country|1.0
singapore|capital_is|singapore|1.0
singapore|located_in|asia|1.0
singapore|language_is|english|0.95
singapore|currency_is|singapore dollar|0.95
singapore|population_is|5900000|0.85
singapore|is_a|capital city|1.0
singapore|capital_of|singapore|1.0
saudi arabia|is_a|country|1.0
saudi arabia|capital_is|riyadh|1.0
saudi arabia|located_in|asia|1.0
saudi arabia|language_is|arabic|0.95
saudi arabia|currency_is|riyal|0.95
saudi arabia|population_is|35000000|0.85
riyadh|is_a|capital city|1.0
riyadh|capital_of|saudi arabia|1.0
israel|is_a|country|1.0
israel|capital_is|jerusalem|1.0
israel|located_in|asia|1.0
israel|language_is|hebrew|0.95
israel|currency_is|shekel|0.95
israel|population_is|9200000|0.85
jerusalem|is_a|capital city|1.0
jerusalem|capital_of|israel|1.0
iran|is_a|country|1.0
iran|capital_is|tehran|1.0
iran|located_in|asia|1.0
iran|language_is|persian|0.95
iran|currency_is|rial|0.95
iran|population_is|84000000|0.85
tehran|is_a|capital city|1.0
tehran|capital_of|iran|1.0
pakistan|is_a|country|1.0
pakistan|capital_is|islamabad|1.0
pakistan|located_in|asia|1.0
pakistan|language_is|urdu|0.95
pakistan|currency_is|rupee|0.95
pakistan|population_is|221000000|0.85
islamabad|is_a|capital city|1.0
islamabad|capital_of|pakistan|1.0
bangladesh|is_a|country|1.0
bangladesh|capital_is|dhaka|1.0
bangladesh|located_in|asia|1.0
bangladesh|language_is|bengali|0.95
bangladesh|currency_is|taka|0.95
bangladesh|population_is|166000000|0.85
dhaka|is_a|capital city|1.0
dhaka|capital_of|bangladesh|1.0
egypt|is_a|country|1.0
egypt|capital_is|cairo|1.0
egypt|located_in|africa|1.0
egypt|language_is|arabic|0.95
egypt|currency_is|pound|0.95
egypt|population_is|102000000|0.85
cairo|is_a|capital city|1.0
cairo|capital_of|egypt|1.0
south africa|is_a|country|1.0
south africa|capital_is|pretoria|1.0
south africa|located_in|africa|1.0
south africa|language_is|english|0.95
south africa|currency_is|rand|0.95
south africa|population_is|60000000|0.85
pretoria|is_a|capital city|1.0
pretoria|capital_of|south africa|1.0
nigeria|is_a|country|1.0
nigeria|capital_is|abuja|1.0
nigeria|located_in|africa|1.0
nigeria|language_is|english|0.95
nigeria|currency_is|naira|0.95
nigeria|population_is|211000000|0.85
abuja|is_a|capital city|1.0
abuja|capital_of|nigeria|1.0
kenya|is_a|country|1.0
kenya|capital_is|nairobi|1.0
kenya|located_in|africa|1.0
kenya|language_is|swahili|0.95
kenya|currency_is|shilling|0.95
kenya|population_is|54000000|0.85
nairobi|is_a|capital city|1.0
nairobi|capital_of|kenya|1.0
ethiopia|is_a|country|1.0
ethiopia|capital_is|addis ababa|1.0
ethiopia|located_in|africa|1.0
ethiopia|language_is|amharic|0.95
ethiopia|currency_is|birr|0.95
ethiopia|population_is|118000000|0.85
addis ababa|is_a|capital city|1.0
addis ababa|capital_of|ethiopia|1.0
morocco|is_a|country|1.0
morocco|capital_is|rabat|1.0
morocco|located_in|africa|1.0
morocco|language_is|arabic|0.95
morocco|currency_is|dirham|0.95
morocco|population_is|37000000|0.85
rabat|is_a|capital city|1.0
rabat|capital_of|morocco|1.0
ghana|is_a|country|1.0
ghana|capital_is|accra|1.0
ghana|located_in|africa|1.0
ghana|language_is|english|0.95
ghana|currency_is|cedi|0.95
ghana|population_is|31000000|0.85
accra|is_a|capital city|1.0
accra|capital_of|ghana|1.0
australia|is_a|country|1.0
australia|capital_is|canberra|1.0
australia|located_in|oceania|1.0
australia|language_is|english|0.95
australia|currency_is|australian dollar|0.95
australia|population_is|26000000|0.85
canberra|is_a|capital city|1.0
canberra|capital_of|australia|1.0
new zealand|is_a|country|1.0
new zealand|capital_is|wellington|1.0
new zealand|located_in|oceania|1.0
new zealand|language_is|english|0.95
new zealand|currency_is|new zealand dollar|0.95
new zealand|population_is|5100000|0.85
wellington|is_a|capital city|1.0
wellington|capital_of|new zealand|1.0
