# MK Knowledge File - DevOps, Cloud Computing, Infrastructure
# Format: source|relation|target|weight
# Covers: Kubernetes, Terraform, CI/CD, cloud services, observability, GitOps

# === KUBERNETES ===
kubernetes|is_a|container_orchestration_platform|1.0
kubernetes|abbreviated|k8s|1.0
kubernetes|created_by|google|1.0
pod|is_a|smallest_deployable_unit|1.0
pod|contains|one_or_more_containers|1.0
pod|has|shared_network_namespace|1.0
deployment|manages|pod_replicas|1.0
deployment|supports|rolling_updates|1.0
statefulset|manages|stateful_applications|1.0
statefulset|has|stable_network_identity|1.0
daemonset|runs|pod_on_every_node|1.0
replicaset|ensures|desired_pod_count|1.0
service|provides|stable_network_endpoint|1.0
clusterip|is_a|internal_service_type|1.0
nodeport|is_a|external_service_type|1.0
loadbalancer|is_a|cloud_service_type|1.0
ingress|manages|external_http_access|1.0
ingress_controller|implements|ingress_rules|1.0
configmap|stores|non_sensitive_configuration|1.0
secret|stores|sensitive_data|1.0
persistent_volume|provides|storage_to_pods|1.0
pvc|stands_for|persistent_volume_claim|1.0
storage_class|defines|dynamic_provisioning|1.0
namespace|provides|resource_isolation|1.0
rbac|controls|kubernetes_access|1.0
service_account|authenticates|pods_to_api|1.0
node|is_a|worker_machine|1.0
control_plane|manages|cluster_state|1.0
etcd|stores|cluster_state|1.0
kube_scheduler|assigns|pods_to_nodes|1.0
kube_controller_manager|runs|controllers|1.0
kubelet|manages|pods_on_node|1.0
kube_proxy|manages|network_rules|1.0
helm|is_a|package_manager_for_k8s|1.0
helm_chart|packages|kubernetes_resources|1.0
operator|extends|kubernetes_api|1.0
operator|automates|application_management|1.0
crd|stands_for|custom_resource_definition|1.0
hpa|stands_for|horizontal_pod_autoscaler|1.0
vpa|stands_for|vertical_pod_autoscaler|1.0
keda|is_a|event_driven_autoscaler|1.0
network_policy|controls|pod_communication|1.0
pod_disruption_budget|limits|voluntary_disruptions|1.0
init_container|runs|before_main_containers|1.0
sidecar|runs|alongside_main_container|1.0
service_mesh|manages|service_to_service_communication|1.0
istio|is_a|service_mesh|1.0
linkerd|is_a|service_mesh|1.0
envoy|is_a|service_proxy|1.0

# === TERRAFORM ===
terraform|is_a|infrastructure_as_code_tool|1.0
terraform|created_by|hashicorp|1.0
terraform|uses|hcl_language|1.0
terraform_provider|interfaces_with|cloud_apis|1.0
terraform_state|tracks|managed_resources|1.0
terraform_plan|shows|intended_changes|1.0
terraform_apply|creates|infrastructure|1.0
terraform_destroy|removes|infrastructure|1.0
terraform_module|is_a|reusable_component|1.0
terraform_workspace|isolates|state_environments|1.0
terraform_backend|stores|state_remotely|1.0
terraform_import|brings|existing_resources_under_management|1.0
terraform_data_source|reads|existing_infrastructure|1.0
terraform_variable|parameterizes|configuration|1.0
terraform_output|exposes|values_to_other_configs|1.0
terragrunt|wraps|terraform_for_dry|1.0
opentofu|is_a|open_source_terraform_fork|1.0
pulumi|is_a|iac_tool_using_programming_languages|1.0
crossplane|manages|cloud_resources_via_k8s|1.0
ansible|is_a|configuration_management_tool|1.0
ansible|uses|yaml_playbooks|1.0
ansible|agentless|uses_ssh|1.0

# === CI/CD ===
ci|stands_for|continuous_integration|1.0
cd|stands_for|continuous_delivery_or_deployment|1.0
ci_pipeline|builds_and_tests|on_every_commit|1.0
cd_pipeline|deploys|to_environments|1.0
github_actions|is_a|ci_cd_platform|1.0
github_actions|uses|yaml_workflows|1.0
github_actions|triggered_by|events|1.0
gitlab_ci|is_a|ci_cd_platform|1.0
gitlab_ci|uses|.gitlab-ci.yml|1.0
jenkins|is_a|ci_cd_server|1.0
jenkins|uses|jenkinsfile|1.0
jenkins|extensible_via|plugins|1.0
argocd|is_a|gitops_cd_tool|1.0
argocd|syncs|k8s_with_git|1.0
flux|is_a|gitops_cd_tool|1.0
tekton|is_a|k8s_native_ci_cd|1.0
circleci|is_a|ci_cd_platform|1.0
drone|is_a|container_native_ci|1.0
buildkite|is_a|ci_cd_platform|1.0
artifact_registry|stores|build_artifacts|1.0
container_registry|stores|docker_images|1.0
blue_green_deployment|switches|between_environments|1.0
canary_deployment|gradually|shifts_traffic|1.0
rolling_update|replaces|instances_incrementally|1.0
feature_flag|toggles|functionality|1.0
trunk_based_development|merges|to_main_frequently|1.0
gitflow|uses|feature_release_branches|1.0

# === CLOUD SERVICES ===
aws|stands_for|amazon_web_services|1.0
aws|largest|cloud_provider|1.0
ec2|is_a|compute_service|1.0
ec2|provides|virtual_machines|1.0
s3|is_a|object_storage|1.0
s3|durability|11_nines|1.0
lambda|is_a|serverless_compute|1.0
lambda|runs|code_without_managing_servers|1.0
rds|is_a|managed_database_service|1.0
dynamodb|is_a|nosql_database|1.0
eks|is_a|managed_kubernetes_service|1.0
ecs|is_a|container_orchestration_service|1.0
sqs|is_a|message_queue|1.0
sns|is_a|notification_service|1.0
cloudfront|is_a|cdn|1.0
route53|is_a|dns_service|1.0
iam|manages|access_and_permissions|1.0
vpc|provides|isolated_network|1.0
elb|is_a|load_balancer_service|1.0
elasticache|provides|managed_redis_memcached|1.0
gcp|stands_for|google_cloud_platform|1.0
gke|is_a|managed_kubernetes|1.0
bigquery|is_a|data_warehouse|1.0
cloud_run|is_a|serverless_containers|1.0
cloud_functions|is_a|serverless_compute|1.0
azure|is_a|microsoft_cloud_platform|1.0
aks|is_a|managed_kubernetes|1.0
azure_functions|is_a|serverless_compute|1.0
cosmos_db|is_a|multi_model_database|1.0
blob_storage|is_a|object_storage|1.0
serverless|eliminates|server_management|1.0
serverless|scales|automatically|1.0
pay_per_use|charges|only_for_consumption|1.0
multi_cloud|uses|multiple_cloud_providers|1.0
hybrid_cloud|combines|on_prem_and_cloud|1.0
cloud_native|designed_for|cloud_environment|1.0
twelve_factor_app|principles_for|cloud_applications|1.0

# === OBSERVABILITY ===
prometheus|is_a|monitoring_system|1.0
prometheus|uses|pull_based_metrics|1.0
prometheus|query_language|promql|1.0
grafana|is_a|visualization_platform|1.0
grafana|creates|dashboards|1.0
elk_stack|stands_for|elasticsearch_logstash_kibana|1.0
elasticsearch|is_a|search_engine|1.0
logstash|processes|log_data|1.0
kibana|visualizes|elasticsearch_data|1.0
fluentd|is_a|log_collector|1.0
loki|is_a|log_aggregation_system|1.0
loki|lightweight|like_prometheus_for_logs|1.0
jaeger|is_a|distributed_tracing_system|1.0
zipkin|is_a|distributed_tracing_system|1.0
opentelemetry|is_a|observability_framework|1.0
opentelemetry|collects|traces_metrics_logs|1.0
three_pillars|of_observability|metrics_logs_traces|1.0
sli|stands_for|service_level_indicator|1.0
slo|stands_for|service_level_objective|1.0
sla|stands_for|service_level_agreement|1.0
error_budget|is|allowed_unreliability|1.0
alertmanager|routes|prometheus_alerts|1.0
pagerduty|is_a|incident_management_tool|1.0
datadog|is_a|monitoring_platform|1.0
new_relic|is_a|observability_platform|1.0

# === GITOPS AND IAC ===
gitops|uses|git_as_source_of_truth|1.0
gitops|principle|declarative_desired_state|1.0
gitops|principle|automatic_reconciliation|1.0
infrastructure_as_code|manages|infrastructure_through_code|1.0
idempotent|same_result|regardless_of_runs|1.0
declarative|specifies|desired_state_not_steps|1.0
imperative|specifies|exact_steps_to_perform|1.0
drift_detection|finds|config_differences|1.0
policy_as_code|enforces|rules_programmatically|1.0
secret_management|tools|vault_sops_sealed_secrets|1.0
vault|is_a|secret_management_tool|1.0
sops|encrypts|yaml_json_secrets|1.0
external_secrets|syncs|secrets_from_provider|1.0

# === SRE PRACTICES ===
sre|stands_for|site_reliability_engineering|1.0
sre|created_by|google|1.0
toil|is|repetitive_manual_work|1.0
error_budget_policy|defines|actions_when_budget_spent|1.0
postmortem|analyzes|incidents_blamlessly|1.0
chaos_engineering|deliberately|injects_failures|1.0
chaos_monkey|randomly|kills_instances|1.0
game_day|is|planned_failure_exercise|1.0
runbook|documents|operational_procedures|1.0
on_call|is|24_7_availability|1.0
incident_management|process|detect_respond_resolve_learn|1.0
mean_time_to_detect|measures|detection_speed|1.0
mean_time_to_resolve|measures|resolution_speed|1.0
availability|measured_as|uptime_percentage|1.0
five_nines|is|99.999_percent_uptime|1.0
four_nines|is|99.99_percent_uptime|1.0
capacity_planning|forecasts|resource_needs|1.0
load_testing|simulates|production_traffic|1.0
performance_testing|identifies|bottlenecks|1.0

# === DATABASES ===
postgresql|is_a|relational_database|1.0
postgresql|supports|json_full_text_search|1.0
mysql|is_a|relational_database|1.0
mariadb|is_a|mysql_fork|1.0
mongodb|is_a|document_database|1.0
redis|is_a|in_memory_datastore|1.0
redis|used_for|caching_sessions_queues|1.0
cassandra|is_a|wide_column_database|1.0
cassandra|designed_for|high_write_throughput|1.0
cockroachdb|is_a|distributed_sql_database|1.0
timescaledb|is_a|time_series_database|1.0
influxdb|is_a|time_series_database|1.0
neo4j|is_a|graph_database|1.0
clickhouse|is_a|column_oriented_database|1.0
clickhouse|optimized_for|analytics|1.0
vitess|scales|mysql_horizontally|1.0
pgbouncer|is_a|postgresql_connection_pooler|1.0
database_replication|copies|data_to_replicas|1.0
read_replica|handles|read_queries|1.0
write_ahead_log|ensures|durability|1.0
sharding|splits|data_across_servers|1.0
cap_theorem|states|consistency_availability_partition_tolerance|1.0
acid|stands_for|atomicity_consistency_isolation_durability|1.0
base|stands_for|basically_available_soft_state_eventually_consistent|1.0
eventual_consistency|data|converges_over_time|1.0
strong_consistency|reads|always_return_latest_write|1.0

# === MESSAGE QUEUES AND STREAMING ===
kafka|is_a|distributed_streaming_platform|1.0
kafka|uses|topics_and_partitions|1.0
kafka|provides|at_least_once_delivery|1.0
rabbitmq|is_a|message_broker|1.0
rabbitmq|uses|amqp_protocol|1.0
nats|is_a|messaging_system|1.0
nats|designed_for|cloud_native|1.0
pulsar|is_a|distributed_messaging|1.0
event_driven_architecture|uses|events_for_communication|1.0
pub_sub|pattern|publisher_subscriber|1.0
message_queue|decouples|producers_and_consumers|1.0
dead_letter_queue|holds|failed_messages|1.0
exactly_once_semantics|guarantees|no_duplicate_processing|1.0
stream_processing|processes|data_in_real_time|1.0
batch_processing|processes|data_in_chunks|1.0
apache_flink|is_a|stream_processor|1.0
apache_spark|is_a|data_processing_framework|1.0

# === MICROSERVICES ===
microservices|decomposes|application_into_services|1.0
monolith|is|single_deployable_unit|1.0
api_gateway|routes|requests_to_services|1.0
api_gateway|handles|auth_rate_limiting|1.0
service_discovery|finds|service_instances|1.0
consul|is_a|service_discovery_tool|1.0
circuit_breaker|prevents|cascade_failures|1.0
bulkhead|isolates|failure_domains|1.0
retry_pattern|handles|transient_failures|1.0
saga_pattern|manages|distributed_transactions|1.0
cqrs|stands_for|command_query_responsibility_segregation|1.0
event_sourcing|stores|state_as_event_log|1.0
domain_driven_design|structures|around_business_domains|1.0
bounded_context|defines|model_boundaries|1.0
sidecar_pattern|runs|alongside_main_service|1.0
strangler_pattern|migrates|from_monolith_gradually|1.0
backend_for_frontend|creates|api_per_client_type|1.0
grpc|is_a|rpc_framework|1.0
rest|is_a|api_architectural_style|1.0
graphql|is_a|query_language_for_apis|1.0

# === CONTAINER ECOSYSTEM ===
docker_swarm|is_a|container_orchestrator|1.0
nomad|is_a|workload_orchestrator|1.0
buildpacks|create|container_images_from_source|1.0
kaniko|builds|images_without_docker_daemon|1.0
harbor|is_a|container_registry|1.0
cosign|signs|container_images|1.0
distroless|is_a|minimal_container_image|1.0
multi_stage_build|reduces|image_size|1.0
scratch_image|is|empty_base_image|1.0
alpine|is_a|minimal_linux_for_containers|1.0
docker_compose|defines|multi_container_apps|1.0
podman_compose|is_a|docker_compose_alternative|1.0
containerd|is_a|container_runtime|1.0
cri|stands_for|container_runtime_interface|1.0
oci|stands_for|open_container_initiative|1.0

# === NETWORKING FOR DEVOPS ===
service_mesh|provides|mtls_observability_traffic_control|1.0
ingress_nginx|is_a|popular_ingress_controller|1.0
traefik|is_a|reverse_proxy|1.0
caddy|is_a|web_server_with_auto_tls|1.0
nginx|is_a|web_server_reverse_proxy|1.0
haproxy|is_a|tcp_http_load_balancer|1.0
dns_based_routing|routes|by_hostname|1.0
path_based_routing|routes|by_url_path|1.0
internal_load_balancer|routes|within_cluster|1.0
external_load_balancer|routes|from_internet|1.0
ssl_termination|at|load_balancer_or_ingress|1.0
certificate_manager|automates|tls_certificates|1.0
letsencrypt|provides|free_tls_certificates|1.0
cert_manager|automates|k8s_certificate_management|1.0
mutual_tls|authenticates|both_client_and_server|1.0
calico|is_a|k8s_network_plugin|1.0
cilium|is_a|ebpf_based_networking|1.0
flannel|is_a|simple_k8s_network|1.0
weave|is_a|k8s_network_plugin|1.0
coredns|is_a|dns_server_for_k8s|1.0

# === COST OPTIMIZATION ===
spot_instances|are|discounted_interruptible_vms|1.0
reserved_instances|offer|discount_for_commitment|1.0
savings_plans|offer|flexible_discount_commitment|1.0
right_sizing|matches|resources_to_workload|1.0
auto_scaling|adjusts|capacity_to_demand|1.0
cluster_autoscaler|adds_removes|k8s_nodes|1.0
karpenter|is_a|k8s_node_provisioner|1.0
finops|optimizes|cloud_spending|1.0
tagging|enables|cost_allocation|1.0
cost_explorer|analyzes|cloud_spending|1.0

# === SECURITY IN DEVOPS ===
devsecops|integrates|security_in_pipeline|1.0
sast|scans|source_code_for_vulnerabilities|1.0
dast|tests|running_application|1.0
container_scanning|checks|image_vulnerabilities|1.0
dependency_scanning|checks|library_vulnerabilities|1.0
secret_detection|finds|leaked_credentials_in_code|1.0
supply_chain_security|verifies|build_integrity|1.0
sbom|tracks|software_components|1.0
sigstore|signs|software_artifacts|1.0
slsa|framework_for|supply_chain_security|1.0
admission_webhook|validates|k8s_resources|1.0
pod_security_standards|define|security_levels|1.0
seccomp|restricts|container_syscalls|1.0
apparmor|confines|container_processes|1.0

# === CONFIGURATION MANAGEMENT ===
chef|is_a|configuration_management_tool|1.0
puppet|is_a|configuration_management_tool|1.0
saltstack|is_a|configuration_management_tool|1.0
ansible_playbook|defines|automation_tasks|1.0
ansible_role|packages|reusable_tasks|1.0
ansible_inventory|lists|managed_hosts|1.0
idempotency|ensures|same_outcome_every_run|1.0
desired_state_configuration|describes|intended_system_state|1.0
configuration_drift|is|unplanned_state_change|1.0

# === DEVELOPER EXPERIENCE ===
platform_engineering|builds|internal_developer_platform|1.0
backstage|is_a|developer_portal|1.0
backstage|created_by|spotify|1.0
internal_developer_platform|provides|self_service_infrastructure|1.0
developer_productivity|measured_by|dora_metrics|1.0
dora_metrics|include|deployment_frequency_lead_time|1.0
change_failure_rate|is_a|dora_metric|1.0
mean_time_to_recovery|is_a|dora_metric|1.0
shift_left|moves|testing_earlier_in_pipeline|1.0
ephemeral_environments|created_per|pull_request|1.0
preview_environments|show|changes_before_merge|1.0
development_container|provides|consistent_dev_environment|1.0
devcontainer|defines|reproducible_dev_setup|1.0
codespace|is_a|cloud_dev_environment|1.0
gitpod|is_a|cloud_dev_environment|1.0

# === STORAGE AND BACKUP ===
object_storage|stores|unstructured_data|1.0
block_storage|provides|raw_storage_volumes|1.0
file_storage|provides|shared_filesystem|1.0
backup_strategy|follows|3_2_1_rule|1.0
3_2_1_rule|means|3_copies_2_media_1_offsite|1.0
rpo|stands_for|recovery_point_objective|1.0
rto|stands_for|recovery_time_objective|1.0
disaster_recovery|plans_for|catastrophic_failure|1.0
hot_standby|provides|immediate_failover|1.0
cold_standby|provides|delayed_failover|1.0
velero|backs_up|kubernetes_resources|1.0
restic|is_a|backup_tool|1.0
snapshot|captures|point_in_time_state|1.0
incremental_backup|stores|only_changes|1.0
deduplication|eliminates|duplicate_data|1.0

# === ADDITIONAL CLOUD PATTERNS ===
twelve_factor_app|principle_1|one_codebase_per_app|1.0
twelve_factor_app|principle_3|store_config_in_environment|1.0
twelve_factor_app|principle_6|execute_as_stateless_processes|1.0
twelve_factor_app|principle_9|maximize_robustness_with_fast_startup|1.0
twelve_factor_app|principle_11|treat_logs_as_event_streams|1.0
immutable_infrastructure|replaces|rather_than_updates|1.0
cattle_not_pets|servers_are|replaceable|1.0
phoenix_server|rebuilt|from_scratch_regularly|1.0
infrastructure_testing|validates|iac_correctness|1.0
terratest|tests|terraform_code|1.0
localstack|emulates|aws_services_locally|1.0
minio|emulates|s3_api_locally|1.0
kind|runs|k8s_in_docker|1.0
k3s|is_a|lightweight_kubernetes|1.0
minikube|runs|local_k8s_cluster|1.0
tilt|is_a|local_k8s_dev_tool|1.0
skaffold|is_a|k8s_dev_workflow_tool|1.0
aws_fargate|is_a|serverless_container_service|1.0
aws_step_functions|orchestrates|serverless_workflows|1.0
aws_eventbridge|is_a|event_bus|1.0
aws_kinesis|is_a|streaming_service|1.0
aws_codepipeline|is_a|ci_cd_service|1.0
aws_cloudformation|is_a|iac_service|1.0
aws_cdk|is_a|infrastructure_sdk|1.0
gcp_cloud_build|is_a|ci_cd_service|1.0
gcp_pub_sub|is_a|messaging_service|1.0
gcp_spanner|is_a|globally_distributed_database|1.0
gcp_dataflow|is_a|stream_batch_processor|1.0
azure_devops|is_a|devops_platform|1.0
azure_container_apps|is_a|serverless_containers|1.0
azure_event_hubs|is_a|streaming_platform|1.0
api_versioning|manages|backward_compatibility|1.0
contract_testing|validates|service_interfaces|1.0
pact|is_a|contract_testing_tool|1.0
smoke_test|verifies|basic_functionality|1.0
integration_test|verifies|component_interaction|1.0
end_to_end_test|verifies|full_user_journey|1.0
synthetic_monitoring|simulates|user_interactions|1.0
real_user_monitoring|measures|actual_user_experience|1.0
apm|stands_for|application_performance_monitoring|1.0
distributed_tracing|tracks|requests_across_services|1.0
span|is_a|unit_of_work_in_trace|1.0
trace_context|propagates|across_service_boundaries|1.0
w3c_trace_context|is_a|standard_for_tracing|1.0
baggage|carries|metadata_across_services|1.0
log_correlation|links|logs_to_traces|1.0
exemplar|links|metrics_to_traces|1.0

# === ADDITIONAL UNIQUE DEVOPS FACTS ===
artifact_signing|verifies|build_authenticity|1.0
reproducible_build|produces|identical_output|1.0
hermetic_build|no|external_dependencies_during_build|1.0
bazel|is_a|build_system|1.0
bazel|advantage|reproducible_incremental|1.0
buck2|is_a|meta_build_system|1.0
gradle|is_a|build_tool_for_jvm|1.0
maven|is_a|build_tool_for_java|1.0
nix_build|provides|reproducible_builds|1.0
container_layer_caching|speeds_up|docker_builds|1.0
build_cache|stores|previous_build_artifacts|1.0
remote_cache|shares|build_cache_across_ci|1.0
monorepo|stores|all_code_in_one_repo|1.0
polyrepo|stores|code_in_many_repos|1.0
monorepo_tools|include|nx_turborepo_bazel|1.0
dependency_graph|tracks|package_relationships|1.0
lockfile|pins|exact_dependency_versions|1.0
semantic_versioning|format|major_minor_patch|1.0
breaking_change|requires|major_version_bump|1.0
changelog_automation|generates|from_commit_messages|1.0
conventional_commits|format|type_scope_description|1.0
release_automation|tools|semantic_release_release_please|1.0
feature_branch_workflow|develops|in_isolated_branches|1.0
trunk_based|commits|directly_to_main|1.0
short_lived_branches|merge|within_hours_or_days|1.0
long_lived_branches|cause|merge_conflicts|0.8
merge_queue|serializes|pull_request_merges|1.0
branch_protection|requires|reviews_before_merge|1.0
status_checks|must_pass|before_merge|1.0
code_owners|assigns|reviewers_by_path|1.0
auto_merge|merges|when_all_checks_pass|1.0
dependabot|updates|dependencies_automatically|1.0
renovate|updates|dependencies_automatically|1.0
green_build|means|all_tests_passing|1.0
broken_build|blocks|team_progress|1.0
build_sheriff|fixes|broken_builds_quickly|1.0
flaky_test|passes|inconsistently|1.0
test_quarantine|isolates|flaky_tests|1.0
test_parallelization|speeds_up|test_suite|1.0
test_sharding|distributes|tests_across_workers|1.0
test_impact_analysis|runs_only|affected_tests|1.0
binary_promotion|promotes|same_artifact_through_stages|1.0
environment_parity|keeps|staging_similar_to_prod|1.0
configuration_drift_detection|alerts_on|unexpected_changes|1.0
reconciliation_loop|continuously|aligns_actual_with_desired|1.0
self_healing_infrastructure|automatically|recovers_from_failures|1.0
predictive_autoscaling|scales|before_demand_spike|1.0
cluster_autoscaler_priority|prefers|cheaper_instance_types|1.0
pod_topology_spread|distributes|pods_across_zones|1.0
pod_affinity|co_locates|related_pods|1.0
pod_anti_affinity|separates|competing_pods|1.0
node_selector|targets|specific_node_labels|1.0
taint_and_toleration|reserves|nodes_for_workloads|1.0
priority_class|determines|pod_scheduling_priority|1.0
resource_quota|limits|namespace_resource_usage|1.0
limit_range|sets|default_resource_limits|1.0
vertical_pod_autoscaler|adjusts|resource_requests|1.0
horizontal_pod_autoscaler|adjusts|replica_count|1.0
custom_metrics_autoscaling|scales_on|application_metrics|1.0
