bitcoin|is_a|cryptocurrency|1.0
bitcoin|created_by|satoshi_nakamoto|1.0
bitcoin|launched_in|2009|1.0
bitcoin|uses|proof_of_work|1.0
bitcoin|symbol|BTC|1.0
bitcoin|max_supply|21_million|1.0
bitcoin|halving_interval|4_years|1.0
bitcoin|block_time|10_minutes|1.0
bitcoin|consensus|nakamoto_consensus|1.0
ethereum|is_a|smart_contract_platform|1.0
ethereum|created_by|vitalik_buterin|1.0
ethereum|symbol|ETH|1.0
ethereum|uses|proof_of_stake|1.0
ethereum|supports|smart_contracts|1.0
ethereum|has|evm|1.0
ethereum|merged_to|proof_of_stake_2022|1.0
ethereum|block_time|12_seconds|1.0
evm|stands_for|ethereum_virtual_machine|1.0
evm|executes|smart_contracts|1.0
evm|compatible_chains|polygon|1.0
evm|compatible_chains|bsc|1.0
evm|compatible_chains|avalanche|1.0
evm|compatible_chains|arbitrum|1.0
solidity|is_a|programming_language|1.0
solidity|used_for|ethereum_smart_contracts|1.0
solidity|similar_to|javascript|0.7
defi|stands_for|decentralized_finance|1.0
defi|eliminates|intermediaries|1.0
defi|uses|smart_contracts|1.0
defi|enables|permissionless_finance|1.0
defi|total_value_locked|billions_usd|0.9
dex|is_a|decentralized_exchange|1.0
dex|enables|token_swaps|1.0
dex|no_need_for|kyc|1.0
dex|uses|liquidity_pools|1.0
uniswap|is_a|dex|1.0
uniswap|runs_on|ethereum|1.0
uniswap|uses|amm|1.0
uniswap|token|UNI|1.0
uniswap|version|v3|1.0
sushiswap|is_a|dex|1.0
sushiswap|forked_from|uniswap|1.0
sushiswap|token|SUSHI|1.0
pancakeswap|is_a|dex|1.0
pancakeswap|runs_on|bsc|1.0
pancakeswap|token|CAKE|1.0
curve_finance|is_a|dex|1.0
curve_finance|specialized_in|stablecoins|1.0
curve_finance|token|CRV|1.0
amm|stands_for|automated_market_maker|1.0
amm|uses|constant_product_formula|1.0
amm|formula|x_times_y_equals_k|1.0
amm|replaces|order_book|1.0
liquidity_pool|is_a|token_pair_reserve|1.0
liquidity_pool|provides|trading_liquidity|1.0
liquidity_pool|earns|trading_fees|1.0
liquidity_provider|deposits_into|liquidity_pool|1.0
liquidity_provider|earns|fee_share|1.0
liquidity_provider|risks|impermanent_loss|1.0
impermanent_loss|occurs_when|price_diverges|1.0
impermanent_loss|higher_with|volatile_pairs|1.0
impermanent_loss|becomes_permanent|if_withdrawn|1.0
yield_farming|is_a|defi_strategy|1.0
yield_farming|involves|providing_liquidity|1.0
yield_farming|earns|token_rewards|1.0
yield_farming|risks_include|impermanent_loss|1.0
yield_farming|risks_include|smart_contract_bugs|1.0
apy|stands_for|annual_percentage_yield|1.0
apy|includes|compound_interest|1.0
apr|stands_for|annual_percentage_rate|1.0
apr|does_not_include|compounding|1.0
staking|is_a|defi_activity|1.0
staking|involves|locking_tokens|1.0
staking|earns|staking_rewards|1.0
staking|secures|proof_of_stake_networks|1.0
liquid_staking|is_a|staking_variant|1.0
liquid_staking|provides|staked_token_derivative|1.0
lido|is_a|liquid_staking_protocol|1.0
lido|provides|stETH|1.0
lido|token|LDO|1.0
rocket_pool|is_a|liquid_staking_protocol|1.0
rocket_pool|provides|rETH|1.0
rocket_pool|is|decentralized|1.0
lending_protocol|is_a|defi_category|1.0
lending_protocol|enables|borrowing|1.0
lending_protocol|enables|lending|1.0
lending_protocol|uses|overcollateralization|1.0
aave|is_a|lending_protocol|1.0
aave|token|AAVE|1.0
aave|supports|flash_loans|1.0
aave|multi_chain|true|1.0
compound|is_a|lending_protocol|1.0
compound|token|COMP|1.0
compound|runs_on|ethereum|1.0
flash_loan|is_a|defi_innovation|1.0
flash_loan|requires|same_transaction_repay|1.0
flash_loan|no_collateral|needed|1.0
flash_loan|used_for|arbitrage|1.0
stablecoin|is_a|cryptocurrency|1.0
stablecoin|pegged_to|fiat_currency|1.0
stablecoin|provides|price_stability|1.0
usdt|is_a|stablecoin|1.0
usdt|pegged_to|us_dollar|1.0
usdt|issued_by|tether|1.0
usdc|is_a|stablecoin|1.0
usdc|pegged_to|us_dollar|1.0
usdc|issued_by|circle|1.0
dai|is_a|stablecoin|1.0
dai|is|decentralized|1.0
dai|backed_by|crypto_collateral|1.0
dai|managed_by|makerdao|1.0
makerdao|is_a|defi_protocol|1.0
makerdao|token|MKR|1.0
makerdao|issues|dai|1.0
layer_2|is_a|scaling_solution|1.0
layer_2|processes_transactions|off_chain|1.0
layer_2|settles_on|layer_1|1.0
layer_2|reduces|gas_fees|1.0
rollup|is_a|layer_2_type|1.0
optimistic_rollup|is_a|rollup_type|1.0
optimistic_rollup|assumes|transactions_valid|1.0
optimistic_rollup|has|fraud_proof_window|1.0
zk_rollup|is_a|rollup_type|1.0
zk_rollup|uses|zero_knowledge_proofs|1.0
zk_rollup|faster_finality_than|optimistic_rollup|1.0
arbitrum|is_a|layer_2|1.0
arbitrum|type|optimistic_rollup|1.0
arbitrum|token|ARB|1.0
optimism|is_a|layer_2|1.0
optimism|type|optimistic_rollup|1.0
optimism|token|OP|1.0
polygon|is_a|scaling_solution|1.0
polygon|token|MATIC|1.0
polygon|evm_compatible|true|1.0
zksync|is_a|layer_2|1.0
zksync|type|zk_rollup|1.0
starknet|is_a|layer_2|1.0
starknet|type|zk_rollup|1.0
starknet|uses|cairo_language|1.0
base|is_a|layer_2|1.0
base|built_by|coinbase|1.0
base|type|optimistic_rollup|1.0
solana|is_a|blockchain|1.0
solana|symbol|SOL|1.0
solana|known_for|high_throughput|1.0
solana|block_time|400_milliseconds|1.0
solana|consensus|proof_of_history|1.0
avalanche|is_a|blockchain|1.0
avalanche|symbol|AVAX|1.0
avalanche|uses|subnets|1.0
avalanche|consensus|avalanche_consensus|1.0
cosmos|is_a|blockchain_ecosystem|1.0
cosmos|token|ATOM|1.0
cosmos|uses|tendermint|1.0
cosmos|enables|interchain_communication|1.0
polkadot|is_a|blockchain|1.0
polkadot|token|DOT|1.0
polkadot|uses|parachains|1.0
polkadot|created_by|gavin_wood|1.0
nft|stands_for|non_fungible_token|1.0
nft|represents|unique_digital_asset|1.0
nft|standard|erc721|1.0
nft|standard|erc1155|1.0
opensea|is_a|nft_marketplace|1.0
blur|is_a|nft_marketplace|1.0
oracle|is_a|blockchain_data_feed|1.0
oracle|provides|off_chain_data|1.0
chainlink|is_a|oracle_network|1.0
chainlink|token|LINK|1.0
chainlink|provides|price_feeds|1.0
wallet|is_a|crypto_tool|1.0
wallet|stores|private_keys|1.0
wallet|types_include|hot_wallet|1.0
wallet|types_include|cold_wallet|1.0
metamask|is_a|browser_wallet|1.0
metamask|supports|ethereum|1.0
metamask|supports|evm_chains|1.0
ledger|is_a|hardware_wallet|1.0
ledger|is_a|cold_wallet|1.0
private_key|controls|wallet_funds|1.0
private_key|must_be|kept_secret|1.0
seed_phrase|is_a|backup_method|1.0
seed_phrase|has|12_or_24_words|1.0
seed_phrase|recovers|wallet_access|1.0
gas|is_a|transaction_fee|1.0
gas|paid_in|native_token|1.0
gas|higher_during|network_congestion|1.0
gas_limit|is|max_gas_units|1.0
gas_price|measured_in|gwei|1.0
gwei|is|0.000000001_ETH|1.0
slippage|is_a|trading_concept|1.0
slippage|occurs_when|price_moves_during_trade|1.0
slippage|higher_with|low_liquidity|1.0
mev|stands_for|maximal_extractable_value|1.0
mev|exploits|transaction_ordering|1.0
mev|types_include|frontrunning|1.0
mev|types_include|sandwich_attack|1.0
frontrunning|is_a|mev_strategy|1.0
frontrunning|places_order|before_user|1.0
sandwich_attack|is_a|mev_strategy|1.0
sandwich_attack|surrounds|user_transaction|1.0
technical_analysis|is_a|trading_method|1.0
technical_analysis|uses|price_charts|1.0
technical_analysis|uses|indicators|1.0
rsi|stands_for|relative_strength_index|1.0
rsi|range|0_to_100|1.0
rsi|oversold_below|30|1.0
rsi|overbought_above|70|1.0
macd|stands_for|moving_average_convergence_divergence|1.0
macd|shows|momentum|1.0
macd|uses|two_emas|1.0
bollinger_bands|is_a|volatility_indicator|1.0
bollinger_bands|uses|standard_deviation|1.0
bollinger_bands|has|upper_middle_lower_bands|1.0
moving_average|is_a|trend_indicator|1.0
ema|stands_for|exponential_moving_average|1.0
sma|stands_for|simple_moving_average|1.0
golden_cross|is_a|bullish_signal|1.0
golden_cross|occurs_when|50ma_crosses_above_200ma|1.0
death_cross|is_a|bearish_signal|1.0
death_cross|occurs_when|50ma_crosses_below_200ma|1.0
support_level|is_a|price_floor|1.0
resistance_level|is_a|price_ceiling|1.0
fibonacci_retracement|is_a|technical_tool|1.0
fibonacci_retracement|levels|23.6_38.2_50_61.8|1.0
volume|is_a|trading_indicator|1.0
volume|confirms|price_movements|1.0
vwap|stands_for|volume_weighted_average_price|1.0
candlestick|is_a|chart_type|1.0
candlestick|shows|open_high_low_close|1.0
doji|is_a|candlestick_pattern|1.0
doji|indicates|indecision|1.0
hammer|is_a|candlestick_pattern|1.0
hammer|indicates|potential_reversal|1.0
bull_market|is_a|market_condition|1.0
bull_market|characterized_by|rising_prices|1.0
bear_market|is_a|market_condition|1.0
bear_market|characterized_by|falling_prices|1.0
dca|stands_for|dollar_cost_averaging|1.0
dca|strategy|buy_regularly_regardless_of_price|1.0
dca|reduces|timing_risk|1.0
stop_loss|is_a|risk_management_tool|1.0
stop_loss|automatically|sells_at_price|1.0
stop_loss|limits|downside_losses|1.0
take_profit|is_a|trading_order|1.0
take_profit|locks_in|gains_at_target|1.0
position_sizing|is_a|risk_strategy|1.0
position_sizing|limits|exposure_per_trade|1.0
risk_reward_ratio|measures|potential_gain_vs_loss|1.0
risk_reward_ratio|good_minimum|1_to_2|1.0
leverage|amplifies|gains_and_losses|1.0
leverage|risky_because|liquidation_possible|1.0
liquidation|occurs_when|margin_insufficient|1.0
funding_rate|is_a|perpetual_futures_mechanism|1.0
funding_rate|balances|long_short_positions|1.0
perpetual_futures|is_a|derivative|1.0
perpetual_futures|no|expiry_date|1.0
airdrop|is_a|token_distribution|1.0
airdrop|given_to|early_users|1.0
airdrop|rewards|protocol_interaction|1.0
airdrop|criteria_include|transaction_count|1.0
airdrop|criteria_include|volume_traded|1.0
airdrop|criteria_include|time_of_usage|1.0
airdrop_farming|is_a|strategy|1.0
airdrop_farming|involves|using_protocols_early|1.0
airdrop_farming|requires|patience|1.0
sybil_resistance|prevents|multiple_airdrop_claims|1.0
governance_token|is_a|token_type|1.0
governance_token|grants|voting_rights|1.0
governance_token|controls|protocol_parameters|1.0
dao|stands_for|decentralized_autonomous_organization|1.0
dao|uses|governance_tokens|1.0
dao|makes_decisions|through_voting|1.0
tvl|stands_for|total_value_locked|1.0
tvl|measures|defi_protocol_size|1.0
smart_contract|is_a|self_executing_program|1.0
smart_contract|runs_on|blockchain|1.0
smart_contract|immutable_once|deployed|1.0
smart_contract_audit|is_a|security_review|1.0
smart_contract_audit|identifies|vulnerabilities|1.0
rug_pull|is_a|crypto_scam|1.0
rug_pull|developers|remove_liquidity|1.0
rug_pull|common_in|new_tokens|1.0
whale|is_a|large_holder|1.0
whale|can_move|markets|0.9
whale_watching|is_a|analysis_method|1.0
whale_watching|tracks|large_transactions|1.0
on_chain_analysis|is_a|analysis_method|1.0
on_chain_analysis|examines|blockchain_data|1.0
on_chain_analysis|reveals|wallet_movements|1.0
defi_aggregator|is_a|tool|1.0
defi_aggregator|finds|best_swap_rates|1.0
1inch|is_a|defi_aggregator|1.0
paraswap|is_a|defi_aggregator|1.0
bridge|is_a|cross_chain_tool|1.0
bridge|transfers|assets_between_chains|1.0
bridge|risks_include|exploits|0.9
multichain|is_a|bridge_protocol|1.0
wormhole|is_a|bridge_protocol|1.0
token_standard|is_a|smart_contract_interface|1.0
erc20|is_a|token_standard|1.0
erc20|for|fungible_tokens|1.0
erc721|is_a|token_standard|1.0
erc721|for|non_fungible_tokens|1.0
erc1155|is_a|token_standard|1.0
erc1155|for|multi_token_standard|1.0
gas_optimization|is_a|development_practice|1.0
gas_optimization|reduces|transaction_costs|1.0
mempool|is_a|transaction_queue|1.0
mempool|holds|unconfirmed_transactions|1.0
block_explorer|is_a|blockchain_tool|1.0
block_explorer|shows|transaction_history|1.0
etherscan|is_a|block_explorer|1.0
etherscan|for|ethereum|1.0
dexscreener|is_a|trading_tool|1.0
dexscreener|shows|dex_trading_data|1.0
coingecko|is_a|price_aggregator|1.0
coinmarketcap|is_a|price_aggregator|1.0
defillama|is_a|defi_analytics|1.0
defillama|tracks|tvl|1.0
market_cap|is_a|valuation_metric|1.0
market_cap|equals|price_times_supply|1.0
fully_diluted_valuation|includes|all_future_tokens|1.0
circulating_supply|is|tokens_currently_available|1.0
max_supply|is|maximum_tokens_possible|1.0
token_burning|reduces|total_supply|1.0
token_burning|can_increase|price|0.7
vesting_schedule|controls|token_release|1.0
vesting_schedule|prevents|immediate_dumping|1.0
cliff|is_a|vesting_term|1.0
cliff|delays|first_token_release|1.0
