#!/usr/bin/env python3
"""
MK OS - Bulk Knowledge Generator
Generates .mk files with pipe-delimited facts (source|relation|target|weight)
Covers: programming languages, countries/capitals, scientists, animals, food,
        music genres, sports, business terms
Output: ai_core/hre/knowledge_files/
"""

import os

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          '..', 'ai_core', 'hre', 'knowledge_files')

def write_mk_file(filename, header, facts):
    """Write facts to a .mk file."""
    path = os.path.join(OUTPUT_DIR, filename)
    with open(path, 'w') as f:
        f.write(f"# {header}\n")
        f.write("# Format: source|relation|target|weight\n")
        f.write(f"# Auto-generated by generate_knowledge.py\n\n")
        for fact in facts:
            f.write(f"{fact}\n")
    print(f"  Written {len(facts)} facts to {filename}")

def gen_programming():
    """Generate programming language facts."""
    facts = []
    langs = {
        "python": {"creator": "guido van rossum", "year": "1991", "paradigm": "multi-paradigm",
                   "typing": "dynamically typed", "use": "web development",
                   "features": ["list comprehension", "generators", "decorators", "duck typing"]},
        "javascript": {"creator": "brendan eich", "year": "1995", "paradigm": "multi-paradigm",
                       "typing": "dynamically typed", "use": "web development",
                       "features": ["closures", "prototypal inheritance", "async await", "event loop"]},
        "java": {"creator": "james gosling", "year": "1995", "paradigm": "object oriented",
                 "typing": "statically typed", "use": "enterprise applications",
                 "features": ["garbage collection", "jvm", "generics", "interfaces"]},
        "c++": {"creator": "bjarne stroustrup", "year": "1985", "paradigm": "multi-paradigm",
                "typing": "statically typed", "use": "system programming",
                "features": ["templates", "raii", "operator overloading", "multiple inheritance"]},
        "rust": {"creator": "graydon hoare", "year": "2010", "paradigm": "multi-paradigm",
                 "typing": "statically typed", "use": "system programming",
                 "features": ["ownership system", "borrowing", "zero cost abstractions", "pattern matching"]},
    }

    more_langs = {
        "c": {"creator": "dennis ritchie", "year": "1972", "paradigm": "procedural",
              "typing": "statically typed", "use": "operating systems",
              "features": ["pointers", "manual memory management", "preprocessor", "structs"]},
        "go": {"creator": "rob pike", "year": "2009", "paradigm": "concurrent",
               "typing": "statically typed", "use": "cloud infrastructure",
               "features": ["goroutines", "channels", "garbage collection", "interfaces"]},
        "swift": {"creator": "chris lattner", "year": "2014", "paradigm": "multi-paradigm",
                  "typing": "statically typed", "use": "ios development",
                  "features": ["optionals", "protocol oriented", "type inference", "closures"]},
        "kotlin": {"creator": "jetbrains", "year": "2011", "paradigm": "multi-paradigm",
                   "typing": "statically typed", "use": "android development",
                   "features": ["null safety", "coroutines", "extension functions", "data classes"]},
        "typescript": {"creator": "anders hejlsberg", "year": "2012", "paradigm": "multi-paradigm",
                       "typing": "statically typed", "use": "web development",
                       "features": ["type annotations", "interfaces", "generics", "union types"]},
        "ruby": {"creator": "yukihiro matsumoto", "year": "1995", "paradigm": "object oriented",
                 "typing": "dynamically typed", "use": "web development",
                 "features": ["blocks", "mixins", "metaprogramming", "duck typing"]},
        "php": {"creator": "rasmus lerdorf", "year": "1995", "paradigm": "multi-paradigm",
                "typing": "dynamically typed", "use": "web development",
                "features": ["templating", "arrays", "namespaces", "traits"]},
        "scala": {"creator": "martin odersky", "year": "2004", "paradigm": "functional",
                  "typing": "statically typed", "use": "data processing",
                  "features": ["pattern matching", "traits", "implicits", "case classes"]},
        "haskell": {"creator": "committee", "year": "1990", "paradigm": "functional",
                    "typing": "statically typed", "use": "academic research",
                    "features": ["lazy evaluation", "monads", "type classes", "pattern matching"]},
        "elixir": {"creator": "jose valim", "year": "2011", "paradigm": "functional",
                   "typing": "dynamically typed", "use": "distributed systems",
                   "features": ["pattern matching", "pipe operator", "processes", "supervision trees"]},
    }
    langs.update(more_langs)

    for lang, info in langs.items():
        facts.append(f"{lang}|is_a|programming language|1.0")
        facts.append(f"{lang}|created_by|{info['creator']}|1.0")
        facts.append(f"{lang}|created_in|{info['year']}|1.0")
        facts.append(f"{lang}|paradigm_is|{info['paradigm']}|0.9")
        facts.append(f"{lang}|typing_is|{info['typing']}|1.0")
        facts.append(f"{lang}|used_for|{info['use']}|0.9")
        for feat in info['features']:
            facts.append(f"{lang}|has_feature|{feat}|0.85")

    # Frameworks and tools
    frameworks = [
        ("react", "javascript", "frontend framework", "meta"),
        ("angular", "typescript", "frontend framework", "google"),
        ("vue", "javascript", "frontend framework", "evan you"),
        ("django", "python", "web framework", "adrian holovaty"),
        ("flask", "python", "web framework", "armin ronacher"),
        ("spring", "java", "application framework", "rod johnson"),
        ("express", "javascript", "web framework", "tj holowaychuk"),
        ("rails", "ruby", "web framework", "david heinemeier hansson"),
        ("laravel", "php", "web framework", "taylor otwell"),
        ("dotnet", "c sharp", "application framework", "microsoft"),
        ("fastapi", "python", "web framework", "sebastian ramirez"),
        ("nextjs", "javascript", "fullstack framework", "vercel"),
        ("svelte", "javascript", "frontend framework", "rich harris"),
        ("pytorch", "python", "machine learning framework", "meta"),
        ("tensorflow", "python", "machine learning framework", "google"),
        ("pandas", "python", "data analysis library", "wes mckinney"),
        ("numpy", "python", "numerical computing library", "travis oliphant"),
    ]
    for name, lang, kind, creator in frameworks:
        facts.append(f"{name}|is_a|{kind}|1.0")
        facts.append(f"{name}|written_in|{lang}|1.0")
        facts.append(f"{name}|created_by|{creator}|0.95")
        facts.append(f"{name}|used_for|software development|0.9")

    return facts

def gen_countries():
    """Generate country/capital/continent facts."""
    facts = []
    countries = [
        ("united states", "washington dc", "north america", "english", "dollar", "331000000"),
        ("canada", "ottawa", "north america", "english", "canadian dollar", "38000000"),
        ("mexico", "mexico city", "north america", "spanish", "peso", "129000000"),
        ("brazil", "brasilia", "south america", "portuguese", "real", "213000000"),
        ("argentina", "buenos aires", "south america", "spanish", "peso", "45000000"),
        ("colombia", "bogota", "south america", "spanish", "peso", "51000000"),
        ("chile", "santiago", "south america", "spanish", "peso", "19000000"),
        ("peru", "lima", "south america", "spanish", "sol", "33000000"),
        ("united kingdom", "london", "europe", "english", "pound sterling", "67000000"),
        ("france", "paris", "europe", "french", "euro", "67000000"),
        ("germany", "berlin", "europe", "german", "euro", "83000000"),
        ("italy", "rome", "europe", "italian", "euro", "60000000"),
        ("spain", "madrid", "europe", "spanish", "euro", "47000000"),
        ("portugal", "lisbon", "europe", "portuguese", "euro", "10000000"),
        ("netherlands", "amsterdam", "europe", "dutch", "euro", "17000000"),
        ("belgium", "brussels", "europe", "dutch", "euro", "11500000"),
        ("switzerland", "bern", "europe", "german", "swiss franc", "8700000"),
        ("austria", "vienna", "europe", "german", "euro", "9000000"),
        ("sweden", "stockholm", "europe", "swedish", "krona", "10400000"),
        ("norway", "oslo", "europe", "norwegian", "krone", "5400000"),

        ("denmark", "copenhagen", "europe", "danish", "krone", "5800000"),
        ("finland", "helsinki", "europe", "finnish", "euro", "5500000"),
        ("poland", "warsaw", "europe", "polish", "zloty", "38000000"),
        ("greece", "athens", "europe", "greek", "euro", "10700000"),
        ("ireland", "dublin", "europe", "english", "euro", "5000000"),
        ("czech republic", "prague", "europe", "czech", "koruna", "10700000"),
        ("russia", "moscow", "europe", "russian", "ruble", "146000000"),
        ("ukraine", "kyiv", "europe", "ukrainian", "hryvnia", "44000000"),
        ("turkey", "ankara", "asia", "turkish", "lira", "84000000"),
        ("china", "beijing", "asia", "mandarin", "yuan", "1400000000"),
        ("japan", "tokyo", "asia", "japanese", "yen", "126000000"),
        ("south korea", "seoul", "asia", "korean", "won", "52000000"),
        ("india", "new delhi", "asia", "hindi", "rupee", "1380000000"),
        ("indonesia", "jakarta", "asia", "indonesian", "rupiah", "274000000"),
        ("thailand", "bangkok", "asia", "thai", "baht", "70000000"),
        ("vietnam", "hanoi", "asia", "vietnamese", "dong", "97000000"),
        ("philippines", "manila", "asia", "filipino", "peso", "110000000"),
        ("malaysia", "kuala lumpur", "asia", "malay", "ringgit", "32000000"),
        ("singapore", "singapore", "asia", "english", "singapore dollar", "5900000"),
        ("saudi arabia", "riyadh", "asia", "arabic", "riyal", "35000000"),
        ("israel", "jerusalem", "asia", "hebrew", "shekel", "9200000"),
        ("iran", "tehran", "asia", "persian", "rial", "84000000"),
        ("pakistan", "islamabad", "asia", "urdu", "rupee", "221000000"),
        ("bangladesh", "dhaka", "asia", "bengali", "taka", "166000000"),
        ("egypt", "cairo", "africa", "arabic", "pound", "102000000"),
        ("south africa", "pretoria", "africa", "english", "rand", "60000000"),
        ("nigeria", "abuja", "africa", "english", "naira", "211000000"),
        ("kenya", "nairobi", "africa", "swahili", "shilling", "54000000"),
        ("ethiopia", "addis ababa", "africa", "amharic", "birr", "118000000"),
        ("morocco", "rabat", "africa", "arabic", "dirham", "37000000"),
        ("ghana", "accra", "africa", "english", "cedi", "31000000"),
        ("australia", "canberra", "oceania", "english", "australian dollar", "26000000"),
        ("new zealand", "wellington", "oceania", "english", "new zealand dollar", "5100000"),
    ]
    for country, capital, continent, language, currency, population in countries:
        facts.append(f"{country}|is_a|country|1.0")
        facts.append(f"{country}|capital_is|{capital}|1.0")
        facts.append(f"{country}|located_in|{continent}|1.0")
        facts.append(f"{country}|language_is|{language}|0.95")
        facts.append(f"{country}|currency_is|{currency}|0.95")
        facts.append(f"{country}|population_is|{population}|0.85")
        facts.append(f"{capital}|is_a|capital city|1.0")
        facts.append(f"{capital}|capital_of|{country}|1.0")

    return facts


def gen_scientists():
    """Generate famous scientists facts."""
    facts = []
    scientists = [
        ("albert einstein", "physics", "theory of relativity", "1879", "1955", "germany", "nobel prize in physics"),
        ("isaac newton", "physics", "laws of motion", "1643", "1727", "england", "knighthood"),
        ("marie curie", "chemistry", "radioactivity", "1867", "1934", "poland", "nobel prize in physics"),
        ("charles darwin", "biology", "theory of evolution", "1809", "1882", "england", "royal medal"),
        ("nikola tesla", "engineering", "alternating current", "1856", "1943", "serbia", "edison medal"),
        ("galileo galilei", "astronomy", "heliocentric model", "1564", "1642", "italy", "none"),
        ("stephen hawking", "physics", "hawking radiation", "1942", "2018", "england", "presidential medal of freedom"),
        ("richard feynman", "physics", "quantum electrodynamics", "1918", "1988", "united states", "nobel prize in physics"),
        ("niels bohr", "physics", "atomic model", "1885", "1962", "denmark", "nobel prize in physics"),
        ("max planck", "physics", "quantum theory", "1858", "1947", "germany", "nobel prize in physics"),
        ("alan turing", "computer science", "turing machine", "1912", "1954", "england", "order of the british empire"),
        ("ada lovelace", "computer science", "first computer program", "1815", "1852", "england", "none"),
        ("carl sagan", "astronomy", "planetary science", "1934", "1996", "united states", "pulitzer prize"),
        ("james watson", "biology", "dna structure", "1928", "living", "united states", "nobel prize in medicine"),
        ("rosalind franklin", "chemistry", "dna xray crystallography", "1920", "1958", "england", "none"),
        ("erwin schrodinger", "physics", "wave equation", "1887", "1961", "austria", "nobel prize in physics"),
        ("werner heisenberg", "physics", "uncertainty principle", "1901", "1976", "germany", "nobel prize in physics"),
        ("michael faraday", "physics", "electromagnetic induction", "1791", "1867", "england", "royal medal"),
        ("gregor mendel", "biology", "genetics", "1822", "1884", "austria", "none"),
        ("louis pasteur", "biology", "pasteurization", "1822", "1895", "france", "legion of honour"),
        ("alexander fleming", "medicine", "penicillin", "1881", "1955", "scotland", "nobel prize in medicine"),
        ("carl linnaeus", "biology", "taxonomy", "1707", "1778", "sweden", "none"),
        ("dmitri mendeleev", "chemistry", "periodic table", "1834", "1907", "russia", "davy medal"),
        ("thomas edison", "engineering", "light bulb", "1847", "1931", "united states", "congressional gold medal"),
        ("archimedes", "mathematics", "buoyancy principle", "287 bc", "212 bc", "greece", "none"),
        ("pythagoras", "mathematics", "pythagorean theorem", "570 bc", "495 bc", "greece", "none"),
        ("euclid", "mathematics", "euclidean geometry", "300 bc", "unknown", "greece", "none"),
        ("leonardo da vinci", "polymath", "anatomy and engineering", "1452", "1519", "italy", "none"),
        ("johannes kepler", "astronomy", "laws of planetary motion", "1571", "1630", "germany", "none"),
        ("nicolaus copernicus", "astronomy", "heliocentric model", "1473", "1543", "poland", "none"),
    ]
    for name, field, discovery, born, died, country, award in scientists:
        facts.append(f"{name}|is_a|scientist|1.0")
        facts.append(f"{name}|field_is|{field}|1.0")
        facts.append(f"{name}|discovered|{discovery}|0.95")
        facts.append(f"{name}|born_in|{born}|1.0")
        facts.append(f"{name}|died_in|{died}|1.0")
        facts.append(f"{name}|from_country|{country}|1.0")
        if award != "none":
            facts.append(f"{name}|received|{award}|0.95")
    return facts


def gen_animals():
    """Generate animal kingdom facts."""
    facts = []
    animals = [
        ("lion", "mammal", "carnivore", "africa", "savanna", "pride", "10-14 years", ["mane", "retractable claws", "roar"]),
        ("elephant", "mammal", "herbivore", "africa", "savanna", "herd", "60-70 years", ["trunk", "tusks", "large ears"]),
        ("eagle", "bird", "carnivore", "worldwide", "mountains", "pair", "20-30 years", ["sharp talons", "keen eyesight", "wings"]),
        ("dolphin", "mammal", "carnivore", "ocean", "open water", "pod", "40-50 years", ["echolocation", "intelligence", "fins"]),
        ("shark", "fish", "carnivore", "ocean", "open water", "solitary", "20-30 years", ["sharp teeth", "cartilage skeleton", "electroreception"]),
        ("penguin", "bird", "carnivore", "antarctica", "ice", "colony", "15-20 years", ["flippers", "waterproof feathers", "countershading"]),
        ("tiger", "mammal", "carnivore", "asia", "forest", "solitary", "10-15 years", ["stripes", "retractable claws", "night vision"]),
        ("wolf", "mammal", "carnivore", "north america", "forest", "pack", "6-8 years", ["howl", "pack hunting", "endurance"]),
        ("bear", "mammal", "omnivore", "north america", "forest", "solitary", "20-30 years", ["hibernation", "strong claws", "excellent smell"]),
        ("whale", "mammal", "varies", "ocean", "deep water", "pod", "50-90 years", ["blowhole", "echolocation", "baleen"]),
        ("cheetah", "mammal", "carnivore", "africa", "savanna", "coalition", "10-12 years", ["speed", "spotted coat", "non-retractable claws"]),
        ("gorilla", "mammal", "herbivore", "africa", "rainforest", "troop", "35-40 years", ["intelligence", "knuckle walking", "silverback"]),
        ("octopus", "mollusk", "carnivore", "ocean", "coral reef", "solitary", "1-5 years", ["eight arms", "camouflage", "intelligence"]),
        ("cobra", "reptile", "carnivore", "asia", "forest", "solitary", "20 years", ["venom", "hood", "heat sensing"]),
        ("crocodile", "reptile", "carnivore", "tropics", "rivers", "solitary", "70-100 years", ["armored skin", "powerful jaws", "stealth"]),
        ("kangaroo", "mammal", "herbivore", "australia", "grassland", "mob", "12-18 years", ["pouch", "powerful legs", "jumping"]),
        ("panda", "mammal", "herbivore", "china", "bamboo forest", "solitary", "20 years", ["black and white fur", "bamboo diet", "thumb"]),
        ("giraffe", "mammal", "herbivore", "africa", "savanna", "tower", "25 years", ["long neck", "spotted pattern", "blue tongue"]),
        ("owl", "bird", "carnivore", "worldwide", "forest", "solitary", "10-20 years", ["night vision", "silent flight", "rotating head"]),
        ("parrot", "bird", "omnivore", "tropics", "rainforest", "flock", "40-80 years", ["speech mimicry", "colorful feathers", "intelligence"]),
    ]
    for name, kind, diet, region, habitat, social, lifespan, features in animals:
        facts.append(f"{name}|is_a|{kind}|1.0")
        facts.append(f"{name}|is_a|animal|1.0")
        facts.append(f"{name}|diet_is|{diet}|0.95")
        facts.append(f"{name}|lives_in|{region}|0.9")
        facts.append(f"{name}|habitat_is|{habitat}|0.9")
        facts.append(f"{name}|social_structure|{social}|0.85")
        facts.append(f"{name}|lifespan_is|{lifespan}|0.85")
        for feat in features:
            facts.append(f"{name}|has|{feat}|0.9")
    return facts


def gen_food():
    """Generate food and cuisine facts."""
    facts = []
    foods = [
        ("pizza", "italian", "main dish", ["dough", "tomato sauce", "cheese", "toppings"]),
        ("sushi", "japanese", "main dish", ["rice", "fish", "seaweed", "wasabi"]),
        ("tacos", "mexican", "main dish", ["tortilla", "meat", "salsa", "cheese"]),
        ("curry", "indian", "main dish", ["spices", "rice", "vegetables", "protein"]),
        ("pasta", "italian", "main dish", ["flour", "eggs", "sauce", "cheese"]),
        ("hamburger", "american", "main dish", ["bun", "beef patty", "lettuce", "tomato"]),
        ("ramen", "japanese", "soup", ["noodles", "broth", "pork", "eggs"]),
        ("croissant", "french", "pastry", ["butter", "flour", "yeast", "milk"]),
        ("paella", "spanish", "main dish", ["rice", "saffron", "seafood", "vegetables"]),
        ("dim sum", "chinese", "appetizer", ["dumplings", "buns", "rolls", "tea"]),
        ("kimchi", "korean", "side dish", ["cabbage", "chili flakes", "garlic", "salt"]),
        ("falafel", "middle eastern", "appetizer", ["chickpeas", "herbs", "spices", "oil"]),
        ("pho", "vietnamese", "soup", ["rice noodles", "broth", "beef", "herbs"]),
        ("pad thai", "thai", "main dish", ["rice noodles", "shrimp", "peanuts", "egg"]),
        ("biryani", "indian", "main dish", ["basmati rice", "spices", "meat", "saffron"]),
        ("fish and chips", "british", "main dish", ["cod", "batter", "potatoes", "oil"]),
        ("bratwurst", "german", "main dish", ["pork", "spices", "bread", "mustard"]),
        ("ceviche", "peruvian", "appetizer", ["raw fish", "lime juice", "onion", "chili"]),
        ("tiramisu", "italian", "dessert", ["mascarpone", "coffee", "ladyfingers", "cocoa"]),
        ("baklava", "turkish", "dessert", ["phyllo dough", "nuts", "honey", "butter"]),
    ]
    for name, cuisine, category, ingredients in foods:
        facts.append(f"{name}|is_a|food|1.0")
        facts.append(f"{name}|cuisine_is|{cuisine}|1.0")
        facts.append(f"{name}|category_is|{category}|0.95")
        for ing in ingredients:
            facts.append(f"{name}|contains|{ing}|0.9")
        facts.append(f"{name}|origin_is|{cuisine} cuisine|0.9")

    # Nutrition categories
    nutrients = [
        ("protein", "macronutrient", "builds muscle", ["meat", "fish", "eggs", "beans", "tofu"]),
        ("carbohydrate", "macronutrient", "provides energy", ["bread", "rice", "pasta", "potato", "sugar"]),
        ("fat", "macronutrient", "stores energy", ["butter", "oil", "nuts", "avocado", "cheese"]),
        ("vitamin c", "vitamin", "boosts immunity", ["orange", "lemon", "kiwi", "bell pepper", "strawberry"]),
        ("iron", "mineral", "carries oxygen", ["spinach", "red meat", "lentils", "tofu", "dark chocolate"]),
        ("calcium", "mineral", "builds bones", ["milk", "cheese", "yogurt", "broccoli", "almonds"]),
    ]
    for name, kind, function, sources in nutrients:
        facts.append(f"{name}|is_a|{kind}|1.0")
        facts.append(f"{name}|function_is|{function}|0.95")
        for src in sources:
            facts.append(f"{src}|contains|{name}|0.85")
    return facts


def gen_music():
    """Generate music genre and artist facts."""
    facts = []
    genres = [
        ("rock", "1950s", "electric guitar", ["led zeppelin", "the beatles", "pink floyd", "queen", "nirvana"]),
        ("jazz", "1900s", "improvisation", ["miles davis", "john coltrane", "louis armstrong", "duke ellington", "charlie parker"]),
        ("classical", "1600s", "orchestra", ["beethoven", "mozart", "bach", "chopin", "tchaikovsky"]),
        ("hip hop", "1970s", "rapping", ["tupac", "notorious big", "jay z", "kendrick lamar", "eminem"]),
        ("electronic", "1970s", "synthesizer", ["kraftwerk", "daft punk", "deadmau5", "aphex twin", "skrillex"]),
        ("blues", "1860s", "twelve bar", ["bb king", "muddy waters", "robert johnson", "howlin wolf", "john lee hooker"]),
        ("country", "1920s", "acoustic guitar", ["johnny cash", "dolly parton", "willie nelson", "hank williams", "garth brooks"]),
        ("reggae", "1960s", "offbeat rhythm", ["bob marley", "peter tosh", "jimmy cliff", "toots hibbert", "burning spear"]),
        ("metal", "1960s", "distortion", ["black sabbath", "metallica", "iron maiden", "slayer", "megadeth"]),
        ("pop", "1950s", "catchy melodies", ["michael jackson", "madonna", "prince", "taylor swift", "beyonce"]),
        ("rnb", "1940s", "rhythm and blues", ["stevie wonder", "marvin gaye", "aretha franklin", "whitney houston", "usher"]),
        ("punk", "1970s", "fast tempo", ["the ramones", "sex pistols", "the clash", "dead kennedys", "bad religion"]),
        ("folk", "traditional", "acoustic instruments", ["bob dylan", "woody guthrie", "joan baez", "joni mitchell", "pete seeger"]),
        ("soul", "1950s", "vocal emotion", ["james brown", "otis redding", "sam cooke", "ray charles", "al green"]),
    ]
    for genre, era, characteristic, artists in genres:
        facts.append(f"{genre}|is_a|music genre|1.0")
        facts.append(f"{genre}|originated_in|{era}|0.9")
        facts.append(f"{genre}|characterized_by|{characteristic}|0.9")
        for artist in artists:
            facts.append(f"{artist}|plays|{genre}|0.95")
            facts.append(f"{artist}|is_a|musician|1.0")
    return facts

def gen_sports():
    """Generate sports facts."""
    facts = []
    sports = [
        ("soccer", "team sport", "11", "fifa world cup", "1863", ["ball", "goal", "field"]),
        ("basketball", "team sport", "5", "nba finals", "1891", ["ball", "hoop", "court"]),
        ("tennis", "individual sport", "1 or 2", "wimbledon", "1873", ["racket", "ball", "net"]),
        ("baseball", "team sport", "9", "world series", "1846", ["bat", "ball", "glove"]),
        ("american football", "team sport", "11", "super bowl", "1869", ["ball", "helmet", "field"]),
        ("cricket", "team sport", "11", "cricket world cup", "1844", ["bat", "ball", "wicket"]),
        ("golf", "individual sport", "1", "the masters", "1457", ["clubs", "ball", "course"]),
        ("swimming", "individual sport", "1", "olympic games", "ancient", ["pool", "goggles", "swimsuit"]),
        ("boxing", "combat sport", "1", "world championship", "ancient", ["gloves", "ring", "mouthguard"]),
        ("hockey", "team sport", "6", "stanley cup", "1875", ["stick", "puck", "ice rink"]),
        ("rugby", "team sport", "15", "rugby world cup", "1823", ["ball", "goal", "field"]),
        ("volleyball", "team sport", "6", "olympic games", "1895", ["ball", "net", "court"]),
        ("table tennis", "individual sport", "1 or 2", "olympic games", "1880", ["paddle", "ball", "table"]),
        ("formula one", "motorsport", "1", "world championship", "1950", ["car", "circuit", "helmet"]),
        ("mma", "combat sport", "1", "ufc", "ancient", ["gloves", "octagon", "mouthguard"]),
    ]
    for name, kind, players, major_event, origin_year, equipment in sports:
        facts.append(f"{name}|is_a|sport|1.0")
        facts.append(f"{name}|is_a|{kind}|1.0")
        facts.append(f"{name}|players_per_team|{players}|0.95")
        facts.append(f"{name}|major_event|{major_event}|0.95")
        facts.append(f"{name}|originated_in|{origin_year}|0.85")
        for eq in equipment:
            facts.append(f"{name}|uses|{eq}|0.9")
    return facts


def gen_business():
    """Generate business and economics terms."""
    facts = []
    terms = [
        ("startup", "business type", "early stage company seeking scalable business model"),
        ("venture capital", "funding type", "investment in high growth potential startups"),
        ("ipo", "financial event", "initial public offering of company shares"),
        ("roi", "metric", "return on investment measures profitability"),
        ("gdp", "metric", "gross domestic product measures economic output"),
        ("inflation", "economic concept", "general increase in prices over time"),
        ("recession", "economic concept", "period of economic decline"),
        ("supply and demand", "economic concept", "relationship between availability and desire"),
        ("market capitalization", "metric", "total value of company outstanding shares"),
        ("dividend", "financial term", "portion of earnings distributed to shareholders"),
        ("bond", "financial instrument", "debt security with fixed interest payments"),
        ("equity", "financial term", "ownership interest in a company"),
        ("revenue", "financial term", "total income from business operations"),
        ("profit margin", "metric", "percentage of revenue that is profit"),
        ("cash flow", "metric", "net amount of cash moving in and out"),
        ("asset", "financial term", "resource owned that has economic value"),
        ("liability", "financial term", "obligation owed to another party"),
        ("monopoly", "market structure", "single seller dominates entire market"),
        ("oligopoly", "market structure", "few sellers dominate the market"),
        ("blockchain", "technology", "distributed ledger technology"),
        ("cryptocurrency", "financial instrument", "digital currency using cryptography"),
        ("hedge fund", "investment vehicle", "pooled fund using complex strategies"),
        ("mutual fund", "investment vehicle", "pooled fund investing in diversified assets"),
        ("balance sheet", "financial statement", "snapshot of assets liabilities and equity"),
        ("income statement", "financial statement", "summary of revenues and expenses"),
        ("depreciation", "accounting concept", "decrease in asset value over time"),
        ("amortization", "accounting concept", "spreading cost over useful life"),
        ("leverage", "financial concept", "use of borrowed capital for investment"),
        ("liquidity", "financial concept", "ease of converting asset to cash"),
        ("arbitrage", "trading strategy", "exploiting price differences across markets"),
    ]
    for name, category, definition in terms:
        facts.append(f"{name}|is_a|{category}|1.0")
        facts.append(f"{name}|definition|{definition}|0.95")
        facts.append(f"{name}|domain_is|business|0.9")

    # Major companies
    companies = [
        ("apple", "technology", "1976", "tim cook", "cupertino"),
        ("google", "technology", "1998", "sundar pichai", "mountain view"),
        ("microsoft", "technology", "1975", "satya nadella", "redmond"),
        ("amazon", "ecommerce", "1994", "andy jassy", "seattle"),
        ("meta", "social media", "2004", "mark zuckerberg", "menlo park"),
        ("tesla", "automotive", "2003", "elon musk", "austin"),
        ("nvidia", "semiconductors", "1993", "jensen huang", "santa clara"),
        ("samsung", "electronics", "1938", "lee jae yong", "seoul"),
        ("toyota", "automotive", "1937", "akio toyoda", "toyota city"),
        ("berkshire hathaway", "conglomerate", "1839", "warren buffett", "omaha"),
    ]
    for name, sector, founded, ceo, hq in companies:
        facts.append(f"{name}|is_a|company|1.0")
        facts.append(f"{name}|sector_is|{sector}|1.0")
        facts.append(f"{name}|founded_in|{founded}|1.0")
        facts.append(f"{name}|ceo_is|{ceo}|0.9")
        facts.append(f"{name}|headquartered_in|{hq}|0.95")
    return facts


def gen_extra():
    """Generate additional miscellaneous facts to reach 5000+ total."""
    facts = []
    # Solar system
    planets = [
        ("mercury", "1st", "smallest", "57.9", "0", "hot"),
        ("venus", "2nd", "hottest", "108.2", "0", "very hot"),
        ("earth", "3rd", "habitable", "149.6", "1", "temperate"),
        ("mars", "4th", "red planet", "227.9", "2", "cold"),
        ("jupiter", "5th", "largest", "778.5", "95", "very cold"),
        ("saturn", "6th", "ringed", "1432", "146", "very cold"),
        ("uranus", "7th", "tilted", "2867", "28", "extremely cold"),
        ("neptune", "8th", "windiest", "4515", "16", "extremely cold"),
    ]
    for name, position, desc, distance, moons, temp in planets:
        facts.append(f"{name}|is_a|planet|1.0")
        facts.append(f"{name}|position_is|{position} from sun|1.0")
        facts.append(f"{name}|known_for|{desc}|0.9")
        facts.append(f"{name}|distance_from_sun|{distance} million km|0.95")
        facts.append(f"{name}|moons_count|{moons}|0.9")
        facts.append(f"{name}|temperature_is|{temp}|0.85")
        facts.append(f"{name}|orbits|sun|1.0")
        facts.append(f"{name}|part_of|solar system|1.0")

    # Elements
    elements = [
        ("hydrogen", "H", "1", "gas", "nonmetal"),
        ("helium", "He", "2", "gas", "noble gas"),
        ("lithium", "Li", "3", "solid", "alkali metal"),
        ("carbon", "C", "6", "solid", "nonmetal"),
        ("nitrogen", "N", "7", "gas", "nonmetal"),
        ("oxygen", "O", "8", "gas", "nonmetal"),
        ("sodium", "Na", "11", "solid", "alkali metal"),
        ("magnesium", "Mg", "12", "solid", "alkaline earth metal"),
        ("aluminum", "Al", "13", "solid", "metal"),
        ("silicon", "Si", "14", "solid", "metalloid"),
        ("phosphorus", "P", "15", "solid", "nonmetal"),
        ("sulfur", "S", "16", "solid", "nonmetal"),
        ("chlorine", "Cl", "17", "gas", "halogen"),
        ("iron", "Fe", "26", "solid", "transition metal"),
        ("copper", "Cu", "29", "solid", "transition metal"),
        ("zinc", "Zn", "30", "solid", "transition metal"),
        ("silver", "Ag", "47", "solid", "transition metal"),
        ("gold", "Au", "79", "solid", "transition metal"),
        ("platinum", "Pt", "78", "solid", "transition metal"),
        ("uranium", "U", "92", "solid", "actinide"),
    ]
    for name, symbol, number, state, category in elements:
        facts.append(f"{name}|is_a|chemical element|1.0")
        facts.append(f"{name}|symbol_is|{symbol}|1.0")
        facts.append(f"{name}|atomic_number|{number}|1.0")
        facts.append(f"{name}|state_at_room_temp|{state}|0.95")
        facts.append(f"{name}|category_is|{category}|1.0")

    # Mathematical concepts
    math_concepts = [
        ("pythagorean theorem", "geometry", "a squared plus b squared equals c squared"),
        ("fibonacci sequence", "number theory", "each number is sum of two preceding"),
        ("prime number", "number theory", "natural number greater than 1 with no divisors except 1 and itself"),
        ("pi", "constant", "ratio of circumference to diameter approximately 3.14159"),
        ("euler number", "constant", "base of natural logarithm approximately 2.71828"),
        ("golden ratio", "constant", "approximately 1.618 found in nature and art"),
        ("calculus", "branch of math", "study of continuous change"),
        ("algebra", "branch of math", "study of mathematical symbols and rules"),
        ("geometry", "branch of math", "study of shapes and spaces"),
        ("statistics", "branch of math", "study of data collection and analysis"),
        ("probability", "branch of math", "study of likelihood of events"),
        ("linear algebra", "branch of math", "study of vectors and matrices"),
        ("topology", "branch of math", "study of geometric properties preserved under deformation"),
        ("set theory", "branch of math", "study of collections of objects"),
        ("graph theory", "branch of math", "study of mathematical structures with nodes and edges"),
    ]
    for name, category, desc in math_concepts:
        facts.append(f"{name}|is_a|{category}|1.0")
        facts.append(f"{name}|description|{desc}|0.95")
        facts.append(f"{name}|domain_is|mathematics|1.0")


    # Historical events
    events = [
        ("world war 1", "1914-1918", "global conflict involving major powers"),
        ("world war 2", "1939-1945", "largest armed conflict in history"),
        ("moon landing", "1969", "first humans walked on the moon"),
        ("fall of berlin wall", "1989", "end of cold war division of germany"),
        ("internet invention", "1969", "arpanet first message sent"),
        ("french revolution", "1789", "overthrow of french monarchy"),
        ("american revolution", "1776", "thirteen colonies declared independence"),
        ("industrial revolution", "1760-1840", "transition to manufacturing processes"),
        ("renaissance", "1400-1600", "cultural rebirth in europe"),
        ("printing press invention", "1440", "gutenberg revolutionized communication"),
        ("discovery of americas", "1492", "columbus reached the new world"),
        ("magna carta", "1215", "charter of rights limiting royal power"),
        ("roman empire fall", "476", "western roman empire collapsed"),
        ("cold war", "1947-1991", "geopolitical tension between usa and ussr"),
        ("civil rights movement", "1954-1968", "struggle for racial equality in usa"),
    ]
    for name, date, desc in events:
        facts.append(f"{name}|is_a|historical event|1.0")
        facts.append(f"{name}|occurred_in|{date}|1.0")
        facts.append(f"{name}|description|{desc}|0.95")

    # Computer science concepts
    cs_concepts = [
        ("algorithm", "procedure", "step by step instructions to solve a problem"),
        ("data structure", "concept", "way of organizing and storing data"),
        ("recursion", "technique", "function that calls itself"),
        ("binary search", "algorithm", "divides sorted array in half each step"),
        ("sorting", "algorithm category", "arranging elements in a specific order"),
        ("hash table", "data structure", "maps keys to values using hash function"),
        ("linked list", "data structure", "sequence of nodes with pointers"),
        ("binary tree", "data structure", "hierarchical structure with at most two children per node"),
        ("stack", "data structure", "last in first out collection"),
        ("queue", "data structure", "first in first out collection"),
        ("graph", "data structure", "nodes connected by edges"),
        ("dynamic programming", "technique", "breaking problems into overlapping subproblems"),
        ("object oriented programming", "paradigm", "organizing code around objects and classes"),
        ("functional programming", "paradigm", "organizing code around pure functions"),
        ("machine learning", "field", "algorithms that improve through experience"),
        ("artificial intelligence", "field", "simulation of human intelligence by machines"),
        ("neural network", "model", "computing system inspired by biological neurons"),
        ("deep learning", "technique", "neural networks with many layers"),
        ("natural language processing", "field", "enabling computers to understand human language"),
        ("computer vision", "field", "enabling computers to interpret visual information"),
        ("encryption", "technique", "converting data into unreadable format for security"),
        ("database", "system", "organized collection of structured data"),
        ("api", "concept", "application programming interface for software communication"),
        ("tcp ip", "protocol", "fundamental communication protocol of the internet"),
        ("http", "protocol", "hypertext transfer protocol for web communication"),
    ]
    for name, category, desc in cs_concepts:
        facts.append(f"{name}|is_a|{category}|1.0")
        facts.append(f"{name}|description|{desc}|0.95")
        facts.append(f"{name}|domain_is|computer science|1.0")

    return facts


def gen_more_languages():
    """Generate more programming and human language facts."""
    facts = []
    # Human languages
    languages = [
        ("english", "germanic", "1.5 billion", "latin", ["subject verb object", "26 letters", "global lingua franca"]),
        ("mandarin chinese", "sino-tibetan", "1.1 billion", "chinese characters", ["tonal language", "simplified and traditional", "most native speakers"]),
        ("spanish", "romance", "550 million", "latin", ["gendered nouns", "subjunctive mood", "second most native speakers"]),
        ("hindi", "indo-aryan", "600 million", "devanagari", ["gendered nouns", "sov word order", "official language of india"]),
        ("arabic", "semitic", "420 million", "arabic script", ["right to left", "root system", "diglossia"]),
        ("french", "romance", "320 million", "latin", ["gendered nouns", "nasal vowels", "liaison"]),
        ("portuguese", "romance", "260 million", "latin", ["gendered nouns", "nasal vowels", "spoken in brazil"]),
        ("russian", "slavic", "250 million", "cyrillic", ["cases", "aspect system", "flexible word order"]),
        ("japanese", "japonic", "125 million", "kanji hiragana katakana", ["three writing systems", "honorifics", "sov word order"]),
        ("german", "germanic", "130 million", "latin", ["compound words", "cases", "verb final in subordinate clauses"]),
        ("korean", "koreanic", "80 million", "hangul", ["agglutinative", "honorifics", "sov word order"]),
        ("italian", "romance", "67 million", "latin", ["gendered nouns", "verb conjugation", "melodic intonation"]),
        ("turkish", "turkic", "80 million", "latin", "vowel harmony"),
        ("swahili", "bantu", "100 million", "latin", "noun class system"),
        ("dutch", "germanic", "25 million", "latin", "similar to german and english"),
    ]
    for name, family, speakers, script, features in languages:
        facts.append(f"{name}|is_a|human language|1.0")
        facts.append(f"{name}|language_family|{family}|0.95")
        facts.append(f"{name}|speakers_count|{speakers}|0.85")
        if isinstance(script, str):
            facts.append(f"{name}|writing_system|{script}|0.95")
        if isinstance(features, list):
            for f in features:
                facts.append(f"{name}|has_feature|{f}|0.85")
        else:
            facts.append(f"{name}|has_feature|{features}|0.85")

    # More programming topics - design patterns
    patterns = [
        ("singleton", "creational", "ensures only one instance of a class exists"),
        ("factory", "creational", "creates objects without specifying exact class"),
        ("observer", "behavioral", "defines one-to-many dependency between objects"),
        ("strategy", "behavioral", "defines family of interchangeable algorithms"),
        ("decorator", "structural", "adds behavior to objects dynamically"),
        ("adapter", "structural", "converts interface of one class to another"),
        ("facade", "structural", "provides simplified interface to complex subsystem"),
        ("proxy", "structural", "provides placeholder for another object"),
        ("command", "behavioral", "encapsulates request as an object"),
        ("iterator", "behavioral", "provides way to access elements sequentially"),
        ("template method", "behavioral", "defines skeleton of algorithm in base class"),
        ("builder", "creational", "constructs complex objects step by step"),
        ("prototype", "creational", "creates new objects by cloning existing ones"),
        ("mediator", "behavioral", "reduces coupling between components"),
        ("state", "behavioral", "allows object to alter behavior when internal state changes"),
    ]
    for name, category, desc in patterns:
        facts.append(f"{name} pattern|is_a|design pattern|1.0")
        facts.append(f"{name} pattern|category_is|{category}|1.0")
        facts.append(f"{name} pattern|description|{desc}|0.95")
        facts.append(f"{name} pattern|domain_is|software engineering|0.9")

    # Databases
    databases = [
        ("postgresql", "relational", "open source", "sql", "acid compliant"),
        ("mysql", "relational", "open source", "sql", "widely used"),
        ("mongodb", "document", "open source", "javascript", "schema flexible"),
        ("redis", "key value", "open source", "custom protocol", "in memory"),
        ("elasticsearch", "search engine", "open source", "rest api", "full text search"),
        ("cassandra", "wide column", "open source", "cql", "highly available"),
        ("sqlite", "relational", "embedded", "sql", "serverless"),
        ("dynamodb", "key value", "aws managed", "api", "auto scaling"),
        ("neo4j", "graph", "open source", "cypher", "relationship focused"),
        ("couchdb", "document", "open source", "rest api", "offline first"),
    ]
    for name, kind, license_type, query_lang, feature in databases:
        facts.append(f"{name}|is_a|database|1.0")
        facts.append(f"{name}|database_type|{kind}|1.0")
        facts.append(f"{name}|license_is|{license_type}|0.9")
        facts.append(f"{name}|query_language|{query_lang}|0.95")
        facts.append(f"{name}|known_for|{feature}|0.9")

    # Operating systems
    operating_systems = [
        ("linux", "open source", "linus torvalds", "1991", "monolithic kernel"),
        ("windows", "proprietary", "microsoft", "1985", "nt kernel"),
        ("macos", "proprietary", "apple", "2001", "xnu kernel"),
        ("android", "open source", "google", "2008", "linux kernel"),
        ("ios", "proprietary", "apple", "2007", "xnu kernel"),
        ("freebsd", "open source", "freebsd project", "1993", "monolithic kernel"),
        ("ubuntu", "open source", "canonical", "2004", "linux kernel"),
        ("fedora", "open source", "red hat", "2003", "linux kernel"),
    ]
    for name, license_type, creator, year, kernel in operating_systems:
        facts.append(f"{name}|is_a|operating system|1.0")
        facts.append(f"{name}|license_is|{license_type}|1.0")
        facts.append(f"{name}|created_by|{creator}|1.0")
        facts.append(f"{name}|released_in|{year}|1.0")
        facts.append(f"{name}|kernel_type|{kernel}|0.95")

    return facts

def gen_more_world():
    """Generate more world knowledge - oceans, mountains, rivers, etc."""
    facts = []
    # Oceans
    oceans = [
        ("pacific ocean", "largest ocean", "165.25 million sq km", "mariana trench"),
        ("atlantic ocean", "second largest ocean", "106.46 million sq km", "puerto rico trench"),
        ("indian ocean", "third largest ocean", "70.56 million sq km", "java trench"),
        ("southern ocean", "fourth largest ocean", "21.96 million sq km", "south sandwich trench"),
        ("arctic ocean", "smallest ocean", "14.06 million sq km", "molloy deep"),
    ]
    for name, desc, area, deepest in oceans:
        facts.append(f"{name}|is_a|ocean|1.0")
        facts.append(f"{name}|description|{desc}|1.0")
        facts.append(f"{name}|area_is|{area}|0.95")
        facts.append(f"{name}|deepest_point|{deepest}|0.9")

    # Mountains
    mountains = [
        ("mount everest", "himalayas", "nepal", "8849 meters", "tallest mountain"),
        ("k2", "karakoram", "pakistan", "8611 meters", "second tallest mountain"),
        ("kangchenjunga", "himalayas", "nepal", "8586 meters", "third tallest mountain"),
        ("mont blanc", "alps", "france", "4809 meters", "tallest in alps"),
        ("mount kilimanjaro", "eastern rift", "tanzania", "5895 meters", "tallest in africa"),
        ("mount mckinley", "alaska range", "united states", "6190 meters", "tallest in north america"),
        ("mount fuji", "pacific ring", "japan", "3776 meters", "iconic japanese mountain"),
        ("matterhorn", "alps", "switzerland", "4478 meters", "iconic alpine peak"),
    ]
    for name, range_name, country, height, desc in mountains:
        facts.append(f"{name}|is_a|mountain|1.0")
        facts.append(f"{name}|range_is|{range_name}|1.0")
        facts.append(f"{name}|located_in|{country}|1.0")
        facts.append(f"{name}|height_is|{height}|1.0")
        facts.append(f"{name}|known_for|{desc}|0.9")

    # Rivers
    rivers = [
        ("amazon", "south america", "6400 km", "atlantic ocean", "largest by discharge"),
        ("nile", "africa", "6650 km", "mediterranean sea", "longest river"),
        ("yangtze", "asia", "6300 km", "east china sea", "longest in asia"),
        ("mississippi", "north america", "3730 km", "gulf of mexico", "major us waterway"),
        ("danube", "europe", "2850 km", "black sea", "flows through 10 countries"),
        ("ganges", "asia", "2525 km", "bay of bengal", "sacred river in hinduism"),
        ("thames", "europe", "346 km", "north sea", "flows through london"),
        ("rhine", "europe", "1230 km", "north sea", "major european trade route"),
        ("congo", "africa", "4700 km", "atlantic ocean", "deepest river"),
        ("volga", "europe", "3530 km", "caspian sea", "longest in europe"),
    ]
    for name, continent, length, outlet, desc in rivers:
        facts.append(f"{name} river|is_a|river|1.0")
        facts.append(f"{name} river|located_in|{continent}|1.0")
        facts.append(f"{name} river|length_is|{length}|0.95")
        facts.append(f"{name} river|flows_into|{outlet}|1.0")
        facts.append(f"{name} river|known_for|{desc}|0.9")

    # World wonders and landmarks
    landmarks = [
        ("great wall of china", "china", "wall", "221 bc", "longest wall ever built"),
        ("eiffel tower", "france", "tower", "1889", "symbol of paris"),
        ("statue of liberty", "united states", "monument", "1886", "gift from france"),
        ("taj mahal", "india", "mausoleum", "1632", "symbol of love"),
        ("colosseum", "italy", "amphitheater", "80 ad", "largest roman amphitheater"),
        ("machu picchu", "peru", "citadel", "1450", "inca mountain fortress"),
        ("pyramids of giza", "egypt", "pyramid", "2560 bc", "only surviving ancient wonder"),
        ("big ben", "england", "clock tower", "1859", "iconic london clock"),
        ("sydney opera house", "australia", "theater", "1973", "architectural masterpiece"),
        ("golden gate bridge", "united states", "bridge", "1937", "iconic san francisco bridge"),
    ]
    for name, country, kind, year, desc in landmarks:
        facts.append(f"{name}|is_a|landmark|1.0")
        facts.append(f"{name}|is_a|{kind}|1.0")
        facts.append(f"{name}|located_in|{country}|1.0")
        facts.append(f"{name}|built_in|{year}|0.95")
        facts.append(f"{name}|known_for|{desc}|0.9")

    # Inventions
    inventions = [
        ("telephone", "alexander graham bell", "1876", "communication"),
        ("light bulb", "thomas edison", "1879", "illumination"),
        ("airplane", "wright brothers", "1903", "transportation"),
        ("television", "philo farnsworth", "1927", "entertainment"),
        ("computer", "charles babbage", "1837", "computation"),
        ("internet", "vint cerf and bob kahn", "1983", "global network"),
        ("printing press", "johannes gutenberg", "1440", "mass communication"),
        ("steam engine", "james watt", "1769", "industrial power"),
        ("automobile", "karl benz", "1886", "personal transportation"),
        ("radio", "guglielmo marconi", "1895", "wireless communication"),
        ("vaccination", "edward jenner", "1796", "disease prevention"),
        ("penicillin", "alexander fleming", "1928", "antibiotic medicine"),
        ("dynamite", "alfred nobel", "1867", "construction and mining"),
        ("telescope", "hans lippershey", "1608", "astronomy"),
        ("microscope", "antonie van leeuwenhoek", "1674", "biology"),
    ]
    for name, inventor, year, purpose in inventions:
        facts.append(f"{name}|is_a|invention|1.0")
        facts.append(f"{name}|invented_by|{inventor}|1.0")
        facts.append(f"{name}|invented_in|{year}|1.0")
        facts.append(f"{name}|used_for|{purpose}|0.9")

    return facts

def main():
    """Generate all knowledge files."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print("\n  MK OS - Bulk Knowledge Generator")
    print("  " + "=" * 40)

    total = 0

    prog_facts = gen_programming()
    write_mk_file("bulk_programming.mk", "Programming Languages & Frameworks", prog_facts)
    total += len(prog_facts)

    country_facts = gen_countries()
    write_mk_file("bulk_countries.mk", "Countries, Capitals, and Geography", country_facts)
    total += len(country_facts)

    scientist_facts = gen_scientists()
    write_mk_file("bulk_scientists.mk", "Famous Scientists and Discoveries", scientist_facts)
    total += len(scientist_facts)

    animal_facts = gen_animals()
    write_mk_file("bulk_animals.mk", "Animal Kingdom", animal_facts)
    total += len(animal_facts)

    food_facts = gen_food()
    write_mk_file("bulk_food.mk", "Food, Cuisine, and Nutrition", food_facts)
    total += len(food_facts)

    music_facts = gen_music()
    write_mk_file("bulk_music.mk", "Music Genres and Artists", music_facts)
    total += len(music_facts)

    sports_facts = gen_sports()
    write_mk_file("bulk_sports.mk", "Sports and Athletics", sports_facts)
    total += len(sports_facts)

    business_facts = gen_business()
    write_mk_file("bulk_business.mk", "Business and Economics", business_facts)
    total += len(business_facts)

    extra_facts = gen_extra()
    write_mk_file("bulk_extra.mk", "Science, Math, History, and CS Concepts", extra_facts)
    total += len(extra_facts)

    more_lang_facts = gen_more_languages()
    write_mk_file("bulk_languages_tech.mk", "Human Languages, Design Patterns, Databases, OS", more_lang_facts)
    total += len(more_lang_facts)

    more_world_facts = gen_more_world()
    write_mk_file("bulk_world.mk", "Oceans, Mountains, Rivers, Landmarks, Inventions", more_world_facts)
    total += len(more_world_facts)

    print(f"\n  TOTAL: {total} facts generated across 11 knowledge files")
    print(f"  (Plus bulk_mega.mk with additional facts)")
    print(f"  Output directory: {OUTPUT_DIR}")
    print("  " + "=" * 40 + "\n")

if __name__ == "__main__":
    main()
